### ISSUE TITLE
TypeError exception in formatting_structure.boxes.Box.padding_height(self)

### ISSUE THREAD

**Issue by vannitotaro** [Kozea/WeasyPrint#544] opened 2017-11-22 11:35 UTC
Using `python -m weasyprint.navigator` and visiting a specific website I get the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/navigator.py", line 143, in app
    return make_response(render_template(url))
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/navigator.py", line 75, in render_template
    for width, height, data_url, links, anchors in get_pages(html):
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/navigator.py", line 32, in get_pages
    document = html.render(enable_hinting=True, stylesheets=[STYLESHEET])
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/__init__.py", line 143, in render
    font_config)
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/document.py", line 326, in _render
    [Page(p, enable_hinting) for p in page_boxes],
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/document.py", line 326, in <listcomp>
    [Page(p, enable_hinting) for p in page_boxes],
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/layout/__init__.py", line 67, in layout_document
    layout_backgrounds(page, get_image_from_uri)
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/layout/backgrounds.py", line 252, in layout_backgrounds
    layout_box_backgrounds(page, page, get_image_from_uri)
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/layout/backgrounds.py", line 58, in layout_box_backgrounds
    layout_box_backgrounds(page, child, get_image_from_uri)
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/layout/backgrounds.py", line 58, in layout_box_backgrounds
    layout_box_backgrounds(page, child, get_image_from_uri)
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/layout/backgrounds.py", line 58, in layout_box_backgrounds
    layout_box_backgrounds(page, child, get_image_from_uri)
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/layout/backgrounds.py", line 58, in layout_box_backgrounds
    layout_box_backgrounds(page, child, get_image_from_uri)
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/layout/backgrounds.py", line 55, in layout_box_backgrounds
    resolve_radii_percentages(box)
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/layout/percentages.py", line 125, in resolve_radii_percentages
    ry = _percentage(ry, box.border_height())
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/formatting_structure/boxes.py", line 143, in border_height
    return self.padding_height() + self.border_top_width + \
  File "/home/myuser/venvs/myvenv/lib/python3.5/site-packages/weasyprint/formatting_structure/boxes.py", line 134, in padding_height
    return self.height + self.padding_top + self.padding_bottom
TypeError: Can't convert 'int' object to str implicitly
```

**Comment by vannitotaro** [comment] 2017-11-22 11:47
```
(Pdb) self.height                                                                                                                                                             
'auto'
(Pdb) self.padding_bottom
0
(Pdb) self.padding_top
0
```

**Comment by liZe** [comment] 2017-11-22 12:32
Thanks for your report. That's actually a duplicate of #171.

**Closed by liZe** 2017-11-22 12:32 UTC
