### ISSUE TITLE
two tests fail: test_links and test_relative_links_missing_base_link

### ISSUE THREAD

**Issue by mcepl** [Kozea/WeasyPrint#1503] opened 2021-11-22 11:13 UTC
When packaging WeasyPrint 53.4 for openSUSE/Tumbleweed I get these tests failing:

```
[  170s] =================================== FAILURES ===================================
[  170s] __________________________________ test_links __________________________________
[  170s]
[  170s]     @assert_no_logs
[  170s]     def test_links():
[  170s]         def assert_links(html, expected_links_by_page, expected_anchors_by_page,
[  170s]                          expected_resolved_links,
[  170s]                          base_url=resource_filename('<inline HTML>'),
[  170s]                          warnings=(), round=False):
[  170s]             with capture_logs() as logs:
[  170s]                 document = FakeHTML(string=html, base_url=base_url).render()
[  170s]                 if round:
[  170s]                     _round_meta(document.pages)
[  170s]                 resolved_links = list(resolve_links(document.pages))
[  170s]             assert len(logs) == len(warnings)
[  170s]             for message, expected in zip(logs, warnings):
[  170s]                 assert expected in message
[  170s]             assert [p.links for p in document.pages] == expected_links_by_page
[  170s]             assert [p.anchors for p in document.pages] == expected_anchors_by_page
[  170s]             assert resolved_links == expected_resolved_links
[  170s]
[  170s]         assert_links('''
[  170s]             <style>
[  170s]                 body { font-size: 10px; line-height: 2; width: 200px }
[  170s]                 p { height: 90px; margin: 0 0 10px 0 }
[  170s]                 img { width: 30px; vertical-align: top }
[  170s]             </style>
[  170s]             <p><a href="http://weasyprint.org"><img src=pattern.png></a></p>
[  170s]             <p style="padding: 0 10px"><a
[  170s]                 href="#lipsum"><img style="border: solid 1px"
[  170s]                                     src=pattern.png></a></p>
[  170s]             <p id=hello>Hello, World</p>
[  170s]             <p id=lipsum>
[  170s]                 <a style="display: block; page-break-before: always; height: 30px"
[  170s]                    href="#hel%6Co"></a>
[  170s]             </p>
[  170s]         ''', [
[  170s]             [
[  170s]                 ('external', 'http://weasyprint.org', (0, 0, 30, 20), None),
[  170s]                 ('external', 'http://weasyprint.org', (0, 0, 30, 30), None),
[  170s]                 ('internal', 'lipsum', (10, 100, 42, 120), None),
[  170s]                 ('internal', 'lipsum', (10, 100, 42, 132), None)
[  170s]             ],
[  170s]             [('internal', 'hello', (0, 0, 200, 30), None)],
[  170s]         ], [
[  170s]             {'hello': (0, 200)},
[  170s]             {'lipsum': (0, 0)}
[  170s]         ], [
[  170s]             (
[  170s]                 [
[  170s]                     ('external', 'http://weasyprint.org', (0, 0, 30, 20), None),
[  170s]                     ('external', 'http://weasyprint.org', (0, 0, 30, 30), None),
[  170s]                     ('internal', 'lipsum', (10, 100, 42, 120), None),
[  170s]                     ('internal', 'lipsum', (10, 100, 42, 132), None)
[  170s]                 ],
[  170s]                 [('hello', 0, 200)],
[  170s]             ),
[  170s]             (
[  170s]                 [
[  170s]                     ('internal', 'hello', (0, 0, 200, 30), None)
[  170s]                 ],
[  170s]                 [('lipsum', 0, 0)]),
[  170s]         ])
[  170s]
[  170s]         assert_links(
[  170s]             '''
[  170s]                 <body style="width: 200px">
[  170s]                 <a href="../lipsum/é_%E9" style="display: block; margin: 10px 5px">
[  170s]             ''', [[('external', 'http://weasyprint.org/foo/lipsum/%C3%A9_%E9',
[  170s]                     (5, 10, 195, 10), None)]],
[  170s]             [{}], [([('external', 'http://weasyprint.org/foo/lipsum/%C3%A9_%E9',
[  170s]                       (5, 10, 195, 10), None)], [])],
[  170s]             base_url='http://weasyprint.org/foo/bar/')
[  170s]
[  170s]         assert_links(
[  170s]             '''
[  170s]                 <body style="width: 200px">
[  170s]                 <div style="display: block; margin: 10px 5px;
[  170s]                             -weasy-link: url(../lipsum/é_%E9)">
[  170s]             ''', [[('external', 'http://weasyprint.org/foo/lipsum/%C3%A9_%E9',
[  170s]                     (5, 10, 195, 10), None)]],
[  170s]             [{}], [([('external', 'http://weasyprint.org/foo/lipsum/%C3%A9_%E9',
[  170s]                       (5, 10, 195, 10), None)], [])],
[  170s]             base_url='http://weasyprint.org/foo/bar/')
[  170s]
[  170s]         # Relative URI reference without a base URI: allowed for links
[  170s]         assert_links(
[  170s]             '''
[  170s]                 <body style="width: 200px">
[  170s]                 <a href="../lipsum" style="display: block; margin: 10px 5px">
[  170s]             ''', [[('external', '../lipsum', (5, 10, 195, 10), None)]], [{}],
[  170s]             [([('external', '../lipsum', (5, 10, 195, 10), None)], [])],
[  170s]             base_url=None)
[  170s]
[  170s]         # Relative URI reference without a base URI: not supported for -weasy-link
[  170s]         assert_links(
[  170s]             '''
[  170s]                 <body style="width: 200px">
[  170s]                 <div style="-weasy-link: url(../lipsum);
[  170s]                             display: block; margin: 10px 5px">
[  170s]             ''', [[]], [{}], [([], [])], base_url=None, warnings=[
[  170s] >               'WARNING: Ignored `-weasy-link: url(../lipsum)` at 1:1, '
[  170s]                 'Relative URI reference without a base URI'])
[  170s]
[  170s] /home/abuild/rpmbuild/BUILD/weasyprint-53.4/tests/test_api.py:735:
[  170s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
[  170s]
[  170s] html = '\n            <body style="width: 200px">\n            <div style="-weasy-link: url(../lipsum);\n                        display: block; margin: 10px 5px">\n        '
[  170s] expected_links_by_page = [[]], expected_anchors_by_page = [{}]
[  170s] expected_resolved_links = [([], [])], base_url = None
[  170s] warnings = ['WARNING: Ignored `-weasy-link: url(../lipsum)` at 1:1, Relative URI reference without a base URI']
[  170s] round = False
[  170s]
[  170s]     def assert_links(html, expected_links_by_page, expected_anchors_by_page,
[  170s]                      expected_resolved_links,
[  170s]                      base_url=resource_filename('<inline HTML>'),
[  170s]                      warnings=(), round=False):
[  170s]         with capture_logs() as logs:
[  170s]             document = FakeHTML(string=html, base_url=base_url).render()
[  170s]             if round:
[  170s]                 _round_meta(document.pages)
[  170s]             resolved_links = list(resolve_links(document.pages))
[  170s]         assert len(logs) == len(warnings)
[  170s]         for message, expected in zip(logs, warnings):
[  170s] >           assert expected in message
[  170s] E           assert 'WARNING: Ignored `-weasy-link: url(../lipsum)` at 1:1, Relative URI reference without a base URI' in 'WARNING: Ignored `-weasy-link: url("../lipsum")` at 1:1, Relative URI reference without a base URI: \'../lipsum\'.'
[  170s]
[  170s] /home/abuild/rpmbuild/BUILD/weasyprint-53.4/tests/test_api.py:650: AssertionError
[  170s] ------------------------------ Captured log call -------------------------------
[  170s] INFO     weasyprint.progress:__init__.py:80 Step 1 - Fetching and parsing HTML - HTML string
[  170s] INFO     weasyprint.progress:__init__.py:209 Step 2 - Fetching and parsing CSS - CSS string
[  170s] INFO     weasyprint.progress:__init__.py:64 Step 3 - Applying CSS
[  170s] INFO     weasyprint.progress:document.py:863 Step 4 - Creating formatting structure
[  170s] INFO     weasyprint.progress:pages.py:796 Step 5 - Creating layout - Page 1
[  170s] INFO     weasyprint.progress:pages.py:796 Step 5 - Creating layout - Page 2
[  170s] INFO     weasyprint.progress:__init__.py:80 Step 1 - Fetching and parsing HTML - HTML string
[  170s] INFO     weasyprint.progress:__init__.py:64 Step 3 - Applying CSS
[  170s] INFO     weasyprint.progress:document.py:863 Step 4 - Creating formatting structure
[  170s] INFO     weasyprint.progress:pages.py:796 Step 5 - Creating layout - Page 1
[  170s] INFO     weasyprint.progress:__init__.py:80 Step 1 - Fetching and parsing HTML - HTML string
[  170s] INFO     weasyprint.progress:__init__.py:64 Step 3 - Applying CSS
[  170s] INFO     weasyprint.progress:document.py:863 Step 4 - Creating formatting structure
[  170s] INFO     weasyprint.progress:pages.py:796 Step 5 - Creating layout - Page 1
[  170s] INFO     weasyprint.progress:__init__.py:80 Step 1 - Fetching and parsing HTML - HTML string
[  170s] INFO     weasyprint.progress:__init__.py:64 Step 3 - Applying CSS
[  170s] INFO     weasyprint.progress:document.py:863 Step 4 - Creating formatting structure
[  170s] INFO     weasyprint.progress:pages.py:796 Step 5 - Creating layout - Page 1
[  170s] INFO     weasyprint.progress:__init__.py:80 Step 1 - Fetching and parsing HTML - HTML string
[  170s] INFO     weasyprint.progress:__init__.py:64 Step 3 - Applying CSS
[  170s] WARNING  weasyprint:__init__.py:86 Ignored `-weasy-link: url("../lipsum")` at 1:1, Relative URI reference without a base URI: '../lipsum'.
[  170s] INFO     weasyprint.progress:document.py:863 Step 4 - Creating formatting structure
[  170s] INFO     weasyprint.progress:pages.py:796 Step 5 - Creating layout - Page 1
[  170s] ____________________ test_relative_links_missing_base_link _____________________
[  170s]
[  170s]     @assert_no_logs
[  170s]     def test_relative_links_missing_base_link():
[  170s]         # Relative URI reference without a base URI: not supported for -weasy-link
[  170s]         with capture_logs() as logs:
[  170s]             pdf = FakeHTML(
[  170s]                 string='<div style="-weasy-link: url(../lipsum)">',
[  170s]                 base_url=None).write_pdf()
[  170s]         assert b'/Annots' not in pdf
[  170s]         assert len(logs) == 1
[  170s] >       assert 'WARNING: Ignored `-weasy-link: url(../lipsum)`' in logs[0]
[  170s] E       assert 'WARNING: Ignored `-weasy-link: url(../lipsum)`' in 'WARNING: Ignored `-weasy-link: url("../lipsum")` at 1:1, Relative URI reference without a base URI: \'../lipsum\'.'
[  170s]
[  170s] /home/abuild/rpmbuild/BUILD/weasyprint-53.4/tests/test_pdf.py:392: AssertionError
[  170s] ------------------------------ Captured log call -------------------------------
[  170s] INFO     weasyprint.progress:__init__.py:80 Step 1 - Fetching and parsing HTML - HTML string
[  170s] INFO     weasyprint.progress:__init__.py:64 Step 3 - Applying CSS
[  170s] WARNING  weasyprint:__init__.py:86 Ignored `-weasy-link: url("../lipsum")` at 1:1, Relative URI reference without a base URI: '../lipsum'.
[  170s] INFO     weasyprint.progress:document.py:863 Step 4 - Creating formatting structure
[  170s] INFO     weasyprint.progress:pages.py:796 Step 5 - Creating layout - Page 1
[  170s] INFO     weasyprint.progress:document.py:1088 Step 6 - Creating PDF
[  170s] INFO     weasyprint.progress:document.py:1244 Step 7 - Adding PDF metadata
[  170s] =============================== warnings summary ===============================
[  170s] ../../../../../usr/lib/python3.6/site-packages/fontTools/misc/py23.py:14
[  170s]   /usr/lib/python3.6/site-packages/fontTools/misc/py23.py:14: DeprecationWarning: The py23 module has been deprecated and will be removed in the next release. Please update your code.
[  170s]     DeprecationWarning,
[  170s]
[  170s] tests/__init__.py: 2 warnings
[  170s] tests/conftest.py: 2 warnings
[  170s] tests/test_acid2.py: 2 warnings
[  170s] tests/test_api.py: 2 warnings
[  170s] tests/test_boxes.py: 2 warnings
[  170s] tests/test_counters.py: 2 warnings
[  170s] tests/test_css.py: 2 warnings
[  170s] tests/test_css_descriptors.py: 2 warnings
[  170s] tests/test_css_validation.py: 2 warnings
[  170s] tests/test_float.py: 2 warnings
[  170s] tests/test_fonts.py: 2 warnings
[  170s] tests/test_pdf.py: 2 warnings
[  170s] tests/test_presentational_hints.py: 2 warnings
[  170s] tests/test_stacking.py: 2 warnings
[  170s] tests/test_target.py: 2 warnings
[  170s] tests/test_text.py: 2 warnings
[  170s] tests/test_unicode.py: 2 warnings
[  170s] tests/test_variables.py: 2 warnings
[  170s] tests/testing_utils.py: 2 warnings
[  170s] tests/draw/__init__.py: 2 warnings
[  170s] tests/draw/test_background.py: 2 warnings
[  170s] tests/draw/test_before_after.py: 2 warnings
[  170s] tests/draw/test_box.py: 2 warnings
[  170s] tests/draw/test_column.py: 2 warnings
[  170s] tests/draw/test_current_color.py: 2 warnings
[  170s] tests/draw/test_float.py: 2 warnings
[  170s] tests/draw/test_gradient.py: 2 warnings
[  170s] tests/draw/test_image.py: 2 warnings
[  170s] tests/draw/test_leader.py: 2 warnings
[  170s] tests/draw/test_list.py: 2 warnings
[  170s] tests/draw/test_opacity.py: 2 warnings
[  170s] tests/draw/test_overflow.py: 2 warnings
[  170s] tests/draw/test_table.py: 2 warnings
[  170s] tests/draw/test_text.py: 2 warnings
[  170s] tests/draw/test_transform.py: 2 warnings
[  170s] tests/draw/test_visibility.py: 2 warnings
[  170s] tests/draw/svg/__init__.py: 2 warnings
[  170s] tests/draw/svg/test_bounding_box.py: 2 warnings
[  170s] tests/draw/svg/test_clip.py: 2 warnings
[  170s] tests/draw/svg/test_gradients.py: 2 warnings
[  170s] tests/draw/svg/test_images.py: 2 warnings
[  170s] tests/draw/svg/test_opacity.py: 2 warnings
[  170s] tests/draw/svg/test_paths.py: 2 warnings
[  170s] tests/draw/svg/test_patterns.py: 2 warnings
[  170s] tests/draw/svg/test_shapes.py: 2 warnings
[  170s] tests/draw/svg/test_text.py: 2 warnings
[  170s] tests/draw/svg/test_visibility.py: 2 warnings
[  170s] tests/layout/__init__.py: 2 warnings
[  170s] tests/layout/test_block.py: 2 warnings
[  170s] tests/layout/test_column.py: 2 warnings
[  170s] tests/layout/test_flex.py: 2 warnings
[  170s] tests/layout/test_image.py: 2 warnings
[  170s] tests/layout/test_inline.py: 2 warnings
[  170s] tests/layout/test_inline_block.py: 2 warnings
[  170s] tests/layout/test_list.py: 2 warnings
[  170s] tests/layout/test_page.py: 2 warnings
[  170s] tests/layout/test_position.py: 2 warnings
[  170s] tests/layout/test_shrink_to_fit.py: 2 warnings
[  170s] tests/layout/test_table.py: 2 warnings
[  170s]   /usr/lib/python3.6/site-packages/flake8/plugins/manager.py:261: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
[  170s]     eps = importlib_metadata.entry_points().get(self.namespace, ())
[  170s]
[  170s] -- Docs: https://docs.pytest.org/en/stable/warnings.html
[  170s] =========================== short test summary info ============================
[  170s] FAILED tests/test_api.py::test_links - assert 'WARNING: Ignored `-weasy-link:...
[  170s] FAILED tests/test_pdf.py::test_relative_links_missing_base_link - assert 'WAR...
[  170s] ===== 2 failed, 1618 passed, 29 xfailed, 119 warnings in 119.49s (0:01:59) =====
[  170s] error: Bad exit status from /var/tmp/rpm-tmp.BtKR4V (%check)
[  170s]
[  170s]
[  170s] RPM build errors:
[  170s]     Bad exit status from /var/tmp/rpm-tmp.BtKR4V (%check)
[  170s]
[  170s] stitny failed "build python-weasyprint.spec" at Mon Nov 22 11:08:42 UTC 2021.
[  170s]
```

Complete build [log](https://github.com/Kozea/WeasyPrint/files/7580466/_log.txt) with all versions of packages used and steps taken to test.

**Comment by liZe** [comment] 2021-11-22 17:16
Hello!

This is a perfect duplicate of #1502 😁.

**Closed by liZe** 2021-11-22 17:16 UTC
