### ISSUE TITLE
xml2rfc test regression with 57.0

### ISSUE THREAD

**Issue by kitterma** [Kozea/WeasyPrint#1752] opened 2022-10-24 15:04 UTC
Since I upgraded to 57.0, xml2rfc fails its tests.  Here's a log (although I don't expect it to help much):

https://ci.debian.net/data/autopkgtest/testing/amd64/x/xml2rfc/27394437/log.gz

It's not clear to me if this is due to an issue in Weasyprint or an error in xml2rfc.  I bisected the issue on the Weasyprint side to this commit:

https://github.com/Kozea/WeasyPrint/commit/4b447d37457ff17b670715069dbc8bcb085b1786

If I add the deleted line of code back in, all the tests pass.  I verified that when the tests are running, font is weasyprint.pdf.stream.Font and last_font is None in some cases and both are weasyprint.pdf.stream.Font in others and the conditional for stream.set_font_size is executed, so I'm somewhat mystified how it could go wrong.  Any suggestions would be appreciated?

**Comment by liZe** [comment] 2022-10-24 16:31
Hi!

It’s probably a duplicate of fixed https://github.com/Kozea/WeasyPrint/issues/1748. Could you please check that it’s fixed in `master`?

**Comment by kitterma** [comment] 2022-10-24 16:58
Yes.  Works now.  Thanks.

**Closed** 2022-10-24 16:59 UTC

**Comment by kitterma** [comment] 2022-10-24 17:05
Excellent news.  Thanks.
