### ISSUE TITLE
`@font-face`: Font appears to be loading from URL, but is not displayed

### ISSUE THREAD

**Issue by RobertAKARobin** [Kozea/WeasyPrint#1331] opened 2021-04-07 15:10 UTC
My Django app uses WeasyPrint to generate PDFs on demand. I am using WeasyPrint 52.4 and Django 3.2.

I have been using system fonts, which has been working great. Now I'm trying to use local fonts. For now, I'm loading static assets through `localhost`, pointing to Django's static server, so I can watch the requests come in and make sure the right things are being loaded.

Here is how WeasyPrint is being called:

```python
font_config = weasyprint.fonts.FontConfiguration()
css = weasyprint.CSS(url='http://localhost:8000/static/kits/static/report.css', font_config=font_config)
return weasyprint.HTML(
    string='<h1>Hello world</h1>',
    encoding='utf-8',
).write_pdf(
    stylesheets=[css],
    font_config=font_config,
)
```

Here is my CSS:

```css
@font-face {
  font-family: 'foobar';
  src: url(http://localhost:8000/static/Oxygen-Regular.ttf) format('truetype');
  font-weight: 400;
}

@font-face {
  font-family: 'foobar';
  src: url(http://localhost:8000/static/Oxygen-Bold.ttf) format('truetype');
  font-weight: 700;
}

:root {
  font-family: 'foobar', sans-serif;
  color: red;
}
```

The text is correctly colored red, so I know the CSS is being loaded. I can see from my server logs that the requests for the fonts are successful, which indicates to me that WeasyPrint is fetching the fonts correctly:

```txt
2021-04-07 09:57:32,147	INFO	"GET /static/mycss.css HTTP/1.1" 200 5748
2021-04-07 09:57:32,193	INFO	"GET /static/Oxygen-Regular.ttf HTTP/1.1" 200 46440
2021-04-07 09:57:32,200	INFO	"GET /static/Oxygen-Bold.ttf HTTP/1.1" 200 47096
```

But the PDF is showing the fallback `sans-serif` font. What am I missing?

**Comment by RobertAKARobin** [comment] 2021-04-07 16:39
I added logging:

```txt
2021-04-07 11:37:20,704	INFO	Step 2 - Fetching and parsing CSS - http://localhost:8000/mycss.css
2021-04-07 11:37:20,704	INFO	Step 2 - Fetching and parsing CSS - http://localhost:8000/mycss.css
2021-04-07 11:37:20,707	INFO	"GET /static/mycss.css HTTP/1.1" 200 5749
2021-04-07 11:37:20,718	WARNING	Font-face "foobar" cannot be loaded
2021-04-07 11:37:20,721	INFO	"GET /static/Oxygen-Bold.ttf HTTP/1.1" 200 47096
2021-04-07 11:37:20,732	INFO	Step 1 - Fetching and parsing HTML - HTML string
2021-04-07 11:37:20,732	INFO	Step 1 - Fetching and parsing HTML - HTML string
2021-04-07 11:37:20,736	INFO	Step 3 - Applying CSS
2021-04-07 11:37:20,736	INFO	Step 3 - Applying CSS
2021-04-07 11:37:20,737	INFO	Step 4 - Creating formatting structure
2021-04-07 11:37:20,737	INFO	Step 4 - Creating formatting structure
2021-04-07 11:37:20,737	INFO	Step 5 - Creating layout - Page 1
2021-04-07 11:37:20,737	INFO	Step 5 - Creating layout - Page 1
2021-04-07 11:37:20,771	INFO	Step 6 - Drawing
2021-04-07 11:37:20,771	INFO	Step 6 - Drawing
2021-04-07 11:37:20,771	INFO	Step 7 - Adding PDF metadata
2021-04-07 11:37:20,771	INFO	Step 7 - Adding PDF metadata
2021-04-07 11:37:20,776	INFO	"GET /mypdf"
```

**Comment by RobertAKARobin** [comment] 2021-04-07 16:40
The fonts are from https://fonts.google.com/specimen/Oxygen

**Comment by liZe** [comment] 2021-04-07 16:52
As explained on Gitter, it’s a duplicate of #1318.

**Closed by liZe** 2021-04-07 16:52 UTC
