### ISSUE TITLE
Euro Symbol problem

### ISSUE THREAD

**Issue by AndreMPCosta** [Kozea/WeasyPrint#1379] opened 2021-06-09 14:23 UTC
So I'm parsing an HTML file to PDF using Weasyprint. But there is this weird problem:

```html
       <tr>
            <td></td>

            <td></td>

            <td> Taxes 23%:
            4.87 €
            </td>
        </tr>
        <tr class="total">
            <td></td>

            <td></td>

            <td>Total: 40.65 €</td>
        </tr>
```

If I put the euro symbol on the last tr, I get an error while trying to open the PDF, (135). But I use the € symbol on the previous row without any issues. I can't comprehend how is this happening, since it works fine on the other row.

Output without using it on the last row:
![](https://i.imgur.com/HesH5KV.png)

**Comment by liZe** [comment] 2021-06-09 14:29
Hello!

Could you please attach your broken PDF? Your problem is probably a duplicate of #1292.

**Comment by AndreMPCosta** [comment] 2021-06-09 14:30
[60b9fc96d8f60d52a97e05cf.pdf](https://github.com/Kozea/WeasyPrint/files/6624557/60b9fc96d8f60d52a97e05cf.pdf)

Sure here it is.

**Comment by liZe** [comment] 2021-06-09 16:25
> Sure here it is.

It’s a duplicate of #1292. You can follow the solutions in the comments and the issues linked to #1292 (downgrading Cairo to 1.17.2, apply a patch, etc.) to fix this problem.

**Closed by liZe** 2021-06-09 16:25 UTC

**Comment by AndreMPCosta** [comment] 2021-06-09 16:45
I don't see any dependencies with Cairo, when I install Weasyprint I get CairoSVG (2.5.2) and cairocffi (1.2.0), so downgrading Cairo won't work here, because it does not depend on it.
