### ISSUE TITLE
pdf2htmlex and weasyprint compatibility: one page pdf

### ISSUE THREAD

**Issue by tang0mani** [Kozea/WeasyPrint#1041] opened 2020-01-24 16:20 UTC
Anyone ever try using weasyprint on a converted file from pdf2htmlex? Opening the html file, there doesn't seem to be any issues with it (table of content, etc, seem to work). However, the resulting converted pdf file always results in one page, scaled to 80% the normal size. The rest of the file doesn't seem to show up.

**Comment by liZe** [comment] 2020-01-24 16:44
Hi!

(PDF to HTML to PDF, WOW!)

The HTML and CSS generated by pdf2htmlex are really adapted for screen, not for print, so you’ll probably need to fight for a long time before getting perfect rendering with WeasyPrint.

But.

You can get better results, at least by removing the `#page-container { position:absolute }` rule (see #36 to know why).

If you can provide a specific example, I can try to find other possible solutions.

**Comment by tang0mani** [comment] 2020-01-24 17:22
I'm sorry, but where exactly would I be able to find that code snippet? I tried looking through the files inside layout, and but I can't seem to find it.

**Comment by liZe** [comment] 2020-01-24 18:54
> I'm sorry, but where exactly would I be able to find that code snippet? I tried looking through the files inside layout, and but I can't seem to find it.

By code snippet, I mean an example of HTML+CSS document generated by pdf2htmlex, so that I can understand your exact needs.

**Comment by tang0mani** [comment] 2020-01-31 15:27
Just read up a little more on pdf2htmlex, and now I understood what you meant in your initial reply. The conversion with weasyprint works better now! Only the formatting with some of the tables and images seem to be formatted incorrectly in the conversion- will see if there's anything else in the css that might help. Thanks!

**Comment by liZe** [comment] 2020-01-31 15:34
> Only the formatting with some of the tables and images seem to be formatted incorrectly in the conversion- will see if there's anything else in the css that might help. Thanks!

Dont hesitate to open new issues with HTML+CSS snippets if you find bugs that are not already reported. I’m closing this issue now, as it’s more or less a duplicate of #36.

**Closed by liZe** 2020-01-31 15:34 UTC
Labels: CSS question
