### ISSUE TITLE
MacOS Preview won't open exported PDF's larger than 17MB (but opens in Chrome)

### ISSUE THREAD

**Issue by charliesneath** [Kozea/WeasyPrint#1960] opened 2023-09-08 14:44 UTC
I'm using weasyprint inside of a Django web app. The Django app downloads photos from Dropbox, generates layouts using Django templates, and then exports a PDF generated by weasyprint.

Until recently, I was able to export and open on my MacBook PDF's with file sizes of many 100's of MB's (many photos) without issue. PDF generation would take a while but it would ultimately deliver what I expected.

Now, when the exported PDF's are larger than 17MB, MacOS's Preview app won't open them. I've done everything I can to confirm it's not an issue with the HTML layout or image files through various permutations of the images and templates used. 

I am able to open the PDF's in Chrome and all images are shown as expected. I need some of Preview's PDF utilities so this won't suffice.

My most recent test downloads a set of images from a Dropbox folder, and then generates a PDF with 1 images, 2 images, 3 images, etc.

When the generated PDF filesizes are below 17MB, I can open the files in preview. See below for the results of the export test with first broken PDF highlighted. The PDF's less than 17MB open without issue.

<img width="398" alt="image" src="https://github.com/Kozea/WeasyPrint/assets/606854/11be8600-97cc-49e5-a93c-86c9a845cff4">

When I try to open the highlighting PDF, I get the following error.

<img width="288" alt="image" src="https://github.com/Kozea/WeasyPrint/assets/606854/a8da86c7-db39-4f3c-b5f7-e92c222f1b27">

I've replicated this on an older MacBook and get the same behavior

I assume there is something happening with memory usage, but I don't have enough knowledge of these systems to understand how to debug further, and don't know if there is any particular significance to the 17MB threshold.

A sample of code is below.

I've replicated behavior on these 2 machines:

- Macbook Air M2 with MacOS 14.0 Beta
- 2016 MacBook Pro with MacOs 12.5.1

Please let me know what additional information would help debug this.

---

```
def generate_pdf(request, template):
    base_url = request.build_absolute_uri("/")
    pdf_buffer = io.BytesIO()
    HTML(string=template, base_url=base_url).write_pdf(pdf_buffer)
    pdf_buffer.seek(0)

    return pdf_buffer

def pdf_test(photos):

    for i in range(len(photos)):
        template = render_to_string(
            "pdf-test.djhtml",
            context={
                "photos": photos[:i], # Trim the list of photos based on loop iteration
            },
        )

        pdf = generate_pdf(request, template)

        with open(
            "pdf-debug-{i}.pdf",
            "wb",
        ) as f:
            f.write(pdf.read())

    return HttpResponse()
```

**Comment by liZe** [comment] 2023-09-08 16:27
Hi!

That’s probably a duplicate of #1938 and #1900. Could you try to update pydyf to version 0.7.0?

**Comment by charliesneath** [comment] 2023-09-08 18:16
That did the trick, thank you!

**Closed** 2023-09-08 18:27 UTC
