### ISSUE TITLE
Tailwind color codes are incompatible

### ISSUE THREAD

**Issue by andreasnuesslein** [Kozea/WeasyPrint#2155] opened 2024-05-16 19:23 UTC
Hi all!, thanks for weasyprint :heart: 

So, I'm using weasyprint v62.1 with Tailwind 3.4.1, and the issue that I'm having is that all the color codes Tailwind generates seem to be incompatible. 

First I thought it was #1998 but it turns out the problem seems to be different.

Tailwind takes e.g. `bg-red-500` and turns it into this:
```css
background-color: rgb(239 68 68 / var(--tw-bg-opacity));
```
 which does not render. I can however force Tailwind to put `/ 1` by using `bg-red-500/100`, which gives me:
```css
background-color: rgb(239 68 68 / 1);
```

Both don't work.

The problem seems to be the format. If I manually put: 
```css
background-color: rgba(239,68,68,1);
```
it works.

(I'm gonna see if I can tell tailwind to use the other format.)

Thank you!

**Comment by andreasnuesslein** [comment] 2024-05-16 19:32
okay, using `postcss-preset-env` fixed that issue too, after all. it generates the required `rgba(239, 68, 68, 1);`

**Comment by liZe** [comment] 2024-05-19 07:52
Hi!

Thank you for this report. This is actually a missing feature of tinycss2 (https://github.com/Kozea/tinycss2/issues/47), and a duplicate of #1630.

**Closed by liZe** 2024-05-19 07:52 UTC
