### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by hashemsawlan** [Kozea/WeasyPrint#2060] opened 2024-02-08 19:42 UTC
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

**Comment by liZe** [comment] 2024-02-08 21:08
Hi.

That’s a duplicate of the last open issue (#2057), please search in open issues before opening a new one.

**Closed by liZe** 2024-02-08 21:08 UTC
