### ISSUE TITLE
Support font-variant: small-caps approximation

### ISSUE THREAD

**Issue by meunierd** [Kozea/WeasyPrint#166] opened 2014-02-04 16:25 UTC
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant

If a font doesn't provide actual small caps, weasyprint should do Mozilla's scaling trick.

**Comment by joostrijneveld** [comment] 2015-11-08 11:21
There appear to be two issues on this topic: see https://github.com/Kozea/WeasyPrint/issues/123. I figured I'd just refer to the other one here for completeness.

**Comment by liZe** [comment] 2016-09-12 22:37
Let's say it's a duplicate of #123.

**Closed by liZe** 2016-09-12 22:37 UTC
Labels: feature
