### ISSUE TITLE
Error: stroke="currentColor" on svg tag not handled

### ISSUE THREAD

**Issue by Vayel** [Kozea/WeasyPrint#1572] opened 2022-02-17 11:24 UTC
Hi!

I've got this svg from https://heroicons.com/:

```
<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
</svg>
```

The `stroke="currentColor"` attribute is attached to `svg` and not to `path`. When I run weasyprint on this, I get the Python exception:

```
ValueError: too many values to unpack (expected 4)
```

in [`weasyprint/svg/__init__.py, line 621, in fill_stroke `](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/svg/__init__.py#L610)

If I move the `stroke="currentColor"` attribute to the `path` element, it works.

Is it possible to handle `currentColor` on the svg tag?

Many thanks!

**Comment by liZe** [comment] 2022-02-17 12:15
Hi!

It’s actually a duplicate of #1497, I’ve renamed the issue for clarification.

**Closed by liZe** 2022-02-17 12:15 UTC

**Comment by Vayel** [comment] 2022-02-17 13:00
Thanks @liZe! I saw that issue but the given example is with `currentColor` applied to `path`. As it already works with `path` but not with `svg`, I though my problem was a slightly different one.

**Comment by liZe** [comment] 2022-02-17 20:11
The problem is always the same: the current color of the HTML state is not given to the SVG renderer. We’ll only keep one issue open, even if it breaks many use cases.
