### ISSUE TITLE
Image not showing up in PDF

### ISSUE THREAD

**Issue by kas03** [Kozea/WeasyPrint#657] opened 2018-07-20 13:28 UTC
I am working on a reporting solution, building reports using html and css and using weasyprint to get them to pdf. I am doing this through Amazon Sagemaker and building the html using BeautifulSoup.

I need to get an image into the pdf, but adding it to the html like below doesn't work:
`img = soup.new_tag('img')`
`img['src'] = 'img.jpg'`

Usually when using SageMaker I just reference the file name (when saved in the same folder as the script as is the case here) and everything works swimmingly.

I started thinking that maybe I just needed to base64 encode the image and put that directly in the html, which I've seen in other examples, like below:

`img = soup.new_tag('img')`
`img['src'] = 'data:image/jpeg;base64,' + image_data`

Where image_data is the base64 encoded image. I know this works because I open the html file in a browser and see the image, but am still seeing my alt=xxx in the pdf.

**Comment by liZe** [comment] 2018-07-21 16:33
Could you try to use a PNG image instead of a JPG? If it works, it means that there's something wrong with gdk-pixbuf.

**Comment by liZe** [comment] 2018-07-30 14:31
@kas03 ping?

**Comment by kas03** [comment] 2018-07-31 12:42
Apologies for the delay. This does in fact work with a .png file.

**Comment by liZe** [comment] 2018-07-31 12:57
> Apologies for the delay.

No problem!

> This does in fact work with a .png file.

Actually, your problem is a duplicate of #428, you have to install gdk-pixbuf but it's not available in AWS packages.

I've never used AWS and don't know what to do to help you. Compiling gdk-pixbuf seems to be the way to go until Amazon provides the package. If you find a way to make this work or would like some help, please add a comment to #428.

**Closed by liZe** 2018-07-31 12:57 UTC
