### ISSUE TITLE
Update the documentation to advertise var() not being supported in shorthand and multi-values properties

### ISSUE THREAD

**Issue by FrancoisCapon** [Kozea/WeasyPrint#1616] opened 2022-03-26 18:51 UTC
Hi!

Me again, as you can see variables are not supported in the shorthand declaration:
![2022-03-26--17-25](https://user-images.githubusercontent.com/46624375/160248487-972b1f01-b507-4fa8-ae70-554cee9fb636.png)
It's because `<Function Block var( … )>` are not evaluated in the shortand expand processus.

I take a look to the code, I think that is impossible without change a lot of thing: in the example above [`expand`](https://github.com/Kozea/WeasyPrint/blob/fe1f3d9e98325162858e8f3f2dd59d8f24803516/weasyprint/css/validation/__init__.py#L116) of  `#three` is called before [`preprocess_declarations`](https://github.com/Kozea/WeasyPrint/blob/fe1f3d9e98325162858e8f3f2dd59d8f24803516/weasyprint/css/validation/__init__.py#L54) of `body`.

So I suggest to add this little restriction  of the usage of `var()`in the documentation, for example in: :sunglasses: 
* [CSS Custom Properties for Cascading Variables Module Level 1](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#css-custom-properties-for-cascading-variables-module-level-1)
* [Parsing CSS](https://doc.courtbouillon.org/weasyprint/stable/going_further.html#parsing-css)

instead of trying to adapt the code to support this :sweat:.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test CSS shorthand properties</title>
</head>
<body>
    <h1>Test CSS shorthand properties</h1>
    <div id="one">
        <pre>
body {
    --color-background: lightgreen;
    --color-border: forestgreen;
}

#one {
    background: lightgreen;
    border: solid 2px forestgreen;
}           
</pre>
    </div>
    <div id="two">
<pre>
#two {
    background-color: var(--color-background);
    border: solid 2px;
    border-color: var(--color-border);
}
</pre>
    </div>
    <div id="three">
<pre>
#three {
    background: var(--color-background);
    border: solid 2px var(--color-border);
}
</pre>
    </div>
    <pre>
# weasyprint -v -s test.css test.html test.pdf
INFO: Step 1 - Fetching and parsing HTML - test.html
INFO: Step 2 - Fetching and parsing CSS - CSS string
WARNING: Ignored `background: var(--color-background)` at 34:5, invalid value.
WARNING: Ignored `border: solid 2px var(--color-border)` at 35:5, invalid value.
INFO: Step 3 - Applying CSS
INFO: Step 4 - Creating formatting structure
INFO: Step 5 - Creating layout - Page 1
INFO: Step 6 - Creating PDF
INFO: Step 7 - Adding PDF metadata</pre>
</body>
</html>
``` 

```css
h1 {
    text-align: center;
}
div {
    width: 100%;
    height: 5cm;
    box-sizing: border-box;
    margin: auto;
    background-color: red;
    margin-bottom: 1cm;
    border: dotted 10px darkred;
}
#one {
    background: lightgreen;
    border: solid 2px forestgreen;
}
#two {
    background-color: var(--color-background);
    border: solid 2px;
    border-color: var(--color-border);
}
#three {
    background: var(--color-background);
    border: solid 2px var(--color-border);
}
pre {
    padding: 0.5rem;
    font-size: 0.8rem;
} 
div > pre {
    margin: 1rem;
}
body > pre {
    background-color: orange;
}
/* variables set after usage */
body  {
    --color-background: lightgreen;
    --color-border: forestgreen;
    padding: 0;
    margin: 0;
}
```

**Comment by liZe** [comment] 2022-03-26 19:52
Hi!

Yes, that’s actually a duplicate of #1219.

> I take a look to the code, I think that is impossible without change a lot of thing

I agree, that’s more or less the conclusion of [this comment](https://github.com/Kozea/WeasyPrint/issues/1219#issuecomment-699857746).

> So I suggest to add this little restriction of the usage of `var()`in the documentation, for example in

I agree. Adding a comment in the chapter of your first link is a good idea.

**Closed** 2022-04-03 17:43 UTC
Labels: documentation
