### ISSUE TITLE
IndexError: tuple index out of range with weasyprint 50

### ISSUE THREAD

**Issue by stefanw** [Kozea/WeasyPrint#953] opened 2019-09-27 09:11 UTC
After upgrading to 50 from 49 I got the following error when generating a PDF:

```
IndexError: tuple index out of range
[...]
  File "weasyprint/layout/blocks.py", line 63, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "weasyprint/layout/blocks.py", line 77, in block_level_layout_switch
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "weasyprint/layout/blocks.py", line 130, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "weasyprint/layout/blocks.py", line 376, in block_container_layout
    for line, resume_at in lines_iterator:
  File "weasyprint/layout/inlines.py", line 53, in iter_line_boxes
    absolute_boxes, fixed_boxes, first_letter_style)
  File "weasyprint/layout/inlines.py", line 70, in get_next_linebox
    skip_stack = skip_first_whitespace(linebox, skip_stack)
  File "weasyprint/layout/inlines.py", line 210, in skip_first_whitespace
    result = skip_first_whitespace(box.children[index], next_skip_stack)

```

Downgrading to 49 prevents this error.
Possibly similar to #783? I will try to come up with a test case when I find some time.

**Comment by liZe** [comment] 2019-09-27 13:28
Thanks for reporting.

Could you please provide an HTML document causing this error?

**Comment by Tontyna** [comment] 2019-09-27 14:42
I'm curious whether this is a new incarnation of the *prime number bug* or a regression introduced by f1b1d140e258b3cba51a9fcbb91c5f688641a30f

**Comment by stefanw** [comment] 2019-09-27 15:33
Mh, I just tried to reproduce and cannot do it. Possibly my setup was broken in some other way? I'll reopen if I see this again.

**Comment by Tontyna** [comment] 2019-09-27 21:37
Here's a snippet that crashes with `IndexError: tuple index out of range`:

```html
<p style="font-family: monospace; width:10.5ch;">
line 1<br><span>123 567 90</span>x
</p>
```

Again a **special width** is required. And a linebreak. And a span that fills exactly one line, trailed by some more non-whitespace.

Removing "line 1" from the snippet, `AssertionError: assert next_skip_stack is None` is raised:

```html
<p style="font-family: monospace; width:10.5ch;">
<br><span>123 567 90</span>x
</p>
```

Instead of a single `<br>` we can fill the first line with letters to trigger the `AssertionError`:

```html
<p style="font-family: monospace; width:10.5ch;">
123 567 90 <span>123 567 90</span>x
</p>
```

Unlike #923 there are no punctuation marks involved.

**Comment by Tontyna** [comment] 2019-09-28 00:18
And yes: Neither the **tuple error** nor this special **AssertionError** happen in v49, these crashes were introduced by f1b1d140e258b3cba51a9fcbb91c5f688641a30f.

As it is written: "adding skip stacks is a bit complicated".

@liZe, if you want, I can provide some more funny snippets not yet in `test_breaking_linebox_regression_*`. They crash or freeze or render strange things without f1b1d140e258b3cba51a9fcbb91c5f688641a30f

**Comment by Tontyna** [comment] 2019-10-01 22:44
In f1b1d14 the check for `same_broken_child` was removed. Dunno why. Probably because it was complicated and error prone and `test_breaking_linebox_regression_*` all passed. 

But for the above 3 snippets https://github.com/Kozea/WeasyPrint/issues/953#issuecomment-536104571 the stack arithmetic calculates a crashing skip stack. 

To understand what should be done to **merge** the original and the partial stack I rendered and debugged various error prone html fragments.

The only thing I'm 100% sure about now is: The first number in the returned `resume_at` must be the `child_index`.
The rest depends on how the (pre-split) child that is passed to `split_inline_level()` actually is related to the original box. But I cannot think of a trustworthy method how to detect that relationship.

IMHO addition of two skip numbers is only the correct operation when both skip stack parts denote the same TextBox. Because otherwise we add child indices :boom: not letter positions.
Probably, when one of the numbers equals zero the addition is innocuous, too.

**Comment by stefanw** [comment] 2019-10-10 12:10
I got hit again and was able to kind of isolate it to this HTML snippet:
```python
import weasyprint as wp
print(wp.__version__)
s = '''<!doctype html>
<html>
  <head>
    <meta charset="utf-8">

  </head>

  <body>
      <section>

<p>-----Ursprüngliche Nachricht-----<br>Von: Antragsteller [#167099] [mailto:email@example.org] <br>Gesendet: Montag, 23. September 2019 09:55<br>An: Transparenzgesetz (HmbBfDI) &lt;<a href="mailto:transparenzgesetz@datenschutz.hamburg.de">transparenzgesetz@datenschutz.hamburg.de</a>&gt;<br>Betreff: [EXTERN]- Zuständigkeit für Meldeportal der AfD [#167099]</p>

      </section>

  </body>
</html>'''
wp.HTML(string=s).write_pdf()
> IndexError: tuple index out of range
```
No styling is applied.

Curiously, this error does **not** happen on my local machine, just on the server Ubuntu 18.04 (weasyprint==50 for both).

Dependencies on server with error:
- libcairo2 == 1.15.10-2ubuntu0.1
- libpango == 1.40.14-1ubuntu0.1
- gdk-pixbuf == 2.36.11-2

Dependencies locally on macos via homebrew:
- cairo == 1.16.0
- pango == 1.44.5
- gdk-pixbuf == 2.38.1

**Comment by Tontyna** [comment] 2019-10-10 13:20
@stefanw would be great if you could test your snippet on both systems with the `line_breaking_tests` branch.

**Comment by stefanw** [comment] 2019-10-10 16:41
I can confirm the `line_breaking_tests` branch works on the server system for the case I posted.

**Comment by elidupree** [comment] 2019-11-03 02:58
I've just started trying to convert a novel of mine from HTML to PDF, and quickly ran into this error (or at least, what I think is the same error). Here's the minimal test case I've been able to reproduce:

```python
from weasyprint import HTML
HTML (string = '''<!DOCTYPE html>
<html>
  <head>
    <style>
@page {
  size: 6in 9in;
  margin: 0.75in;
}
    </style>
  </head>
  <body>
I opened my mouth to yell another retort, but Yali's hand fell heavily on my shoulder. "It's okay. He was in less danger than you both realize. Since his injuries weren't inflicted with <em>hostile intent</em>, they only damaged his body, never his soul. And the body can recover from almost anything, through manifesting." When she said <em>hostile intent</em>,
  </body>
</html>''').write_pdf ()
```

with the output
```
Traceback (most recent call last):
  File "./render_ravelling_wrath_book.py", line 25, in <module>
    </html>''').write_pdf ()
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/__init__.py", line 211, in write_pdf
    font_config=font_config).write_pdf(
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/__init__.py", line 168, in render
    font_config)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/document.py", line 393, in _render
    [Page(page_box, enable_hinting) for page_box in page_boxes],
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/document.py", line 393, in <listcomp>
    [Page(page_box, enable_hinting) for page_box in page_boxes],
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/__init__.py", line 126, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/pages.py", line 803, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/pages.py", line 742, in remake_page
    page_number, page_state)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/pages.py", line 553, in make_page
    positioned_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 63, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 77, in block_level_layout_switch
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 130, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 510, in block_container_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 63, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 77, in block_level_layout_switch
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 130, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 510, in block_container_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 63, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 77, in block_level_layout_switch
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 130, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 376, in block_container_layout
    for line, resume_at in lines_iterator:
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/inlines.py", line 53, in iter_line_boxes
    absolute_boxes, fixed_boxes, first_letter_style)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/inlines.py", line 70, in get_next_linebox
    skip_stack = skip_first_whitespace(linebox, skip_stack)
  File "/n/HOME/.local/lib/python3.7/site-packages/weasyprint/layout/inlines.py", line 210, in skip_first_whitespace
    result = skip_first_whitespace(box.children[index], next_skip_stack)
IndexError: tuple index out of range
```

With other variations, I also encountered the same AssertionError as above.

Downgrading to weasyprint 49 successfully worked around this, and also worked around unreasonably large conversion times that I had with weasyprint 50 (in 50, rendering 25% of my novel took 50 seconds, and rendering 50% ran over 20 minutes; in 49, rendering the entire novel took only 30 seconds.)

**Comment by Tontyna** [comment] 2019-11-03 12:56
@elidupree your snippet (and probably your novel) doesnt crash anymore when #956 is merged.

I'd be interested whether #956 also sanitizes the conversion time -- is it possible for you to render your novel with that patch and tell what happens?

**Comment by elidupree** [comment] 2019-11-03 17:06
I'd love to test that. How do I do it? I can do the installation descrived [here]( https://weasyprint.readthedocs.io/en/stable/hacking.html), but I don't know how to do it with the pull request merged.

**Comment by Tontyna** [comment] 2019-11-03 17:45
If you have your own fork of WeasyPrint you could merge this PR into your fork etc. pp, but the simplest way is to clone my fork and check out the PR's branch:

```
git clone https://github.com/Tontyna/WeasyPrint.git -b skip_crash
```

**Comment by hlolli** [comment] 2019-11-03 18:33
I think I'm also getting this error

```
  File "/nix/store/bm5fbfhpp0d57qhqxhkmy3lb94h93zdh-python3.7-weasyprint-50/lib/python3.7/site-packages/weasyprint/layout/inlines.py", line 210, in skip_first_whitespace
    result = skip_first_whitespace(box.children[index], next_skip_stack)
IndexError: tuple index out of range
Error producing PDF.
```

Would be nice to see your PR merged.

**Comment by elidupree** [comment] 2019-11-03 22:41
I tried it out, and #956 **does** fix the conversion time! Back the 30seconds for the whole novel, just like in WeasyPrint 49.

**Closed** 2019-11-07 09:34 UTC
Labels: crash
