### ISSUE TITLE
Unexpected horizontal whitespace

### ISSUE THREAD

**Issue by Kodiologist** [Kozea/WeasyPrint#628] opened 2018-05-10 00:24 UTC
Running WeasyPrint 0.42.3 on Python 3.6.5 and Ubuntu 18.04, I occasionally see odd horizontal gaps in documents. Here's an example that's about as minimal as I can make it:

    <!DOCTYPE html>

    <html lang="en-US">
    <head>
    <meta charset="UTF-8">
    <title>foo</title>
    <style>

    body
       {font-family: "Times New Roman";
        font-size: 12pt;}

    </style></head><body>

    <p>Xyzz, B. B., <b>Smith A.</b> <i>Hello world</i>.</p>

    </body>
    </html>

The generated PDF looks like this in Okular 1.3.3 (200% zoom):

![Screenshot](https://i.imgur.com/cwoaOID.png)

Why is there a lot of whitespace after "Smith A."?

**Comment by Tontyna** [comment] 2018-05-12 08:29
OMG! Is this another Pango?
Cant reproduce the gap. WeasyPrint 0.42.3, Python 3.6.4, Pango 1.40.11, Windows 7 (64bit)

**Comment by Tontyna** [comment] 2018-05-12 08:39
Is "Times New Roman, 12pt" a prerequisite to produce the space?

**Comment by Tontyna** [comment] 2018-05-12 22:13
What happens when you change the font-family to
```css
font-family: "Times New Roman, serif";
```

I'm almost shure that this is a Pango feature - what's the version of your  Pango?

**Comment by Kodiologist** [comment] 2018-05-12 22:17
The gap's still there.

How do I tell what version of Pango I'm using? Does it have a Python package?

**Comment by Tontyna** [comment] 2018-05-12 23:06
```python
from weasyprint.text import pango

print('pango:', pango.pango_version())
```

**Comment by Kodiologist** [comment] 2018-05-12 23:08
Thanks, I got `pango: 14014`, which I guess would be 1.40.14.

**Comment by Tontyna** [comment] 2018-05-12 23:46
Hmm... something weird with the fonts? "Arial" and "Times New Roman" sounds windowish to me...
 
Not shure whether I'll see anything, but could you upload the buggy PDF?

**Comment by Kodiologist** [comment] 2018-05-12 23:48
Sure: [test.pdf](https://github.com/Kozea/WeasyPrint/files/1998015/test.pdf)

**Comment by Tontyna** [comment] 2018-05-13 10:27
Analyzing your PDF I can see that after the bold **Smith A.** instead of just printing a space char and then the italic *Hello world!* (like my PDF does) there is a command to advance the output position to the right. That's the gap.

When WeasyPrint paginates the HTML it gives every TextBox an x- and y-position on the page. Those positions are calculated with the help of Pango/Cairo.
To get the horizontal position of *Hello world!* WeasyPrint asks Pango how wide the bold Mr. Smith is.

Looks to me as if your Pango gets the size of text formatted with "Times New Roman, bold" font wrong.

To verify or falsify this hypothesis, please execute the following snippet:

```Python
import weasyprint.css

from weasyprint.css.properties import INITIAL_VALUES
from weasyprint.text import split_first_line

_needsStyleDict = 'StyleDict' in dir(weasyprint.css)

def calc_text_width(text, font_family, font_weight=None):
    new_style = dict(INITIAL_VALUES)
    new_style['font_family'] = font_family.split(',')
    new_style['font_size'] = 12
    if _needsStyleDict:
        new_style = weasyprint.css.StyleDict(new_style)
    if font_weight == 'bold':
        new_style['font_weight'] = 700
    _, _, _, width, _, _ = split_first_line(
        text, new_style,
        context=None, max_width=None,
        justification_spacing=0)
    return width

def print_text_width(text, font_family):
    width = calc_text_width(text, font_family)
    print(font_family, 'normal:', width)
    width = calc_text_width(text, font_family, 'bold')
    print(font_family, '  bold:', width)
    print('')

snippet = 'Smith A.'
print_text_width(snippet, 'Times New Roman')
print_text_width(snippet, 'serif')
# print_text_width(snippet, 'DejaVu Sans')
# print_text_width(snippet, 'Arial')
# print_text_width(snippet, 'sans-serif')
```

Gives me:
```
Times New Roman normal: 43.341796875
Times New Roman   bold: 45.33984375

serif normal: 52.283203125
serif   bold: 57.85546875
```
I excpect your bold Times will be something around 90...

**Comment by Kodiologist** [comment] 2018-05-13 14:52
It looks like both roman and bold are large:

    Times New Roman normal: 133.009765625
    Times New Roman   bold: 135.0078125

    serif normal: 52.283203125
    serif   bold: 57.85546875

**Comment by liZe** [comment] 2018-05-13 15:36
I can reproduce on Ubuntu 18.04.

Swapping the `b` and the `i` tags puts the space after the `i` tag, so the problem is not in the bold font.

I have the same problem with Arial (another MS font), but not with DejaVu or Liberation fonts.

**Comment by liZe** [comment] 2018-05-13 15:49
OK, there's only a problem when the string ` A` (space + upper a) is in the text. I suppose there's something wrong between MS kerning tables and Pango.

**Comment by Tontyna** [comment] 2018-05-13 15:53
Reminds me of the rendering issues I had with the Linux fonts on Windows when my fontconfig was not active - see 4. Broken fonts in #587

**Comment by Tontyna** [comment] 2018-05-13 17:59
Sounds like the culprit isnt Pango but Cairo, or rather the cairo.PDFSurface.
No chance to work around that within WeasyPrint.

BTW: On my system the output of 'weasyprint.tests.test_acid2.test_acid2()` only looks perfect as PNG, when rendered as PDF the smiley is still disrupted.

**Comment by liZe** [comment] 2018-05-13 19:29
> On my system the output of 'weasyprint.tests.test_acid2.test_acid2()` only looks perfect as PNG, when rendered as PDF the smiley is still disrupted.

If you get something like that, it's normal (it's even explained in WeasyPrint's home page):
![capture d ecran de 2018-05-13 21-27-41](https://user-images.githubusercontent.com/952243/39971013-86b05e94-56f4-11e8-9901-795ac6a82360.png)

**Comment by Tontyna** [comment] 2018-05-13 20:35
Yes, that's how it looks like.

Furthermore it looks like it's Cairo that decides whether (instead of a simple  `Tj`) a `TJ` operator is emitted in the PDF and what the amount of horizontal relocation should be. Couldnt find in the Cairo source code what algorithm it uses to calculate the glyphs' advances...
Let's hope Cairo asks Pango -- Pango's release frequency is higher :grimacing:

**Comment by MindFluid** [comment] 2019-03-20 01:10
I'm reproducing this issue on Cairo 1.16.0.0, it does not occur in 1.15.10

**Comment by liZe** [comment] 2019-03-20 22:22
As said in #770, the problem appears when we generate PDF documents including some Windows fonts (at least Arial and Times) with a text including special kerning pairs (' A' (space + A) in the original example).

The bug is probably either in the fonts, in Pango or in Cairo.

**Comment by MindFluid** [comment] 2019-03-21 00:58
Sorry, I should be more clear. I'm trying to provide a workaround for people that arrive here looking for one.
**I believe Cairo is the issue.** I have not tested with the latest version of Cairo, but 1.15.10 does not suffer the issue. _(Changing the Pango version did not reproduce the error with special kerning pairs)_

**Comment by liZe** [comment] 2019-03-21 12:54
> I'm reproducing this issue on Cairo 1.16.0.0, it does not occur in 1.15.10

I've tried hard to reproduce on Gentoo using various 1.14.x, 1.15.x and 1.16.0 versions, but I can't. I've only reproduced on Ubuntu 18.04 with … cairo 1.15.10 (true story).

@MindFluid What's your OS (+distribution)?

I'm not convinced yet that the bug is in cairo.

**Comment by liZe** [comment] 2019-03-21 13:01
It works on Arch too with cairo 1.16.0.
[test.pdf](https://github.com/Kozea/WeasyPrint/files/2992099/test.pdf)

**Comment by MindFluid** [comment] 2019-03-22 05:35
I am *not* reproducing error with `Cairo 1.15.x` on `Ubuntu 18.04.1 LTS`
I am reproducing on `Cairo 1.16.x` on `Ubuntu 14.04.6 LTS`

**Comment by liZe** [comment] 2019-03-22 09:46
> I am _not_ reproducing error with `Cairo 1.15.x` on `Ubuntu 18.04.1 LTS (bionic)`
> I am reproducing on Cairo 1.16.x on Alpine Linux v3.8

For the record: I am reproducing with cairo 1.15.10 on Ubuntu 18.04.2 LTS.

[table.pdf](https://github.com/Kozea/WeasyPrint/files/2995865/table.pdf)

I use exactly the same fonts everywhere.

I'm starting to think that it comes from some font-related configuration, not from a specific version of some library.

**Comment by MindFluid** [comment] 2019-04-01 05:22
Yeah, currently I'm working around it on the product environment by avoiding references to MS Fonts -- actually just using a default fallback font of `font-family: sans-serif` 😂

I hope we can get to the bottom of this soon.

**Comment by liZe** [comment] 2019-04-01 09:30
I've tried various versions, configurations and compilation options of freetype and fontconfig on my Gentoo box, but I've not been able to reproduce the bug.

**Comment by Kodiologist** [comment] 2019-08-01 14:07
I'm no longer seeing this bug. I'm now using WeasyPrint 47, Python 3.7.3, Pango 1.42.03, and Ubuntu 19.04.

**Comment by liZe** [comment] 2019-08-01 16:11
> I'm no longer seeing this bug. I'm now using WeasyPrint 47, Python 3.7.3, Pango 1.42.03, and Ubuntu 19.04.

Thanks for this information. I'll check that everything works fine on my Ubuntu installation, and close this issue if I'm not able to reproduce anymore.

**Comment by craigpla** [comment] 2019-11-25 15:01
It's still happening, at least for me. I had some monospace in a heading and was using Courier New. If I had the EXACT same heading twice in a row, only the second one had the spacing issue.

The problem is solved with Source Code Pro. I had already moved on last week when I saw what was going on, but I can change my template back and slap another PDF together if someone needs to see.

**Comment by liZe** [comment] 2021-09-16 16:19
Should be gone now that Cairo has been removed. Feel free to reopen if it can be reproduced with version 53+.

**Closed by liZe** 2021-09-16 16:19 UTC
Labels: bug

**Comment by wf-r** [comment] 2021-11-04 13:24
Hi,
I can reproduce this issues on 53.3 (however not on 52.5) using the following code:

```
import jinja2
import weasyprint

pdf_pages = weasyprint.HTML(
    string=jinja2.Environment(
        loader=jinja2.FileSystemLoader(searchpath='.')
    ).get_template(
        'example.html'
    ).render(
        ueberschrift='Lw, UmP, TrD',
    ),
    base_url='.'
).render().pages
pdf_pages.extend(
    weasyprint.HTML(
        string=jinja2.Environment(
            loader=jinja2.FileSystemLoader(searchpath='.')
        ).get_template(
            'example.html'
        ).render(
            ueberschrift='Bw, Offz, GeoInfoD',
        ),
        base_url='.'
    ).render().pages
)

with open('out.pdf', 'w+b') as out:
    # noinspection PyUnresolvedReferences
    weasyprint.Document(
        pages=pdf_pages,
        metadata=weasyprint.document.DocumentMetadata(),
        # font_config=weasyprint.text.fonts.FontConfiguration(),  # for 53.3
        font_config=weasyprint.document.FontConfiguration(),  # for 52.5
        url_fetcher=None,
        # optimize_size='none'  # for 53.3
    ).write_pdf(out)
```

The two respective documents are attached, on 53.3 I get unexpected horizontal whitespaces, on 52.5 it works fine. However, the behaviour is pretty random: 
* if i render only one page in the snippet above, everything is fine
* other strings render fine

System:

* Weasyprint: 53.3 and 52.5
* Python 3.8.6
* Windows 10 64bit Build 18363
* Pango 1.48.4

If you would like to investigate and need further information please let me know.

Best
Wolfgang

Template used in snippet:
```
<!DOCTYPE html>
<html>
	<head>

		<!-- CSS property to place div
			side by side -->
		<style>
			@page{
				size: A4 landscape;
				margin: 0px;
				padding: 0px;
			}
			html {
				height: 100%;
			}
			body {
				height: 100%;
				display: flex;
				flex-direction: column;
			}
			h1{
				text-align:center; 
			}
			#boxes{
				flex-grow: 1;
				display: flex;
				flex-direction: row;
			}
			.box {
			height: 100%;
				width: 50%;
				margin-left: 20px;
				margin-right: 20px;
				background: #C0C0C0;
				padding-left: 20px;
				padding-right: 20px;
				padding-bottom: 20px;
				border-radius: 30px;
			}
		</style>
	</head>

	<body>
		<h1>{{ ueberschrift }}</h1>
		<div id="boxes">
			<div class="box">
				Some random tetx
            		</div>
			<div class="box">
				Some more random text
        	       </div>
		</div>
	</body>
</html>					 
```
[out-52_5.pdf](https://github.com/Kozea/WeasyPrint/files/7475039/out-52_5.pdf)
[out-53_3.pdf](https://github.com/Kozea/WeasyPrint/files/7475040/out-53_3.pdf)

**Comment by liZe** [comment] 2021-11-04 14:05
> I can reproduce this issues on 53.3 (however not on 52.5) using the following code:

Then your bug is different. Could you please open a new issue with your example?
