### ISSUE TITLE
It not work when you render 汉字 by `code` tag

### ISSUE THREAD

**Issue by lar-ry** [Kozea/WeasyPrint#1718] opened 2022-09-15 03:07 UTC
I want to render `<code>汉字</code>`,

it will display the tip:

`invalid literal for int() with base 16: ''`

v55.0 is normal, but v56.0b1, v56.0 and v56.1 is abnormal.

**Comment by liZe** [comment] 2022-09-15 08:43
Hi!

Could you please send the PDF generated by version 55 and the one generated by version 56 (if the error doesn’t make WeasyPrint crash).

**Comment by lar-ry** [comment] 2022-09-20 01:39
version 55:![image](https://user-images.githubusercontent.com/31038096/191148476-fd5b62fd-792d-49d2-9e6b-ea68fe717ec9.png)

**Comment by lar-ry** [comment] 2022-09-20 01:42
version 56:
```

**Comment by liZe** [comment] 2022-09-23 13:59
I have two questions:

1. Could you please share (by mail) the font file used in your document with version 55? It’s 新宋体.
2. We need to have a traceback to know why WeasyPrint crashes. Could you please make your `md2pdf.py` script display this whole traceback?

**Comment by lar-ry** [comment] 2022-09-26 07:18
1.

**Comment by liZe** [comment] 2022-10-11 07:29
@lar-ry Is there a way we could help you solving this problem?

**Comment by lar-ry** [comment] 2022-10-11 07:33
I had to continue using version 55 because this font was required.

> @lar-ry Is there a way we could help you solving this problem?

**Comment by liZe** [comment] 2022-10-11 07:50
> I had to continue using version 55 because this font was required.

OK, I understand.

The bug is actually caused by another font, a bitmap font installed on your system. The problem is that we don’t know which font it is.

Do you have some programming skills? If so, I could tell you how to find the font, so that I can fix the problem. But if you don’t have programming skills or don’t want to spend more time on this, no problem 😁️, we can then close this issue.

**Comment by lar-ry** [comment] 2022-10-11 07:55
I want to try, what do I need to do?

**Comment by liZe** [comment] 2022-10-11 08:32
> I want to try, what do I need to do?

Thank you!

Here’s what you can do:
- Install WeasyPrint 56.1
- Open `C:\Users\larry\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\weasyprint\pdf\fonts.py`
- Add `open('C:\\Users\\larry\\font-' + font.hash, 'wb').write(font.file_content)` on line 40. You should have something like:
```python
    for font in fonts.values():
        open('C:\\Users\\larry\\font-' + font.hash, 'wb').write(font.file_content)
        widths = pydyf.Array()
```
- Generate your document (you’ll have the bug, it’s normal).

You should now have one or more files named `font-XXXXXX` (with uppercase characters instead of X) created in your `C:\Users\larry\` folder. You can attach them in a comment or send them by mail, that’s the file I need!

**Comment by lar-ry** [comment] 2022-10-11 08:38
[fonts.zip](https://github.com/Kozea/WeasyPrint/files/9753128/fonts.zip)
I did it, and it created 3 files in fonts.zip

**Comment by lar-ry** [comment] 2022-10-11 08:45
Font files: 
- Source Han Sans SC
- Source Han Serif SC
- 宋体

PS: You are really professional, thank you.

**Closed** 2022-10-11 11:37 UTC

**Comment by liZe** [comment] 2022-10-11 11:42
The bug should now be fixed. The 宋体 font includes both bitmap characters and vector characters. We should use the vector variant (see #1736), removing the bug.

Moreover, the crash happened when characters have no data (ie. they have a width of 0). If we ever meet these characters in bitmap-only fonts again, we’ll now correctly include them.
