### ISSUE TITLE
Hyphenation of words with Punctuation

### ISSUE THREAD

**Issue by mbarkhau** [Kozea/WeasyPrint#779] opened 2019-01-29 21:51 UTC
Hi. I was surprised when using `hyphens: auto` to see the word `programs` split as `program-s`, especially since Pyphen produces `pro-grams`

```
>>> import pyphen
>>> dic = pyphen.Pyphen(lang='en_US')
>>> list(dic.iterate("programs"))
[('pro', 'grams')]
```

So I stepped through the code to the point where Pyphen is used and it turns out the argument that was actually given was `"programs."` and indeed the word is at the end of the sentence and so:

```
>>> list(dic.iterate("programs."))
[('program', 's.'), ('pro', 'grams.')]
```

So I dug around in Pyphen and found [this ticket](https://github.com/Kozea/Pyphen/issues/4), which I read as saying that this is the job of WeazyPrint.

For now I've made use of `hyphenate-limit-chars: 6 3 3;` and the results look better on the particular document I'm generating atm. but I guess I'll have to wait and see if there are other cases. I guess you could have pathological cases like this

```
>>> list(dic.iterate("programs..."))
[('program', 's...'), ('pro', 'grams...')]
```

Should WeazyPrint pass only text (without punctuation) to Pyphen or is this intended behaviour?

**Comment by liZe** [comment] 2019-01-30 11:57
Hello!

Thanks for taking the time to report this issue with a lot of details :heart:.

This bug is a duplicate of #109 that has been fixed recently. No version with this fix has been released yet, but the fix will be included in [version 45](https://github.com/Kozea/WeasyPrint/milestone/12) (coming soon). If you have the time to test the current master branch, I'd be glad to know if it fixes your different use cases.

**Closed by liZe** 2019-01-30 11:57 UTC

**Comment by mbarkhau** [comment] 2019-01-30 20:05
I can confirm that the git repo doesn't have the issue.
