### ISSUE TITLE
SVG rendering problem

### ISSUE THREAD

**Issue by lafar6502** [Kozea/WeasyPrint#2234] opened 2024-08-21 09:01 UTC
Hi, attached test case shows some problems with svg graphics support
[examples.zip](https://github.com/user-attachments/files/16689172/examples.zip)

this is how the svg image looks rendered in the browser

![image](https://github.com/user-attachments/assets/a542f1c3-3ac7-4cc9-ad3f-2148e686fc9d)

and this is how it looks after converting to PDF with weasyprint:

![image](https://github.com/user-attachments/assets/1f8f5598-a54c-4b10-8db5-a3777e1fb88d)

I suppose there's some problem with svg transform() implementation.

[test1.zip](https://github.com/user-attachments/files/16689251/test1.zip)
using WeasyPrint version 62.3 on Windows (standalone executable)

**Comment by liZe** [comment] 2024-08-21 12:01
Hi!

Thanks for the report. The bug happens because transforms are not applied to `symbol` elements. Here’s a small example:
```svg
<svg height="100" width="100" xmlns="http://www.w3.org/2000/svg">
  <symbol id="rect">
    <rect x="0" y="0" width="25" height="25" />
  </symbol>
  <use x="0" y="0" transform="skewX(30)" href="#rect" />
</svg>
```

**Comment by liZe** [comment] 2024-08-21 22:55
I’ve actually fixed 3 (!!) different bugs thanks to your sample:
- `symbol` tags are not displayed anymore when seen in the tree,
- bounding boxes is used as a fallback when `symbol` tag don’t give their size,
- CSS is correctly applied to use tags references.

We can now correctly render symbols with visible overflow and no explicit size referenced by `use` tags. That’s somewhere between beauty and torture.

(Out of curiosity, which tool do you use to generate these SVG files?)

The rendering is now close to what browsers draw:

![Capture d’écran du 2024-08-22 00-38-11](https://github.com/user-attachments/assets/2cde6526-724c-49a3-9cbe-e09fe3c4533c)

Looks like some black stroke is missing. Any idea about what could do this?

**Comment by lafar6502** [comment] 2024-08-22 06:59
That's crazy. Thanks!
Will be testing soon.
the SVG is generated from a product configurator, as you have noticed there's a trick to make 3d view from 3 flat pictures by torturing them a little. No vector drawing tool is used, just raw XML.

**Comment by lafar6502** [comment] 2024-08-22 07:31
pardon my ignorance, but what's the easiest way of testing the last changes to the code if i've only been using windows executable / commandline so far?

**Comment by liZe** [comment] 2024-08-22 07:56
> the SVG is generated from a product configurator, as you have noticed there's a trick to make 3d view from 3 flat pictures by torturing them a little. No vector drawing tool is used, just raw XML.

Yes, that’s what I thought. That’s a tool you’re developing?

> pardon my ignorance, but what's the easiest way of testing the last changes to the code if i've only been using windows executable / commandline so far?

Executable files are automatically generated for each commit, you can find them here: https://github.com/Kozea/WeasyPrint/actions/workflows/exe.yml

**Comment by lafar6502** [comment] 2024-08-22 08:30
Yep, it's a tool - product configurator for ordering various sun shading stuff. There's a part of it that generates an SVG drawing representing a simplified view of the product, with dimensions, colors etc according to choices made by the user. Most of it is flat (like roller blinds) but the pergola was a little challenging because it's not flat - that's how the fake 3d view was born.
The reason i started experimenting with weasyprint is that i need to find some better alternative to wkhtmltopdf, which is currently used for generating PDFs with order specification. Wkhtmltopdf is a nice workhorse but sometimes it's hard to convince it to generate something that looks good on print...

**Comment by lafar6502** [comment] 2024-08-22 08:42
And first test done with the most recent Windows build

Much better, but there's a bit missing in my result - the dimension numbers are not visible. But on your screenshot they're there.
Maybe some commit didn't make it into the build?

![image](https://github.com/user-attachments/assets/a9ec1adb-25d3-415a-b8d9-5cb5ea989fff)

[test_svg_20240822.zip](https://github.com/user-attachments/files/16707825/test_svg_20240822.zip)

**Comment by lafar6502** [comment] 2024-08-22 09:38
I think there's a problem with rendering 'monospace' font family specified in my style

`.dimtxt {text-anchor: middle; font-family: monospace;font-size:150pt;fill:blue;font-weight:normal}`

if font-weight is bold then the text renders. If font-weight:normal, or not specified at all - doesn't render
Should be easy to work around this so don't worry too much.

[test2.zip](https://github.com/user-attachments/files/16708517/test2.zip)

**Comment by liZe** [comment] 2024-08-22 12:58
> if font-weight is bold then the text renders. If font-weight:normal, or not specified at all - doesn't render
> Should be easy to work around this so don't worry too much.

That’s strange, I didn’t have the problem. It’s probably caused by the fonts installed on your system, using a specific font family instead of Monospace will probably work too.

The other difference I was talking about is the missing black lines around the slats at the top of the pergola (if it’s a pergola 😄). It can be fixed with `stroke:black` set to `.slat`, but I have to find why it’s not required for browsers, it’s probably a bug.

**Comment by liZe** [comment] 2024-08-22 13:33
I think that everything’s fixed now.

![Capture d’écran du 2024-08-22 15-26-59](https://github.com/user-attachments/assets/ba759314-dcb0-4896-88d5-3279df05f080)

The result is great, the only problem I have is with the text: there’s a small black stroke line on text, that’s too visible in some PDF readers at some zoom levels (and even in browsers, actually). That’s caused by the `stroke: black` set on `svg`: the default value of `stroke-width` is 1, so if you set `stroke: black` on `svg` you’ll get a very thin line drawn around everything (including letters), and it can give strange renderings. Maybe you want to set `stroke-width: 0` on `svg` too!

**Comment by lafar6502** [comment] 2024-08-22 13:42
Beautiful. let's close it, i'll be doing more tests in next days so if there's anything else, i'll make a new task.
Thanks for all your help so far and great work on this framework.

**Closed** 2024-08-22 14:32 UTC
Labels: bug
