### ISSUE TITLE
Unable to work with WeasyPrint due to a library not found called "cairo" and "libcairo"

### ISSUE THREAD

**Issue by lrodri14** [Kozea/WeasyPrint#1279] opened 2020-12-31 20:59 UTC
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': dlopen(libcairo.so, 2): image not found
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 2): image not found
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 2): image not found

This error shows up every time i try to run my local django server, i installed WeasyPrint following the instructions in https://weasyprint.readthedocs.io/en/latest/install.html#macos, all the dependencies have been installed using homebrew,
i am using the python 3.7 version and django 2.2.13 and MacOS Big Sur

**Comment by liZe** [comment] 2020-12-31 22:18
Hello!

You have to be sure to use Homebrew’s Python (3.9 by default, as it should be installed if you follow the documentation instructions), and not macOS’ system Python. If you do, WeasyPrint should be able to find Cairo.

**Comment by lrodri14** [comment] 2021-01-01 17:22
@liZe Yes, it was pointed to the python version installed by HomeBrew but is still giving me this error

**Comment by liZe** [comment] 2021-01-01 20:09
> @liZe Yes, it was pointed to the python version installed by HomeBrew but is still giving me this error

Here’s what you can do:
- launch `which python3` (replace `python3` by the executable you use for your Django) and check that it’s Homebrew’s Python executable,
- execute `python3 -c "from cffi import FFI;FFI().dlopen('libcairo.2.dylib')"`.

If it doesn’t work, it means that the problem is probably not in WeasyPrint, but in the way Cairo is installed with Homebrew.

If it works, it means that your application does something strange that prevents cffi from finding Cairo.

**Comment by liZe** [comment] 2021-01-16 12:56
@lrodri14 Can I close this issue?

**Comment by liZe** [comment] 2021-01-20 14:06
Feel free to reopen if needed.

**Closed by liZe** 2021-01-20 14:06 UTC
