### ISSUE TITLE
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2

### ISSUE THREAD

**Issue by Otooo** [Kozea/WeasyPrint#721] opened 2018-10-29 23:42 UTC
Evry command with Weasyprint or import weasyprint given this erro "OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2"

**Comment by Tontyna** [comment] 2018-10-30 08:14
Duplicate of #589. You must install Cairo / GTK. Howto install that depends on your OS.

**Comment by Tontyna** [comment] 2018-10-30 10:15
@Otooo if you are on Windows, have a look at the latest [installation instructions](https://weasyprint.readthedocs.io/en/latest/install.html#windows)

**Comment by Otooo** [comment] 2018-10-30 17:41
I've already followed the steps, but still the error. and it's not just that of cairo / cairo-2

**Comment by Tontyna** [comment] 2018-10-30 19:46
Are you on Windows? Which Windows? Which Python? Which GTK? `WHERE libcairo-2.dll`?

**Comment by jonthemango** [comment] 2018-11-13 18:35
Python Version: **Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]**

Same issue. Recently installed Python 3.7.1, checked off added to path (used the Windows x86) installer, pip was also installed. Ran the command to update pip and setuptools package.

When installing WeasyPrint, all messages say "Requirement already satisfied".

I used the  GTK+ 64 Bit Installer and it installed the GTK version 2 here "C:\Program Files\GTK2-Runtime Win64\bin". Added those to path (at the bottom) and later moved it to the top of the path. When running "WHERE libcairo-2.dll" there is no message outputted. 

Did not cheat! 👍  Does WeasyPrint support the latest version of Python on Windows?

**Comment by jonthemango** [comment] 2018-11-13 18:59
Checked "System Settings > Apps & Features" and uninstalled a .NET version of the GTX environment. WeasyPrint is working now.

**Comment by Tontyna** [comment] 2018-11-13 20:30
> When running "WHERE libcairo-2.dll" there is no message outputted.

You mean: No message at all? Not even "Nothing found" or similar? Can't believe it. 
If `WHERE` doesn't find a file, then WeasyPrint shouldn't be able to find it, too; at least if the Windows user running WeasyPrint and the user calling `WHERE` are the same -- I recall, the GTK installer adds the path to the **user's** PATH , not to the **system** PATH

**Comment by jonthemango** [comment] 2018-11-15 20:11
When I ran "WHERE libcairo-2.dll" there was no message outputted. Just allowed me to keep entering powershell commands. 

I fixed the problem by uninstalling a version of GTK that was installed by .NET sometime ago.

**Comment by liZe** [comment] 2018-11-16 07:49
> As previously stated though the issue was likely caused by the **other** version of GTK.

Then we can safely close this issue :smile:.

**Closed by liZe** 2018-11-16 07:49 UTC

**Comment by shamrose** [comment] 2018-12-02 01:53
> Python Version: **Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]**
> 
> Same issue. Recently installed Python 3.7.1, checked off added to path (used the Windows x86) installer, pip was also installed. Ran the command to update pip and setuptools package.
> 
> When installing WeasyPrint, all messages say "Requirement already satisfied".
> 
> I used the GTK+ 64 Bit Installer and it installed the GTK version 2 here "C:\Program Files\GTK2-Runtime Win64\bin". Added those to path (at the bottom) and later moved it to the top of the path. When running "WHERE libcairo-2.dll" there is no message outputted.
> 
> Did not cheat! 👍 Does WeasyPrint support the latest version of Python on Windows?

Moving GTK version "C:\Program Files\GTK2-Runtime Win64\bin" right at the top in environment variables path worked for me, Thanks!

**Comment by deleuterio** [comment] 2019-01-25 16:35
> Duplicate of #589. You must install Cairo / GTK. Howto install that depends on your OS.

I recommend check the [instalations prerequisites](https://weasyprint.readthedocs.io/en/latest/install.html#linux) of Weasyprint.

Cairo/GTK dependencies are required in some Linux distros like Fedora and Geento.

**Comment by theobarnhart-USGS** [comment] 2019-01-31 23:36
I

> > Duplicate of #589. You must install Cairo / GTK. Howto install that depends on your OS.
> 
> I recommend check the [instalations prerequisites](https://weasyprint.readthedocs.io/en/latest/install.html#linux) of Weasyprint.
> 
> Cairo/GTK dependencies are required in some Linux distros like Fedora and Geento.

Not sure where to put this, but I had the same error installing onto Ubuntu 16 (anaconda python 3.7).

I created a new python 3.7 environment and installed weasyprint using `pip install weasyprint` but then got the OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2 error 

which after much googling around and reading these issue reports I did:

`pip uninstall cairocffi`
'conda install cairocffi`

and weasyprint now works!

Also, thank you weasyprint for such a useful tool.

**Comment by haifzhan** [comment] 2019-03-29 18:16
@theobarnhart-USGS  Thank you for your comment which saved my day!

**Comment by harveynr** [comment] 2019-04-11 14:15
For anyone else running into this, something else to check:  When you change your Windows path, make sure to restart any processes (or, aheam, IDEs) that are currently running, to make sure your whole environment picks up the changes.  I was racking my brain trying to figure this out, and then I restarted PyCharm, problem solved.

**Comment by Nougati** [comment] 2019-07-29 01:47
> Moving GTK version "C:\Program Files\GTK2-Runtime Win64\bin" right at the top in environment variables path worked for me, Thanks!

This was my issue. Bizarrely, it happens for me as soon as `C:\Program Files\GTK3-Runtime Win64\bin` is above `C:\Program Files\Intel\WiFi\bin` in the system PATH. 

Why would this happen? If the file is unique, shouldn't Windows just fail to find it in `\WiFi\bin` and move on to check `\GTK3-Runtime Win64\bin`?

**Comment by Tontyna** [comment] 2019-07-29 06:05
@Nougati -- yes, if the file is unique, the order of folders in the `PATH` doesn't matter. So either the file isn't unique or (as @pytrumpeter pointed out)  your command prompt or shell or IDE or wheresoever you run WeasyPrint didn't pick up the new PATH. 
Countless times me myself forgot to re-start *FreeCommander*...

**Comment by Wenze** [comment] 2019-08-23 03:36
> > Python Version: **Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]**
> > Same issue. Recently installed Python 3.7.1, checked off added to path (used the Windows x86) installer, pip was also installed. Ran the command to update pip and setuptools package.
> > When installing WeasyPrint, all messages say "Requirement already satisfied".
> > I used the GTK+ 64 Bit Installer and it installed the GTK version 2 here "C:\Program Files\GTK2-Runtime Win64\bin". Added those to path (at the bottom) and later moved it to the top of the path. When running "WHERE libcairo-2.dll" there is no message outputted.
> > Did not cheat! 👍 Does WeasyPrint support the latest version of Python on Windows?
> 
> Moving GTK version "C:\Program Files\GTK2-Runtime Win64\bin" right at the top in environment variables path worked for me, Thanks!

Same here

**Comment by tljstewart** [comment] 2022-04-05 15:19
Add GTK to front of Path Variable
```bash
#git bash
export PATH="/c/Program Files/GTK3-Runtime Win64/bin":$PATH
```
Setting the `WEASYPRINT_DLL_DIRECTORIES=...` as stating in the troubleshooting docs doesn't work

**Comment by liZe** [comment] 2022-04-05 16:45
> Setting the `WEASYPRINT_DLL_DIRECTORIES=...` as stated in the [troubleshooting docs](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#troubleshooting) doesn't work

It should work if you use Python 3.8+ and WeasyPrint 54+, and you have GTK installed in this repository.

**Comment by liZe** [comment] 2022-04-05 17:21
> I tried with Python  3.9

Then if you carefully followed the installation guide, using Python from the Microsoft store, with WeasyPrint 54.x, with GTK installed in the default folder, it should work.

You can give your backtrace here to see if there’s something obviously wrong. Otherwise, you can open a new issue.

**Comment by best2160187** [comment] 2023-08-17 02:29
@liZe 
I tried with Python 3.11.4 and GTK 59 on windows 10 and encountered with OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
I suppose you have so experienced with it that you can solve this problem.
How kind of you if you give me a solution.
Thanks in advance.

**Comment by liZe** [comment] 2023-08-20 09:34
@best2160187 If you installed GTK in the default folder, everything should work out-of-the-box. If you installed it anywhere else, you can set [an environment variable](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#missing-library) to give WeasyPrint a hint about where to find these libraries. There’s nothing more to do.

**Comment by best2160187** [comment] 2023-08-20 15:00
@liZe Thank you for your kind reply.
Now it works.
I installed Python 3.9 and the problem was solved.
