### ISSUE TITLE
WeasyPrint doesn't respect exit code when can't load an image

### ISSUE THREAD

**Issue by igoose1** [Kozea/WeasyPrint#1330] opened 2021-04-06 09:56 UTC
Loot at this example:

```
% weasyprint file.html file.pdf
ERROR: Failed to load image at "file:///tmp/photo.webp" (Pixbuf error: Unrecognised image file format)
```

Exit code expects to be positive as there is an error, a real error, file.pdf wasn't created as it was expected and weasyprint knows it and helpfully prompts about one.

I see an exception is being thrown in https://github.com/Kozea/WeasyPrint/blob/16725609095b6839e2cf2313e84e1ff052b41a49/weasyprint/images.py#L97

I understand why this one could be an ignored error: a user wants a rendered document and errors with one or two images are miserable. But in my case (rendering in a build tool like `make(1)`) I understand "exit code is 0" as "everything is fine!"

**Comment by liZe** [comment] 2021-04-06 19:12
Hello!

Thanks for reporting this issue. It’s actually a duplicate of #351, so I’ll close this one.

There’s probably a way to raise an exception when the logging module gets an error… If anyone’s interested in adding this issue, I can help!

**Closed by liZe** 2021-04-06 19:12 UTC
