### ISSUE TITLE
Grid gap adds margin at the end

### ISSUE THREAD

**Issue by mbndr** [Kozea/WeasyPrint#2187] opened 2024-06-19 08:02 UTC
Hello and thanks for the great work on WeasyPrint, I really like it!

I (probably) found a bug with the grid gap. At the end of a grid margin is added, the more grid rows the more the margin exists there (see images). When no gap is specified there's also no wrong margin.

I built a minimal example here:
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <style>
            @page {
                size: A4;
                margin: 15mm;
            }
            * {
                margin: 0;
                padding: 0;
            }
            .grid {
                display: grid;
                gap: 2mm;
                grid-template-columns: 1fr;
                background-color: #006699;
                
                > * {
                    background-color: #ff6633;
                    color: white;
                }
            }
        </style>
    </head>
    <body>
        <div class="grid">
            <div>Grid item</div>
            <div>Grid item</div>
            <div>Grid item</div>
            <div>Grid item</div>
        </div>
    </body>
</html>
```

HTML output:
![html](https://github.com/Kozea/WeasyPrint/assets/7734369/33a537a4-0a4b-4059-9f9e-526aa4ec7c4b)

PDF output:
![pdf](https://github.com/Kozea/WeasyPrint/assets/7734369/e15809c7-fe02-4a52-afb9-b18f68f3aad6)

**Update:**
Maybe that helps: if multiple colums exist (`grid-template-columns: 1fr 1fr;`) the margins are correct.
![grafik](https://github.com/Kozea/WeasyPrint/assets/7734369/6dc9c534-369a-49d1-968b-4020fdd5b7f3)
But if (for example) the last item has a manually set `grid-column: 1/2;` the margin is there again.

**Comment by liZe** [comment] 2024-06-19 11:10
Hi!

I think that it’s a duplicate of #2162, fixed in version 62.2. Do you use an older version?

**Comment by mbndr** [comment] 2024-06-20 06:17
Hello, yes now I saw https://github.com/Kozea/WeasyPrint/issues/2167, sorry to bother you.
I'm using 62.1 but will upgrade to 62.2.
Thanks!

**Comment by liZe** [comment] 2024-06-21 09:02
> Can you recreate this behaviour?

Yes! Thanks for the example, it’s fixed too.

**Closed** 2024-06-21 09:02 UTC
