### ISSUE TITLE
Unable to create more than one page

### ISSUE THREAD

**Issue by rose-ramasamy** [Kozea/WeasyPrint#1314] opened 2021-03-17 09:10 UTC
Hi there, 

I am trying to create PDF reports using python. I have the content for more than one page but if I generate a report it is failing to create.

Note: If I reduce the content the pdf is created with a single page.

Please help me.. Thanks in advance.

My python file look like this:
```python
import pandas
from pdf_reports import pug_to_html, write_report
from pdf_reports import ReportWriter

litems = ["apple", "banana", "cherry","apple", "banana", "cherry","apple", "banana", "cherry","apple", "banana", "cherry","apple", "banana", "cherry","apple", "banana", "cherry"]

dataframe = pandas.DataFrame.from_records({
    "Name": ["US", "Netherlands", "Germany"],
    "Status": ['Pass','Pass','Fail']
}, columns=["Name", "Status"])

print(dataframe)

df = pandas.DataFrame({'Date':['10/2/2011', '11/2/2011', '12/2/2011', '13/2/11'],
                    'Event':['Music', 'Poetry', 'Theatre', 'Comedy'],
                    'Cost':[10000, 5000, 15000, 2000]})

# Create an empty list
Row_list = []

# Iterate over each row
for index, rows in df.iterrows():
    # Create list for the current row
    my_list = [rows.Date, rows.Event, rows.Cost]

    # append the list to the final list
    Row_list.append(my_list)

# Print the list
print(Row_list)

report_writer = ReportWriter(
    default_stylesheets=["style.css"],
    default_template="example_template.pug"
)

html = report_writer.pug_to_html(title="My report",items= litems,data= Row_list)
report_writer.write_report(html, "example.pdf")
```

my template file look like this:

```md
#sidebar: p Hey, I am a sidebar text ! I make your document look much more serious.

h1 {{ title }}
:markdown
  You can install `pdf_reports` with Python's PIP:

.ui.container
  .ui.icon.message.yellow.block-center
    i.exclamation.circle.icon
    .content .header This is an important message, as per the exclamation mark.

:markdown
  ##  I am a section title
{% for c in items %}
p {{c}}
{% endfor %}

{% for value in data %}
p {{ value }}
{% endfor %}

table.ui.celled.table
thead
    tr
      th File
      th description
tbody
    tr
      td No Name Specified
      td Unknown
      td.negative None
```

**Comment by rose-ramasamy** [comment] 2021-04-21 06:22
Thanks

**Comment by liZe** [comment] 2021-04-21 08:01
For the record: Edinburgh-Genome-Foundry/pdf_reports#15.

The problem you have in [this comment](https://github.com/Edinburgh-Genome-Foundry/pdf_reports/issues/15#issuecomment-801585325) is a duplicate of #1292.

Feel free to reopen if we can help you!

**Closed by liZe** 2021-04-21 08:01 UTC
