### ISSUE TITLE
Column Layout problem when spreading on multiple pages.

### ISSUE THREAD

**Issue by stockersky** [Kozea/WeasyPrint#816] opened 2019-03-05 11:06 UTC
Python 3.7
Weasyprint 45

I encounter layout problems with WeasyPrint. With `Flexbox` but also with `float` and `position`.

**First, I used flexbox** to display two columns.
[Here is a gist](https://gist.github.com/stockersky/efd1a53530b3490c31f6fd81aa7226c7) you can try with the weasyprint renderer (python -m weasyprint.tools.renderer)

    page-wrapper {
         display: flex;
      }

     #col1 {
         width: 35%;
      }

     #col2 {
          width: 65%;
      }

if col1 content makes that col1 to be spread on a next printed page, then col2 starts at the beginning of this next page. 

     |- - - -col1-----|
     |                     |                             <--- page1
     |                     |
     |                     |
     |                     |
     |---------------------| ----- col2 -------   
     |                     |                       |     <---- page2
     |                     |                       |

I am expecting those 2 columns to start at the beginning of page1

I do not have this pb while printing with chrome : the two columns start at the beginning of the first page, whatever col1 spreads on the second page.

**Well, actually, from the gist I provided , you will see that the second column is printed on the LAST page....**

As an alternative, while **trying with `float`**, I noticed another pb : **only one page is printed !**. It seems that the document is "truncated" at the end of the first page.
To see this, still in the gist, comment the `display: flex` and uncomment the `float: left`.

Then, I tried with `position: absolute` : same thing as with float : only the first page is printed.

NOTE : all of this works in the chrome printer!

Maybe, if I'm doing it wrong, you could provide me a proper way to handle column in multiple pages with WeasyPrint?

**Comment by liZe** [comment] 2019-03-06 12:06
Hello!

The problems you're having are caused by the same reason: there's no parallel flows support yet in WeasyPrint, meaning that in "common" conditions you can't have two separate blocks split between pages. That's a major limitation of WeasyPrint and creates problems for float boxes, for absolute boxes, for tables, for flex boxes… See #36.

The only solution currently working is [columns](https://developer.mozilla.org/fr/docs/Web/CSS/columns), but I think that it's not what you need.

I'm closing this issue because it's a duplicate of #36. Feel free to reopen if there's something new about your specific use case.

**Closed by liZe** 2019-03-06 12:06 UTC

**Comment by stockersky** [comment] 2019-03-06 15:01
Wow, that's very bad news... It's definitely a major limitation of WeasyPrint.
Is there a schedule for fixing it?

**Comment by liZe** [comment] 2019-03-06 15:55
> It's definitely a major limitation of WeasyPrint.

It is.

> Is there a schedule for fixing it?

Unfortunately, no: #36 is 6 years old! I think that implementing parallel flows would require **at least** 1 month working full-time on this, and would require a lot of small changes everywhere in the code (leading to zillion small bugs for sure, even if we have a pretty good test suite).

If someone really wants to see this done "quickly", we have a [Patreon page](https://www.patreon.com/kozea) for donations where higher tiers offer the possibility to give higher priority to some issues. But even with a generous sponsor, we'll probably need at least 3 months before the feature is ready to be included in a stable version.

**Comment by stockersky** [comment] 2019-03-07 13:04
Hello Guillaume,
It seems you're french, so I'll write in french. If you can't read it, just reply to me and I'll write in english.
Bonjour Guillaume,
Je t'écris à propos de l'issue #816 de WeasyPrint, en relation avec l'issue #36 qui concerne les "parallel flows".
Tout d'abord, merci pour WeasyPrint. Cette bibliothèque m'a permise d'atteindre de bons résultats très facilement. 
Cependant, la limitation en question est problématique pour mon projet.
A propos du financement de l'implémentation de cette fonctionnalité via Patreon, quel est l'investissement demandé?Full time, signifie 3 mois/homme ou bien de consacrer 3 mois de ton temps dédié à WeasyPrint?
Je développe une appli sur mon temps libre. Je ne suis pas une société.
Peut être une implémentation du "parallel flow" pour seulement un aspect de layout est plus rapide? Par exemple, de seulement flexbox...
Cordialement,
Guillaume Tessier


    Le mercredi 6 mars 2019 à 16:55:52 UTC+1, Guillaume Ayoub <notifications@github.com> a écrit :  
 
 

It's definitely a major limitation of WeasyPrint.


It is.


Is there a schedule for fixing it?


Unfortunately, no: #36 is 6 years old! I think that implementing parallel flows would require at least 1 month working full-time on this, and would require a lot of small changes everywhere in the code (leading to zillion small bugs for sure, even if we have a pretty good test suite).

If someone really wants to see this done "quickly", we have a Patreon page for donations where higher tiers offer the possibility to give higher priority to some issues. But even with a generous sponsor, we'll probably need at least 3 months before the feature is ready to be included in a stable version.

**Comment by Tontyna** [comment] 2019-03-09 00:05
It's not about *adding* or *patching* or *enhancing* the layout code, IMHO a complete **redesign** is required. 

Each time a bug turns up in the layout area I'm tempted to radically clean up the headaching source, and each time I give up ... not enough leisure time available. I'd probably contribute ideas and PRs to such a redesign to achieve peace of mind in the future, but not to another hotpotch as @stockersky seems to propose (does he? I'm not very familiar with French)

**Comment by stockersky** [comment] 2019-03-12 14:40
Hello Tontyna,
Thanks for paying attention to my request.Sorry writing in french, but I found out that LyZe was french and I thought that would be easier to communicate in our native language.
I understand this feature involves lot's of work to be implemented.In my mail, as LyZe spoke about Patreon, I was asking how much would it coast to have it implemented (NOTE : I'm not a company!!!)I was also asking if - maybe - just some part of multipage layout could be implemented (like, only flexbox....)....

WeasyPrint is great, but the fact you cannot have a layout that spread on multiple pages is a serious limitation! 
In fact, If you use a layout, then you can't print more than one page :-(

Maybe you know how to deal with this (alternative)? 
... Or other libs? JS on the client could be great but it does not seem that easy to implement...
Grabz.it sounds the easiest way to implement it for me without changing too much code and design.
Sincerely,
Guillaume
    Le samedi 9 mars 2019 à 01:05:26 UTC+1, Tontyna <notifications@github.com> a écrit :  
 
 
It's not about adding or patching or enhancing the layout code, IMHO a complete redesign is required.

Each time a bug turns up in the layout area I'm tempted to radically clean up the headaching source, and each time I give up ... not enough leisure time available. I'd probably contribute ideas and PRs to such a redesign to achieve peace of mind in the future, but not to another hotpotch as @stockersky seems to propose (does he? I'm not very familiar with French)

**Comment by Tontyna** [comment] 2019-03-12 19:43
Hi @stockersky,

> I was asking how much would it coast to have it implemented

looking at the patreon's page it seems like $150 per month allow for 1 extra hour per day. To promote a special issue the $100-tier-ship is minimum. Mind that it's not about you paying 3 month's full-time work to get the redesign of the layout done. Sooner or later the redesign is due, anyhow, but a dedicated sponsorship can push it forward.

> In fact, If you use a layout, then you can't print more than one page

Of course you can print more than one page. The limitation only affects **out-of-flow** elements. Since I'm old-fashioned I rarely use out-of-flow contents, at maximum small floats or absolute positioned boxes. No flex or grid or column layout. At least in the (parts of my) documents I convert to PDFs. 

> Maybe you know how to deal with this (alternative)?

If your documents must look like in the browser and applying `@media print` styles that transform the out-of-flow layout into an in-flow layout is out of the question, then (current) WeasyPrint is out of the question, too.
Sorry, can't suggest alternatives because I know nothing about currently available tools and their capabilities.

**Comment by liZe** [comment] 2019-03-13 10:23
> It seems you're french, so I'll write in french. If you can't read it, just reply to me and I'll write in english.

:fr: :gb: :smile:

French is easier for me too, but English is better to share information. There's no need to be shy, English is just a convenient way to share.

> It's not about _adding_ or _patching_ or _enhancing_ the layout code, IMHO a complete **redesign** is required.

It is.

> Peut être une implémentation du "parallel flow" pour seulement un aspect de layout est plus rapide? Par exemple, de seulement flexbox...

As many types of layout are nested (tables in blocks in flex in …), we need to have one common way to store where flows are cut. It basically means that we have to change the structure of the `skip` and `resume_at` variables everywhere, not only for one layout. So…

> Full time, signifie 3 mois/homme ou bien de consacrer 3 mois de ton temps dédié à WeasyPrint?

It means full-time. As I spend at most 20% of my time now, it means more than 1 year at current pace. Of course, we can hack something in less time than that, but the change is so deep that transforming this hack into something really solid will be the longest part of the work.

> ... Or other libs? JS on the client could be great but it does not seem that easy to implement...

You can check:
- [Prince](https://www.princexml.com/): free trial version, but the commercial version is much more expensive than a WeasyPrint sponsorship :smile:.
- [Paged.js](https://www.pagedmedia.org/paged-js/): really different solution to web paged media, early state but may be interesting for your use.

> looking at the patreon's page it seems like $150 per month allow for 1 extra hour per day. To promote a special issue the $100-tier-ship is minimum. Mind that it's not about you paying 3 month's full-time work to get the redesign of the layout done. Sooner or later the redesign is due, anyhow, but a dedicated sponsorship can push it forward.

Perfect summary.

**Comment by stockersky** [comment] 2019-03-13 15:20
Hello Tontyna,
Thanks for answering me!
In your mail, you say that the limitation only affect out-of-flow elements. How can you achieve a column layout this way?
I started web development two years ago. And I thought that CSS float and absolute were the really old fashionable way !
And I cannot find any ressources about layout not using float, absolute, tables, flexbox or grid...
Could you, please, lead me to ressources where I can achieve such layout (two columns) that would work with WeasyPrint?
My pages are only meant to be printed.

Sincerely,
Guillaume

    Le mardi 12 mars 2019 à 20:43:59 UTC+1, Tontyna <notifications@github.com> a écrit :  
 
 
Hi @stockersky,


I was asking how much would it coast to have it implemented


looking at the patreon's page it seems like $150 per month allow for 1 extra hour per day. To promote a special issue the $100-tier-ship is minimum. Mind that it's not about you paying 3 month's full-time work to get the redesign of the layout done. Sooner or later the redesign is due, anyhow, but a dedicated sponsorship can push it forward.


In fact, If you use a layout, then you can't print more than one page


Of course you can print more than one page. The limitation only affects out-of-flow elements. Since I'm old-fashioned I rarely use out-of-flow contents, at maximum small floats or absolute positioned boxes. No flex or grid or column layout. At least in the (parts of my) documents I convert to PDFs.


Maybe you know how to deal with this (alternative)?


If your documents must look like in the browser and applying @media print styles that transform the out-of-flow layout into an in-flow layout is out of the question, then (current) WeasyPrint is out of the question, too.
Sorry, can't suggest alternatives because I know nothing about currently available tools and their capabilities.

**Comment by Tontyna** [comment] 2019-03-13 16:40
> How can you achieve a column layout this way?

You can't. Quoting @liZe:

> The only solution currently working is columns, but I think that it's not what you need.

Since I didn't play around with *columns* yet, I dont know whether or not they might work for you.

**Comment by liZe** [comment] 2019-03-14 10:02
Columns allow you to do something like
```
Page 1
+---+---+
| A | C |
| B | D |
+---+---+

Page 2
+---+---+
| E | G |
| F | H |
+---+---+
```

but I think that you want

```
Page 1
+---+---+
| A | E |
| B | F |
+---+---+

Page 2
+---+---+
| C | G |
| D | H |
+---+---+
```

**Comment by challabeehyv** [comment] 2024-12-20 23:35
Any update on the above issue? Is there a workaround?

**Comment by liZe** [comment] 2024-12-20 23:46
> Any update on the above issue? Is there a workaround?

This issue is closed. What’s your issue?
