### ISSUE TITLE
pydyf 0.11.0 breaks weasyprint

### ISSUE THREAD

**Issue by andyhird** [Kozea/WeasyPrint#2202] opened 2024-07-13 00:30 UTC
Hi there.

It looks the new release of pydyf 0.11.0 has broken weasyprint.

We're seeing:
```

document = <weasyprint.document.Document object at 0x7f5ea25c6420>
target = <tempfile._TemporaryFileWrapper object at 0x7f5ea2617920>, zoom = 1
attachments = None, optimize_size = ('fonts',), identifier = None
variant = None, version = None, custom_metadata = False

    def generate_pdf(document, target, zoom, attachments, optimize_size,
                     identifier, variant, version, custom_metadata):
        # 0.75 = 72 PDF point per inch / 96 CSS pixel per inch
        scale = zoom * 0.75
    
        PROGRESS_LOGGER.info('Step 6 - Creating PDF')
    
        # Set properties according to PDF variants
        mark = False
        if variant:
            variant_function, properties = VARIANTS[variant]
            if 'version' in properties:
                version = properties['version']
            if 'mark' in properties:
                mark = properties['mark']
    
>       pdf = pydyf.PDF((version or '1.7'), identifier)
E       TypeError: PDF.__init__() takes 1 positional argument but 3 were given

```

In our various unit tests. pydyf 0.11.0 mentions a change to remove depreciated use of some positional arguments.

**Comment by grewn0uille** [comment] 2024-07-13 07:21
Hi,

This issue is a duplicate of #2200.

**Closed by grewn0uille** 2024-07-13 07:21 UTC

**Comment by frague59** [comment] 2024-10-18 08:49
Downgrade to `pydyf==0.10.0` solve the problem.

**Comment by VictorMwachi** [comment] 2024-12-15 09:57
Downgrading works.Thank you @frague59

**Comment by mazaharul** [comment] 2024-12-28 01:19
Thanks @frague59 
Downgrading to`pydyf==0.10.0` from `pydyf==0.11.0` did worked!
