### ISSUE TITLE
bookmark-label needs to retain significant spaces

### ISSUE THREAD

**Issue by Smylers** [Kozea/WeasyPrint#738] opened 2018-11-15 17:38 UTC
When a `bookmark-label` is composed from multiple components, the components shouldn't be trimmed where they meet: if the first component ends in a space then that space should still exist in the bookmark's label before the second component.

For instance, this puts some content in `h1:before` pseudo-elements:

````html
<!DOCTYPE html><title>Bookmark with Space</title>
<style>
#s:before { content: '1. '   }
#n:before { content: '2.\a0' }
#x:before { content: '3.'    }
h1        { bookmark-label: content(before) content(text) }
</style>

<h1 id=s>Space</h1>
<h1 id=n>Non-Breaking Space</h1>
<h1 id=x>Nothing</h1>
````

The first heading in the document renders as expected: “1. Space”. But in the PDF index, it's “1.Space”, without the space. And the second heading shows that a trailing non-breaking space also goes missing.

![bookmark_space](https://user-images.githubusercontent.com/598534/48570716-e9665300-e8fc-11e8-9f71-55010a074df7.png)

Discovered in WeasyPrint 43; I haven't tried older versions. Kind-of seems like the opposite issue to #607.

**Comment by liZe** [comment] 2018-11-15 17:54
Yes, that's actually a duplicate of #607. I've changed #607's title to be less specific.

**Closed by liZe** 2018-11-15 17:54 UTC
