### ISSUE TITLE
TTF hinting ignored

### ISSUE THREAD

**Issue by 500cm** [Kozea/WeasyPrint#1858] opened 2023-04-08 07:05 UTC
WeasyPrint seems to be ignoring hinted TTF fonts and resulting in blurry and unclear text. Even when fonts are properly hinted, the output is still not as sharp as expected. Additionally, I couldn't find any option to create proper sharp texts in the documentation or options list. It would be great if WeasyPrint could improve text rendering by properly handling hinted fonts or adding an option to create sharp text output.

Tested with WeasyPrint latest version.

**Comment by liZe** [comment] 2023-04-08 07:14
Hi!

Hinting is done by the PDF renderer, not by WeasyPrint. WeasyPrint includes letters and fonts in the PDF, and the PDF renderer displays the text on the screen, possibly adjusting the position of the letters to the screen pixels, according to the position of the document on the screen, the zoom level and the screen resolution (and many other things such as the hinting preferences of the user). Hinting depends on these parameters that are not fixed when the PDF is generated, I’m not sure there’s something WeasyPrint can do here.

If you have two equivalent documents, one blurry generated by WeasyPrint and another one generated by another tool, don’t hesitate to share them! Maybe there’s a feature we don’t know.

**Comment by tsastsin** [comment] 2023-04-09 01:38
Hinting is crucial for Windows users to enhance text readability, particularly at smaller font sizes. However, it is not relevant for users of other systems, such as Apple devices. Both TTF and OTF font files contain hinting instructions, and applications like Adobe Acrobat, web browsers, and other PDF renderers on Windows do not optimize fonts on their own, so you can't give up hinting built into fonts.

The issue arises when creating PDFs using WeasyPrint, as font optimization (enabled by default) disables hinting for fonts. If font optimization is disabled (e.g., optimize_size=("images")), the PDF is generated with hinting, but the file size increases significantly due to the lack of optimization and full font inclusion.

Disabling hinting altogether by default is not a viable solution. It's essential to either set hinting=true in the library or provide an option to use the variable. Unfortunately, I cannot share the PDF files, but I have attached screenshots of text from WeasyPrint-generated PDFs, comparing cases with and without font optimization.

To reproduce this problem, create a PDF file containing text with optimization turned on and off. You will see a clear difference on Windows systems with a 92 PPI monitor (not 4K).

![pdf](https://user-images.githubusercontent.com/45525094/230749621-0bf83695-4155-4b63-8601-81b1c2d03c6f.png)

**Comment by 500cm** [comment] 2023-04-09 02:45
Two files, with and without hinting

[hinting on.pdf](https://github.com/Kozea/WeasyPrint/files/11184680/hinting.on.pdf)
[hinting off.pdf](https://github.com/Kozea/WeasyPrint/files/11184681/hinting.off.pdf)

**Comment by liZe** [comment] 2023-04-09 18:00
Thanks for sharing your documents and the screenshot.

> Disabling hinting altogether by default is not a viable solution.

WeasyPrint is downloaded 10 million times a year, so it may be viable, at least for some people, even without hinting 😄. Funny that nobody ever complained before.

We’ve never met this problem, probably because Poppler (the library used by most PDF readers on Linux) [ignores hinting information on purpose](https://gitlab.freedesktop.org/poppler/poppler/-/blob/cfea6a76/poppler/CairoFontEngine.cc?ref_type=heads#L188). Hopefully, pdf.js does follow hinting tables, so we’re able to test the difference, even on Linux.

(There’s actually another bug in WeasyPrint that’s been fixed in 8a800a0, while solving #1855. This bug sets wrong widths for characters when fonts are not optimized, so you won’t get the exact same rendering with the fixed master branch than what you got with v58.1 + non-optimized fonts.)

Here’s what I get with the fix:
- hinting disabled: [test.pdf](https://github.com/Kozea/WeasyPrint/files/11186015/test.pdf)
- hinting enabled: [test-hint-fix.pdf](https://github.com/Kozea/WeasyPrint/files/11186014/test-hint-fix.pdf)
- no font optimization: [test-none.pdf](https://github.com/Kozea/WeasyPrint/files/11186016/test-none.pdf)

I find the result better with hinting, at least with pdf.js, but a bit different than with full font. Feedback is welcome!

If you want to test various options, you can tweak options here: https://github.com/Kozea/WeasyPrint/blob/d9c8af813987bdb117c6da9100c9373816825a78/weasyprint/pdf/stream.py#L107-L111

**Comment by 500cm** [comment] 2023-04-10 09:50
> Funny that nobody ever complained before

This is the most surprising part

Thank you for the fix, I'll check it out

**Comment by 500cm** [comment] 2023-04-12 14:33
Strategically this is not correct. Hinting should not be disabled by the library. It should remain under the control of the font itself. Those who don't need hinting can convert the font to a format without hinting or do automatic hinting, which is common practice.

**Comment by 500cm** [comment] 2023-04-12 14:37
By the way, disabling font optimization causes a number of bugs with fonts. They are converted to UTF characters, which are not readable in PDF file (it turns out: 􀍏􀍘.􀍡􀍛) and after some characters are added unnecessary space. Apparently, a separate task should be created for this.

**Comment by liZe** [comment] 2023-04-12 15:05
> Strategically this is not correct. Hinting should not be disabled by the library. It should remain under the control of the font itself.

I have to disagree on that point.

I understand that hinting is important for you, and I agree that it may be important for others. But the fact that this issue was opened just 4 days ago is a proof that most users don’t care and will prefer a smaller PDF than correct hinting. That’s sad (I spend so much time spent adding hinting information in the fonts I create 😢), but that’s a fact. By the way, many PDF readers do a decent job at automatically hinting fonts, and some even voluntarily discard hinting information in embedded fonts.

The feature is now available for the people who care.

> Those who don't need hinting can convert the font to a format without hinting or do automatic hinting, which is common practice.

I think that users don’t want to learn how to convert fonts. Many don’t even want to optimize and resize their images themselves! Having these features in WeasyPrint is important in my opinion, they help users to let the tool take care of the topics they don’t want to spend time on. Pre-processing (HTML, CSS, images, fonts…) is always possible, but we have to take care of common options when possible.

> They are converted to UTF characters, which are not readable in PDF file (it turns out: 􀍏􀍘.􀍡􀍛)

I can’t easily reproduce this problem. Could you please send an HTML sample and the corresponding PDF in another issue?

> after some characters are added unnecessary space

Maybe that’s fixed by https://github.com/Kozea/WeasyPrint/commit/8a800a0058937b7e16d97f14ec62a5111e0419de. If it’s not, you can open another issue 😄.

**Closed** 2023-04-12 15:06 UTC
Labels: feature

**Comment by liZe** [comment] 2023-04-12 15:11
(The issue is now closed because the PR is merged, but feel free to add comments!)
