### ISSUE TITLE
PDF selection order

### ISSUE THREAD

**Issue by rhodon-jargon** [Kozea/WeasyPrint#1910] opened 2023-07-13 13:19 UTC
I have a problem where selecting (and copy-pasting) text in the generated PDF results in the text being in a different order than selecting the text in the original HTML.

For example, the following CSS
```css
.indent {
  margin-left: 2em;
  position: relative;
}
.back-indent {
  float: left;
  left: -2em;
  position: absolute;
}
```
and HTML
```html
<div class="indent">
  <div class="back-indent">
    (1)
  </div>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>
```
are rendered the same:
![(1) Lorem ipsum...](https://github.com/Kozea/WeasyPrint/assets/113766614/10aea9ea-f13c-4980-bb42-ce9c134e5042)

But the text when copied from e.g. a browser is:
```
(1)
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
```

While copying from a generated PDF document yields:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
(1)
```

This same problem occurs with many PDF generators, including Prince. So this problem might be inherent to the generation process. But I thought I would ask if there is any way to force the selection order to be the same as copying from a browser (with or without the newline after `(1)`, that's not important). Or if there is any way to change the generation process to not mixup the order.

**Comment by liZe** [comment] 2023-07-13 15:33
Hi!

Thanks for your bug report.

That’s actually a duplicate of #531. Text selection can be very different depending on the PDF reader, and I’m not sure that there’s something we can do about that.

If anyone wants to search what’s possible to do in the PDF specification, that would be useful, but I didn’t find anything interesting and reliable yet 😢.

**Closed by liZe** 2023-07-13 15:33 UTC
