### ISSUE TITLE
Html to PDF - word-break: break-all does not reflect the correct expected formatting

### ISSUE THREAD

**Issue by frafor** [Kozea/WeasyPrint#1507] opened 2021-11-27 02:08 UTC
I have attached a couple images of what I see in HTML and what WeasyPrint "believes" I want to see.

Please, look at this. Just help here by, if you know, simply showing the CSS to be included so that WeasyPrint will do it the way we need in the HTML image.

## This is what we need: (html)

![wordwraphtml](https://user-images.githubusercontent.com/4719577/143664774-e0126c85-6770-46c4-967c-cdda1f783f2d.png)

## This is what WeasyPrint “believes” we need: (pdf)

![wordwrappdf](https://user-images.githubusercontent.com/4719577/143664777-5d643ff5-acbb-477a-bf9b-a85d774d6efd.png)

**Comment by frafor** [comment] 2021-11-27 07:38
One more example of something that WeasyPrint cannot do when transforming from HTML to PDF:

This is what the HTML page contains (which is what we need):

![wordwraphtml2](https://user-images.githubusercontent.com/4719577/143672775-504157d8-6a18-46ed-9034-ad347a34b8b1.png)

And this is what the PDF contains, which HAS NO REASON to be like that (it is not following the instructions given):

![wordwrappdf2](https://user-images.githubusercontent.com/4719577/143672789-fd3822e8-c5b3-444b-b5cf-a2c97283fb9f.png)

**Comment by liZe** [comment] 2021-11-28 13:13
Hello!

You’re right, `word-break` is not correctly supported. This issue is a duplicate of #1153.

**Closed by liZe** 2021-11-28 13:13 UTC
