### ISSUE TITLE
CLI ignores --encoding when piping from stdin

### ISSUE THREAD

**Issue by carstenblt** [Kozea/WeasyPrint#1513] opened 2021-12-01 16:46 UTC
I am using the npm weasyprint-wrapper package with node.js, which feeds the input to stdin. The character encoding in the resulting PDF is wrong.

Providing a `<meta charset="utf8" />` works. Calling the command line with `-e utf8` does not.

**Comment by liZe** [comment] 2021-12-06 10:08
Hello!

This code works for me: `echo "é" | weasyprint -e utf-8 - output.pdf`. When I don’t give `-e utf-8`, I get latin-1 instead, so I suppose that the `-e` parameter is correctly handled when the input is stdin.

Could you please give more information about the code you use to get the wrong encoding?

**Comment by liZe** [comment] 2022-01-03 13:34
@carstenblt Did you find why you have this problem?

**Comment by carstenblt** [comment] 2022-01-08 14:08
@liZe No idea... I am still using the meta tag workaround.

**Comment by liZe** [comment] 2022-01-08 14:44
> @liZe No idea... I am still using the meta tag workaround.

That’s strange…

I’ll close this issue, as you found a suitable workaround and there’s no way to reproduce. If anyone gets the same error (and more information about how to reproduce it), we’ll reopen it.

**Closed by liZe** 2022-01-08 14:44 UTC
