### ISSUE TITLE
image missing with django and nginx

### ISSUE THREAD

**Issue by hervest** [Kozea/WeasyPrint#664] opened 2018-08-06 08:48 UTC
I used django and weasyprint 0.42.3 to make an application which print a pdf file with picture and css file which design my pdf file. I used nginx, gunicorn and supervisor to deploy my application. Nginx serves my static file. In my intranet all work well. When i used INTERNET PUBLIC IP ADDRESS to publish it on internet, my pdf file don't show anymore picture. but all the application's static files work well I see my gunicorn log but nothing. this the configuration

`html = render_to_string('pdf/print.html', {'pagesize':'A4'}) response = HttpResponse(content_type="application/pdf",) response['Content-Disposition'] = 'inline; filename="print.pdf"' weasyprint.HTML(string=html,base_url=request.build_absolute_uri()).write_pdf(response,stylesheets=[CSS(settings.STATIC_ROOT+'/css/default.css')])
return response`

Any help?

**Comment by liZe** [comment] 2018-08-06 09:44
> Any help?

Yes. Please use [Django-WeasyPrint](https://github.com/fdemmer/django-weasyprint), it will probably save you a lot of time and avoid useless requests.

Otherwise, enable [logging](http://weasyprint.readthedocs.io/en/latest/tutorial.html#logging), you will know why WeasyPrint cannot reach / draw images.

**Comment by hervest** [comment] 2018-08-06 14:33
can you help in the log, how i will do it? after return response?

**Comment by liZe** [comment] 2018-08-06 14:54
> can you help in the log, how i will do it? after return response?

As explained in the documentation (link is in previous comment), you can for example add this code to your application:
```python
import logging
logger = logging.getLogger('weasyprint')
logger.addHandler(logging.FileHandler('/tmp/weasyprint.log'))
```

You'll then get logs in the `/tmp/weasyprint.log` file.

**Comment by hervest** [comment] 2018-08-12 23:45
i try since one week, i saw nothing in the log. The problem is that its work well in my intranet, but refused when you try by internet.

**Comment by hervest** [comment] 2018-08-13 18:38
ok i got the log now

Failed to load stylesheet at http://IP_ADDR/static/css/default.css : HTTPError: HTTP Error 401: 
Failed to load image at "http://IP_ADDR/static/image/cirdes_50x48.png" (HTTPError: HTTP Error 401: )

**Comment by liZe** [comment] 2018-08-13 22:05
401 is [Unauthorized](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors), accessing these URLs needs authentication.

Please use Django-WeasyPrint, it will probably save *us* a lot of time :wink:.

Closing, as it's definitely not a bug in WeasyPrint.

**Closed by liZe** 2018-08-13 22:05 UTC
