### ISSUE TITLE
Missing header and footer when table is missing a body

### ISSUE THREAD

**Issue by takis** [Kozea/WeasyPrint#978] opened 2019-10-25 15:02 UTC
When a table without a body is being rendered, the header and footer do not show up (while they do show up in Firefox and Chrome).
```html
<!DOCTYPE html>
<html>
  <body>
    <table>
      <thead>
        <tr><th>header</th></tr>
      </thead>
      <tfoot>
        <tr>
          <td>footer</td>
        </tr>
      </tfoot>
    </table>
  </body>
</html>

```

I'm using:
- Weasyprint 50
- evince: Gnome-documentenviewer 3.34.1

![Screenshot 2019-10-25 17:15:43](https://user-images.githubusercontent.com/128511/67583055-1ea13500-f74b-11e9-8c9b-e8be34c64f80.png)

**Comment by takis** [comment] 2019-10-25 15:14
When a table without a body is being rendered, the header and footer do not show up (while they do show up in Firefox and Chrome).
```html
<!DOCTYPE html>
<html>
  <body>
    <table>
      <thead>
        <tr><th>header</th></tr>
      </thead>
      <tfoot>
        <tr>
          <td>footer</td>
        </tr>
      </tfoot>
    </table>
  </body>
</html>

```

**Comment by takis** [comment] 2019-10-25 15:18
> When a table without a body is being rendered, the header and footer do not show up (while they do show up in Firefox and Chrome).
> 
> ```
> <!DOCTYPE html>
> <html>
>   <body>
>     <table>
>       <thead>
>         <tr><th>header</th></tr>
>       </thead>
>       <tfoot>
>         <tr>
>           <td>footer</td>
>         </tr>
>       </tfoot>
>     </table>
>   </body>
> </html>
> ```
> 
> I'm using:
> 
>     * Weasyprint 50
> 
>     * evince: Gnome-documentenviewer 3.34.1
> 
> 
> ![Screenshot 2019-10-25 17:15:43](https://user-images.githubusercontent.com/128511/67583055-1ea13500-f74b-11e9-8c9b-e8be34c64f80.png)

The output in Firefox:
![Screenshot 2019-10-25 17:17:47](https://user-images.githubusercontent.com/128511/67583208-717aec80-f74b-11e9-8530-7aaf0eda2919.png)

**Comment by takis** [comment] 2019-10-25 15:19
Firefox is showing the expected output:
![Screenshot 2019-10-25 17:17:47](https://user-images.githubusercontent.com/128511/67583283-953e3280-f74b-11e9-8f44-2c7eeffe29b0.png)
:

**Comment by Tontyna** [comment] 2019-10-25 15:45
Error condition: The bodyless table must be the **first** thing on the page. 

This table renders as expected:

```html
x<table>
  <thead>
    <tr><th>header</th></tr>
  </thead>
  <tfoot>
    <tr><td>footer</td></tr>
  </tfoot>
</table>
```

**Comment by Tontyna** [comment] 2019-10-26 15:11
The header and footer are thrown away by `table_layout` trying tho avoid widows and orphans. It detects a header and a footer but the empty table body suppresses their output.

There is an additional check for `page_is_empty` to avoid the suppression of tables like the one in your example. That's why the "x" in front of the table suppresses the suppression.

**Comment by liZe** [comment] 2019-12-15 21:09
Oh, that's actually a duplicate of #129.

**Closed by liZe** 2019-12-15 21:09 UTC
Labels: bug
