### ISSUE TITLE
Unable to render 'Platform' font correctly

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#1265] opened 2020-12-11 11:34 UTC
Consider a following html: 

https://gist.github.com/knyttl/dda77ba3bc211abe0737d2dc4e2dbd50

The HTML looks like this:

![Screenshot 2020-12-11 at 12 33 33](https://user-images.githubusercontent.com/401107/101898852-1bfeda80-3bad-11eb-9b20-4e4f9fe90755.png)

When you render it with 47, the text is broken like this:

![Screenshot_2020-12-11_at_11 14 49](https://user-images.githubusercontent.com/401107/101898788-04275680-3bad-11eb-9b17-92afe2e359ac.png)

With version 51, it looks fine, but it uses a different font:

![Screenshot 2020-12-11 at 12 34 01](https://user-images.githubusercontent.com/401107/101898890-2caf5080-3bad-11eb-852d-7c6a549ffa10.png)

I am not sure when but with some other versions, we used to use this font normally.

**Comment by liZe** [comment] 2020-12-11 15:36
Hello, and thank you for reporting this issue.

The latest stable version (52.2) should fix your problem. It is a duplicate of #1237.

**Closed by liZe** 2020-12-11 15:36 UTC
