### ISSUE TITLE
Test suite failures with python 3.9/3.10/3.11

### ISSUE THREAD

**Issue by darix** [Kozea/WeasyPrint#1873] opened 2023-05-08 10:06 UTC
While working on the opensuse package i noticed that the testsuite no longer passes.

Tests running with:

python311-base-3.11.2-1.3
python311-Pyphen-0.10.0-1.11
python311-appdirs-1.4.4-4.1
python311-attrs-22.2.0-5.1
python311-exceptiongroup-1.1.1-2.1
python311-flit-core-3.8.0-5.1
python311-iniconfig-2.0.0-4.2
python311-olefile-0.46-4.1
python311-packaging-23.1-4.1
python311-pluggy-1.0.0-2.1
python311-pycparser-2.21-2.1
python311-pydyf-0.6.0-1.1
python311-tomli-2.0.1-3.1
python311-webencodings-0.5.1-5.1
python311-zipp-3.15.0-2.1
python311-setuptools-67.6.1-5.1
python311-six-1.16.0-3.13
python311-psutil-5.9.5-1.1
python311-pytz-2023.3-5.5
python311-Brotli-1.0.9-2.1
python311-zopfli-0.2.2-2.1
python311-importlib-metadata-6.3.0-3.1
python311-tinycss2-1.2.1-3.1
python311-html5lib-1.1-5.1
python311-cffi-1.15.1-4.1
python311-pip-22.3.1-2.1
python311-fs-2.4.16-2.1
python311-Pillow-9.5.0-2.1
python311-cssselect2-0.7.0-2.1
python311-FontTools-4.39.3-2.1
python311-pytest-7.2.0-7.4

(test with 3.9 and 3.10 use the same python libraries)

Build log attached 
[build.log](https://github.com/Kozea/WeasyPrint/files/11420123/build.log)

**Comment by liZe** [comment] 2023-05-08 10:32
Hi!

The test suite of WeasyPrint 58.x (and previous versions) will only pass with pydyf 0.5.0 (even if WeasyPrint itself should work perfectly with 0.6.0). Sorry for the inconvenience.

**Comment by darix** [comment] 2023-05-08 10:59
is there a patch we can backport? will it be included in 59?

**Comment by liZe** [comment] 2023-05-08 11:11
> is there a patch we can backport?

Sure: https://github.com/Kozea/WeasyPrint/commit/e49d9555090ecec4f76b31f7beba18975f471211.

> will it be included in 59?

It’s already in [59.0b1](https://github.com/Kozea/WeasyPrint/releases/tag/v59.0b1).

**Comment by darix** [comment] 2023-05-08 11:22
better but not completely fixed:

```
=================================== FAILURES ===================================
___________________________ test_linear_gradients_5 ____________________________

assert_pixels = <function assert_pixels.<locals>.<lambda> at 0x7f0f317f93a0>

    @assert_no_logs
    def test_linear_gradients_5(assert_pixels):
>       assert_pixels('''
            rBrrrBrrrB
            rBrrrBrrrB
            rBrrrBrrrB
            rBrrrBrrrB
            rBrrrBrrrB
        ''', '''
          <style>@page { size: 10px 5px; background: repeating-linear-gradient(
          to right, blue 50%, blue 60%, red 60%, red 90%
        )''')

/home/abuild/rpmbuild/BUILD/weasyprint-58.1/tests/draw/test_gradient.py:68: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/abuild/rpmbuild/BUILD/weasyprint-58.1/tests/conftest.py:98: in <lambda>
    return lambda *args, **kwargs: draw.assert_pixels(
/home/abuild/rpmbuild/BUILD/weasyprint-58.1/tests/draw/__init__.py:55: in assert_pixels
    assert_pixels_equal(name, width, height, pixels, expected_pixels)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'linear_gradients_5', width = 10, height = 5
raw = <ImagingCore object at 0x7f0f2a5fadf0>
expected_raw = [(255, 0, 0), (0, 0, 255), (255, 0, 0), (255, 0, 0), (255, 0, 0), (0, 0, 255), ...]
tolerance = 0

    def assert_pixels_equal(name, width, height, raw, expected_raw, tolerance=0):
        """Take 2 matrices of pixels and assert that they are the same."""
        if raw != expected_raw:  # pragma: no cover
            pixels = zip_longest(raw, expected_raw, fillvalue=(-1, -1, -1))
            for i, (value, expected) in enumerate(pixels):
                if expected is None:
                    continue
                if any(abs(value - expected) > tolerance
                       for value, expected in zip(value, expected)):
                    actual_height = len(raw) // width
                    write_png(name, raw, width, actual_height)
                    expected_raw = [
                        pixel or (255, 255, 255) for pixel in expected_raw]
                    write_png(f'{name}.expected', expected_raw, width, height)
                    x = i % width
                    y = i // width
>                   assert 0, (
                        f'Pixel ({x}, {y}) in {name}: '
                        f'expected rgba{expected}, got rgba{value}')
E                   AssertionError: Pixel (0, 0) in linear_gradients_5: expected rgba(255, 0, 0), got rgba(255, 255, 255)

/home/abuild/rpmbuild/BUILD/weasyprint-58.1/tests/draw/__init__.py:104: AssertionError
------------------------------ Captured log call -------------------------------
INFO     weasyprint.progress:__init__.py:88 Step 1 - Fetching and parsing HTML - HTML string
INFO     weasyprint.progress:__init__.py:231 Step 2 - Fetching and parsing CSS - CSS string
INFO     weasyprint.progress:__init__.py:62 Step 3 - Applying CSS
INFO     weasyprint.progress:document.py:197 Step 4 - Creating formatting structure
INFO     weasyprint.progress:page.py:846 Step 5 - Creating layout - Page 1
INFO     weasyprint.progress:__init__.py:108 Step 6 - Creating PDF
INFO     weasyprint.progress:__init__.py:207 Step 7 - Adding PDF metadata
___________________________ test_linear_gradients_12 ___________________________

assert_pixels = <function assert_pixels.<locals>.<lambda> at 0x7f0f2ab865e0>

    @assert_no_logs
    def test_linear_gradients_12(assert_pixels):
>       assert_pixels('''
            BBBBBBBBB
            BBBBBBBBB
            BBBBBBBBB
            BBBBBBBBB
            BBBBBBBBB
        ''', '''<style>@page { size: 9px 5px; background:
          repeating-linear-gradient(to right, red 3px, blue 3px, blue 4px, red 4px
        )''')

/home/abuild/rpmbuild/BUILD/weasyprint-58.1/tests/draw/test_gradient.py:159: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/abuild/rpmbuild/BUILD/weasyprint-58.1/tests/conftest.py:98: in <lambda>
    return lambda *args, **kwargs: draw.assert_pixels(
/home/abuild/rpmbuild/BUILD/weasyprint-58.1/tests/draw/__init__.py:55: in assert_pixels
    assert_pixels_equal(name, width, height, pixels, expected_pixels)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'linear_gradients_12', width = 9, height = 5
raw = <ImagingCore object at 0x7f0f2ad7af30>
expected_raw = [(0, 0, 255), (0, 0, 255), (0, 0, 255), (0, 0, 255), (0, 0, 255), (0, 0, 255), ...]
tolerance = 0

    def assert_pixels_equal(name, width, height, raw, expected_raw, tolerance=0):
        """Take 2 matrices of pixels and assert that they are the same."""
        if raw != expected_raw:  # pragma: no cover
            pixels = zip_longest(raw, expected_raw, fillvalue=(-1, -1, -1))
            for i, (value, expected) in enumerate(pixels):
                if expected is None:
                    continue
                if any(abs(value - expected) > tolerance
                       for value, expected in zip(value, expected)):
                    actual_height = len(raw) // width
                    write_png(name, raw, width, actual_height)
                    expected_raw = [
                        pixel or (255, 255, 255) for pixel in expected_raw]
                    write_png(f'{name}.expected', expected_raw, width, height)
                    x = i % width
                    y = i // width
>                   assert 0, (
                        f'Pixel ({x}, {y}) in {name}: '
                        f'expected rgba{expected}, got rgba{value}')
E                   AssertionError: Pixel (0, 0) in linear_gradients_12: expected rgba(0, 0, 255), got rgba(255, 255, 255)

/home/abuild/rpmbuild/BUILD/weasyprint-58.1/tests/draw/__init__.py:104: AssertionError
------------------------------ Captured log call -------------------------------
INFO     weasyprint.progress:__init__.py:88 Step 1 - Fetching and parsing HTML - HTML string
INFO     weasyprint.progress:__init__.py:231 Step 2 - Fetching and parsing CSS - CSS string
INFO     weasyprint.progress:__init__.py:62 Step 3 - Applying CSS
INFO     weasyprint.progress:document.py:197 Step 4 - Creating formatting structure
INFO     weasyprint.progress:page.py:846 Step 5 - Creating layout - Page 1
INFO     weasyprint.progress:__init__.py:108 Step 6 - Creating PDF
INFO     weasyprint.progress:__init__.py:207 Step 7 - Adding PDF metadata
=============================== warnings summary ===============================
../../../../../usr/lib/python3.9/site-packages/pkg_resources/__init__.py:121
  /usr/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/draw/test_gradient.py::test_linear_gradients_5 - AssertionError:...
FAILED tests/draw/test_gradient.py::test_linear_gradients_12 - AssertionError...
======= 2 failed, 1903 passed, 38 xfailed, 1 warning in 62.32s (0:01:02) =======
```

**Comment by darix** [comment] 2023-05-08 11:26
same with 59.0b1

```
=================================== FAILURES ===================================
___________________________ test_linear_gradients_5 ____________________________

assert_pixels = <function assert_pixels.<locals>.<lambda> at 0x7fda345f3f70>

    @assert_no_logs
    def test_linear_gradients_5(assert_pixels):
>       assert_pixels('''
            rBrrrBrrrB
            rBrrrBrrrB
            rBrrrBrrrB
            rBrrrBrrrB
            rBrrrBrrrB
        ''', '''
          <style>@page { size: 10px 5px; background: repeating-linear-gradient(
          to right, blue 50%, blue 60%, red 60%, red 90%
        )''')

/home/abuild/rpmbuild/BUILD/weasyprint-59.0b1/tests/draw/test_gradient.py:68: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/abuild/rpmbuild/BUILD/weasyprint-59.0b1/tests/conftest.py:94: in <lambda>
    return lambda *args, **kwargs: draw.assert_pixels(
/home/abuild/rpmbuild/BUILD/weasyprint-59.0b1/tests/draw/__init__.py:55: in assert_pixels
    assert_pixels_equal(name, width, height, pixels, expected_pixels)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'linear_gradients_5', width = 10, height = 5
raw = <ImagingCore object at 0x7fda348d3af0>
expected_raw = [(255, 0, 0), (0, 0, 255), (255, 0, 0), (255, 0, 0), (255, 0, 0), (0, 0, 255), ...]
tolerance = 0

    def assert_pixels_equal(name, width, height, raw, expected_raw, tolerance=0):
        """Take 2 matrices of pixels and assert that they are the same."""
        if raw != expected_raw:  # pragma: no cover
            pixels = zip_longest(raw, expected_raw, fillvalue=(-1, -1, -1))
            for i, (value, expected) in enumerate(pixels):
                if expected is None:
                    continue
                if any(abs(value - expected) > tolerance
                       for value, expected in zip(value, expected)):
                    actual_height = len(raw) // width
                    write_png(name, raw, width, actual_height)
                    expected_raw = [
                        pixel or (255, 255, 255) for pixel in expected_raw]
                    write_png(f'{name}.expected', expected_raw, width, height)
                    x = i % width
                    y = i // width
>                   assert 0, (
                        f'Pixel ({x}, {y}) in {name}: '
                        f'expected rgba{expected}, got rgba{value}')
E                   AssertionError: Pixel (0, 0) in linear_gradients_5: expected rgba(255, 0, 0), got rgba(255, 255, 255)

/home/abuild/rpmbuild/BUILD/weasyprint-59.0b1/tests/draw/__init__.py:104: AssertionError
------------------------------ Captured log call -------------------------------
INFO     weasyprint.progress:__init__.py:155 Step 1 - Fetching and parsing HTML - HTML string
INFO     weasyprint.progress:__init__.py:276 Step 2 - Fetching and parsing CSS - CSS string
INFO     weasyprint.progress:__init__.py:62 Step 3 - Applying CSS
INFO     weasyprint.progress:document.py:246 Step 4 - Creating formatting structure
INFO     weasyprint.progress:page.py:851 Step 5 - Creating layout - Page 1
INFO     weasyprint.progress:__init__.py:107 Step 6 - Creating PDF
INFO     weasyprint.progress:__init__.py:210 Step 7 - Adding PDF metadata
___________________________ test_linear_gradients_12 ___________________________

assert_pixels = <function assert_pixels.<locals>.<lambda> at 0x7fda345f3f70>

    @assert_no_logs
    def test_linear_gradients_12(assert_pixels):
>       assert_pixels('''
            BBBBBBBBB
            BBBBBBBBB
            BBBBBBBBB
            BBBBBBBBB
            BBBBBBBBB
        ''', '''<style>@page { size: 9px 5px; background:
          repeating-linear-gradient(to right, red 3px, blue 3px, blue 4px, red 4px
        )''')

/home/abuild/rpmbuild/BUILD/weasyprint-59.0b1/tests/draw/test_gradient.py:159: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/abuild/rpmbuild/BUILD/weasyprint-59.0b1/tests/conftest.py:94: in <lambda>
    return lambda *args, **kwargs: draw.assert_pixels(
/home/abuild/rpmbuild/BUILD/weasyprint-59.0b1/tests/draw/__init__.py:55: in assert_pixels
    assert_pixels_equal(name, width, height, pixels, expected_pixels)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'linear_gradients_12', width = 9, height = 5
raw = <ImagingCore object at 0x7fda34679510>
expected_raw = [(0, 0, 255), (0, 0, 255), (0, 0, 255), (0, 0, 255), (0, 0, 255), (0, 0, 255), ...]
tolerance = 0

    def assert_pixels_equal(name, width, height, raw, expected_raw, tolerance=0):
        """Take 2 matrices of pixels and assert that they are the same."""
        if raw != expected_raw:  # pragma: no cover
            pixels = zip_longest(raw, expected_raw, fillvalue=(-1, -1, -1))
            for i, (value, expected) in enumerate(pixels):
                if expected is None:
                    continue
                if any(abs(value - expected) > tolerance
                       for value, expected in zip(value, expected)):
                    actual_height = len(raw) // width
                    write_png(name, raw, width, actual_height)
                    expected_raw = [
                        pixel or (255, 255, 255) for pixel in expected_raw]
                    write_png(f'{name}.expected', expected_raw, width, height)
                    x = i % width
                    y = i // width
>                   assert 0, (
                        f'Pixel ({x}, {y}) in {name}: '
                        f'expected rgba{expected}, got rgba{value}')
E                   AssertionError: Pixel (0, 0) in linear_gradients_12: expected rgba(0, 0, 255), got rgba(255, 255, 255)

/home/abuild/rpmbuild/BUILD/weasyprint-59.0b1/tests/draw/__init__.py:104: AssertionError
------------------------------ Captured log call -------------------------------
INFO     weasyprint.progress:__init__.py:155 Step 1 - Fetching and parsing HTML - HTML string
INFO     weasyprint.progress:__init__.py:276 Step 2 - Fetching and parsing CSS - CSS string
INFO     weasyprint.progress:__init__.py:62 Step 3 - Applying CSS
INFO     weasyprint.progress:document.py:246 Step 4 - Creating formatting structure
INFO     weasyprint.progress:page.py:851 Step 5 - Creating layout - Page 1
INFO     weasyprint.progress:__init__.py:107 Step 6 - Creating PDF
INFO     weasyprint.progress:__init__.py:210 Step 7 - Adding PDF metadata
=============================== warnings summary ===============================
../../../../../usr/lib/python3.9/site-packages/pkg_resources/__init__.py:121
  /usr/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/draw/test_gradient.py::test_linear_gradients_5 - AssertionError:...
FAILED tests/draw/test_gradient.py::test_linear_gradients_12 - AssertionError...
======= 2 failed, 1914 passed, 38 xfailed, 1 warning in 62.06s (0:01:02) =======
```

**Comment by liZe** [comment] 2023-05-08 11:33
These problems are different, and probably not related to the latest changes in WeasyPrint because [tests pass on our CI](https://github.com/Kozea/WeasyPrint/actions/runs/4900693387).

The usual suspect for problems with gradients is Ghostscript. Which version of Ghostscript do you use?

**Comment by darix** [comment] 2023-05-08 11:42
ghostscript-9.56.1-3.1

**Comment by darix** [comment] 2023-05-08 11:46
This is openSUSE Tumbleweed JFYI

**Comment by liZe** [comment] 2023-05-08 11:54
> ghostscript-9.56.1-3.1

Then the problem is probably caused by this bug in Ghostscript https://bugs.ghostscript.com/show_bug.cgi?id=705225. Tests should pass with older 9.55 and newer 10.x versions.

If you can’t change Ghostscript’s version, the easiest workaround is to ignore these tests (and mark them as `xfail` for example).

**Comment by darix** [comment] 2023-05-08 11:59
I pinged our ghostscript maintainer about it.

**Comment by liZe** [comment] 2023-07-12 08:59
Closing, as there’s nothing more we can do here.

**Closed as not planned by liZe** 2023-07-12 08:59 UTC
