### ISSUE TITLE
Rendering cropped table figures

### ISSUE THREAD

**Issue by surfmachina** [Kozea/WeasyPrint#535] opened 2017-11-13 03:58 UTC
I'm using weazyprint to render tables into figures with python. The problem that I am having is weazyprint renders the table into a full page, which then requires me to open the png file and crop out the table. Is there a way render the table with just a simple margin?

The basic code I am using is:

```python
env = Environment(loader=FileSystemLoader('.'))
template = env.get_template("myreport.html")
report_title = "%s %s" % ("Work", "Tuesday 17-9-2017")
print report_title

template_vars = {"title": report_title, "oneday_report_table": df.to_html(index=False, justify='left')}
html_out = template.render(template_vars)

HTML(string=html_out).write_png("report.png", stylesheets=["style.css"])
```

Thanks, Tom

**Comment by liZe** [comment] 2017-11-16 14:13
Could you please provide your `myreport.html` file, so that I can understand your problem?

**Comment by liZe** [comment] 2017-12-04 20:39
@surfmachina Can I close this issue?

**Comment by TomCompCogNeuro** [comment] 2017-12-04 23:42
Sorry for the delayed update. I figured out that if you set the page attributes in the css style sheet you can crop the table size. This, however, is an ugly solution becasue I had to search to find the right page size and hard code the numbers and if something in the table changes size, you have to go back and search for new parameters.  

It might be useful to keep it open in case someone with more css experience has an elegant solution. I'm newbie, so the answer might be trivial for the right person. Attached is the css file and the html template. 

[CSSandMyReport.zip](https://github.com/Kozea/WeasyPrint/files/1529156/CSSandMyReport.zip)

**Comment by liZe** [comment] 2019-07-19 09:04
Long time no see!

There's no way to dynamically adjust the page size to the content size. This issue is a duplicate of #274 and #193.

**Closed by liZe** 2019-07-19 09:04 UTC
Labels: CSS question
