### ISSUE TITLE
In column layout, break-inside: avoid-page; / page-break-inside: avoid; is not working as expected.

### ISSUE THREAD

**Issue by mimecine** [Kozea/WeasyPrint#2032] opened 2024-01-03 14:29 UTC
In a column layout, you can't seem to let content flow, but avoid a page-break.
I can't find a reference to this not being supported in the documentation.

Attached is a pdf that shows the problem and the html that was used to produce it with WeasyPrint 60.2
[column-break.pdf](https://github.com/Kozea/WeasyPrint/files/13820057/column-break.pdf)

And the html to generate is 
[column-break.html.zip](https://github.com/Kozea/WeasyPrint/files/13820089/column-break.html.zip)

I am hoping that it's just me who is stupid and can't figure it out... My book would look much better with this working!

**Comment by liZe** [comment] 2024-01-03 15:34
Hello!

Thanks for the report and for the example. I think that it’s a duplicate of #1963.

> I am hoping that it's just me who is stupid and can't figure it out... My book would look much better with this working!

No, you’re not stupid, that’s a real bug!

**Closed by liZe** 2024-01-03 15:34 UTC

**Comment by mimecine** [comment] 2024-01-03 18:16
Thanks for confirming. Now I can stop pulling my hair out:) 

P.S. It's an amazing project you have. I can't thank you enough for it.
