### ISSUE TITLE
Absolute positioning inside relatively positioned flexbox does not work

### ISSUE THREAD

**Issue by LukasKlement** [Kozea/WeasyPrint#1679] opened 2022-07-10 18:50 UTC
Absolutely positioning an element inside a flex-element appears to be broken. The relative position appears to be ignored.

WeasyPrint version: 56

Minimum reproducible example:
```
<html>
  <head>
    <style>
      .item {
        position: relative;
        display: flex;
        justify-content: center;
        width: 100%;
      }

      .primary-language,
      .secondary-language {
        display: block;
        flex: 1;
        text-align: right;
      }

      .primary-language {
        padding-right: 12pt;
      }

      .primary-language::after {
        content: '';
        border-width: 1pt;
        border-style: solid;
        border-color: var(--color-text);
        position: relative;
        top: 1pt;
        display: inline-block;
        width: 8pt;
        height: 8pt;
        position: absolute;
        left: 50%;
        transform: translateX(-5pt);
      }

      .secondary-language {
        text-align: left;
        padding-left: 12pt;
        color: var(--color-text-secondary);
      }
    </style>
  </head>
  <body>
    <div class="item">
      <span class="primary-language">Coffee</span><span class="secondary-language">قهوة</span>
    </div>
    <div class="item">
      <span class="primary-language">Tea</span><span class="secondary-language">شاي</span>
    </div>
    <div class="item">
      <span class="primary-language">Hot milk</span><span class="secondary-language">حليب ساخن</span>
    </div>
  </body>
</html>
```

If you were to wrap each `<div class="item"></div>` in a `<div>` with position: relative, WeasyPrint would produce the correct output.

**Comment by liZe** [comment] 2022-07-10 20:08
Hi!

Thanks for the bug report. I think that it’s a duplicate of #996, isn’t it?

**Comment by liZe** [comment] 2022-07-16 21:09
Let’s continue the discussion in #996.

**Closed by liZe** 2022-07-16 21:09 UTC
