### ISSUE TITLE
Problems with pydyf versions

### ISSUE THREAD

**Issue by nitroxido** [Kozea/WeasyPrint#2206] opened 2024-07-17 12:55 UTC
Our system auto-updated to latest pydyf (0.11.0) and we started to get this error:

```
  File "/env/lib/python3.11/site-packages/weasyprint/pdf/__init__.py", line 127, in generate_pdf
    pdf = pydyf.PDF((version or '1.7'), identifier)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PDF.__init__() takes 1 positional argument but 3 were given
```

It seems they changed the "__init__" signature so it doesn't support the `pdf = pydyf.PDF((version or '1.7'), identifier)` syntax anymore, but just `pdf = pydyf.PDF()`

This had me stalled for hours until I found the culprit!

**Comment by grewn0uille** [comment] 2024-07-17 12:57
Hi,

That’s a duplicate of #2205, https://github.com/Kozea/WeasyPrint/issues/2204, https://github.com/Kozea/WeasyPrint/issues/2203, https://github.com/Kozea/WeasyPrint/issues/2202 and https://github.com/Kozea/WeasyPrint/issues/2200.

**Closed by grewn0uille** 2024-07-17 12:57 UTC
