### ISSUE TITLE
Nested variables for "font-family" property will improperly lead to "unsupported computed value"

### ISSUE THREAD

**Issue by Avlyssna** [Kozea/WeasyPrint#1696] opened 2022-07-23 01:23 UTC
This issue originally was noticed when using `mkdocs-material`. Fonts were not showing within the PDF, although they would render fine in the browser. Upon closer inspection, it appears that nested variables will break the font name resolution:
```
WARNING: Unsupported computed value "var(--md-text-font,_),-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif" set in variable '--md-text-font-family' for property 'font-family'.
```

This can be reproduced with the following CSS:

```css
body {
  --md-text-font: Roboto;
  --md-text-font-family: var(--md-text-font, _), -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif;
  font-family: var(--md-text-font-family);
}
```

Ultimately, the `font-family` property validator does not have a case to handle when the list contains a `FunctionBlock` value.

**Comment by liZe** [comment] 2022-07-23 10:40
Hi!

Thanks for the bug report.

The problem is not exactly caused by nested variables, it’s caused by variables in properties allowing multiple values. This bug is thus a duplicate of #1219.

**Closed by liZe** 2022-07-23 10:40 UTC
