### ISSUE TITLE
SVG Display issue from v47 to v48

### ISSUE THREAD

**Issue by peironem** [Kozea/WeasyPrint#938] opened 2019-09-06 09:42 UTC
Hi,
apologize me for my bad english.

I'm here to report an issue founded moving from weasyprint v.47 to v.48.
I'm currently using this package under Win 10 x64 to create documents (of course) with barcodes and some data.

Now my problem is that while barcode is visible in version 47, moving to 48 seems to make them disappearing: here is my code (container plus img tag and relative styles)

 - HTML:
```HTML
<div class="abs t-45 h-15 w-58 label-box" style="left: {{some_value}};">
	<div class="abs w-100 h-70 t-5 over-none">
		<img src="{{an_image_path}}" class="abs center-vrt w-98 l-1">
	</div>
	<p class="abs h-20 w-100 all-c" style="bottom: 7.5%;">{{some_text}}</p>
</div>
```

- CSS
```CSS
.abs {position: absolute;}
.t-5 {top: 5%;}
.t-45 {top: 45%;}
.l-1 {left: 1%;}
.h-15 {height: 15%;}
.h-20 {height: 20%;}
.h-70 {height: 70%;}
.w-58 {width: 58%}
.w-98 {width: 98%}
.w-100 {width: 100%}
.label-box {border: .25mm #000 solid;}
.over-none {overflow: hidden;}
.center-vrt {top: 50%; transform: translateY(-50%);}
.all-c {text-align: center;}
```

So, i'm using weasyprint as a python package, passing to the **write_pdf()** function html and css:

Here is the template, blue section defines the img tag position. Notice taht the image is bigger that the container: that's because i need to have barcode width 100% to fit the entire available space, but i can't force the height or i'll lose the ratio and barcode does't works anymore.
That's why container has the **overflow: hidden** property.
![container](https://user-images.githubusercontent.com/54980751/64417176-e3627e00-d098-11e9-97f0-501bc2605800.PNG)

Here's what i get rendered with weasyprint v.47
![==47](https://user-images.githubusercontent.com/54980751/64417173-e3627e00-d098-11e9-9787-d421fa16c064.PNG)

Here's what i get rendered with weasyprint v.48
![==48](https://user-images.githubusercontent.com/54980751/64417174-e3627e00-d098-11e9-828a-aa6675a78582.PNG)

Unfortunately i wasn't able to dig more deeper in the issue, i've tried to check if logs says something different in both versions but nothings, logs are the same, only warnings about some unknown value or property (not related with te issue).
Reading v.48 documentation i can't find something taht can help me understanding or solving the problem.
So, i'm here to ask if you can kindly check what is going wrong or if i'm doing somenthing wrong

Many thanks.
Best regards,
P.M.

**Comment by liZe** [comment] 2019-09-06 14:01
Thanks for reporting this issue.

Could you please provide a sample that gives what's in your v47/v48 images? It will be easier for me to find where the problem comes from.

**Comment by peironem** [comment] 2019-09-06 15:31
Sure.
Images are simple svg made up by balck and white rectangles generated via third-party library named 'python-barcode'

Py library doesn't change, so both generated images are identical each other, anyhow i'll update both pictures. Here you can find the archive:
**[images.zip](https://github.com/Kozea/WeasyPrint/files/3584583/images.zip)**


Thanks for your help.
P.M.

**Comment by liZe** [comment] 2019-09-13 14:15
> Could you please provide a sample that gives what's in your v47/v48 images? It will be easier for me to find where the problem comes from.

I'd like to have real HTML samples too :smile:.

**Comment by peironem** [comment] 2019-09-16 12:58
Ok,
I'll give you the template before the render.

Here it is:
[template.zip](https://github.com/Kozea/WeasyPrint/files/3616335/template.zip)

Do you need linked css(s) either?

**Comment by liZe** [comment] 2019-09-16 15:00
> Do you need linked css(s) either?

I do.

What I need is a HTML sample that helps me to reproduce your problem. I have to be able to generate the document with v47 and with v48, and see the difference. Without the CSS sheets, I can't  see the problem.

**Comment by peironem** [comment] 2019-09-16 15:41
As i thought.

Here you have the csses:
[csss.zip](https://github.com/Kozea/WeasyPrint/files/3617028/csss.zip)

Do you have all what you need?

**Comment by liZe** [comment] 2019-09-17 08:34
> Do you have all what you need?

Thank you, I can reproduce now.

**Comment by liZe** [comment] 2019-09-17 09:03
The bug is actually in CairoSVG: it's a duplicate of Kozea/CairoSVG#248. You can fix it by upgrading CairoSVG to version 2.4.2.

**Comment by peironem** [comment] 2019-09-17 13:27
I'll try that way.

Thanks for your help!
Have a nice day.

P.M.

**Comment by liZe** [comment] 2019-09-18 08:11
@peironem Please let me know if it works, so that we can close this issue!

**Comment by peironem** [comment] 2019-09-19 10:02
> @peironem Please let me know if it works, so that we can close this issue!

@liZe I've upgraded the gtk3 environ from 3.24.8 to 3.24.10 and weasyprint works fine in 47, 48 and 49 (currently in-use) versions.

Thanks for your prompt help.
Didn't realized that the problem whas triggered by cairoSVG lib.

Sorry for wasting your Time, issue can be closen
Have a nice day.

P.M.

**Comment by liZe** [comment] 2019-09-19 10:09
> Sorry for wasting your Time, issue can be closed

No problem, have fun with WeasyPrint!

**Closed by liZe** 2019-09-19 10:09 UTC
