### ISSUE TITLE
problems testing the installation: Step 5 - Run WeasyPrint

### ISSUE THREAD

**Issue by Miguel-Android** [Kozea/WeasyPrint#1335] opened 2021-04-13 15:42 UTC
(tecnomarket-AiptmeKt) D:\Proyectos\Django\tecnomarket>python -m weasyprint http://weasyprint.org weasyprint.pdf

WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:1686.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:1863.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:2040.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:2141.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:2242.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:2304.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:2367.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:2574.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:2782.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:2843.
WARNING: Ignored `width:100vw` at 1:3795, invalid value.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:4335.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:5559.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:6585.
WARNING: Ignored `overflow-x:hidden` at 1:6712, unknown property.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:7421.
WARNING: Ignored `width:-moz-min-content` at 1:7652, invalid value.
WARNING: Ignored `width:-webkit-min-content` at 1:7675, invalid value.
WARNING: Ignored `width:min-content` at 1:7701, invalid value.
WARNING: Ignored `min-height:60vh` at 1:8072, invalid value.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:8441.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:9331.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:9528.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:9713.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:10036.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:10393.
WARNING: Ignored `box-shadow:0 0 0 .01em #1ee494` at 1:10702, unknown property.
WARNING: Ignored `box-shadow:0 0 0 .65em #19d489` at 1:11162, unknown property.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:11297.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:11400.
WARNING: Ignored `background-position-y:0` at 1:11986, unknown property.
WARNING: Ignored `left:calc(-.8em - .35em / 2)` at 1:12201, invalid value.
WARNING: Ignored `background-position-y:100%` at 1:12526, unknown property.
WARNING: Ignored `max-width:calc(100% + 45px * 2 + 2px)` at 1:12778, invalid value.
WARNING: Ignored `box-shadow:0 1px 0` at 1:12905, unknown property.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:14267.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:14713.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:14805.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:15475.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:15586.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:16755.
WARNING: Ignored `box-shadow:0 5px 5px 0 rgba(111,122,137,0.3)` at 1:17986, unknown property.
WARNING: Ignored `box-shadow:0 0 0 0 #e2e4e8` at 1:18090, unknown property.
WARNING: Ignored `background-position-x:0` at 1:18533, unknown property.
WARNING: Ignored `box-shadow:0 5px 5px 0 rgba(111,122,137,0.1)` at 1:19035, unknown property.
WARNING: Ignored `background-position-x:0` at 1:19870, unknown property.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:19939.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:20047.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:21239.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:21432.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:21656.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:22331.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 831px)
WARNING: Invalid media type " screen and (min-width: 831px)" the whole @media rule was ignored at 1:26061.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 830px)
WARNING: Invalid media type " screen and (max-width: 830px)" the whole @media rule was ignored at 1:26276.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:29200.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:30333.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:30461.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:30620.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:30721.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:31681.
WARNING: Ignored `background-position-y:100%` at 1:32173, unknown property.
WARNING: Ignored `vertical-align:center` at 1:32414, invalid value.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:32773.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 831px)
WARNING: Invalid media type " screen and (min-width: 831px)" the whole @media rule was ignored at 1:33286.
[weasyprint.pdf](https://github.com/Kozea/WeasyPrint/files/6304913/weasyprint.pdf)

![image](https://user-images.githubusercontent.com/64152814/114580607-4954b580-9c7f-11eb-8651-98211cae15f5.png)

**Comment by liZe** [comment] 2021-04-13 15:48
Hello!

The problem you have is caused by [a bug in Cairo 1.17.4](https://gitlab.freedesktop.org/cairo/cairo/-/issues/449). It’s actually a duplicate of #1292. You can use a previous version of Cairo, or wait for a new version of Cairo (the bug fix is not released yet), or even try the current master branch of WeasyPrint that doesn’t use Cairo anymore (probably not ready for production, though).

**Closed by liZe** 2021-04-13 15:48 UTC

**Comment by Miguel-Android** [comment] 2021-04-13 16:49
Gracias. Lo voy a probar.
