### ISSUE TITLE
Kerning issues after merging pages

### ISSUE THREAD

**Issue by pferreir** [Kozea/WeasyPrint#1517] opened 2021-12-08 16:22 UTC
Hello. First of all, congratulations for this library. I'm impressed at how accurate the DOM layout implementation is!

I am using weasyprint in a web app and trying to produce a multi-page PDF. The only way I found to do that (short of using some separate lib to manually join weasyprint-produced PDFs) was a code fragment I found in your docs:

```python
all_pages = [p for doc in documents for p in doc.pages]
documents[0].copy(all_pages).write_pdf('combined.pdf')
```

This works fine, except that then I get very serious kerning/space issues in the resulting PDF. Some letters end up really too far apart and break words apart.

Is this a known issue and what can I do to avoid it?

Thanks!

**Comment by liZe** [comment] 2021-12-08 17:31
Hello!

> First of all, congratulations for this library. I'm impressed at how accurate the DOM layout implementation is!

💛



> This works fine, except that then I get very serious kerning/space issues in the resulting PDF.

This problem really looks like #1489. Do you use the latest 53.4 version?

**Comment by pferreir** [comment] 2021-12-09 11:06
You are absolutely right! Apologies, I should have upgraded to the last version. I'll close the ticket.

**Comment by SchrodingersGat** [comment] 2022-08-15 00:11
@liZe I have found a regression here - documented below. Please LMK if you want me to start a new issue rather than resurrecting this thread.

This issue has returned in [v56.1](https://github.com/Kozea/WeasyPrint/releases/tag/v56.1) - I have confirmed by switching between 56.1 and 53.4 (without any other changes).

| 53.4 | 56.1 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10080325/184559979-96f785ab-7be4-4719-aef1-f4395eeb3a5c.png) | 
![image](https://user-images.githubusercontent.com/10080325/184560047-f86c5da8-6158-47dc-997b-0a20d3f11b07.png) |

And the code used to merge these PDF files together:

```python
pages = []

for output in outputs:
    doc = output.get_document()
    for page in doc.pages:
        pages.append(page)

pdf = outputs[0].get_document().copy(pages).write_pdf()
```

**Comment by liZe** [comment] 2022-08-15 06:42
That’s maybe related to #1662.

**Comment by liZe** [comment] 2022-08-15 07:56
> That’s maybe related to #1662.

Yes, that’s definitely a duplicate of #1662. Mixing pages from different documents (as in your issue) or adding elements into the tree after the rendering (as in #1662) are features that are not explicitly prevented by WeasyPrint, but they were not supposed to work and to be supported 😀.

Let’s continue the discussion in #1662.

**Closed by liZe** 2022-08-15 07:56 UTC
