### ISSUE TITLE
SVGs Not Fully Rendering

### ISSUE THREAD

**Issue by HipHoff** [Kozea/WeasyPrint#549] opened 2017-12-12 01:42 UTC
I'm having an issue where SVGs are not fully rendering in the PDF WeasyPrint is generating. This seems to be subtly different from https://github.com/Kozea/WeasyPrint/issues/339 since it isn't a full crop; rather, elements just seem to stop rendering after a certain point.

HTML file:

```
<!DOCTYPE HTML>
<html>
<head>
    <style>

    @page {
            size: landscape;
	    margin: 0px;
	}

    </style>
</head>

<body>
    <img src='bubble_chart.svg'>
</body>
</html>
```

[Link to Bubble Chart SVG file](http://uploads.trib3.com.s3.amazonaws.com/data_sci/bubble_chart.svg)

The Bubble Chart looks fine when viewed with the browser or a program like Sketch:
![image](https://user-images.githubusercontent.com/5578340/33862745-232feb10-de99-11e7-9b00-0e996935dd63.png)

Note the x-axis rendering. However, when converted into a PDF via Weasyprint, that SVG looks like:

![image](https://user-images.githubusercontent.com/5578340/33862762-3a00f514-de99-11e7-97fd-376cdf320b13.png)

This isn't actually a pure crop, as the y-axis is actually displaying below where the 3.0 tick should be on the y-axis.

Any idea why this is happening? I've tried adjusting the page size, swapping to a data url approach (as mentioned in https://github.com/Kozea/WeasyPrint/issues/75), et cetera, yet this SVG never fully renders. (The SVG will fully render if I make the height and width smaller, but I want this chart to fill up most of the page.)

Also, the svg fully renders to a PDF when running `cairosvg bubble_chart.svg -o bubble_chart.pdf`. I'm running WeasyPrint .41 and Cairo 1.14.10.

Thanks for any help you can offer here!

**Comment by liZe** [comment] 2017-12-12 11:31
Hello!

It's another duplicate of #339: the bug is in Cairo, you need to install Cairo ≥ 1.15.4.

**Closed by liZe** 2017-12-12 11:31 UTC

**Comment by HipHoff** [comment] 2017-12-12 20:21
Thanks for the quick reply @liZe! That's working well after updating Cairo.
