### ISSUE TITLE
Truncated text lines in table with wide image

### ISSUE THREAD

**Issue by greycat70** [Kozea/WeasyPrint#521] opened 2017-10-10 19:21 UTC
http://wooledge.org/~greg/bug-20171010.html

This is a trimmed-down version of the source HTML which demonstrates the problem.  The actual image used in production is 1086x822, but I found a random web banner that's wide enough to still trigger it.

When converted to PDF, some of the lines of text get truncated -- for example, the word "perisylvian" is lost after "left posterior" in the first numbered section, and the word "dipole" is lost from "Only three dipole were seen" in the third.  The truncation is even more dramatic with the original image.

Problem reproduced using weasyprint 0.41 on Debian 9 amd64 (python 2.7.13, libcairo2 1.14.8, libpango 1.40.5).

**Comment by liZe** [comment] 2017-10-11 07:48
Thanks for taking the time to report this issue.

It's a duplicate of #227. The [spec](https://drafts.csswg.org/css-sizing/#intrinsic-contribution) was wrong in 2014 when the issue was reported, but it looks now fixed. It should be easy to fix in the code too.

I'm closing this issue and adding #227 to next release.

**Closed by liZe** 2017-10-11 07:48 UTC
