### ISSUE TITLE
v57.0 throws OSError: cannot write mode CMYK as PNG

### ISSUE THREAD

**Issue by mgu** [Kozea/WeasyPrint#1758] opened 2022-10-29 14:17 UTC
```py
from weasyprint import HTML

with open("test.html", "r") as f:
    html_data = f.read()

html = HTML(string=html_data, base_url="")
html.write_pdf()
```

```html
<html>
	<head>
	</head>
	<body>
		<img src="https://upload.wikimedia.org/wikipedia/en/2/25/Channel_digital_image_CMYK_color.jpg" />
	</body>
</html>
```

This code works on v56.1 and master branch, but fails on v57.0

pip freeze output:
```
Brotli==1.0.9
cairocffi==1.4.0
CairoSVG==2.5.2
cffi==1.15.1
cssselect2==0.7.0
defusedxml==0.7.1
fonttools==4.38.0
html5lib==1.1
pdfrw==0.4
Pillow==9.2.0
pycparser==2.21
pydyf==0.5.0
pyphen==0.13.0
six==1.16.0
tinycss2==1.2.1
-e git+ssh://git@github.com/Kozea/WeasyPrint.git@3c6ac5ec4b720d50b5a371a03d42ca3499829126#egg=weasyprint
webencodings==0.5.1
zopfli==0.2.1
```

**Comment by liZe** [comment] 2022-10-29 21:07
Hi!

Thanks for the report.

It’s actually a duplicate of #1755, it’s already fixed!

**Closed by liZe** 2022-10-29 21:07 UTC
Labels: crash

**Comment by liZe** [comment] 2022-10-29 21:08
(Note that the colors are broken because CMYK is not supported, that’s another problem discussed in #1091.)
