### ISSUE TITLE
pydyf 0.11.0 not supported

### ISSUE THREAD

**Issue by Hellboy94520** [Kozea/WeasyPrint#2203] opened 2024-07-15 09:37 UTC
Your library is not working anymore with pydyf 0.11.0 (release data 07/12/2024) pydyf.PDF is not taking any arguments any more on constructor ! 

`File "XXXX", line XXX, inmy_method
    HTML(string=html_out).write_pdf(path, stylesheets=[CSS(string='@page { size: A4; margin: 1cm }, h3 { font-weight:bold; }')])
  File "/usr/local/lib/python3.11/dist-packages/weasyprint/__init__.py", line 259, in write_pdf
    self.render(font_config, counter_style, **options)
  File "/usr/local/lib/python3.11/dist-packages/weasyprint/document.py", line 390, in write_pdf
    pdf = generate_pdf(self, target, zoom, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/weasyprint/pdf/__init__.py", line 127, in generate_pdf
    pdf = pydyf.PDF((version or '1.7'), identifier)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PDF.__init__() takes 1 positional argument but 3 were given`

**Comment by grewn0uille** [comment] 2024-07-15 09:39
Hi,

Duplicate of #2200.

**Closed by grewn0uille** 2024-07-15 09:39 UTC

**Comment by liZe** [comment] 2024-07-15 09:45
> And what about a release with the fix ?

You use a pinned version of WeasyPrint, we can’t fix that with a new release 😄. The latest stable version of WeasyPrint already works with pydyf 0.11.0.

**Comment by Hellboy94520** [comment] 2024-07-15 09:50
Yes but we are still blocked in 61.2 because of tinycss2>=1.3.0 requirements. So the latest release in 62.X, are not interesting  for us, that is why, we have the issue. 
Thank you for your quick answer, we are gonna fix the pydyf release by ourselves.

**Comment by liZe** [comment] 2024-07-15 09:53
OK! Versions will be pinned for you in future versions (#2200).
