### ISSUE TITLE
Could not load source '<string>': Source unavailable.

### ISSUE THREAD

**Issue by yeonjae-han** [Kozea/WeasyPrint#837] opened 2019-03-28 18:40 UTC
hi,

I am facing trouble with the simple python code below.
would you help me to come over the error? 

anaconda python 3.7.1.64 + vs code.

```
from weasyprint import HTML
HTML('http://weasyprint.org/').write_pdf('/tmp/weasyprint-website.pdf')

```

### **error log**
```
Could not load source '<string>': Source unavailable.

Exception has occurred: GeneratorExit
  File "<string>", line 1, in <genexpr>
  File "<string>", line 1, in <lambda>
  File "/Users/han-yeonjae/anaconda3/lib/python3.7/site-packages/cssselect2/__init__.py", line 108, in <listcomp>
    if test(element)
  File "/Users/han-yeonjae/anaconda3/lib/python3.7/site-packages/cssselect2/__init__.py", line 106, in match
    for selector_list in relevant_selectors
  File "/Users/han-yeonjae/anaconda3/lib/python3.7/site-packages/weasyprint/css/__init__.py", line 852, in get_all_computed_styles
    for selector in sheet.matcher.match(element):
  File "/Users/han-yeonjae/anaconda3/lib/python3.7/site-packages/weasyprint/document.py", line 354, in _render
    page_rules, target_collector)
  File "/Users/han-yeonjae/anaconda3/lib/python3.7/site-packages/weasyprint/__init__.py", line 168, in render
    font_config)
  File "/Users/han-yeonjae/anaconda3/lib/python3.7/site-packages/weasyprint/__init__.py", line 211, in write_pdf
    font_config=font_config).write_pdf(
  File "/Users/han-yeonjae/Documents/python_tst/.vscode/hellowworld.py", line 2, in <module>
    HTML('http://weasyprint.org/').write_pdf('/tmp/weasyprint-website.pdf')
  File "/Users/han-yeonjae/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/han-yeonjae/anaconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/han-yeonjae/anaconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
```

**Comment by liZe** [comment] 2019-03-28 20:56
Hello!

There's probably a problem in VSCode. I think that it's Microsoft/vscode#64193 (as explained in dart-lang/sdk#35392 and flutter/flutter#24912). Anyway, judging from the trace, I'm pretty sure that it's not a problem in WeasyPrint (or in cssselect2).

**Comment by liZe** [comment] 2019-04-01 12:11
@yeonjae-han I'm closing this issue as it's definitely not a bug in WeasyPrint. Please feel free to reopen if we can do anything else about this problem.

**Closed by liZe** 2019-04-01 12:11 UTC

**Comment by yeonjae-han** [comment] 2019-04-02 16:50
Hi Guillaume,

Thank you for the your response on my inquire. yes  you are correct ! it is
not a error of  WeasyPrint . with your comments. I could solve it . now it
works well.

thanks you again.


Regards,




2019년 4월 1일 (월) 오후 9:11, Guillaume Ayoub <notifications@github.com>님이 작성:

**Comment by senshuran** [comment] 2019-04-16 20:58
Hi, I have the question as following: "Could not load source '<string>': Source unavailable." during import process. Could you please help me check the error?
 VS Code + Anaconda3 + tensorflow-gpu 1.10.0 + python3.6.8

**Comment by senshuran** [comment] 2019-04-16 20:59
Hi, 
I have the question as following:Could not load source '<string>': Source unavailable. during import process. Could you please help me check the error?
VS Code + Anaconda3 + tensorflow-gpu 1.10.0 + python3.6.8

**Comment by liZe** [comment] 2019-04-17 08:06
@yeonjae-han Do you remember how you solved your problem?

**Comment by lichuang0529** [comment] 2019-05-09 02:16
Have you solved the bug? My confirmation is VS Code+mxnet+virtualenv+python2.7 @senshuran
