### ISSUE TITLE
Assertion error with <th> tags in v54.X

### ISSUE THREAD

**Issue by msf-dev** [Kozea/WeasyPrint#1586] opened 2022-03-02 18:30 UTC
Hi, 

I have a django project using weasyprint and when I upgraded from version 53.4 to 54.X I recieve an assertion error. I've determined it only occurs when using `<th>` tags in the templates. Specifically, it's caused when the value of`align` is equal to `-webkit-match-parent` within the function `text_align` located in `weasyprint/layout/inline.py`. 

I was able to prevent the exception occuring by changing all `<th>`  tags to `<td>` but believe it may be similar to  #1538 as I am also using bootstrap v4.5.3 

### Python Code:
```py
def generate_pdf(template_name, context, http_request=None):
    base_url = "/"

    if http_request:
        base_url = http_request.build_absolute_uri()

    html_string = render_to_string(template_name, context)
    html_obj = HTML(string=html_string, base_url=base_url, url_fetcher=custom_url_fetcher)
    return html_obj.write_pdf(presentational_hints=True)
```

### Traceback:
```sh
  File "/home/runner/work/DjangoProject/Project/src/base/utils/files.py", line 43, in generate_pdf
    return html_obj.write_pdf(presentational_hints=True)
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/__init__.py", line 183, in write_pdf
    self.render(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/__init__.py", line 134, in render
    return Document._render(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/document.py", line 930, in _render
    [Page(page_box) for page_box in page_boxes],
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/document.py", line 930, in <listcomp>
    [Page(page_box) for page_box in page_boxes],
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/__init__.py", line 133, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/page.py", line 855, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/page.py", line 792, in remake_page
    page, resume_at, next_page = make_page(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/page.py", line 590, in make_page
    root_box, resume_at, next_page, _, _ = block_level_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 449, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 449, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 449, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 449, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 449, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 70, in block_level_layout_switch
    return block_box_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 112, in block_box_layout
    result = block_container_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 641, in block_container_layout
    next_page, new_children) = _in_flow_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 449, in _in_flow_layout
    collapsing_through) = block_level_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 56, in block_level_layout
    return block_level_layout_switch(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 66, in block_level_layout_switch
    return table_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/table.py", line 533, in table_layout
    all_groups_layout())
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/table.py", line 435, in all_groups_layout
    header, resume_at, next_page = group_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/table.py", line 166, in group_layout
    new_cell, cell_resume_at, _, _, _ = block_container_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 631, in block_container_layout
    abort, stop, resume_at, position_y = _linebox_layout(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/block.py", line 304, in _linebox_layout
    for i, (line, resume_at) in enumerate(lines_iterator):
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/inline.py", line 43, in iter_line_boxes
    line, resume_at = get_next_linebox(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/inline.py", line 114, in get_next_linebox
    offset_x = text_align(
  File "/home/runner/work/DjangoProject/Project/.venv/lib/python3.9/site-packages/weasyprint/layout/inline.py", line 1143, in text_align
    assert align == 'end'
AssertionError
```

**Comment by liZe** [comment] 2022-03-02 19:22
Hello,

This bug really looks like #1538. Did you try the latest version of WeasyPrint?

**Comment by liZe** [comment] 2022-03-02 19:26
> Specifically, it's caused when the value of`align` is equal to `-webkit-match-parent` within the function `text_align` located in `weasyprint/layout/inline.py`.

Sorry, I didn’t read your comment carefully. This bug is probably different, we have to check this.

**Comment by msf-dev** [comment] 2022-03-02 19:26
Yes, I tried it with 54.1 and 54.2 and the problem persists

**Comment by liZe** [comment] 2022-03-02 20:16
The bug was already fixed and tested in `master` as a side effect of #1524. It’s now fixed and tested in the `54.x` branch too, using some old-style code to avoid possible regressions that #1524 could introduce.

Before 54.3 is released, you can apply [the patch](https://github.com/Kozea/WeasyPrint/commit/c1178a559ca1cf566211bb712fc0e0c42e26b019.patch), or try the 54.x (safe) or master (less safe) branches.

Thanks for the bug report!

**Closed by liZe** 2022-03-02 20:16 UTC
Labels: crash

**Comment by msf-dev** [comment] 2022-03-02 20:21
Awesome thanks @liZe!
