### ISSUE TITLE
Page break report

### ISSUE THREAD

**Issue by pocomane** [Kozea/WeasyPrint#1894] opened 2023-06-04 10:32 UTC
I would like to add a page break before a specific element, if both the following conditions are true:
- It is split on multiple page without the new page break
- The new page break prevents the element to be split

Probably this is a too specific feature, so I would ask:
1) What is currently the most similar result I can get?
2) Can a flag be added to support "External page break logic"?

The 2) can be also something very simple and "Passive" like a --report-breaks flag that return a list of where the page breaks will be placed. For my scenario this would be enough since I can write a script/program that call WeasyPrint multiple times, adding iteratively some page breaks until it gets the desired result.

What this "List of page breaks" actually contains is an open point; anything related to the position in the input HTML would work for me.

Currently I am experimenting with this workaround:
- Adding a `<h4>possible-break-uid</h4>` before each div/p/etc
- Using `position: absolute; left: -999px;` style for `<h4>` to effectively hide them, but keeping weasyprint to generate metadata about them
- Searching the uid in the bookmarks of the pages returned by `weasyprint.HTML().render()`
- The "List of page breaks" are simply the uids in the first `<h4>` of each page  

but obviously an integrated solution would be a lot more usable.
.

**Comment by liZe** [comment] 2023-06-04 11:15
Hi!

> I would like to add a page break before a specific element, if both the following conditions are true:
> 
> * It is split on multiple page without the new page break
> * The new page break prevents the element to be split

I think that it’s a duplicate of #1252, isn’t it?

**Comment by pocomane** [comment] 2023-06-04 14:55
The issue I described would be solved if the behaviour in #1252 were implemented. However I described a more general solution that will enable the users to control page breaking in detail (at least the programmers user). I do not know how much is complex to implement, but my tests with the H4 trick suggest to me that all what is needed is already in place.

**Comment by liZe** [comment] 2023-07-12 08:48
WeasyPrint tries to follow the specifications, so we can try to add such a behaviour if it’s in the specification. Is your idea to get all the different [break points](https://www.w3.org/TR/css-break-3/#possible-breaks) with the Python API?

**Comment by pocomane** [comment] 2023-07-12 19:23
> WeasyPrint tries to follow the specifications

Which specification? I am proposing a way to get the list of the breaks added by WeasyPrint to a specific document, I do not think this can be covered by the html/css specification.

> Is your idea to get all the different [break points](https://www.w3.org/TR/css-break-3/#possible-breaks) with the Python API?

My idea was a command line flag, but yes, a python API would be enough for me since I can write a simple command line wrap.

Is it already possible to do something like that? The most close thing I found was the one I described as workaround.

**Comment by liZe** [comment] 2023-07-13 08:17
> Which specification? I am proposing a way to get the list of the breaks added by WeasyPrint to a specific document, I do not think this can be covered by the html/css specification.

The specification describing break points (linked in my comment).

> My idea was a command line flag, but yes, a python API would be enough for me since I can write a simple command line wrap.

If it’s a workaround to solve your original problem, then it would be better to solve #1252.

For a more general case, and as a workaround for now, if you want to know where your document was split with the API then you can add ids to your HTML document and use the [Page.anchors](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#weasyprint.document.Page.anchors) information to know where the pages are split. Would that be OK for you?

**Comment by pocomane** [comment] 2023-07-13 08:40
If I understand correctly, the page.anchor trick is similar to the one presented on my first post. I can continue to use it, sure. And yes, fixing #1252 would be helpfull in a lot of situation, but with 2) I was proposing a general way to handle page breaks programmatically.

I understand the confusion, so please close this issue. I will open a new one in case I found another situation in which I need a more powerful control on page breaks.

**Comment by liZe** [comment] 2023-07-13 08:43
> If I understand correctly, the page.anchor trick is similar to the one presented on my first post.

Yes, it is.

> I understand the confusion, so please close this issue. I will open a new one in case I found another situation in which I need a more powerful control on page breaks.

OK!

**Closed by liZe** 2023-07-13 08:43 UTC
Labels: CSS
