### ISSUE TITLE
Strange hyphenation result.

### ISSUE THREAD

**Issue by jjsarton** [Kozea/WeasyPrint#1633] opened 2022-04-30 12:48 UTC
Example:

```
<!DOCTYPE html>
<html>
    <head>
        <style>
			body {
				font-family: Sans;
			}
			div {
				border: 1px solid black;
			}
			.small {
				width:4em;
				border: 1px solid black;
			}
		</style>
	</head>
	<body>
		<div>
			anticonstitutionnellement
		</div>
		<div>
			anti&shy;cons&shy;ti&shy;tu&shy;tionnelle&shy;ment
		</div>
		<div class="small">
			anti&shy;cons&shy;ti&shy;tu&shy;tionnelle&shy;ment
		</div>
	</body>
</html>
```

Look at the result weasyprint shall do this better.

**Comment by grewn0uille** [comment] 2022-04-30 13:21
Hello!

I got the same result with Firefox and WeasyPrint.

![Screenshot 2022-04-30 at 15-18-36 Screenshot](https://user-images.githubusercontent.com/13187416/166107275-0de86ef1-a437-4db6-b69f-5d3e679e0807.png)
![Screenshot from 2022-04-30 15-17-22](https://user-images.githubusercontent.com/13187416/166107278-39830530-f6a1-4716-8a77-dda8cb14d7ec.png)

Can you please share the render you get?

**Comment by jjsarton** [comment] 2022-04-30 13:41
Look nice, I get other results.
I work with Fedora 35 XFCE
I use 53.4 (From Fedora).
![firefox](https://user-images.githubusercontent.com/951168/166107867-eca8f850-741f-4b50-8e5d-45fa0a4084db.png)
[index.pdf](https://github.com/Kozea/WeasyPrint/files/8597009/index.pdf)

[index.html.txt](https://github.com/Kozea/WeasyPrint/files/8597017/index.html.txt)

**Comment by jjsarton** [comment] 2022-04-30 13:52
I work with fedora 35 Xfce 
weasyprint 53.4 (from Fedora).

![evince](https://user-images.githubusercontent.com/951168/166108256-d9ce43ee-4fc1-4e24-aa18-232e0b485a2b.png)
![firefox](https://user-images.githubusercontent.com/951168/166108261-1793c782-04f1-4d94-8897-d470d6afa9e7.png)
[index.html.txt](https://github.com/Kozea/WeasyPrint/files/8597041/index.html.txt)

**Comment by grewn0uille** [comment] 2022-04-30 14:15
This issue is a duplicate of https://github.com/Kozea/WeasyPrint/issues/1515.
It has been fixed in v54 :)

**Closed by grewn0uille** 2022-04-30 14:15 UTC

**Comment by jjsarton** [comment] 2022-04-30 14:17
I have installed 54.3 within a virtual environment, weasyprint worked.
