### ISSUE TITLE
Image handling ideas

### ISSUE THREAD

**Issue by survtur** [Kozea/WeasyPrint#1828] opened 2023-03-06 11:03 UTC
First of all, let me tell you that I am related to printing works, that is why I care a about images. My documents (books!) have a lot of images, they are usually huge, and I care about their quality. That is why...       

1. It would be good to embed images without additional compression. I may have them already prepared.

2. Local images, especially prepares ones, should not be cached in RAM and on disk cache. Even for those images, which are not ready yet, it may be better to read them from the source again and compress them just before writing to PDF.
I imagine two different sequences. And I think the second is better.
  
```
Current:
    1. readFromSource
    2. compress
    3. writeToDiskCache (slow)
    4. render
    5. readFromCache
    6. writeToPdf 
    
Alternative:
    1. readFromSource
    2. justCheckSize (for render only)
    3. render
    4. readFromSource
    5. resize if need for DPI
    6. compress
    7. writeToPdf
```

3. It would be nice to control jpeg compression. I mean to decide should it be compressed or not (see point 1) and set its jpeg quality.

4. It would be excellent to know the image rendered size and use it to resize images in order to get desired DPI.

5. I'd like to be able to modify the source image with custom function knowing its final printing size. For example unsharp mask filter needs this data for better results.

How could it be achieved
=================

I think some data should be added to some kind of `ImageData` object: final image dimensions (its size on-paper) and local source file. Maybe also cached file for downloaded images.

There should be a special function that will receive this `ImageData`, then read the source, rotate and compress, and return bytes and image parameters like pixel size and format.

**The main idea is to be able to supply custom function instead**

This is what would my custom function do: read original image from disk, rotate, reduce if DPI is too high, enhance with filters I want, then return all required data.

A good thing is that caching may be is a part of this function, so logic should be simple.

**Is it worth it? Or are there some complications I didn’t think of?**

P.S: I already made something like that for myself. But I want to have this __hook__ for custom function in main code of weasyprint, so I could easy update it without having to rewrite everything again.

**Comment by liZe** [comment] 2023-03-06 15:59
> It would be good to embed images without additional compression. I may have them already prepared.

Looks like a good idea.

> Local images, especially prepares ones, should not be cached in RAM and on disk cache. Even for those images, which are not ready yet, it may be better to read them from the source again and compress them just before writing to PDF.

For sure. We’ll work on this in the current PR.

> It would be nice to control jpeg compression. I mean to decide should it be compressed or not (see point 1) and set its jpeg quality.

A client just hired us to work on this, looks like it’s your lucky day!

> It would be excellent to know the image rendered size and use it to resize images in order to get desired DPI.

> I'd like to be able to modify the source image with custom function knowing its final printing size. For example unsharp mask filter needs this data for better results.

It may be complicated. Having the image size in the layout is not even sufficient, because we have to deal with zooms, scales and various other matrix transformations.

> **Is it worth it? Or are there some complications I didn’t think of?**

We’ll work on points 1, 2 and 3, I’m pretty confident it’s possible to solve them.

For 4 and 5, it may be more complex. If you want to play with these points, don’t hesitate to write and share some code!

**Comment by survtur** [comment] 2023-03-06 20:13
Seem like getting the image rendered size and use it to resize images in order to get desired DPI not so difficult. There is a `RasterImage.draw()` function. It gets dimensions as parameter.

I've added first line to function that function:
```print(f"Draw image w={px_to_mm(int(concrete_width))} h={int(px_to_mm(concrete_height))} {self.url=}")``` 
And it shows me real dimensions of image in final PDF.

> It may be complicated. Having the image size in the layout is not even sufficient, because we have to deal with zooms, scales and various other matrix transformations.

Could you provide an example of such transformations where these dimensions will be not enough? It seems that they are final.

**Comment by liZe** [comment] 2023-03-07 10:18
> Seem like getting the image rendered size to find its DPI could be not so difficult. There is a `RasterImage.draw()` function. It is called on write, it means that rendering is finished and images are placed. And this function gets dimensions as parameters!

This is possible, but this function is called when images are drawn. Currently, the strategy is to do everything that’s Pillow-related (find the size, find the format, convert format…) when the layout structure is built, not when it’s drawn. We need to do this early because we need at least the size for the layout. As we don’t keep the Pillow image anymore, it means that we’ll have to parse it twice.

By definition, we don’t have the rendered image before the layout.

> Could you provide an example of such transformations where these dimensions may be incorrect? It seems that they are final.

An example I have in mind is to apply `transform: scale(2)` on an image or on one of its parents. I don’t think that we get the right size in this case.

**Comment by survtur** [comment] 2023-03-23 15:05
I implemented all the things I need in my local copy and use it in "production". But the code is based on older branch of weasyprint and quite ugly, that is why  I can't even make a pull request for it.

The main idea is that I moved a lot into a class that you called LazyImage. It returns image information depending on its size on paper. So I can modify the image on the fly. For example I'll change its resolution and apply unsharp mask depending on printing size. My solution is not compatible with DiskCache you made in ram-save branch.

**Comment by survtur** [comment] 2023-03-23 15:17
One think I would like to have is to get the `Settings` object that will be available almost everywhere. It will reduce quantity of parameters to pass, and it will allow an easy way to use custom classes for something like `LazyImage` or for my `ImageCook` which prepares images according to its printing resolution.

**Comment by liZe** [comment] 2023-03-27 11:54
> One thing I would like to have is to get the `Settings` object that will be available almost everywhere.

I’ve tried many times to do something like that, but the code I got was a lot less convincing that what I had in mind, and each time I dropped the code. Now that we have more and more options, it may be worth trying again.

> The main idea is that I moved a lot into a class that you called LazyImage. It returns image information depending on its size on paper. So I can modify the image on the fly. For example I'll change its resolution and apply unsharp mask depending on printing size. My solution is not compatible with DiskCache you made in ram-save branch.

No problem. We can discuss this point when the `size` branch is merged.

**Comment by liZe** [comment] 2023-03-28 16:43
(1) has been done (for JPEG and PNG with no alpha channel), (2) and (4) will follow soon.

**Comment by liZe** [comment] 2023-03-29 19:24
> (1) has been done (for JPEG and PNG with no alpha channel), (2) and (4) will follow soon.

(2) has been done for JPEG images.

I’ve tried to implement (4), but the result wasn’t really satisfying for me. The first approach I’ve tried is to set a `dpi` attribute stored in the `RasteImage` instance. That’s the "easy" way, but I don’t like at all the logic: the `dpi` attribute should be set while drawing the image, not during the layout, just like `image_rendering`.

So, I’ve tried to set it during the layout. The problem is that none of the CLI features are given yet to the drawing functions (`image_rendering` is a CSS attribute, not a CLI parameter). And passing the attribute everywhere seems to be over-complicated.

Until we find something that’s both "simple" and "logical", I think that it’s better to wait before implementing a `--dpi` option.

**Comment by liZe** [comment] 2023-03-29 20:12
I’ve open an issue, #1854, to get a `--dpi` option in the future.

If everything’s OK for you, I think that we can close this issue.

**Closed** 2023-03-30 08:57 UTC
Labels: feature

**Comment by liZe** [comment] 2023-04-13 17:39
> One thing I would like to have is to get the `Settings` object that will be available almost everywhere

@survtur You’ll probably be interested in #1860!
