### ISSUE TITLE
SVG is not rendered complete with img-tag in PDF

### ISSUE THREAD

**Issue by doekman** [Kozea/WeasyPrint#514] opened 2017-10-02 07:50 UTC
I've got a HTML page in which I include an SVG-image with the IMG-tag (see [svg-test.zip](https://github.com/Kozea/WeasyPrint/files/1348168/svg-test.zip)). I create a PDF with the command `weasyprint test.html test.pdf` (no warnings in output).

The logo renders partly, only the image-mark (rounded square with a white dot) is rendered, not the text ("Archipunt"). The SVG is created with Sketch, and the text is converted to vectors (to get rid of the font-dependency).

I've opened `test.pdf` in macOS Reader, Adobe Acrobat Reader and Google Chrome (all on macOS Sierra 10.12.6) and all programs don't show the text.

However, when rendering to PNG, the text shows: `weasyprint test.html test.png`.

Also when rendering the SVG with Cairo to PDF, the text shows: `cairosvg -f pdf --width 480 -o logo.pdf logo.svg`.

I'm using WeasyPrint version 0.40 and cairosvg 2.0.3.

**Comment by liZe** [comment] 2017-10-02 08:38
It's a duplicate of #278 / #339 / #431 / #438… Short answer: it's a bug in cairo fixed upstream since April 2016, but no stable version has the patch. You can use the unstable 1.15.6 version for example.

**Closed by liZe** 2017-10-02 08:38 UTC

**Comment by doekman** [comment] 2017-10-02 10:28
OK, thanks! I only looked at open bug reports.
