### ISSUE TITLE
Japanese characters are not displayed in some PDF viewers

### ISSUE THREAD

**Issue by lazex** [Kozea/WeasyPrint#1844] opened 2023-03-18 14:20 UTC
I created a PDF containing Japanese characters using WeasyPrint.
Some viewers display Japanese characters, some viewers do not display Japanese characters.
Should I add need any options?

HTML:

```html
<!doctype html>
<meta charset="utf-8" />
<style>
	@font-face {
		font-family: 'NotoSansJP';
		src: url(./NotoSansJP-Regular.otf);
	}
	.content {
		font-family: NotoSansJP;
	}
</style>
<section class="content">
	<div>
		en: ABCDE
	</div>
	<div>
		ja: あいうえお
	</div>
</section>
```

`NotoSansJP-Regular.otf` font can be downloaded here.
https://fonts.google.com/noto/specimen/Noto+Sans+JP

Commands:

```
root@490c2fc60458:/mnt# weasyprint --info
System: Linux
Machine: x86_64
Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
Release: 5.10.102.1-microsoft-standard-WSL2

WeasyPrint version: 58.1
Python version: 3.10.6
Pydyf version: 0.5.0
Pango version: 15006

root@490c2fc60458:/mnt# weasyprint page.html page.pdf
```

Result:

In Edge Browser

![image](https://user-images.githubusercontent.com/6133978/226111359-8e26e71d-23f0-4473-a060-dacb3dd6ebd1.png)

In PDF.JS Viewer (https://mozilla.github.io/pdf.js/), Foxit PDF Reader (https://www.foxit.com/pdf-reader/)

![image](https://user-images.githubusercontent.com/6133978/226111365-48cd30bc-1afd-4176-b890-a2d20ec95ca7.png)

These viewers can normally display PDFs containing Japanese characters created by other methods (For example, wkhtmltopdf) .

**Comment by Khnsimeon29** [comment] 2023-03-18 22:24
Je comprend

**Comment by liZe** [comment] 2023-03-19 10:08
Hi!

Thanks for your bug report. This problem is a duplicate of #1593, the workaround for now is to use another font than the CID fonts proposed by Google Fonts.

**Closed** 2023-03-19 10:08 UTC
