### ISSUE TITLE
AssertionError When using overflow-wrap

### ISSUE THREAD

**Issue by chirinosky** [Kozea/WeasyPrint#206] opened 2014-07-02 13:00 UTC
Hello, I'm trying to break long lines that sometimes span multiple rows and am using `overflow-wrap: break-word` to do so.  However, it is creating the error below:

```
Exception Type:	AssertionError
Exception Value:	
Got u'name="KEY_USER_ID">7oItbkd8h2J2Aettn3WHNj5LJ8G9TM8quKiTi0u0m0WLBJ304oI' between two lines. Expected nothing or a preserved line break
```
It seems to be triggered by line 175 in weasyprint\layout\inlines.py.

Is the break-all supported, or just normal?

**Comment by liZe** [comment] 2015-04-28 17:24
I can't reproduce with your example. @chirinosky is this fixed for you with the master version of WeasyPrint?

**Comment by cvillemure** [comment] 2015-07-30 02:30
@liZe Here's a link to another [test case](http://jsfiddle.net/2Qw6S/1/).

On my side with WeasyPrint dating from 2013-10-01, I've got the error :
```AssertionError: Got 'and3\xa0\u200b' between two lines. Expected nothing or a preserved line break```

I could consider an upgrade if necessary, but it the master still have this bug I would wait.

Thanks

**Comment by SimonSapin** [comment] 2015-07-30 06:01
@cvillemure JSFiddle is not very friends with a UA that doesn’t support JavaScript, but after copying your test case to http://dabblet.com/gist/04d4782ffe7e2b0072fd I could not reproduce the exception. This gave a PDF that looks alright:

```
weasyprint http://result.dabblet.com/gist/04d4782ffe7e2b0072fd/d048b1222e8732da5b04d670a376fe5abe919932 /tmp/a.pdf
```

Is there a particular reason you’re using such an old version?

**Comment by liZe** [comment] 2015-08-14 12:15
@chirinosky @cvillemure no way to reproduce the bug. Could you try a recent version of WeasyPrint?

**Comment by cvillemure** [comment] 2015-08-15 01:54
@liZe Will try that as soon as I can!

**Comment by cvillemure** [comment] 2015-10-21 19:09
@liZe Just tried with release 0.24 and still got the error 
```
File "c:\Python27\venv\lib\site-packages\weasyprint\layout\inlines.py", line 744, in split_text_box
    'Expected nothing or a preserved line break' % (between,))
AssertionError: Got u'and3\xa0\u200b' between two lines. Expected nothing or a preserved line break
```

Using http://dabblet.com/gist/04d4782ffe7e2b0072fd with
- Windows 7
- Python 2.7.10 32bits
- cffi-1.3.0-cp27-none-win32.whl
- lxml-3.4.4-cp27-none-win32.whl
- pywin32-219.win32-py2.7.exe

**Comment by liZe** [comment] 2015-10-22 10:19
@cvillemure No problem here on linux 64bits with the same libs (except cffi-1.2.1). Do you have the latest Cairo and Pango versions?

**Comment by liZe** [comment] 2016-03-08 19:03
@cvillemure @chirinosky Can I close this bug?

**Comment by chirinosky** [comment] 2016-03-08 19:18
No issues from my side, but I haven't used the library in some time.




---- On Tue, 08 Mar 2016 14:03:15 -0500 Guillaume Ayoub &lt;notifications@github.com&gt;wrote ---- 




@cvillemure @chirinosky Can I close this bug?

**Comment by cvillemure** [comment] 2016-03-08 19:49
@liZe I've switched to wkhtmltopdf.  Much easier to use in our architecture and no bug with the line wraps.  So if you cannot reproduce you can close it

Farewell

**Closed** 2016-07-28 23:34 UTC
Labels: bug
