### ISSUE TITLE
segmentation fault during import 

### ISSUE THREAD

**Issue by sterlingbaldwin** [Kozea/WeasyPrint#1544] opened 2022-01-18 20:00 UTC
Hello, Im having some trouble getting up and running with weasyprint due to an annoying segfault during the import step. Im on a brand new M1 macbook air, running python 3.10.2, and after following the install instructions I get this:
```
$ python                                                                                                                                                   (pdf✱) 
Python 3.10.2 | packaged by conda-forge | (main, Jan 14 2022, 08:04:21) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import faulthandler
>>> faulthandler.enable()
>>> from weasyprint import HTML, CSS
Fatal Python error: Segmentation fault

Current thread 0x00000001011c4580 (most recent call first):
  File "/Users/sterling/miniforge3/envs/nabu-dev/lib/python3.10/site-packages/weasyprint/text/fonts.py", line 86 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/Users/sterling/miniforge3/envs/nabu-dev/lib/python3.10/site-packages/weasyprint/text/line_break.py", line 18 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/Users/sterling/miniforge3/envs/nabu-dev/lib/python3.10/site-packages/weasyprint/css/computed_values.py", line 17 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1078 in _handle_fromlist
  File "/Users/sterling/miniforge3/envs/nabu-dev/lib/python3.10/site-packages/weasyprint/css/__init__.py", line 27 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/Users/sterling/miniforge3/envs/nabu-dev/lib/python3.10/site-packages/weasyprint/__init__.py", line 325 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<stdin>", line 1 in <module>

Extension modules: _cffi_backend, _brotli (total: 2)
[1]    46793 segmentation fault  python
```

**Comment by liZe** [comment] 2022-01-18 20:31
Hello!

That’s a duplicate of https://github.com/Kozea/WeasyPrint/issues/1533, and the people able to help you are cffi’s developers in [this issue](https://foss.heptapod.net/pypy/cffi/-/issues/523).

**Closed by liZe** 2022-01-18 20:31 UTC
