### ISSUE TITLE
Alignment of footnotes spawning multiple rows

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1583] opened 2022-02-28 17:11 UTC
https://print-css.rocks/lesson/lesson-footnotes

All footnote texts should be left-aligned.
Please compare to the other renderings above.

<img width="966" alt="Bildschirmfoto 2022-02-28 um 18 09 10" src="https://user-images.githubusercontent.com/594239/156027142-25cf9ca7-530a-4d7f-8adb-7ac4c0ec683e.png">

**Comment by grewn0uille** [comment] 2022-02-28 17:16
Duplicate of #1582

**Closed by grewn0uille** 2022-02-28 17:16 UTC
