### ISSUE TITLE
Installing WeasyPrint on AWS is failing for me

### ISSUE THREAD

**Issue by Phrancko** [Kozea/WeasyPrint#711] opened 2018-10-18 18:27 UTC
[I posted this same question on StackOverflow before I found this place to post issues. The link to "Report a problem" on https://weasyprint.readthedocs.io/en/stable/install.html goes to a 404 error.]

The bottom line:
On AWS, after successfully installing dependencies, 'pip install weasyprint' fails with error message:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-gs8u357u/cairocffi/

Can anyone help me get past that?

The details:
I successfully executed the following instruction for installing on Fedora at https://weasyprint.readthedocs.io/en/latest/install.html:

sudo yum install redhat-rpm-config python-devel python-pip python-setuptools python-wheel python-cffi libffi-devel cairo pango gdk-pixbuf2

Result:

`Updated:
  cairo.x86_64 0:1.14.8-2.amzn2.0.2          pango.x86_64 0:1.40.4-1.amzn2.0.2 
  python-devel.x86_64 0:2.7.14-58.amzn2.0.4 

Dependency Updated:
  cairo-gobject.x86_64 0:1.14.8-2.amzn2.0.2 python.x86_64 0:2.7.14-58.amzn2.0.4
  python-libs.x86_64 0:2.7.14-58.amzn2.0.4 
`
While still in my virtual environment, I executed:

pip install WeasyPrint

`Collecting WeasyPrint
  Using cached https://files.pythonhosted.org/packages/a5/3c/a7021bea33ef7515901d77b11cb0d356171068055591e9d813962a0092d8/WeasyPrint-0.42.3-py3-none-any.whl
Collecting cairocffi>=0.5 (from WeasyPrint)
  Using cached https://files.pythonhosted.org/packages/62/be/ad4d422b6f38d99b09ad6d046ab725e8ccac5fefd9ca256ca35a80dbf3c6/cairocffi-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no previously-included files found matching 'setup.pyc'
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    Traceback (most recent call last):
      File "/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
`
[long traceback clipped]
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-gs8u357u/cairocffi/

**Comment by liZe** [comment] 2018-10-21 15:36
> [I posted this same question on StackOverflow before I found this place to post issues. The link to "Report a problem" on https://weasyprint.readthedocs.io/en/stable/install.html goes to a 404 error.]

Sorry, it's fixed in `master` and will be fixed online when a new stable version is released.

> [long traceback clipped]

Could you please provide the whole traceback? If it's too long, you can zip it and attach it to your comment.

**Comment by Tontyna** [comment] 2018-10-21 16:05
I recall getting similar errors when pip installing weasyprint (not reproducable). Workaround seemed to be installing the required packages separately and one by one.

**Comment by liZe** [comment] 2018-10-26 16:33
@Tontyna Yes, something like #632

@Phrancko Could you please provide your full stacktrace?

**Comment by Phrancko** [comment] 2018-10-26 18:30
Thank you for your response.

Here it is:

$ pip install -U django-weasyprint

Collecting django-weasyprint

  Using cached
https://files.pythonhosted.org/packages/f4/bc/07e80c8fd18cb9b0ae7d193f2e4e5d1b4c650b9cdf64eb6bdb3f06949112/django_weasyprint-0.5.4-py2.py3-none-any.whl

Requirement already satisfied, skipping upgrade: Django>=1.8 in
./myenv/lib/python3.7/site-packages (from django-weasyprint) (2.1)

Collecting WeasyPrint (from django-weasyprint)

  Using cached
https://files.pythonhosted.org/packages/a5/3c/a7021bea33ef7515901d77b11cb0d356171068055591e9d813962a0092d8/WeasyPrint-0.42.3-py3-none-any.whl

Requirement already satisfied, skipping upgrade: pytz in
./myenv/lib/python3.7/site-packages (from Django>=1.8->django-weasyprint)
(2018.5)

Collecting cssselect2>=0.1 (from WeasyPrint->django-weasyprint)

  Using cached
https://files.pythonhosted.org/packages/12/e2/91fcd4cd32545beec6e11628d64d3e20f11b5a95dd1ccf3216fd69f176b7/cssselect2-0.2.1-py2.py3-none-any.whl

Collecting CairoSVG>=1.0.20; python_version >= "3.0" (from
WeasyPrint->django-weasyprint)

  Using cached
https://files.pythonhosted.org/packages/5c/57/dadc80948bcb83ea9c0968ccfd5a1a25ace6be0884484526f70dad3c10b9/CairoSVG-2.2.1-py3-none-any.whl

Collecting cffi>=0.6 (from WeasyPrint->django-weasyprint)

  Using cached
https://files.pythonhosted.org/packages/51/7b/d1014289d0578c3522b2798b9cb87c65e5b36798bd3ae68a75fa1fe09e78/cffi-1.11.5-cp37-cp37m-manylinux1_x86_64.whl

Collecting html5lib>=0.999999999 (from WeasyPrint->django-weasyprint)

  Using cached
https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl

Collecting pdfrw>=0.4 (from WeasyPrint->django-weasyprint)

  Using cached
https://files.pythonhosted.org/packages/c0/84/af442c4458756bb0c0d2424102d1200616f3ff9b82c48aaa130e08549bf6/pdfrw-0.4-py2.py3-none-any.whl

Collecting Pyphen>=0.8 (from WeasyPrint->django-weasyprint)

  Using cached
https://files.pythonhosted.org/packages/15/82/08a3629dce8d1f3d91db843bb36d4d7db6b6269d5067259613a0d5c8a9db/Pyphen-0.9.5-py2.py3-none-any.whl

Collecting cairocffi>=0.5 (from WeasyPrint->django-weasyprint)

  Using cached
https://files.pythonhosted.org/packages/62/be/ad4d422b6f38d99b09ad6d046ab725e8ccac5fefd9ca256ca35a80dbf3c6/cairocffi-0.9.0.tar.gz

    Complete output from command python setup.py egg_info:

    warning: no previously-included files found matching 'setup.pyc'

    warning: no previously-included files matching 'yacctab.*' found under
directory 'tests'

    warning: no previously-included files matching 'lextab.*' found under
directory 'tests'

    warning: no previously-included files matching 'yacctab.*' found under
directory 'examples'

    warning: no previously-included files matching 'lextab.*' found under
directory 'examples'

    zip_safe flag not set; analyzing archive contents...

    Traceback (most recent call last):

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 154, in save_modules

        yield saved

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 195, in setup_context

        yield

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 250, in run_setup

        _execfile(setup_script, ns)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 45, in _execfile

        exec(code, globals, locals)

      File "/tmp/easy_install-kqa55979/pycparser-2.19/setup.py", line 65,
in <module>

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/__init__.py",
line 129, in setup

        return distutils.core.setup(**attrs)

      File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup

        dist.run_commands()

      File "/usr/lib64/python3.7/distutils/dist.py", line 966, in
run_commands

        self.run_command(cmd)

      File "/usr/lib64/python3.7/distutils/dist.py", line 985, in
run_command

        cmd_obj.run()

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/bdist_egg.py",
line 218, in run

        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/bdist_egg.py",
line 269, in zip_safe

        return analyze_egg(self.bdist_dir, self.stubs)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/bdist_egg.py",
line 379, in analyze_egg

        safe = scan_module(egg_dir, base, name, stubs) and safe

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/bdist_egg.py",
line 418, in scan_module

        code = marshal.load(f)

    ValueError: bad marshal data (unknown type code)



    During handling of the above exception, another exception occurred:



    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-install-b_s4c85u/cairocffi/setup.py", line 51, in
<module>

        'test': ['pytest-runner', 'pytest-cov'],

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/__init__.py",
line 128, in setup

        _install_setup_requires(attrs)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/__init__.py",
line 123, in _install_setup_requires

        dist.fetch_build_eggs(dist.setup_requires)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/dist.py",
line 461, in fetch_build_eggs

        replace_conflicting=True,

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/pkg_resources/__init__.py",
line 866, in resolve

        replace_conflicting=replace_conflicting

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/pkg_resources/__init__.py",
line 1146, in best_match

        return self.obtain(req, installer)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/pkg_resources/__init__.py",
line 1158, in obtain

        return installer(requirement)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/dist.py",
line 528, in fetch_build_egg

        return cmd.easy_install(req)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/easy_install.py",
line 672, in easy_install

        return self.install_item(spec, dist.location, tmpdir, deps)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/easy_install.py",
line 698, in install_item

        dists = self.install_eggs(spec, download, tmpdir)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/easy_install.py",
line 881, in install_eggs

        return self.build_and_install(setup_script, setup_base)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/easy_install.py",
line 1149, in build_and_install

        self.run_setup(setup_script, setup_base, args)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/easy_install.py",
line 1135, in run_setup

        run_setup(setup_script, args)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 253, in run_setup

        raise

      File "/usr/lib64/python3.7/contextlib.py", line 130, in __exit__

        self.gen.throw(type, value, traceback)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 195, in setup_context

        yield

      File "/usr/lib64/python3.7/contextlib.py", line 130, in __exit__

        self.gen.throw(type, value, traceback)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 166, in save_modules

        saved_exc.resume()

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 141, in resume

        six.reraise(type, exc, self._tb)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/pkg_resources/_vendor/six.py",
line 685, in reraise

        raise value.with_traceback(tb)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 154, in save_modules

        yield saved

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 195, in setup_context

        yield

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 250, in run_setup

        _execfile(setup_script, ns)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/sandbox.py",
line 45, in _execfile

        exec(code, globals, locals)

      File "/tmp/easy_install-kqa55979/pycparser-2.19/setup.py", line 65,
in <module>

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/__init__.py",
line 129, in setup

        return distutils.core.setup(**attrs)

      File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup

        dist.run_commands()

      File "/usr/lib64/python3.7/distutils/dist.py", line 966, in
run_commands

        self.run_command(cmd)

      File "/usr/lib64/python3.7/distutils/dist.py", line 985, in
run_command

        cmd_obj.run()

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/bdist_egg.py",
line 218, in run

        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/bdist_egg.py",
line 269, in zip_safe

        return analyze_egg(self.bdist_dir, self.stubs)

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/bdist_egg.py",
line 379, in analyze_egg

        safe = scan_module(egg_dir, base, name, stubs) and safe

      File
"/home/ec2-user/phrancko-project/myenv/lib64/python3.7/site-packages/setuptools/command/bdist_egg.py",
line 418, in scan_module

        code = marshal.load(f)

    ValueError: bad marshal data (unknown type code)

    ------------------------file---------------------


build/bdist.linux-x86_64/egg/pycparser/__pycache__/__init__.cpython-37.pyc



    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-install-b_s4c85u/cairocffi/



Frank Jernigan

**Comment by Tontyna** [comment] 2018-10-26 19:40
The traceback looks familiar to me, I suspect it's an issue related to the `_cffi_backend` binary.

**Comment by Phrancko** [comment] 2018-10-28 02:33
I suspect it has something to do with this:

ValueError: bad marshal data (unknown type code)


I can't find out what that means.

Frank

**Comment by Phrancko** [comment] 2018-11-02 22:45
Sorry for the delayed response. That worked!

Thank you so much for your help.

Frank Jernigan

**Closed** 2018-11-03 11:44 UTC

**Comment by kluz9** [comment] 2019-03-19 21:09
I am having a similar issue. Unable to install weasyprint on AWS. Here is my log:

Installing collected packages: cairocffi
  Exception:
  Traceback (most recent call last):
    File "/opt/python/run/venv/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
      status = self.run(options, args)
    File "/opt/python/run/venv/local/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
      prefix=options.prefix_path,
    File "/opt/python/run/venv/local/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
      **kwargs
    File "/opt/python/run/venv/local/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
      self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
    File "/opt/python/run/venv/local/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
      isolated=self.isolated,
    File "/opt/python/run/venv/local/lib/python3.6/site-packages/pip/wheel.py", line 347, in move_wheel_files
      assert info_dir, "%s .dist-info directory not found" % req
  AssertionError: cairocffi==1.0.2 .dist-info directory not found
  You are using pip version 9.0.1, however version 19.0.3 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  2019-03-19 21:03:05,814 ERROR    Error installing dependencies: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 2
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 22, in main
      install_dependencies()
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 18, in install_dependencies
      check_call('%s install -r %s' % (os.path.join(APP_VIRTUAL_ENV, 'bin', 'pip'), requirements_file), shell=True)
    File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  CalledProcessError: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 2 (Executor::NonZeroExitStatus)

**Comment by Tontyna** [comment] 2019-03-19 22:11
Eye-catcher:

> You are using pip version 9.0.1, however version 19.0.3 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

And 

> File "/usr/lib64/**python2.7**/subprocess.py"

Upps! Python 2.7!?

**Comment by kluz9** [comment] 2019-03-20 00:13
Thanks @Tontyna 
I upgraded pip to latest version. Now i directly try to login to my aws server and install cairocffi but I  get this error:

(venv) [root@ip-172-31-21-74 ec2-user]# pip install cairocffi
Collecting cairocffi
Installing collected packages: cairocffi
Exception:
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 913, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 445, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/wheel.py", line 428, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: cairocffi .dist-info directory not found

Any idea why .dist-info directory not found ?

**Comment by Tontyna** [comment] 2019-03-20 07:44
> I upgraded pip to latest version

Blind guess: What about upgrading `setuptools`, too?

**Comment by kluz9** [comment] 2019-03-20 17:51
upgraded setuptools too. But still the same error 

AssertionError: cairocffi .dist-info directory not found

Any other ides?

**Comment by Tontyna** [comment] 2019-03-20 19:41
I'm confused because AFAIK cairocffi isnt distributed via wheel (`.dist-info` directory) but as an egg with `.egg-info` directory... hmm...

If you hadnt already opened Kozea/cairocffi#125 I'd advice to do that.
