### ISSUE TITLE
Segfault on WeasyPrint 52.4 in get_first_line

### ISSUE THREAD

**Issue by Badg** [Kozea/WeasyPrint#1402] opened 2021-07-22 10:39 UTC
Hi!

We're seeing an intermittent segfault when trying to write a PDF from html. I haven't been able to repro it locally; I've only seen it on live code in the cloud. The code in question calls Weasyprint like this:

```python
from weasyprint import CSS, HTML

...

    html = HTML(
        string=render_html(product, template_name, payload),
        base_url=STATIC_DIR,
    )

    css = CSS(filename=css_filename)
    pdf = html.write_pdf(stylesheets=[css])
```

Running python with ``faulthandler.enable()`` traces the problem to [this line](https://github.com/Kozea/WeasyPrint/blob/52.x/weasyprint/text.py#L736):

```
Fatal Python error: Segmentation fault

(other threads omitted)

Current thread 0x00007f6af0959b48 (most recent call first):
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/text.py", line 736 in get_first_line
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/text.py", line 1271 in show_first_line
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/draw.py", line 1059 in draw_text
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/draw.py", line 1031 in draw_inline_level
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/draw.py", line 269 in draw_stacking_context
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/draw.py", line 279 in draw_stacking_context
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/draw.py", line 275 in draw_stacking_context
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/draw.py", line 161 in draw_page
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/document.py", line 282 in paint
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/document.py", line 654 in write_pdf
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/__init__.py", line 222 in write_pdf
(continues from here within application code)
```

Additional info:

- alpine linux, specifically, dockerized using: ``FROM python:3.9-alpine``
- pango version ``pango-dev-1.48.5-r0``, installed via apk
- we occasionally see errors from pango in our logs, but as far as I can tell they're isolated from this. And by that I mean, we'll see a log for the pango error, and then more than an hour later, the segfault happens. And we see the segfault both with and without the pango error showing up in the logs.

Do you have any guidance on this? I took a quick look at the WeasyPrint source, but python CFFI is beyond my powers of speculation and/or debugging.

**Comment by liZe** [comment] 2021-07-25 16:40
Hello!

Could you please try to reproduce this error with version 52.5? Some bugs have been fixed in this version, and they may be related (even if it’s hard to know with segfaults…).

**Comment by Badg** [comment] 2021-08-02 11:29
Yep, we're still seeing this in 52.5.

**Comment by liZe** [comment] 2021-08-17 17:18
Hmmmm…

It’s hard to know what’s going on, and I don’t know a simple way to find the source of the problem. Using gdb is the only solution that comes in my mind, and that’s probably a bad solution if we don’t have a reliable example.

Having a segmentation fault means that there’s a problem in Pango, or a problem in the way we use Pango. That’s strange, because I’ve been using WeasyPrint for a very long time and I’ve never seen this problem :/.

Could it be possible for you to try another distribution? Alpine uses a different building stack than other distributions, and it may explain why a segfault happens for you but not for many other users. Maybe it’s totally unrelated, but at least we could discard this possibility.

Another question: do you use WeasyPrint in a multiprocess or multithread context?

**Comment by Badg** [comment] 2021-08-23 14:59
I have some hopefully-helpful updates! First off, we are indeed using WeasyPrint in a threaded context, ie, behind a wsgi server. But much more importantly, I was able to reliably reproduce the crash locally, using a script that simply hammers away identical canned requests at the endpoint we were seeing the crash in until the crash happens. Sometimes it takes a few seconds, sometimes it takes several minutes, but it very reliably reproduces the crash. And that allowed me to do a little testing. I think your hunch re: alpine was right on the money, because switching the docker image to debian solved the problem for us. That's not much help to anyone who's stuck on alpine, but for us, it's a perfectly valid solution. I'll leave this issue open in case you want to investigate further, but as far as I'm concerned you're welcome to close it!

Despite having a local repro, I was unfortunately not able to get a traceback using gdb. I tried valiantly, but I simply couldn't get gdb to run within alpine + poetry + debug symbols. Maybe it's just because of my relative inexperience with gdb, but at a certain point I just didn't have any more time I could justify devoting to it. Particularly because we're perfectly happy to just change our distro to debian and be done with it :)

Also, I think the pango errors we see might actually be related. Every single local crash I've been able to repro has had a pango failure first, and then a while later, the segfault happens. I think in our production logs it just *seems* like it's not always related, because our production traffic is low enough that it gets drowned out by the rest of the logs. For example, here's one I got locally just now:

```
(process:83): Pango-CRITICAL **: 14:42:08.580: pango_fc_patterns_unref: assertion 'pats->ref_count > 0' failed

(... 301 identical requests later...)

Fatal Python error: Segmentation fault

Thread 0x00007fb208c1ab38 (most recent call first):
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/text.py", line 643 in first_line_metrics
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/text.py", line 1033 in split_first_line
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 298 in inline_line_widths
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 201 in inline_max_content_width
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 80 in max_content_width
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 99 in <listcomp>
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 98 in _block_content_width
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 175 in block_max_content_width
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 241 in table_cell_max_content_width
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 73 in max_content_width
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/preferred.py", line 459 in table_and_columns_preferred_widths
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/tables.py", line 631 in auto_table_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/tables.py", line 738 in table_wrapper_width
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 121 in block_box_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 72 in block_level_layout_switch
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 58 in block_level_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 517 in block_container_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 126 in block_box_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 72 in block_level_layout_switch
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 58 in block_level_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 517 in block_container_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 126 in block_box_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 72 in block_level_layout_switch
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 58 in block_level_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 517 in block_container_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 126 in block_box_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 72 in block_level_layout_switch
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 58 in block_level_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 517 in block_container_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 126 in block_box_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 72 in block_level_layout_switch
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/blocks.py", line 58 in block_level_layout
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/pages.py", line 548 in make_page
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/pages.py", line 738 in remake_page
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/pages.py", line 801 in make_all_pages
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/layout/__init__.py", line 123 in layout_document
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/document.py", line 406 in <listcomp>
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/document.py", line 406 in _render
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/__init__.py", line 172 in render
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/__init__.py", line 222 in write_pdf
  (continues from within application code)

Thread 0x00007fb208e2fb38 (most recent call first):
  File "/opt/app/.venv/lib/python3.9/site-packages/cairocffi/context.py", line 107 in _check_status
  File "/opt/app/.venv/lib/python3.9/site-packages/cairocffi/context.py", line 1410 in fill
  File "/opt/app/.venv/lib/python3.9/site-packages/weasyprint/draw.py", line 839 in draw_rect_border
```

**Comment by liZe** [comment] 2021-08-23 16:52
Thanks **a lot** for this information.

> alpine was right on the money, because switching the docker image to debian solved the problem for us.

Then we can assume that this bug is caused by the way Alpine compiles Pango. Alpine using musl libc may discover problems that were not visible when using glibc. Here, I suppose that there’s a race condition that unreferences Fontconfig patterns twice.

We could report this issue. But without a sample in C showing the problem, I suppose that it’s almost impossible to debug.

> Maybe it's just because of my relative inexperience with gdb, but at a certain point I just didn't have any more time I could justify devoting to it. Particularly because we're perfectly happy to just change our distro to debian and be done with it :)

gdb is a kind of nightmare for me too :wink:.

I close the issue, as there’s nothing more we can easily do. If anyone meets the same problem and has more time and experience to debug it, feel free to reopen, I’m sure that the Pango team would be happy to fix the bug.

**Closed by liZe** 2021-08-23 16:52 UTC
Labels: crash
