### ISSUE TITLE
WeasyPrint crash on OSX

### ISSUE THREAD

**Issue by benjolitz** [Kozea/WeasyPrint#482] opened 2017-06-30 23:55 UTC
The issue:
```
Fontconfig warning: line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
!!! uWSGI process 55934 got Segmentation Fault !!!
*** backtrace of 55934 ***
0   uwsgi                               0x000000010b2a2b1c uwsgi_backtrace + 44
1   uwsgi                               0x000000010b2a3053 uwsgi_segfault + 51
2   libsystem_platform.dylib            0x00007fff94b23b3a _sigtramp + 26
3   Python                              0x000000010b468f26 vgetargs1 + 1267
4   CoreFoundation                      0x00007fff7f15912b ____initDayChangedNotification_block_invoke + 187
5   libdispatch.dylib                   0x00007fff948de8fc _dispatch_client_callout + 8
6   libdispatch.dylib                   0x00007fff948de8b9 dispatch_once_f + 38
7   CoreFoundation                      0x00007fff7f157a29 __CFNotificationCenterGetLocalCenter_block_invoke + 201
8   libdispatch.dylib                   0x00007fff948de8fc _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00007fff948de8b9 dispatch_once_f + 38
10  CoreFoundation                      0x00007fff7f157949 CFNotificationCenterGetLocalCenter + 41
11  CoreText                            0x00007fff8074950c _Z24_CTFontCollectionCreatedPK18__CTFontCollection + 59
12  CoreText                            0x00007fff80759545 CTFontCollectionCreateFromAvailableFonts + 210
13  libpangocairo-1.0.dylib             0x00000001172d641b pango_core_text_font_map_init + 138
14  libgobject-2.0.dylib                0x000000011715cb10 g_type_create_instance + 577
15  libgobject-2.0.dylib                0x000000011714cc3d g_object_new_internal + 57
16  libgobject-2.0.dylib                0x000000011714c58c g_object_newv + 157
17  libgobject-2.0.dylib                0x000000011714c4b0 g_object_new + 187
18  libpangocairo-1.0.dylib             0x00000001172d31d7 pango_cairo_font_map_get_default + 41
19  libpangocairo-1.0.dylib             0x00000001172d1bdb pango_cairo_create_context + 20
20  libpangocairo-1.0.dylib             0x00000001172d1c28 pango_cairo_create_layout + 17
21  libffi.dylib                        0x00007fff9396bf1c ffi_call_unix64 + 76
22  ???                                 0x0000000117ca2e48 0x0 + 4694093384
*** end of backtrace ***
```

Packages:
```
(cpython27) benjolitz-laptop:~/software/input_order_ui [staging]$ pip freeze | grep -i 'cffi.*\|weasy.*\|lxml.*\|html5.*\|tinycss.*\|css.*\|Pyphen.*'
cairocffi==0.8.0
cffi==1.10.0
cssselect==1.0.1
html5lib==1.0b10
lxml==3.8.0
Pyphen==0.9.4
tinycss==0.3
tinycss2==0.5
WeasyPrint==0.39
```
C libraries:
```
(cpython27) benjolitz-laptop:~/software/input_order_ui [staging]$ brew list --versions | grep -i 'cairo.*\|pango.*'
cairo 1.14.10 1.14.6_1 1.14.8
pango 1.40.1 1.40.3 1.40.5 1.40.6
```

It's recently quit working for me on my development box, but I do not recall making any changes to cairo/pango.

I matched my library versions with a coworker who does have a working build. Didn't make any difference. I reset my Font Book to the defaults. No dice.

Looks like a null pointer somewhere.

**Comment by liZe** [comment] 2017-07-01 03:57
Thanks a lot for this information. It's probably a duplicate of the old #167.

**Closed by liZe** 2017-07-01 03:57 UTC
Labels: bug, crash
