### ISSUE TITLE
Failed import with werkzeug

### ISSUE THREAD

**Issue by pothos** [Kozea/WeasyPrint#436] opened 2017-02-27 23:48 UTC
So both are called html and somehow the wrong is chosen…

```
$ sudo apt install python3-cairocffi python3-cairosvg python3-tinycss  # and maybe others
$ python3.5 -m pip install --no-deps pyphen
$ python3.5 -m pip install --no-deps WeasyPrint
  [...]
$ python3.5 -m weasyprint.navigator
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.5/site-packages/weasyprint/navigator.py", line 171, in <module>
    run()
  File "/home/kai/.local/lib/python3.5/site-packages/weasyprint/navigator.py", line 156, in run
    from werkzeug.serving import run_simple
  File "/usr/lib/python3/dist-packages/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/usr/lib/python3/dist-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 36, in <module>
    from werkzeug.utils import cached_property, environ_property, \
  File "/usr/lib/python3/dist-packages/werkzeug/utils.py", line 18, in <module>
    from html.entities import name2codepoint
  File "/home/kai/.local/lib/python3.5/site-packages/weasyprint/html.py", line 24, in <module>
    from .css import get_child_text
SystemError: Parent module '' not loaded, cannot perform relative import


```

**Comment by pothos** [comment] 2017-02-27 23:55
But this here works:
```
from weasyprint import HTML
HTML(in).write_pdf(out)

```

**Comment by liZe** [comment] 2017-02-28 02:04
Thanks for taking the time to report this issue.

It's a duplicate of #133.

**Closed by liZe** 2017-02-28 02:04 UTC
