### ISSUE TITLE
there is no img when convert html to pdf

### ISSUE THREAD

**Issue by zhizunbao84** [Kozea/WeasyPrint#994] opened 2019-11-18 07:21 UTC
in the html file there are some img:
`<p style="text-align: center;"><img class="rich_pages " data-ratio="0.5625" data-s="300,640" data-src="https://s1.51cto.com/images/20190714/1563098235772223.png?x-oss-process=image/watermark,size_16,text_QDUxQ1RP5Y2a5a6i,color_FFFFFF,t_100,g_se,x_10,y_10,shadow_90,type_ZmFuZ3poZW5naGVpdGk=" data-type="jpeg" data-w="1280" style="width: 677px !important; height: auto !important; visibility: visible !important;" _width="677px" src="https://s1.51cto.com/images/20190714/1563098235772223.png?x-oss-process=image/watermark,size_16,text_QDUxQ1RP5Y2a5a6i,color_FFFFFF,t_100,g_se,x_10,y_10,shadow_90,type_ZmFuZ3poZW5naGVpdGk=" crossorigin="anonymous" data-fail="0"></p>`

but i get no img when convert html to pdf.

**Comment by zhizunbao84** [comment] 2019-11-18 07:26
[weasyprint.log](https://github.com/Kozea/WeasyPrint/files/3857267/weasyprint.log)

**Comment by zhizunbao84** [comment] 2019-11-18 07:35
the page seems lazy load

**Comment by Tontyna** [comment] 2019-11-18 09:20
When I weasyprint your example paragraph my PDF contains the image as expected.

In the given weasyprint.log there is nothing that indicates an image-not-found-problem.

So maybe the images you are missing are hit by a css rule that hides them?

@zhizunbao84  Could you please provide an HTML+CSS example that fails to show images?

**Comment by zhizunbao84** [comment] 2019-11-18 09:41
from the source code of the html page, the img is actually like this:
` <img class="" data-copyright="0" data-ratio="0.8169934640522876" data-s="300,640" data-src="https://s1.51cto.com/images/20190714/1563098235772223.png?x-oss-process=image/watermark,size_16,text_QDUxQ1RP5Y2a5a6i,color_FFFFFF,t_100,g_se,x_10,y_10,shadow_90,type_ZmFuZ3poZW5naGVpdGk=" data-type="jpeg" data-w="1224" style=""/>`

the img file will be lazy loaded by javascript

**Comment by zhizunbao84** [comment] 2019-11-18 10:06
from the source code of the html page, the img is actually like this:
<img class="" data-copyright="0" data-ratio="0.8169934640522876" data-s="300,640" data-src="https://s1.51cto.com/images/20190714/1563098235772223.png?x-oss-process=image/watermark,size_16,text_QDUxQ1RP5Y2a5a6i,color_FFFFFF,t_100,g_se,x_10,y_10,shadow_90,type_ZmFuZ3poZW5naGVpdGk=" data-type="jpeg" data-w="1224" style=""/>

the scr of the img will be changed by javascript

**Comment by zhizunbao84** [comment] 2019-11-18 10:07
from the source code of the html page, the img is actually like this:
`<img class="" data-copyright="0" data-ratio="0.8169934640522876" data-s="300,640" data-src="https://s1.51cto.com/images/20190714/1563098235772223.png?x-oss-process=image/watermark,size_16,text_QDUxQ1RP5Y2a5a6i,color_FFFFFF,t_100,g_se,x_10,y_10,shadow_90,type_ZmFuZ3poZW5naGVpdGk=" data-type="jpeg" data-w="1224" style=""/>`

the src of the img file will be changed by javascript

**Comment by Tontyna** [comment] 2019-11-18 11:10
> the src of the img file will be changed by javascript

WeasyPrint doesn't support JavaScript, cf #817

**Comment by liZe** [comment] 2019-11-25 16:59
> WeasyPrint doesn't support JavaScript, cf #817

Yes, it's a disguised duplicate of #817.

**Closed by liZe** 2019-11-25 16:59 UTC
