### ISSUE TITLE
Getting PDF error 135 when opening with Adobe. WeasyPrint 53.2

### ISSUE THREAD

**Issue by afedosenko** [Kozea/WeasyPrint#1437] opened 2021-09-03 09:46 UTC
Python code is:

```
from weasyprint import HTML
HTML('http://weasyprint.org/').write_pdf('weasyprint-website.pdf')
```

Adobe message when I open the file: "There was an error processing a page. There was a problem reading this document (135)."

Libraries:
```
brotli==1.0.9
    # via fonttools
cffi==1.14.6
    # via weasyprint
cssselect2==0.4.1
    # via weasyprint
fonttools[woff]==4.26.2
    # via weasyprint
html5lib==1.1
    # via weasyprint
pillow==8.3.1
    # via weasyprint
pycparser==2.20
    # via cffi
pydyf==0.1.1
    # via weasyprint
pyphen==0.11.0
    # via weasyprint
six==1.16.0
    # via html5lib
tinycss2==1.1.0
    # via
    #   cssselect2
    #   weasyprint
weasyprint==53.2
    # via -r requirements.in
webencodings==0.5.1
    # via
    #   cssselect2
    #   html5lib
    #   tinycss2
zopfli==0.1.8
```

PDF file:
[weasyprint-website.pdf.zip](https://github.com/Kozea/WeasyPrint/files/7104969/weasyprint-website.pdf.zip)

**Comment by grewn0uille** [comment] 2021-09-03 15:40
Hello!
Could you please try to generate the PDF with the master branch or with WeasyPrint 53.0?

**Comment by afedosenko** [comment] 2021-09-03 19:20
WeasyPrint 53.0 - all good, no 135 error

I can't install the package from the master branch. While executing the command `pip install -e git+https://github.com/Kozea/weasyprint@5816d77b1147320fc86a48331f80bc9b698a3fde#egg=weasyprint`, I get the following error:
```
  Running setup.py develop for weasyprint
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/opt/project/src/weasyprint/setup.py'"'"'; __file__='"'"'/opt/project/src/weasyprint/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /opt/project/src/weasyprint/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

```

**Comment by afedosenko** [comment] 2021-09-03 19:52
I can install the master branch if I do:
`pip install https://github.com/Kozea/weasyprint/archive/master.zip`
or
`pip install git+https://github.com/Kozea/weasyprint.git@master`

So, all good with the master branch, no 135 error

**Comment by grewn0uille** [comment] 2021-09-03 21:33
Thanks for testing :)
So we know now it’s a duplicate of #1431.
This error has been fixed in `53.x` and `master`. We’ll do a release soon!

**Closed by grewn0uille** 2021-09-03 21:33 UTC
