### ISSUE TITLE
legend text missing in matplotlib svg graphs given as data URI

### ISSUE THREAD

**Issue by jxrossel** [Kozea/WeasyPrint#431] opened 2017-02-14 06:54 UTC
Hi,

When I try to convert the given HTML, I get the given pdf, with legend text missing (Python 3.4, Weasyprint 0.34, Windows 10). SVG conversion with cairosvg works fine. Any idea ?

[test.pdf](https://github.com/Kozea/WeasyPrint/files/773331/test.pdf)
[test-html.txt](https://github.com/Kozea/WeasyPrint/files/773334/test-html.txt)

**Comment by liZe** [comment] 2017-02-14 07:46
> Any idea ?

Yes! It's a duplicate of #278 and #339, it's a bug in Cairo that you can fix by installing Cairo 1.15.4 (it's an unstable version).

**Closed by liZe** 2017-02-14 07:46 UTC

**Comment by jxrossel** [comment] 2017-02-14 08:39
Ok, thanks for the quick answer ! I did a search and these issues didn't come up. Sorry for the trouble.

**Comment by liZe** [comment] 2017-02-14 13:48
> Sorry for the trouble.

No problem, you're welcome!
