### ISSUE TITLE
AttributeError: 'list' object has no attribute 'anchors'

### ISSUE THREAD

**Issue by annashen** [Kozea/WeasyPrint#743] opened 2018-11-27 07:05 UTC
I am trying to convert over 600 local html files into the same PDF using weasyprint. With the reference of this ticket (https://github.com/Kozea/WeasyPrint/issues/212), I composed my code as the following: 

=====================the code====================
//here I collected all the html files and combined them into a list of Document objects

all_pages = [[p for p in doc.pages] for doc in documents]
documents[0].copy(all_pages).write_pdf('combined.pdf')

====================the track trace========================

----------------------------------When executed:--------------------------------------
"Process finished with exit code -1073741819 (0xC0000005)"

----------------------------------When debugged:-------------------------------------

  File "C:/Users/Anna/PycharmProjectsLeetCode/MultipleHTML2PDF.py", line 17, in <module>
    documents[0].copy(all_pages).write_pdf('combined.pdf')
  File "C:\Users\Anna\AppData\Local\Programs\Python\Python37\lib\site-packages\weasyprint\document.py", line 563, in write_pdf
    paged_links_and_anchors = list(self.resolve_links())
  File "C:\Users\Anna\AppData\Local\Programs\Python\Python37\lib\site-packages\weasyprint\document.py", line 436, in resolve_links
    for anchor_name, (point_x, point_y) in page.anchors.items():
AttributeError: 'list' object has no attribute 'anchors'

Process finished with exit code -1

======================the end of the track trace======================

According to API (https://weasyprint.readthedocs.io/en/latest/api.html#weasyprint.document.Document), resolve_links will remove links in the page when anchor is missing (with warnings). Am I understanding it correctly? If yes, why that "resolve_links" method yells for attribute 'anchors'? 

With all these local htm files, I do not care about the links inside, all I try to collect are the text contents. 

Thank you for your input and help!

**Comment by Tontyna** [comment] 2018-11-27 08:43
try it with only one pair of brackets:

```Python
all_pages = [p for p in doc.pages for doc in documents]
```

**Comment by annashen** [comment] 2018-11-27 21:12
With the following code:
=================code without double brackets==============
all_pages = [p for p in doc.pages for doc in documents]
documents[0].copy(all_pages).write_pdf('combined.pdf')
=================track trace==========================
-----------------------------when run---------------------------------
"Process finished with exit code -1073741819 (0xC0000005)"
-----------------------------with debugger---------------------------------------
__exception__={tuple}<class 'tuple'>: (<class 'NameError'>, NameError("name 'doc' is not defined"), None)
================end of trace track======================

my pycharm does not like this single bracketed loop, it simply throws out exception for the first "doc" occurrence in "doc.pages".

**Comment by Tontyna** [comment] 2018-11-27 22:35
I confess: I didn't test it, copied the snippet 1:1 from the docs, believing the code was written by Python experts -- me myself will never grasp those Python shortcuts...

And indeed: It doesn't work for me, either.

This one finally worked for me:

```Python
all_pages = [p for doc in documents for p in doc.pages]
```

Should be the shortcut for:

```Python
all_pages = []
for doc in documents:
    for p in doc.pages:
        all_pages.append(p)
```

In any case you need a list of pages, the double brackets generate a list of lists of pages.

**Comment by annashen** [comment] 2018-11-28 00:50
Pycharm takes doubly bracketed nested for loop perfectly fine, in other words, 
"all_pages=[[p for p in doc.pages] for doc in documents]"
passed both execution and debugging, without any warnings or exceptions. Why are we talking back and forth about this line? 

As I stated at my first comment, the issue was triggered/caused by a method called "resolve_links" while it looks for attribute "anchors" and my code does not care about links between html contents thus did not provide any parameters related to "anchors".

**Comment by annashen** [comment] 2018-11-28 00:56
API (https://weasyprint.readthedocs.io/en/latest/api.html#weasyprint.document.Document) says, 
------------------------------------------------------------------
resolve_links()
   Resolve internal hyperlinks.
   Links to a missing anchor are removed with a warning.
--------------------------------------------------------------------------

I am assuming even I simply ignore the links between my target html files thus did not provide any code in my script to handle them, weasyprint API should still process the html contents without exceptions. 

However, the execution proves otherwise.

**Comment by annashen** [comment] 2018-11-30 00:08
Now I got what you were trying to say. 

In fact, the regular two staged for loop:
`all_pages = []
for doc in documents:
    for p in doc.pages:
        all_pages.append(p)`
 was my first version of adjustment when I came across with the exception from singly bracketed nested loop. The execution of that block of code gave me the same exit code:

`Process finished with exit code -1073741819 (0xC0000005)`

That was why I believed the exception came from the "write_pdf()", since whether it was written in singly or doubly bracketed or in regularly rendered loop, this piece of code threw out the same exception and exited with the same type of error code. 

And the above all happened before I posted/opened this thread...

last night I tried to debug with a check/break point at line "all_pages.append(p)", stepped over one by one, the program exited with error code -1 and a targeted pdf file was generated surprisingly. It seems the block of code only works when there is certain pause during execution. So I suspect if it is because API timed out too quickly for my local files...

**Comment by Tontyna** [comment] 2018-11-30 11:13
You mean, your pdf is generated successfully only when you step-and-break in the loop where `all_pages` are collected?

How many documents / pages do you try to concat?

**Comment by Tontyna** [comment] 2018-11-30 23:37
Can you turn on logging and post the output?

```Python
from weasyprint.logger import LOGGER
LOGGER.setLevel(logging.INFO)
```

**Comment by annashen** [comment] 2018-12-01 02:46
`import sys
import logging

from weasyprint import HTML
from weasyprint.logger import LOGGER
LOGGER.setLevel(logging.INFO)

try:
documents = []
# collecting documents from local .htm files

    all_pages = []
    for doc in documents:
        for page in doc.pages:
            all_pages.append(page)

    documents[0].copy(all_pages).write_pdf('zzz.pdf')
except (RuntimeError, TypeError, NameError):
    print("Unexpected error:", sys.exc_info()[0])
`

`Process finished with exit code -1073741819 (0xC0000005)`

no changes... exit with error code without generating any PDF. 

To my surprise, no logging output, no sys Error output.

**Comment by Tontyna** [comment] 2018-12-01 08:08
What if you run your script outside of PyCharm?

BTW: There is no file access within the *all_pages-loop*. 
Files are accessed and processed during `HTML(filename=<filenameX>).render()` -- in the part of your code where you build the `documents[]` list. 
The *all_pages-loop* just collects pointers (`Pages` objects).

**Comment by liZe** [comment] 2018-12-27 14:09
@annashen Is your problem solved?

**Comment by annashen** [comment] 2018-12-30 03:10
> @annashen Is your problem solved?

not quite. just back from vacation. will try to run script through CLI to see if it works. will update this thread no matter what.

**Comment by liZe** [comment] 2019-01-21 22:14
As I think that this issue is not a bug in WeasyPrint, I'm closing it.

**Closed** 2019-09-16 14:36 UTC
