### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by takis** [Kozea/WeasyPrint#979] opened 2019-10-25 16:17 UTC
I have a specific PDF page which misses text when being rendered with WeasyPrint.

I took the original HTML and CSS and removed code to get a smaller and simpler example illustrating the problem. I tried adding the boxes together to further simplify the example, but doing so resulted in the correct behavior of spilling over the contents to the next page.

```html
<!DOCTYPE html>
<html>
  <head>
    <style>
      @page {
        margin: 5mm;
      }
      #boxa {
        height: 25mm;
      }
      #boxb {
        height: 35mm;
      }
      #boxc {
        height: 65mm;
      }
      #boxd {
        height: 35mm;
      }
      #boxe {
        height: 30mm;
      }
      #boxf {
        height: 10mm;
      }
      #boxg {
        height: 45mm;
      }
      .group {
        border: 1pt solid red;
        padding: 2mm;
      }
      td {
        padding-top: 1mm;
      }
    </style>
  </head>
  <body>
    <div>
      <div id="boxa" class="group"></div>
      <div id="boxb" class="group"></div>
      <div id="boxc" class="group"></div>
      <div id="boxd" class="group"></div>
      <div id="boxe" class="group"></div>
      <div id="boxf" class="group"></div>
      <div id="boxg" class="group"></div>
      <div id="boxh" class="group">
        <table>
          <tbody></tbody>
          <tfoot>
            <tr>
              <th>missing</th>
              <td>missing</td>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </body>
</html>


```

The output of WeasyPrint:
![Screenshot 2019-10-25 18:17:13](https://user-images.githubusercontent.com/128511/67587231-b86ce000-f753-11e9-8ddd-0ef3a0b57ec5.png)

**Comment by Tontyna** [comment] 2019-10-26 10:48
Duplicate of #978

**Comment by Tontyna** [comment] 2019-10-26 14:53
Naa, not exactly a duplicate. Though both issues stem from the fact that WeasyPrint tries to avoid orphaned table headers and widowed table footers.

In the above example `table_layout` detects that the table footer is too big to fit on the remaining space. But since there is nothing in the table's body the footer looks like a widow and is suppressed.

No decision is made between "there is nothing left" and "there never has been anything" in the table body.

**Closed** 2019-12-20 13:44 UTC
Labels: bug
