### ISSUE TITLE
Failed rendering of "Inconsolata" font

### ISSUE THREAD

**Issue by ondras** [Kozea/WeasyPrint#2266] opened 2024-10-03 18:33 UTC
The [Inconsolata](https://fonts.google.com/specimen/Inconsolata) font is a nice Google-hosted monospaced typeface that works fine in web browsers. Rendering Inconsolata text with WeasyPrint fails in a funny way.

Source:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
</head>
<body>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inconsolata:wdth,wght@50..200,200..900&display=swap');
    body { font-family: Inconsolata; }
  </style>

  <p>This is a test.</p>

</body>
</html>
```

Command line:
```sh
$ weasyprint -d test.html test.pdf
INFO: Step 1 - Fetching and parsing HTML - test.html
INFO: Step 2 - Fetching and parsing CSS - CSS string
INFO: Step 2 - Fetching and parsing CSS - https://fonts.googleapis.com/css2?family=Inconsolata:wdth,wght@50..200,200..900&display=swap
INFO: Step 3 - Applying CSS
INFO: Step 4 - Creating formatting structure
INFO: Step 5 - Creating layout - Page 1
INFO: Step 6 - Creating PDF
INFO: Step 7 - Adding PDF metadata
```

Result: 
![obrazek](https://github.com/user-attachments/assets/18aaab8c-56f8-4643-88f9-74df840d284e)

In-browser HTML rendering: 
![obrazek](https://github.com/user-attachments/assets/0994b04d-82a0-4ecb-b491-e634ef7847a6)

Comparison with the default "monospace": 
![obrazek](https://github.com/user-attachments/assets/f5cde2e2-f5bb-47b6-a542-76aa6bfcba5d)

Versions:
```
weasyprint             62.3
libpango-1.0-0:amd64              1.50.12+ds-1 
libpangocairo-1.0-0:amd64         1.50.12+ds-1
libpangoft2-1.0-0:amd64           1.50.12+ds-1 
```

**Comment by liZe** [comment] 2024-10-03 21:17
Hi!

Thanks for this report.

I get the correct rendering on my computer. Here’s what I’ve tried:

```html
  <p>This is a test.</p>
  <p style="font-stretch: ultra-condensed">This is a test (narrow).</p>
  <p style="font-stretch: ultra-expanded">This is a test (wide).</p>
```

![Capture d’écran du 2024-10-03 23-13-17](https://github.com/user-attachments/assets/33447d73-5159-4c96-8919-329f42554792)

I suspect that for some reason the default font stretch is a really narrow one for you. If you don’t want condensed variants, you can try this URL as a workaround:

`https://fonts.googleapis.com/css2?family=Inconsolata:wght@200..900&display=swap`

Could you please try my HTML with the original URL, and your HTML sample with this URL?

Do you have Insconsolata installed on your computer?

**Comment by liZe** [comment] 2024-10-05 07:34
I was afraid that it was a problem caused by #1073 with a variable font installed, but if it works with the simpler URL, it’s unrelated.

I suspect that there’s something wrong in the way fontconfig selects the correct font on your computer. Maybe a bug that’s been fixed in my version. Let’s close the issue for now, as the workaround is easy for you and the bug is probably not in WeasyPrint.

If anyone gets this problem again, feel free to add a comment.

**Closed by liZe** 2024-10-05 07:34 UTC
