### ISSUE TITLE
SVG Paths dropped due to low DPI during image draw

### ISSUE THREAD

**Issue by malthe** [Kozea/WeasyPrint#502] opened 2017-09-08 09:48 UTC
I have an SVG path that seems to be dropped or discarded from PDF output due to the DPI setting of 96 in `weasyprint/images.py:draw(...)`. If I reduce the DPI even lower, predictably even more paths are discarded from output.

This seems somewhat logical but it's unfortunate that the DPI setting is not configurable.

But now, for a mystery. If I put an `import pdb; pdb.set_trace()` like so:
```python
    def draw(self, context, concrete_width, concrete_height, _image_rendering):
        try:
            svg = ScaledSVGSurface(
                cairosvg.parser.Tree(
                    bytestring=self._svg_data, url=self._base_url,
                    url_fetcher=self._cairosvg_url_fetcher),
                output=None, dpi=96, parent_width=concrete_width,
                parent_height=concrete_height)
            if svg.width and svg.height:
                context.scale(
                    concrete_width / svg.width, concrete_height / svg.height)
                context.set_source_surface(svg.cairo)
 
                # sic !!!
                import pdb; pdb.set_trace()

                context.paint()
        except Exception as e:
            LOGGER.error(
                'Failed to draw an SVG image at %s : %s', self._base_url, e)
```
In this case, the DPI setting seems to be ignored and no paths are discarded at all, no matter the DPI setting.

I have not been able to get any further in understanding this behavior.

**Comment by liZe** [comment] 2017-09-08 10:16
It's proably a duplicate of #278 / #339 / #431 / #438… Short answer: it's a bug in cairo fixed upstream since April 2016, but no stable version has the patch. You can use the unstable 1.15.6 version for example.

**Comment by malthe** [comment] 2017-09-08 10:43
OK thanks!

I ended up simply patching the DPI parameter:
```python
def replace_tuple_value(t, value, new_value):
    l = list(t)
    i = l.index(value)
    assert i >= 0
    l[i] = new_value
    return tuple(l)


# Monkey-patch DPI setting to 300, see
# https://github.com/Kozea/WeasyPrint/issues/502.
from weasyprint.images import SVGImage
func = SVGImage.draw.im_func
fn_code = func.func_code
func.func_code = types.CodeType(
    fn_code.co_argcount,
    fn_code.co_nlocals,
    fn_code.co_stacksize,
    fn_code.co_flags,
    fn_code.co_code,
    replace_tuple_value(fn_code.co_consts, 96, 300),
    fn_code.co_names,
    fn_code.co_varnames,
    fn_code.co_filename,
    fn_code.co_name,
    fn_code.co_firstlineno,
    fn_code.co_lnotab,
    fn_code.co_freevars,
    fn_code.co_cellvars
)
```
Works for me but YMMV :-)

**Comment by liZe** [comment] 2017-09-08 11:20
Thanks, may help other users too!

**Closed by liZe** 2017-09-08 11:20 UTC
