### ISSUE TITLE
Missing Content

### ISSUE THREAD

**Issue by xinyou90** [Kozea/WeasyPrint#737] opened 2018-11-15 02:41 UTC
Some pdfs have missing content issue while doing html export.
Check this

![issue](https://user-images.githubusercontent.com/32596477/48526542-fe25f500-e8c2-11e8-94d8-39ad43caa6bd.png)

This is original

![original](https://user-images.githubusercontent.com/32596477/48526642-65dc4000-e8c3-11e8-9ab3-3203e24a3308.png)

**Comment by liZe** [comment] 2018-11-15 14:18
Hello,

It's probably a duplicate of #233. The bug is in cairo and has been fixed in cairo 1.14.2. Could you please upgrade your version of cairo and tell us if fixes this problem?

**Comment by xinyou90** [comment] 2018-11-15 14:49
Cairo?
Could you please let me know how to update this on Mac?

**Comment by xinyou90** [comment] 2018-11-15 16:10
@liZe ,
I just updated cairo following this guide.
https://weasyprint.readthedocs.io/en/latest/install.html#macos

After this, html.write_pdf() makes infinite loop.

**Comment by liZe** [comment] 2018-11-15 16:50
> After this, html.write_pdf() makes infinite loop.

Strange. Does WeasyPrint works with other documents? (You can try `python -m weasyprint https://weasyprint.org /tmp/weasyprint.pdf` for example.)

**Comment by xinyou90** [comment] 2018-11-15 16:52
Does not work,
![screen shot 2018-11-16 at 12 51 25 am](https://user-images.githubusercontent.com/32596477/48568215-cefe9a80-e939-11e8-98d8-bd72668bc778.png)

**Comment by liZe** [comment] 2018-11-15 16:57
Oh. Your problem is the same as Kozea/CairoSVG#207. This problem is not related to WeasyPrint, it's a problem of Python on macOS. Setting the locale environment variables (as explained on [this StackOverflow post](https://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8#19961403)) will solve this problem.

**Comment by xinyou90** [comment] 2018-11-15 18:29
Thanks for your help, @liZe 
But I have a new problem.
http://staging.alportal.com.au/api/mail/TWFpbFR5cGU6MjA5MjU=/
This is the html content.

If I export this as pdf (I created pdf file on the server and send to the frontend to download)
[export.pdf](https://github.com/Kozea/WeasyPrint/files/2586558/export.pdf)

**Closed** 2018-11-20 08:45 UTC
