### ISSUE TITLE
Bug in "running" headers: table row border is only rendered for first page

### ISSUE THREAD

**Issue by benboeck** [Kozea/WeasyPrint#1687] opened 2022-07-17 19:08 UTC
Hi, thank you very much for WeasyPrint!

We are ecstatic that WeasyPrint can now do headers/footers without ugly hacks (see issue [1662](https://github.com/Kozea/WeasyPrint/issues/1662))!

However, for our use case, I think I we identified a bug: though tables in "running" headers work, row borders (tr) only work on the first page.

We think this is a bug as borders work fine for paragraphs - and when specified either in the @top-center CSS or headerCenter DIV - and most importantly, it works fine on the FIRST page, but not the others.

![image](https://user-images.githubusercontent.com/14967118/179420911-8bfc31d6-d706-45e2-83b6-106af38fa9ab.png)

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>table in header border bug</title>
        <style>
            @page  {
                size: A6 landscape;
                margin: 30mm;

                @top-center{
                    content: element(headerCenter);
                }
            }

            .headerCenter{
                position: running(headerCenter);
            }
        </style>
    </head>
    <body>
        
        <div class="headerCenter">
            <table style="border-collapse: collapse; width: 100%;">
                <tr style="border-bottom: dotted 2pt; border-bottom-color: red;">
                    <td>there should be a red dotted border below this table row - but it only works on the <b>first</b> page.</td>
                </tr>
            </table>
            <p style="border-bottom: solid 2pt; border-bottom-color: blue;">
                the blue line below this paragraph works on all pages, however.
            </p>
        </div>

        <div class="content">
            <p>&nbsp;</p>
            <p style="page-break-before:always;">&nbsp;</p>
        </div>
    </body>
</html>
```

**expected functionality:**

html content in the "runnung" header is repeated correctly for all pages, including table row (TR) borders.

**Comment by liZe** [comment] 2022-07-18 08:17
Hi!

Thanks for the report. That’s actually a duplicate of #1278.

We’ve tried many times to solve this, as the problem is caused by a dirty workaround (removing cells borders to avoid them to be drawn instead of the collapsed borders) that seems easy to fix. There should be a very clean and smart way to avoid this, but … it’s not been found yet.

**Closed by liZe** 2022-07-18 08:17 UTC
