### ISSUE TITLE
BIDI text not working in weasyprint

### ISSUE THREAD

**Issue by SamWoofterHorn** [Kozea/WeasyPrint#1793] opened 2023-01-18 00:40 UTC
Hello, I am working on a project leveraging weasyprint where I need to be able to render bi-directional text correctly.

I have created a super simple example to explain the problem I am having:

Here is the example python code I have provided to render the html to pdf:
from weasyprint import CSS, HTML

```py
def render_weasy():
	weasy_html = HTML("weasyprint_basic.html")
	weasy_css = CSS("weasyprint_basic.css")
	weasy_html.write_pdf(target="weasy.pdf", stylesheets=[weasy_css])

if __name__ == "__main__":
	render_weasy()
```

Here is the html with the example text:
```html
<html>
	<head>
		<meta charset="utf-8">
	</head>
	<body>
		<div class="div-class">
			هذه قائمة بالعناصر باللغة العربية. هم كالتالي: <br>a. هذا هو العنصر الأول <br>b. هذا هو العنصر الثاني <br>c. هذا هو العنصر الثالث
		</div>
	</body>
</html>
```

In case the Arabic does not display correctly here in the markdown, here is a screenshot:
![Screen Shot 2023-01-17 at 6 28 33 PM](https://user-images.githubusercontent.com/101649793/213047973-f311ccbe-5dd9-4ce1-b49e-034cc174a05d.png)

Here is the example css - the font is just a system font on Mac for displaying Arabic correctly:
```css
@font-face {
	font-family: 'baghdad';
	src: url('../../../../System/Library/Fonts/Supplemental/Baghdad.ttc');
}

div.div-class {
	position: fixed;
	width: 100%;
	text-align: right;
	font-family: 'baghdad';
}
```

The output pdf shows the item looking like this:
<img width="348" alt="Screen Shot 2023-01-17 at 6 18 49 PM" src="https://user-images.githubusercontent.com/101649793/213048298-eb3e1331-8652-416b-aa83-cc300818f90a.png">

However, I think the letters in the last three lines (a, b, or c) are supposed be after the arabic text with the periods preceding the letters, like this:
<html>
	<head>
		<meta charset="utf-8">
	</head>
	<body>
		<div class="div-class">
			هذه قائمة بالعناصر باللغة العربية. هم كالتالي: <br>a. هذا هو العنصر الأول <br>b. هذا هو العنصر الثاني <br>c. هذا هو العنصر الثالث
		</div>
	</body>
</html>

Would it be possible for you to update weasyprint to accommodate for bi-directional text better? 

I have been extracting the letters from these types of texts and converting them to tables with the letters in the right column, but I would like to avoid those types of special cases if I can.

Thanks!

**Comment by liZe** [comment] 2023-01-18 13:48
Hi!

Thanks for your report.

This problem is well known, that’s actually a duplicate of #1620. As explained in the different issues open about RTL and bidi, even when the bug seems "easy" to fix, it’s usually not the case as we don’t want to accumulate workarounds for different use cases. Correctly handling rtl (and bidi, and vertical text, and…) in WeasyPrint is possible but it requires a lot of time.

**Closed by liZe** 2023-01-18 13:48 UTC
