### ISSUE TITLE
OSError: cannot load library 'pango-1.0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage  to locate a library called 'pango-1.0'

### ISSUE THREAD

**Issue by AhmedSalam22** [Kozea/WeasyPrint#1459] opened 2021-10-05 01:04 UTC
I am using Win 10 64bit and I have been installed GTK3 and add to PATH Variables.
```

(env) D:\Projects\مشاريع التخرج>weasyprint http://github.com test.pdf
Traceback (most recent call last):
  File "c:\users\ahmed maher\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ahmed maher\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ahmed Maher\AppData\Local\Programs\Python\Python38\Scripts\weasyprint.exe\__main__.py", line 4, in <module>
  File "c:\users\ahmed maher\appdata\local\programs\python\python38\lib\site-packages\weasyprint\__init__.py", 
line 440, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "c:\users\ahmed maher\appdata\local\programs\python\python38\lib\site-packages\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values, media_queries
  File "c:\users\ahmed maher\appdata\local\programs\python\python38\lib\site-packages\weasyprint\css\computed_values.py", line 18, in <module>
    from .. import text
  File "c:\users\ahmed maher\appdata\local\programs\python\python38\lib\site-packages\weasyprint\text.py", line 259, in <module>
    pango = dlopen(ffi, 'pango-1.0', 'libpango-1.0-0', 'libpango-1.0.so',
  File "c:\users\ahmed maher\appdata\local\programs\python\python38\lib\site-packages\weasyprint\text.py", line 254, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "c:\users\ahmed maher\appdata\local\programs\python\python38\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "c:\users\ahmed maher\appdata\local\programs\python\python38\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "c:\users\ahmed maher\appdata\local\programs\python\python38\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'pango-1.0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage 
to locate a library called 'pango-1.0'

(env) D:\Projects\مشاريع التخرج>
```

**Comment by liZe** [comment] 2021-10-05 04:42
Hello!

Thanks a lot for this bug report. It’s actually a duplicate of #1435, and there’s unfortunately no easy fix for the moment (other than using an old version of Python, or copying the dlls into the folder where Python is installed) 😒.

**Closed by liZe** 2021-10-05 04:42 UTC
