### ISSUE TITLE
Virus Total detects malware in windows binary

### ISSUE THREAD

**Issue by Eulender** [Kozea/WeasyPrint#2281] opened 2024-10-22 14:36 UTC
On virus total this file is recognised 15 times as a virus and the Chrome browser also does not allow the file to be downloaded due to a malware warning.

https://www.virustotal.com/gui/file/730a445728a0434f34462788326759135d6bb5215df1e143f6b5dd39cc2bf261

**Comment by liZe** [comment] 2024-10-22 19:09
Hi!

This is a duplicate of #2254 and some other issues. Documentation about that has been added [on the current main branch](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#windows). If anyone knows how we can avoid that, don’t hesitate to share your ideas here!

**Closed by liZe** 2024-10-22 19:09 UTC
