### ISSUE TITLE
Weird linebreak under certain circumstances

### ISSUE THREAD

**Issue by Christoph-Wagner** [Kozea/WeasyPrint#1122] opened 2020-05-25 06:21 UTC
Weasyprint v51 on Windows

Sorry for the bad title, I didn’t know how to describe this better.

This might not be easily reproduced as it seems to happen extremely rarely and I could only reproduce it with those exact settings, it requires Adobe’s "Myriad Pro" font family.

Essentially even a minuscule change of spacing fixes the problem. So going from `letter-spacing: -0.4px` to `letter-spacing: -0.404px;`, changing the margins, changing the font-size all make the problem disappear.

[testcase.pdf](https://github.com/Kozea/WeasyPrint/files/4675488/testcase.pdf)
[testcase.zip (contains the html)](https://github.com/Kozea/WeasyPrint/files/4675489/testcase.zip)

**Comment by Tontyna** [comment] 2020-05-25 06:59
Duplicate of #1051

How is it called when rare and strange fenomenons suddenly happen all the time? Space-time distortion?

**Comment by liZe** [comment] 2020-05-25 11:43
> How is it called when rare and strange fenomenons suddenly happen all the time? Space-time distortion?

It’s the new version of Pango being more and more adopted. Using Ahem everywhere in the tests make the error almost invisible for our testing suite.

**Closed by liZe** 2020-05-25 11:43 UTC
