### ISSUE TITLE
Including Bootstrap style sheet breaks styling

### ISSUE THREAD

**Issue by grant116** [Kozea/WeasyPrint#270] opened 2015-09-26 16:21 UTC
I have a fairly simple page I am trying to style and render as a PDF.  I noticed that I was not getting any styling to work if I include the bootstrap css file.  If I render this page via Django as a normal HTML document it works just fine.   Any thoughts on why this may be happening?

The HTML.

    <!doctype html>
    <html lang="en">
        <head>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <style>
            h1 {
                color: #0D1DFF;
            }
        </style>
        </head>
    <body>
        <div id="content" class="container">
            <div id="logo" class="col-md-3">
                <img src="/static/images/logo_small.png">
            </div>
            <div id="heading" class="col-md-6">
                <h1>Packing Slip</h1>
            </div>
            <div class="col-md-3">
                <h2>78126</h2>
            </div>
        </div>    
    </body>
    </html>

I am using the following code to generate the PDF.

        def get(self, request, *args, **kwargs):
            packslip_id = kwargs.get('packslip_id')
            context= {'packslip_id': packslip_id }
            template_string = render_to_string(self.template_name, context)
            html = HTML(string=template_string, base_url=request.build_absolute_uri())
            main_doc = html.render()
            pdf = main_doc.write_pdf()
            response = HttpResponse(pdf, content_type='application/pdf')
            #Download as attachment
            # response['Content-Disposition'] = 'attachment; filename=packslip-{0}.pdf'.format(packslip_id)
            # Display in browser
            response['Content-Disposition'] = 'filename=packslip-{0}.pdf'.format(packslip_id)
            return response

Trace information:

			Ignored `-webkit-text-size-adjust: 100%` at 5:108, unknown property.
			Ignored `-ms-text-size-adjust: 100%` at 5:138, unknown property.
			Ignored `-webkit-box-sizing: content-box` at 5:846, unknown property.
			Ignored `-moz-box-sizing: content-box` at 5:877, unknown property.
			Ignored `-webkit-appearance: button` at 5:1210, unknown property.
			Ignored `cursor: pointer` at 5:1236, the property does not apply for the print media.
			Ignored `cursor: default` at 5:1289, the property does not apply for the print media.
			Invalid or unsupported selector 'button::-moz-focus-inner,input::-moz-focus-inner', Unknown pseudo-element: -moz-focus-inner
			Ignored `-webkit-box-sizing: border-box` at 5:1436, unknown property.
			Ignored `-moz-box-sizing: border-box` at 5:1466, unknown property.
			Invalid or unsupported selector 'input[type=number]::-webkit-inner-spin-button,input[type=number]::-webkit-outer-spin-button', Unknown pseudo-element: -webkit-inner-spin-button
			Ignored `-webkit-box-sizing: content-box` at 5:1648, unknown property.
			Ignored `-moz-box-sizing: content-box` at 5:1679, unknown property.
			Ignored `-webkit-appearance: textfield` at 5:1730, unknown property.
			Ignored `-webkit-appearance: none` at 5:1854, unknown property.
			Ignored `text-shadow: none` at 5:2225, unknown property.
			Ignored `-webkit-box-shadow: none` at 5:2277, unknown property.
			Ignored `box-shadow: none` at 5:2311, unknown property.
			Ignored `-webkit-font-smoothing: antialiased` at 5:3619, unknown property.
			Ignored `-moz-osx-font-smoothing: grayscale` at 5:3654, unknown property.
			Ignored `-webkit-box-sizing: border-box` at 5:15119, unknown property.
			Ignored `-moz-box-sizing: border-box` at 5:15149, unknown property.
			Ignored `-webkit-box-sizing: border-box` at 5:15213, unknown property.
			Ignored `-moz-box-sizing: border-box` at 5:15243, unknown property.
			Ignored `-webkit-tap-highlight-color: rgba(0,0,0,0)` at 5:15312, unknown property.
			Ignored `outline: 5px auto -webkit-focus-ring-color` at 5:15694, invalid value.
			Ignored `outline-offset: -2px` at 5:15736, unknown property.
			Ignored `-webkit-transition: all .2s ease-in-out` at 5:16132, unknown property.
			Ignored `-o-transition: all .2s ease-in-out` at 5:16171, unknown property.
			Ignored `transition: all .2s ease-in-out` at 5:16205, unknown property.
			Ignored `cursor: pointer` at 5:16593, the property does not apply for the print media.
			Ignored `cursor: help` at 5:19593, the property does not apply for the print media.
			Ignored `-webkit-box-shadow: inset 0 -1px 0 rgba(0,0,0,.25)` at 5:20975, unknown property.
			Ignored `box-shadow: inset 0 -1px 0 rgba(0,0,0,.25)` at 5:21025, unknown property.
			Ignored `-webkit-box-shadow: none` at 5:21116, unknown property.
			Ignored `box-shadow: none` at 5:21140, unknown property.
			Ignored `word-break: break-all` at 5:21253, unknown property.
			Ignored `overflow-y: scroll` at 5:21510, unknown property.
			Ignored `overflow-x: auto` at 5:33828, unknown property.
			Ignored `-webkit-box-sizing: border-box` at 5:35593, unknown property.
			Ignored `-moz-box-sizing: border-box` at 5:35623, unknown property.
			Ignored `margin-top: 1px\9` at 5:35726, invalid value.
			Ignored `outline: 5px auto -webkit-focus-ring-color` at 5:35972, invalid value.
			Ignored `outline-offset: -2px` at 5:36014, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075)` at 5:36321, unknown property.
			Ignored `box-shadow: inset 0 1px 1px rgba(0,0,0,.075)` at 5:36373, unknown property.
			Ignored `-webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s` at 5:36417, unknown property.
			Ignored `-o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s` at 5:36502, unknown property.
			Ignored `transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s` at 5:36574, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)` at 5:36694, unknown property.
			Ignored `box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)` at 5:36775, unknown property.
			Invalid or unsupported selector '.form-control::-moz-placeholder', Unknown pseudo-element: -moz-placeholder
			Invalid or unsupported selector '.form-control:-ms-input-placeholder', The pseudo-class :-ms-input-placeholder is unknown
			Invalid or unsupported selector '.form-control::-webkit-input-placeholder', Unknown pseudo-element: -webkit-input-placeholder
			Ignored `cursor: not-allowed` at 5:37170, the property does not apply for the print media.
			Ignored `-webkit-appearance: none` at 5:37242, unknown property.
			Ignored `cursor: pointer` at 5:38228, the property does not apply for the print media.
			Ignored `margin-top: 4px\9` at 5:38387, invalid value.
			Ignored `cursor: pointer` at 5:38614, the property does not apply for the print media.
			Ignored `cursor: not-allowed` at 5:38914, the property does not apply for the print media.
			Ignored `cursor: not-allowed` at 5:39051, the property does not apply for the print media.
			Ignored `cursor: not-allowed` at 5:39184, the property does not apply for the print media.
			Ignored `pointer-events: none` at 5:40753, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075)` at 5:41436, unknown property.
			Ignored `box-shadow: inset 0 1px 1px rgba(0,0,0,.075)` at 5:41488, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 6px #67b168` at 5:41586, unknown property.
			Ignored `box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 6px #67b168` at 5:41654, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075)` at 5:42191, unknown property.
			Ignored `box-shadow: inset 0 1px 1px rgba(0,0,0,.075)` at 5:42243, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 6px #c0a16b` at 5:42341, unknown property.
			Ignored `box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 6px #c0a16b` at 5:42409, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075)` at 5:42924, unknown property.
			Ignored `box-shadow: inset 0 1px 1px rgba(0,0,0,.075)` at 5:42976, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 6px #ce8483` at 5:43072, unknown property.
			Ignored `box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 6px #ce8483` at 5:43140, unknown property.
			Ignored `-ms-touch-action: manipulation` at 5:45297, unknown property.
			Ignored `touch-action: manipulation` at 5:45327, unknown property.
			Ignored `cursor: pointer` at 5:45353, the property does not apply for the print media.
			Ignored `-webkit-user-select: none` at 5:45368, unknown property.
			Ignored `-moz-user-select: none` at 5:45393, unknown property.
			Ignored `-ms-user-select: none` at 5:45415, unknown property.
			Ignored `user-select: none` at 5:45436, unknown property.
			Ignored `outline: 5px auto -webkit-focus-ring-color` at 5:45636, invalid value.
			Ignored `outline-offset: -2px` at 5:45678, unknown property.
			Ignored `-webkit-box-shadow: inset 0 3px 5px rgba(0,0,0,.125)` at 5:45819, unknown property.
			Ignored `box-shadow: inset 0 3px 5px rgba(0,0,0,.125)` at 5:45871, unknown property.
			Ignored `cursor: not-allowed` at 5:45968, the property does not apply for the print media.
			Ignored `filter: alpha(opacity=65)` at 5:45987, unknown property.
			Ignored `-webkit-box-shadow: none` at 5:46012, unknown property.
			Ignored `box-shadow: none` at 5:46036, unknown property.
			Ignored `pointer-events: none` at 5:46104, unknown property.
			Ignored `-webkit-box-shadow: none` at 5:54931, unknown property.
			Ignored `box-shadow: none` at 5:54955, unknown property.
			Ignored `-webkit-transition: opacity .15s linear` at 5:55781, unknown property.
			Ignored `-o-transition: opacity .15s linear` at 5:55820, unknown property.
			Ignored `transition: opacity .15s linear` at 5:55854, unknown property.
			Ignored `-webkit-transition-timing-function: ease` at 5:56084, unknown property.
			Ignored `-o-transition-timing-function: ease` at 5:56124, unknown property.
			Ignored `transition-timing-function: ease` at 5:56159, unknown property.
			Ignored `-webkit-transition-duration: .35s` at 5:56191, unknown property.
			Ignored `-o-transition-duration: .35s` at 5:56224, unknown property.
			Ignored `transition-duration: .35s` at 5:56252, unknown property.
			Ignored `-webkit-transition-property: height,visibility` at 5:56277, unknown property.
			Ignored `-o-transition-property: height,visibility` at 5:56323, unknown property.
			Ignored `transition-property: height,visibility` at 5:56364, unknown property.
			Ignored `border-top: 4px solid\9` at 5:56507, invalid value.
			Ignored `-webkit-background-clip: padding-box` at 5:56868, unknown property.
			Ignored `-webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175)` at 5:57005, unknown property.
			Ignored `box-shadow: 0 6px 12px rgba(0,0,0,.175)` at 5:57052, unknown property.
			Ignored `cursor: not-allowed` at 5:57812, the property does not apply for the print media.
			Ignored `filter: progid:DXImageTransform.Microsoft.gradient(enabled=false)` at 5:57882, unknown property.
			Ignored `border-bottom: 4px solid\9` at 5:58416, invalid value.
			Ignored `-webkit-box-shadow: inset 0 3px 5px rgba(0,0,0,.125)` at 5:60452, unknown property.
			Ignored `box-shadow: inset 0 3px 5px rgba(0,0,0,.125)` at 5:60504, unknown property.
			Ignored `-webkit-box-shadow: none` at 5:60590, unknown property.
			Ignored `box-shadow: none` at 5:60614, unknown property.
			Ignored `pointer-events: none` at 5:62438, unknown property.
			Ignored `cursor: not-allowed` at 5:66315, the property does not apply for the print media.
			Ignored `cursor: default` at 5:66899, the property does not apply for the print media.
			Ignored `overflow-x: visible` at 5:69209, unknown property.
			Ignored `-webkit-overflow-scrolling: touch` at 5:69228, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,.1)` at 5:69294, unknown property.
			Ignored `box-shadow: inset 0 1px 0 rgba(255,255,255,.1)` at 5:69348, unknown property.
			Ignored `overflow-y: auto` at 5:69414, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,.1),0 1px 0 rgba(255,255,255,.1)` at 5:72392, unknown property.
			Ignored `box-shadow: inset 0 1px 0 rgba(255,255,255,.1),0 1px 0 rgba(255,255,255,.1)` at 5:72475, unknown property.
			Ignored `cursor: default` at 5:80420, the property does not apply for the print media.
			Ignored `cursor: not-allowed` at 5:80669, the property does not apply for the print media.
			Ignored `cursor: not-allowed` at 5:81914, the property does not apply for the print media.
			Ignored `cursor: pointer` at 5:82196, the property does not apply for the print media.
			Ignored `cursor: pointer` at 5:83378, the property does not apply for the print media.
			Ignored `-webkit-transition: border .2s ease-in-out` at 5:84321, unknown property.
			Ignored `-o-transition: border .2s ease-in-out` at 5:84363, unknown property.
			Ignored `transition: border .2s ease-in-out` at 5:84400, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 2px rgba(0,0,0,.1)` at 5:86012, unknown property.
			Ignored `box-shadow: inset 0 1px 2px rgba(0,0,0,.1)` at 5:86062, unknown property.
			Ignored `-webkit-box-shadow: inset 0 -1px 0 rgba(0,0,0,.15)` at 5:86235, unknown property.
			Ignored `box-shadow: inset 0 -1px 0 rgba(0,0,0,.15)` at 5:86285, unknown property.
			Ignored `-webkit-transition: width .6s ease` at 5:86327, unknown property.
			Ignored `-o-transition: width .6s ease` at 5:86361, unknown property.
			Ignored `transition: width .6s ease` at 5:86390, unknown property.
			Ignored `background-image: -webkit-linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transparent)` at 5:86470, invalid value.
			Ignored `background-image: -o-linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transparent)` at 5:86656, invalid value.
			Ignored `-webkit-background-size: 40px 40px` at 5:87015, unknown property.
			Ignored `-webkit-animation: progress-bar-stripes 2s linear infinite` at 5:87127, unknown property.
			Ignored `-o-animation: progress-bar-stripes 2s linear infinite` at 5:87185, unknown property.
			Ignored `animation: progress-bar-stripes 2s linear infinite` at 5:87238, unknown property.
			Ignored `background-image: -webkit-linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transparent)` at 5:87375, invalid value.
			Ignored `background-image: -o-linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transparent)` at 5:87561, invalid value.
			Ignored `background-image: -webkit-linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transparent)` at 5:88001, invalid value.
			Ignored `background-image: -o-linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transparent)` at 5:88187, invalid value.
			Ignored `background-image: -webkit-linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transparent)` at 5:88633, invalid value.
			Ignored `background-image: -o-linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transparent)` at 5:88819, invalid value.
			Ignored `background-image: -webkit-linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transparent)` at 5:89263, invalid value.
			Ignored `background-image: -o-linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transparent)` at 5:89449, invalid value.
			Ignored `zoom: 1` at 5:89898, unknown property.
			Ignored `cursor: not-allowed` at 5:91170, the property does not apply for the print media.
			Ignored `-webkit-box-shadow: 0 1px 1px rgba(0,0,0,.05)` at 5:95455, unknown property.
			Ignored `box-shadow: 0 1px 1px rgba(0,0,0,.05)` at 5:95500, unknown property.
			Ignored `-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.05)` at 5:106801, unknown property.
			Ignored `box-shadow: inset 0 1px 1px rgba(0,0,0,.05)` at 5:106852, unknown property.
			Ignored `text-shadow: 0 1px 0 #fff` at 5:107113, unknown property.
			Ignored `filter: alpha(opacity=20)` at 5:107138, unknown property.
			Ignored `cursor: pointer` at 5:107232, the property does not apply for the print media.
			Ignored `filter: alpha(opacity=50)` at 5:107247, unknown property.
			Ignored `-webkit-appearance: none` at 5:107296, unknown property.
			Ignored `cursor: pointer` at 5:107330, the property does not apply for the print media.
			Ignored `-webkit-overflow-scrolling: touch` at 5:107491, unknown property.
			Ignored `-webkit-transition: -webkit-transform .3s ease-out` at 5:107560, unknown property.
			Ignored `-o-transition: -o-transform .3s ease-out` at 5:107610, unknown property.
			Ignored `transition: transform .3s ease-out` at 5:107650, unknown property.
			Ignored `-webkit-transform: translate(0,-25%)` at 5:107684, unknown property.
			Ignored `-ms-transform: translate(0,-25%)` at 5:107720, unknown property.
			Ignored `-o-transform: translate(0,-25%)` at 5:107752, unknown property.
			Ignored `-webkit-transform: translate(0,0)` at 5:107835, unknown property.
			Ignored `-ms-transform: translate(0,0)` at 5:107868, unknown property.
			Ignored `-o-transform: translate(0,0)` at 5:107897, unknown property.
			Ignored `overflow-x: hidden` at 5:107969, unknown property.
			Ignored `overflow-y: auto` at 5:107987, unknown property.
			Ignored `-webkit-background-clip: padding-box` at 5:108113, unknown property.
			Ignored `-webkit-box-shadow: 0 3px 9px rgba(0,0,0,.5)` at 5:108259, unknown property.
			Ignored `box-shadow: 0 3px 9px rgba(0,0,0,.5)` at 5:108303, unknown property.
			Ignored `filter: alpha(opacity=0)` at 5:108456, unknown property.
			Ignored `filter: alpha(opacity=50)` at 5:108509, unknown property.
			Ignored `text-align: start` at 5:109507, invalid value.
			Ignored `text-shadow: none` at 5:109545, unknown property.
			Ignored `word-break: normal` at 5:109604, unknown property.
			Ignored `filter: alpha(opacity=0)` at 5:109678, unknown property.
			Ignored `line-break: auto` at 5:109712, unknown property.
			Ignored `filter: alpha(opacity=90)` at 5:109740, unknown property.
			Ignored `text-align: start` at 5:111308, invalid value.
			Ignored `text-shadow: none` at 5:111346, unknown property.
			Ignored `word-break: normal` at 5:111405, unknown property.
			Ignored `-webkit-background-clip: padding-box` at 5:111501, unknown property.
			Ignored `-webkit-box-shadow: 0 5px 10px rgba(0,0,0,.2)` at 5:111637, unknown property.
			Ignored `box-shadow: 0 5px 10px rgba(0,0,0,.2)` at 5:111682, unknown property.
			Ignored `line-break: auto` at 5:111719, unknown property.
			Ignored `-webkit-transition: .6s ease-in-out left` at 5:113376, unknown property.
			Ignored `-o-transition: .6s ease-in-out left` at 5:113416, unknown property.
			Ignored `transition: .6s ease-in-out left` at 5:113451, unknown property.
			Ignored `text-shadow: 0 1px 2px rgba(0,0,0,.6)` at 5:114829, unknown property.
			Ignored `filter: alpha(opacity=50)` at 5:114866, unknown property.
			Ignored `background-image: -webkit-linear-gradient(left,rgba(0,0,0,.5) 0,rgba(0,0,0,.0001) 100%)` at 5:114925, invalid value.
			Ignored `background-image: -o-linear-gradient(left,rgba(0,0,0,.5) 0,rgba(0,0,0,.0001) 100%)` at 5:115012, invalid value.
			Ignored `background-image: -webkit-gradient(linear,left top,right top,from(rgba(0,0,0,.5)),to(rgba(0,0,0,.0001)))` at 5:115094, invalid value.
			Ignored `filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#00000000', GradientType=1)` at 5:115281, unknown property.
			Ignored `background-image: -webkit-linear-gradient(left,rgba(0,0,0,.0001) 0,rgba(0,0,0,.5) 100%)` at 5:115468, invalid value.
			Ignored `background-image: -o-linear-gradient(left,rgba(0,0,0,.0001) 0,rgba(0,0,0,.5) 100%)` at 5:115555, invalid value.
			Ignored `background-image: -webkit-gradient(linear,left top,right top,from(rgba(0,0,0,.0001)),to(rgba(0,0,0,.5)))` at 5:115637, invalid value.
			Ignored `filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#80000000', GradientType=1)` at 5:115824, unknown property.
			Ignored `filter: alpha(opacity=90)` at 5:116049, unknown property.
			Ignored `cursor: pointer` at 5:116973, the property does not apply for the print media.
			Ignored `background-color: #000\9` at 5:116988, invalid value.
			Ignored `text-shadow: 0 1px 2px rgba(0,0,0,.6)` at 5:117311, unknown property.
			Ignored `text-shadow: none` at 5:117371, unknown property.
			Ignored `text-shadow: none` at 5:119108, unknown property.
			Parse error at 5:3012, unknown at-rule in stylesheet context: @font-face
			Parse error at 5:17606, expected a media type, got (
			Parse error at 5:19373, expected a media type, got (
			Parse error at 5:21618, expected a media type, got (
			Parse error at 5:21667, expected a media type, got (
			Parse error at 5:21716, expected a media type, got (
			Parse error at 5:24200, expected a media type, got (
			Parse error at 5:25966, expected a media type, got (
			Parse error at 5:27732, expected a media type, got (
			Parse error at 5:33851, expected a media type, got IDENT, IDENT, (
			Parse error at 5:37273, expected a media type, got IDENT, IDENT, (
			Parse error at 5:43528, expected a media type, got (
			Parse error at 5:44748, expected a media type, got (
			Parse error at 5:44920, expected a media type, got (
			Parse error at 5:45028, expected a media type, got (
			Parse error at 5:58557, expected a media type, got (
			Parse error at 5:67219, expected a media type, got (
			Parse error at 5:67543, expected a media type, got (
			Parse error at 5:68246, expected a media type, got (
			Parse error at 5:68572, expected a media type, got (
			Parse error at 5:69058, expected a media type, got (
			Parse error at 5:69110, expected a media type, got (
			Parse error at 5:69437, expected a media type, got (
			Parse error at 5:69929, expected a media type, got (, IDENT, (
			Parse error at 5:70237, expected a media type, got (
			Parse error at 5:70465, expected a media type, got (
			Parse error at 5:70608, expected a media type, got (
			Parse error at 5:70981, expected a media type, got (
			Parse error at 5:71468, expected a media type, got (
			Parse error at 5:71624, expected a media type, got (
			Parse error at 5:72091, expected a media type, got (
			Parse error at 5:72557, expected a media type, got (
			Parse error at 5:73483, expected a media type, got (
			Parse error at 5:73604, expected a media type, got (
			Parse error at 5:74237, expected a media type, got (
			Parse error at 5:74322, expected a media type, got (
			Parse error at 5:75681, expected a media type, got (
			Parse error at 5:77991, expected a media type, got (
			Parse error at 5:83971, expected a media type, got IDENT, IDENT, (
			Parse error at 5:85625, unknown at-rule in stylesheet context: @-webkit-keyframes
			Parse error at 5:85725, unknown at-rule in stylesheet context: @-o-keyframes
			Parse error at 5:85820, unknown at-rule in stylesheet context: @keyframes
			Parse error at 5:109080, expected a media type, got (
			Parse error at 5:109268, expected a media type, got (
			Parse error at 5:113558, expected a media type, got IDENT, IDENT, (
			Parse error at 5:117395, expected a media type, got IDENT, IDENT, (
			Parse error at 5:119216, unknown at-rule in stylesheet context: @-ms-viewport
			Parse error at 5:119598, expected a media type, got (
			Parse error at 5:119800, expected a media type, got (
			Parse error at 5:119868, expected a media type, got (
			Parse error at 5:119938, expected a media type, got (
			Parse error at 5:120020, expected a media type, got (, IDENT, (
			Parse error at 5:120244, expected a media type, got (, IDENT, (
			Parse error at 5:120334, expected a media type, got (, IDENT, (
			Parse error at 5:120426, expected a media type, got (, IDENT, (
			Parse error at 5:120530, expected a media type, got (, IDENT, (
			Parse error at 5:120755, expected a media type, got (, IDENT, (
			Parse error at 5:120846, expected a media type, got (, IDENT, (
			Parse error at 5:120939, expected a media type, got (, IDENT, (
			Parse error at 5:121044, expected a media type, got (
			Parse error at 5:121247, expected a media type, got (
			Parse error at 5:121316, expected a media type, got (
			Parse error at 5:121387, expected a media type, got (
			Parse error at 5:121470, expected a media type, got (
			Parse error at 5:121530, expected a media type, got (, IDENT, (
			Parse error at 5:121612, expected a media type, got (, IDENT, (
			Parse error at 5:121695, expected a media type, got (
			[26/Sep/2015 11:19:02]"GET /static/images/logo_small.png HTTP/1.1" 200 6761
			Sep 26 11:19:03 mini.local python[14993] <Error>: The function ‘CGFontGetGlyphPath’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.
			Sep 26 11:19:03 mini.local python[14993] <Error>: The function ‘CGFontGetGlyphPaths’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.
			[26/Sep/2015 11:19:03]"GET /shipping/weasypdf/78126 HTTP/1.1" 200 21863

**Comment by SimonSapin** [comment] 2015-09-29 15:50
It’s not at all clear to me what the issue is here. Could you explain precisely what you mean by "not getting any styling" and "works just fine"?

As far as I can tell when trying to render this document, styles do get applied. The title is not blue, but that’s probably overridden by one rule or another from Bootstrap. Not getting the same styles as in a browser is expected: WeasyPrint doesn’t support media queries and so ignores blocks like `@media (max-width: 767px) { … }`. But it *will* apply `@media print { … }` which browsers ignore (when not printing).

In general, I’d recommend against using Bootstrap with WeasyPrint as it’s not at all designed for printing. In particular, its usage of floats for doing columns is problematic since WeasyPrint does not support page breaks inside of floats.

(This particular version of bootstrap, when not minified, is 6800 lines of CSS. There’s a lot going on these, I don’t think it qualifies as a "fairly simple page".)

Closing, as this doesn’t seem to be a bug in WeasyPrint. If you still think it is, please provide a minimal test case (so preferably without a big framework like Bootstrap) and describe in details what results you expected and what you got instead.

**Closed by SimonSapin** 2015-09-29 15:50 UTC
