### ISSUE TITLE
Floats add a lot of empty space

### ISSUE THREAD

**Issue by shinokada** [Kozea/WeasyPrint#1452] opened 2021-09-25 22:30 UTC
Versions:

```
$ weasyprint --info
System: Darwin
Machine: arm64
Version: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101
Release: 20.6.0

WeasyPrint version: 53.3
Python version: 3.8.10
Pydyf version: 0.1.1
Pango version: 14810
```

When I run `weasyprint http://weasyprint.org ./test1.pdf`, I get the following warning. Since they are warning, I can ignore them. 

But the PDF file is a mess. [test1.pdf](https://github.com/Kozea/WeasyPrint/files/7230436/test1.pdf)

```
$ weasyprint http://weasyprint.org ./test1.pdf
Fontconfig warning: ignoring UTF-8: not a valid region tag
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px) ' the whole @media rule was ignored at 80:1.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 83:1.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px) ' the whole @media rule was ignored at 87:1.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 90:1.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px) ' the whole @media rule was ignored at 94:1.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 97:1.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px) ' the whole @media rule was ignored at 101:1.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 104:1.
WARNING: Ignored `width: 100vw` at 130:3, invalid value.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 143:1.
WARNING: Ignored `overflow-x: hidden` at 168:3, unknown property.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 200:1.
WARNING: Ignored `width: -moz-min-content` at 217:3, invalid value.
WARNING: Ignored `width: -webkit-min-content` at 218:3, invalid value.
WARNING: Ignored `width: min-content` at 219:3, invalid value.
WARNING: Ignored `min-height: 60vh` at 243:3, invalid value.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 263:1.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 331:1.
WARNING: Ignored `max-width: calc(100% + 45px * 2 + 2px)` at 380:3, invalid value.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px) ' the whole @media rule was ignored at 455:1.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px) ' the whole @media rule was ignored at 479:1.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 484:1.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px) ' the whole @media rule was ignored at 519:1.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 524:1.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 578:1.
WARNING: Ignored `box-shadow: 0 5px 5px 0 rgba(111, 122, 137, 0.3)` at 620:3, unknown property.
WARNING: Ignored `box-shadow: 0 0 0 0 #e2e4e8` at 624:3, unknown property.
WARNING: Ignored `background-position-x: 0` at 635:3, unknown property.
WARNING: Ignored `box-shadow: 0 5px 5px 0 rgba(111, 122, 137, 0.1)` at 654:3, unknown property.
WARNING: Ignored `background-position-x: 0` at 680:3, unknown property.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px) ' the whole @media rule was ignored at 685:1.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 691:1.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px) ' the whole @media rule was ignored at 738:1.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px) ' the whole @media rule was ignored at 749:1.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 581px)'
WARNING: Invalid media type ' screen and (min-width: 581px) ' the whole @media rule was ignored at 761:1.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 580px)'
WARNING: Invalid media type ' screen and (max-width: 580px) ' the whole @media rule was ignored at 773:1.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 831px)'
WARNING: Invalid media type ' screen and (min-width: 831px) ' the whole @media rule was ignored at 884:1.
WARNING: Expected a media type, got 'screen/**/and/**/(max-width: 830px)'
WARNING: Invalid media type ' screen and (max-width: 830px) ' the whole @media rule was ignored at 903:1.
WARNING: Expected a media type, got 'screen/**/and/**/(min-width: 831px)'
WARNING: Invalid media type ' screen and (min-width: 831px) ' the whole @media rule was ignored at 1029:1.
```

How can I fix the problems?

**Comment by liZe** [comment] 2021-09-26 07:07
Hello! Thanks a lot for this bug report.

> Since they are warning, I can ignore them.

Yes, you can :smile:.

> But the PDF file is a mess.

Oh, yes… We’ve recently changed the website, and it introduced this layout problem. That’s sad 😒.

> How can I fix the problems?

There’s nothing to fix for you, everything should work well with other HTML files! The bug is in WeasyPrint for this web page. We’ll probably fix the website so that users don’t have the problem anymore with the example from the documentation, but we definitely have to fix this bug anyway.

**Comment by shinokada** [comment] 2021-09-26 07:21
I used the following code but when I try to open, it returns The file “mytest.png” could not be opened.

```
$ weasyprint https://google.com ./mytest.png
Fontconfig warning: ignoring UTF-8: not a valid region tag
WARNING: Ignored `overflow-y:scroll` at 1:59, unknown property.
WARNING: Ignored `display:inline-box` at 1:330, invalid value.
```

I tried a local HTML, but the result is the same. No image.

**Comment by liZe** [comment] 2021-09-26 07:58
> I tried a local HTML, but the result is the same. No image.

WeasyPrint generates PDF files, not PNG images :wink:.

**Comment by liZe** [comment] 2021-09-27 09:17
Reopening (and renaming), as your original bug has to be fixed!

The website has been changed to avoid the problem for now.

**Comment by liZe** [comment] 2021-09-27 12:31
The bug is a duplicate of #1311. I’ll add comments there.

**Closed by liZe** 2021-09-27 12:31 UTC
Labels: bug
