### ISSUE TITLE
does not print table header at all, cuts off body

### ISSUE THREAD

**Issue by andreixk** [Kozea/WeasyPrint#522] opened 2017-10-12 14:15 UTC
If you try to print this html with simple CTRL+P on chrome it prints it properly (header on every page, 3 pages total). 
However WeasyPrint (0.41) does not print header at all, only prints the body on 1 page, and cuts off the rest:

```
<table>
<thead>
  <tr>
    <td> 
    	headrerrrrrrrrr <br> headrerrrrrrrrr <br> headrerrrrrrrrr <br> headrerrrrrrrrr <br> headrerrrrrrrrr <br>
    	headrerrrrrrrrr <br> headrerrrrrrrrr <br> headrerrrrrrrrr <br> headrerrrrrrrrr <br> headrerrrrrrrrr <br>
    </td>
  </tr>
</thead>
<tbody>
  <tr>
    <td>
    	body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br>
    	body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br>
    	body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br>
    	body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br>
    	body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br>
    	body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br>
    	body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br>
    	body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br> body <br>
    	Last Entry
    </td>
  </tr>
</tbody>
</table>
```

**Comment by liZe** [comment] 2017-10-12 16:25
Thank you for this bug report.

It's a duplicate of #36. WeasyPrint desesperately tries to display the whole table and even removes the header if the body is too large, that's why it's not displayed. This really naive and buggy behavior will be removed as soon as (4-year-old) #36 is closed.

**Closed by liZe** 2017-10-12 16:25 UTC
