### ISSUE TITLE
Crashing with TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by albertlidas** [Kozea/WeasyPrint#617] opened 2018-04-18 08:12 UTC
Here is my code:
```   
    cover_page = render_to_string('guest/components/pdf_cover.html', context)
    content_page = render_to_string('guest/components/pdf_content.html', context)
    pdf1 = HTML(string=cover_page)
    pdf2 = HTML(string=content_page)
    pdf_doc_1 = pdf1.render()
    pdf_doc_2 = pdf2.render()

    val = []

    for doc in pdf_doc_1, pdf_doc_2:
        for p in doc.pages:
            val.append(p)

    pdf_file = pdf_doc_1.copy(val).write_pdf()
```
The issue happens in `pdf_doc_2 = pdf2.render()`. When I render this just like a django template it works fine and I see an html page in the browser.
Traceback:
```
Traceback (most recent call last):
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "./touchstay/views/invitation.py", line 368, in get
    return generate_pdf(request, destination, None)
  File "./touchstay/views/invitation.py", line 414, in generate_pdf
    pdf_doc_2 = pdf2.render()
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/__init__.py", line 143, in render
    font_config)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/document.py", line 326, in _render
    [Page(p, enable_hinting) for p in page_boxes],
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/__init__.py", line 55, in layout_document
    context, root_box, html, cascaded_styles, computed_styles))
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/pages.py", line 601, in make_all_pages
    context, root_box, page_type, resume_at, page_number)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/pages.py", line 520, in make_page
    positioned_boxes, positioned_boxes, adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 83, in block_level_layout
    adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 111, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 638, in block_container_layout
    adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 83, in block_level_layout
    adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 111, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 638, in block_container_layout
    adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 83, in block_level_layout
    adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 111, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 638, in block_container_layout
    adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 83, in block_level_layout
    adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 111, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 638, in block_container_layout
    adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 83, in block_level_layout
    adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 111, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 638, in block_container_layout
    adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 83, in block_level_layout
    adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 111, in block_box_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/blocks.py", line 510, in block_container_layout
    for line, resume_at in lines_iterator:
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/inlines.py", line 51, in iter_line_boxes
    device_size, absolute_boxes, fixed_boxes, first_letter_style)
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/inlines.py", line 108, in get_next_linebox
    waiting_floats, line_children=[])
  File "/home/virtualenvs/mts/local/lib/python2.7/site-packages/weasyprint/layout/inlines.py", line 839, in split_inline_box
    child_resume_at[0] + current_skip,
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by albertlidas** [comment] 2018-04-18 10:06
I found the cause.
`<p>Test string<em>Some text</em>.</p>`
In the string above a user didn't put the `.` into <em></em> tags.

**Comment by albertlidas** [comment] 2018-04-18 10:24
The cause was `.` in `</em>.</p>`

**Comment by albertlidas** [comment] 2018-04-18 10:29
Could you please add this case to your project code?

**Comment by Tontyna** [comment] 2018-04-21 21:54
Can't reproduce the crash with a pure `<p><em>string</em>.</p>`. Not with WeasyPrint 0.42 / Python 3.6. 
Whats your version of WeasyPrint?

**Comment by albertlidas** [comment] 2018-04-23 08:27
Here is original string 
`<p><br>"<em>It is helpful to know if there is anything broken or damaged so that we can fix it before the next guests arrive</em>."</p>`
WeasyPrint 0.42.2 / Python 2.7.12

**Comment by Tontyna** [comment] 2018-04-23 20:06
I suspect it's Pango again.
Could you please run the following Python script and post the output?

```python
# coding: utf-8
from weasyprint import HTML
from weasyprint.text import (
    ffi, pango, unicode_to_char_p)

def test_can_break_text(text):
    if not text or len(text) < 2:
        print('can_break:','"'+text+'"')
        print('=> text too short:', False)
        return False
    # quickndirty get body text
    myhtml = HTML(string=text)
    for element in myhtml.etree_element:
        if element.text:
            text = element.text
    print('can_break:','"'+text+'"')
    # BTW: this is "en-us" on (my) Windows 7
    language = pango.pango_language_get_default()
    # TODO: this should be removed when bidi is supported
    for char in ('\u202a', '\u202b', '\u202c', '\u202d', '\u202e'):
        text = text.replace(char, '')
    text_p, bytestring = unicode_to_char_p(text)
    length = len(bytestring) + 1
    log_attrs = ffi.new('PangoLogAttr[]', length)
    pango.pango_get_log_attrs(
        text_p, len(bytestring), -1, language, log_attrs, length)
    i = 0
    for attr in log_attrs[0:length - 1]:
        print(bytestring[i], text_p[i], attr.is_line_break)
        i=i+1
    res = any(attr.is_line_break for attr in log_attrs[1:length - 1])
    print('=>', res)
    return res


print('pango:' , pango.pango_version(), '\n')
test_can_break_text('."')
````

**Comment by liZe** [comment] 2018-09-17 16:32
> TypeError: parse() got an unexpected keyword argument 'override_encoding'

This is another problem, see #353.

> The cause was `.` in `<p><em>string</em>.</p>`

It's a duplicate of #580, it's fixed now!

**Closed by liZe** 2018-09-17 16:32 UTC
Labels: bug, crash
