### ISSUE TITLE
Radio button selection is pdf with forms is not working as expected

### ISSUE THREAD

**Issue by prigal** [Kozea/WeasyPrint#1918] opened 2023-07-20 07:02 UTC
Hello,

We expect radio buttons allow a choice between several input "type=radio" with same "name" like in an html document, but it's not working.

Actually choice is allowed between all radio input in the whole pdf. 

Example : 

```
<input name="radio1" type="radio" id="l1"> Label 1
<input name="radio1" type="radio" id="l2"> Label 2
<input name="radio2" type="radio" id="l2"> Label 3
<input name="radio2" type="radio" id="l2"> Label 4
```

This code will not allow me to select Label 1 and Label 3, I can only select 1 of 4.

**Comment by liZe** [comment] 2023-07-20 08:04
Hi!

Thanks for the bug report. It’s actually a duplicate of #1831.

**Closed by liZe** 2023-07-20 08:04 UTC
