### ISSUE TITLE
CLI tool fails to convert weasyprint.org to PDF

### ISSUE THREAD

**Issue by ciconia** [Kozea/WeasyPrint#1845] opened 2023-03-21 09:47 UTC
```
$ weasyprint https://weasyprint.org /tmp/weasyprint-website.pdf
WARNING: Ignored `background: var(--white)` at 44:3, invalid value.
WARNING: Ignored `word-break: break-all` at 65:3, unknown property.
WARNING: Ignored `text-decoration: inherit` at 77:3, invalid value.
WARNING: Ignored `background-image: linear-gradient(90deg, var(--green) 50%, var(--blue) 50%)` at 167:3, invalid value.
WARNING: Ignored `text-decoration: inherit` at 171:3, invalid value.
WARNING: Ignored `appearance: none` at 208:3, unknown property.
WARNING: Ignored `background: var(--half-gray)` at 227:3, invalid value.
WARNING: Ignored `border-right: 1px solid var(--green)` at 263:3, invalid value.
WARNING: Ignored `aspect-ratio: 1.5` at 289:3, unknown property.
WARNING: Ignored `filter: grayscale(10%)` at 354:3, unknown property.
WARNING: Ignored `background-image: linear-gradient(90deg, var(--half-gray) 50%, var(--gray) 50%)` at 385:3, invalid value.
Traceback (most recent call last):
  File "/usr/bin/weasyprint", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/weasyprint/__main__.py", line 188, in main
    html.write_pdf(output, **kwargs)
  File "/usr/lib/python3/dist-packages/weasyprint/__init__.py", line 183, in write_pdf
    self.render(
  File "/usr/lib/python3/dist-packages/weasyprint/__init__.py", line 134, in render
    return Document._render(
  File "/usr/lib/python3/dist-packages/weasyprint/document.py", line 930, in _render
    [Page(page_box) for page_box in page_boxes],
  File "/usr/lib/python3/dist-packages/weasyprint/document.py", line 930, in <listcomp>
    [Page(page_box) for page_box in page_boxes],
  File "/usr/lib/python3/dist-packages/weasyprint/layout/__init__.py", line 133, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/usr/lib/python3/dist-packages/weasyprint/layout/page.py", line 855, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/page.py", line 792, in remake_page
    page, resume_at, next_page = make_page(
  File "/usr/lib/python3/dist-packages/weasyprint/layout/page.py", line 595, in make_page
    root_box.children = tuple(out_of_flow_boxes) + root_box.children
TypeError: can only concatenate tuple (not "list") to tuple
```

My system:

```
$ uname -a
Linux nf1 6.2.5-surface #1 SMP PREEMPT_DYNAMIC Sun Mar 12 17:50:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ apt info weasyprint
Package: weasyprint
Version: 54.1-1
Priority: optional
Section: universe/text
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Python Team <team+python@tracker.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1,126 kB
Depends: libpango-1.0-0, libpangoft2-1.0-0, shared-mime-info, python3-cffi, python3-cffi-backend-api-min (<= 9729), python3-cffi-backend-api-max (>= 9729), python3-cssselect2, python3-fonttools, python3-html5lib, python3-pil, python3-pydyf, python3-pyphen, python3-tinycss2, python3:any
...
```

**Comment by grewn0uille** [comment] 2023-03-21 10:12
Hello,
This bug is a duplicate of #1575 and has been fixed in 54.2.
You can ask to Ubuntu to apply a patch on their package (the fix is two lines https://github.com/Kozea/WeasyPrint/commit/b1027ffa1582487a8efcbc9aae2f69238c1936bb) or to package 54.2.

**Closed** 2023-03-23 05:47 UTC
