### ISSUE TITLE
Line breaking simplification breaks PDF RFC generation

### ISSUE THREAD

**Issue by kitterma** [Kozea/WeasyPrint#973] opened 2019-10-18 15:19 UTC
This is a bug I'm forwarding on behalf of a Debian user:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942366

The xml2rfc program uses WeasyPrint to generate PDF versions of IETF RFCs.  Up to WeasyPrint version 49, it worked.  In version 50, it does not.  I bisected the code and it starts failing after the line breaking redesign commit (f1b1d140e258b3cba51a9fcbb91c5f688641a30f).

There is an attachment in the Debian bug that shows the exact error.  It also gives instructions on replicating the bug which worked for me.

I don't believe this was meant to be an API breaking change, so I think it's reasonably something that should be addressed in WeasyPrint.

Scott K

**Comment by kitterma** [comment] 2019-10-18 16:34
Forgot to mention, in case it matters, this is with python3.7.

**Comment by levkowetz** [comment] 2019-10-18 16:35
The xml provided in the original bug report won't be helpful in tracking down the bug.  I'm providing the HTML and 2 css snippets that are handed to WeasyPrint as a result of that XML:

https://tools.ietf.org/src/xml2rfc/issue/weasyprint/973/sample.html
https://tools.ietf.org/src/xml2rfc/issue/weasyprint/973/sample_1.css
https://tools.ietf.org/src/xml2rfc/issue/weasyprint/973/sample_2.css

Best regards,
    Henrik

**Comment by Tontyna** [comment] 2019-10-19 09:03
@levkowetz -- feeding the html and css to my WeasyPrint v50 renders without problem. Using v49 I see no difference in the PDFs. 

So what's the actual error? Could you provide WeasyPrint's stack trace? Since you mention f1b1d14 I guess it's a crash with an `IndexError` or `AssertionError` and a duplicate of #953.

**Comment by kitterma** [comment] 2019-10-19 15:30
Here's the stack trace from the original bug reporter.  I was able to replicate this (using his xml and xml2rfc):

Traceback (most recent call last):
  File "/usr/bin/xml2rfc", line 11, in <module>
    load_entry_point('xml2rfc==2.32.0', 'console_scripts', 'xml2rfc')()
  File "/usr/lib/python3/dist-packages/xml2rfc/run.py", line 615, in main
    writer.write(filename)
  File "/usr/lib/python3/dist-packages/xml2rfc/writers/pdf.py", line 100, in write
    pdf = self.pdf()
  File "/usr/lib/python3/dist-packages/xml2rfc/writers/pdf.py", line 89, in pdf
    pdf = writer.write_pdf(None, stylesheets=[ css, page_css ])
  File "/usr/lib/python3/dist-packages/weasyprint/__init__.py", line 211, in write_pdf
    font_config=font_config).write_pdf(
  File "/usr/lib/python3/dist-packages/weasyprint/__init__.py", line 168, in render
    font_config)
  File "/usr/lib/python3/dist-packages/weasyprint/document.py", line 393, in _render
    [Page(page_box, enable_hinting) for page_box in page_boxes],
  File "/usr/lib/python3/dist-packages/weasyprint/document.py", line 393, in <listcomp>
    [Page(page_box, enable_hinting) for page_box in page_boxes],
  File "/usr/lib/python3/dist-packages/weasyprint/layout/__init__.py", line 126, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/usr/lib/python3/dist-packages/weasyprint/layout/pages.py", line 803, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/pages.py", line 742, in remake_page
    page_number, page_state)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/pages.py", line 553, in make_page
    positioned_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 63, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 77, in block_level_layout_switch
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 130, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 510, in block_container_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 63, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 77, in block_level_layout_switch
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 130, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 510, in block_container_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 63, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 77, in block_level_layout_switch
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 130, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 510, in block_container_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 63, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 77, in block_level_layout_switch
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 130, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 510, in block_container_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 63, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 77, in block_level_layout_switch
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 130, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/blocks.py", line 376, in block_container_layout
    for line, resume_at in lines_iterator:
  File "/usr/lib/python3/dist-packages/weasyprint/layout/inlines.py", line 53, in iter_line_boxes
    absolute_boxes, fixed_boxes, first_letter_style)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/inlines.py", line 70, in get_next_linebox
    skip_stack = skip_first_whitespace(linebox, skip_stack)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/inlines.py", line 210, in skip_first_whitespace
    result = skip_first_whitespace(box.children[index], next_skip_stack)
  File "/usr/lib/python3/dist-packages/weasyprint/layout/inlines.py", line 196, in skip_first_whitespace
    assert next_skip_stack is None
AssertionError
make: *** [Makefile:18: draft-deremin-test.pdf] Error 1

**Comment by kitterma** [comment] 2019-10-19 15:44
Looks like you are correct.  I can also confirm that with the changes from https://github.com/Kozea/WeasyPrint/pull/956 the problem does not happen anymore.

**Comment by Tontyna** [comment] 2019-10-19 16:05
So I'd say: Status == waiting for @liZe to merge #956

**Comment by liZe** [comment] 2019-10-22 08:27
> So I'd say: Status == waiting for @liZe to merge #956

I'm sorry, I'm late! I currently spend most of my spare time organizing PyConFr, I hope that I'll find the time soon to look at the looooong list of issues in my todo list.

**Comment by Tontyna** [comment] 2019-10-22 09:15
No worries -- WeasyPrint will survive without bug fixes until 3rd of November. All the best for PyConFr!

**Comment by liZe** [comment] 2019-11-07 13:11
Fixed by #956, thanks @Tontyna :heart_eyes_cat:.

**Closed by liZe** 2019-11-07 13:11 UTC
