### ISSUE TITLE
Page references

### ISSUE THREAD

**Issue by trans** [Kozea/WeasyPrint#218] opened 2014-09-11 00:31 UTC
Is there any way to insert page references so that the page number is given? e.g. 

```
    <a id="foo">

    ... blah blah blah some pages later ...

    See <page-number ref="foo" />.
```

So it will replace `<page-number ref="#foo" />` with the page number that `<a id="foo">` is on.

**Comment by liZe** [comment] 2015-08-14 12:03
@trans can we close this issue as a duplicate of #23?

**Closed** 2016-02-20 21:51 UTC
