### ISSUE TITLE
Crash on boxes padding

### ISSUE THREAD

**Issue by lutostag** [Kozea/WeasyPrint#369] opened 2016-10-11 14:56 UTC
Ran into this traceback: WeasyPrint==0.31

Will try to get a small sample that does this for you. (seems to only happen when position: fixed, for a header, with relative it does not crash)

Happens when height: auto

```
  23.     pdf_file = HTML(string=html, base_url=base_url).write_pdf()
File "/usr/local/lib/python3.5/dist-packages/weasyprint/__init__.py" in write_pdf
  167.         return self.render(stylesheets).write_pdf(target, zoom, attachments)
File "/usr/local/lib/python3.5/dist-packages/weasyprint/__init__.py" in render
  135.         return Document._render(self, stylesheets, enable_hinting)
File "/usr/local/lib/python3.5/dist-packages/weasyprint/document.py" in _render
  327.         return cls([Page(p, enable_hinting) for p in page_boxes],
File "/usr/local/lib/python3.5/dist-packages/weasyprint/document.py" in <listcomp>
  327.         return cls([Page(p, enable_hinting) for p in page_boxes],
File "/usr/local/lib/python3.5/dist-packages/weasyprint/layout/__init__.py" in layout_document
  64.         layout_backgrounds(page, get_image_from_uri)
File "/usr/local/lib/python3.5/dist-packages/weasyprint/layout/backgrounds.py" in layout_backgrounds
  251.     layout_box_backgrounds(page, page, get_image_from_uri)
File "/usr/local/lib/python3.5/dist-packages/weasyprint/layout/backgrounds.py" in layout_box_backgrounds
  59.         layout_box_baon3.5/dist-packages/weasyprint/layout/backgrounds.py" in layout_box_backgrounds
  59.         layout_box_backgrounds(page, child, get_image_from_uri)
File "/usr/local/lib/python3.5/dist-packages/weasyprint/layout/backgrounds.py" in layout_box_backgrounds
  56.     resolve_radii_percentages(box)
File "/usr/local/lib/python3.5/dist-packages/weasyprint/layout/percentages.py" in resolve_radii_percentages
  125.         ry = _percentage(ry, box.border_height())
File "/usr/local/lib/python3.5/dist-packages/weasyprint/formatting_structure/boxes.py" in border_height
  146.         return self.padding_height() + self.border_top_width + \
File "/usr/local/lib/python3.5/dist-packages/weasyprint/formatting_structure/boxes.py" in padding_height
  137.         return self.height + self.padding_top + self.padding_bottom

Exception Type: TypeError at /pdf
Exception Value: Can't convert 'int' object to str implicitlyckgrounds(page, child, get_image_from_uri)
File "/usr/local/lib/python3.5/dist-packages/weasyprint/layout/backgrounds.py" in layout_box_backgrounds
  59.         layout_box_backgrounds(page, child, get_image_from_uri)
File "/usr/local/lib/pyth
```

Thanks!

**Comment by liZe** [comment] 2016-10-18 00:42
> Will try to get a small sample that does this for you.

Did you find the time to have a small example?

**Comment by liZe** [comment] 2016-10-25 16:30
@lutostag ping?

**Comment by liZe** [comment] 2016-10-28 10:17
@lutostag I've tried to write an example, but I can't reproduce. There's also a problem with your stacktrace, it's a bit hard to know what's the problem exactly. If you could just send your HTML/CSS sample, that would be really helpful :smile:.

**Comment by liZe** [comment] 2016-10-28 10:26
OK, I've finally found it! It's a duplicate of #171.

**Closed by liZe** 2016-10-28 10:26 UTC
Labels: bug
