### ISSUE TITLE
Issue with rendering tags within a <p> tag for Arabic language

### ISSUE THREAD

**Issue by mohdnajdy** [Kozea/WeasyPrint#868] opened 2019-05-17 07:49 UTC
Hello 

I wanted to report a rendering issue at least this is how i think it is.
i ran the tool python -m weasyprint.tools.renderer and i did a test on an html which resulted in the next image:

![issue_with_using_mark_within_p_tag](https://user-images.githubusercontent.com/15247545/57911735-3964a900-7891-11e9-8977-573a888700d3.png)

then i did this in normal html file and browse in the chrome browser and here what i got.
![correct](https://user-images.githubusercontent.com/15247545/57911764-526d5a00-7891-11e9-903a-917cf9ff7a1f.png)

keep in mind second one is what i want and how it should be.

Is there something wrong i did or is there other way to do what i want.?

secondly: I want to contribute to fixing such issues but i am not sure how

**Comment by mohdnajdy** [comment] 2019-05-17 07:51
@Kozea your input on this is appreciated

**Comment by mohdnajdy** [comment] 2019-05-17 07:51
@liZe your input in this is appreciated

**Comment by randomstuff** [comment] 2019-05-17 19:51
@mohdnajdy, Could you give the HTML source ?

**Comment by mohdnajdy** [comment] 2019-05-18 07:30
@randomstuff Here is the HTML
```
<html>
<head>
<style>
body { margin: 1em 2em }
h1 { text-decoration : underline }
div { border: 10px solid; background: #ddd }
p { text-align:right;}
</style>
</head>
<body>
<h1>Weasyprint testing</h1>

<p>
<mark>السلام عليكم ورحمة الله وبركاته</mark>السلام عليكم ورحمة الله وبركاته السلام عليكم ورحمة الله وبركاته السلام عليكم ورحمة الله وبركاته السلام عليكم ورحمة الله وبركاته السلام عليكم ورحمة الله وبركاته السلام عليكم ورحمة الله وبركاته السلام عليكم ورحمة الله وبركاته
</p>
</body>
</html>
```

**Comment by mohdnajdy** [comment] 2019-05-22 14:01
@randomstuff what do you think is the issue ?

**Comment by randomstuff** [comment] 2019-05-23 18:48
@mohdnajdy, I guess this is related to the numerous " # TODO: handle rtl" comments (and similar). I currently don't really understand how mixed LTT/RTLcontent is supposed to work so…

**Comment by liZe** [comment] 2019-05-23 20:57
> I guess this is related to the numerous " # TODO: handle rtl" comments (and similar). I currently don't really understand how LTR/RTL is supposed to work (eg. interaction bewteen `dir` and the Unicode related bits) so…

It is. Unfortunately, there's no simple way to handle RTL and bidi. It's definitely possible but requires a lot of work. Pango can handle really simple cases, but as soon as you've got nested tags or layouts different from the normal flow, WeasyPrint often doesn't do what's needed.

This issue is one more duplicate of #106. I close this issue, but it's still referenced in the original issue.

**Closed by liZe** 2019-05-23 20:57 UTC
