### ISSUE TITLE
font-variant-ligatures doesn't appear to be working with a custom font

### ISSUE THREAD

**Issue by Davide-Cocchiara** [Kozea/WeasyPrint#928] opened 2019-08-27 20:03 UTC
While utilizing the font  "CMU Concrete Roman" , I can't seem to be able to disable ligatures by setting font-variant-ligatures to none. This appears to be working on the browser, but not on WeasyPrint. This becomes apparent in combinations such as "ff" and "fl" which give me problems, inexplicably appearing bold on the browser and on KDP, but not on the output PDF when font ligatures are present.

**Comment by liZe** [comment] 2019-09-03 10:11
Hello!

Could you please provide an HTML sample and screenshots of what you get (in WeasyPrint) and what you expect (in your browser for example)? That would be easier for me to fully understand your problem.

It seems to work for me:
```html
<link rel="stylesheet" href="https://fontlibrary.org/face/cmu-concrete" type="text/css"/>
<style>
  body {
    font-family: CMUConcreteRoman;
  }
  .with-liga {
    font-variant-ligatures: common-ligatures;
  }
  .without-liga {
    font-variant-ligatures: no-common-ligatures;
  }
</style>
<body>
  <div>
    <h1>Default</h1>
    Affinity.
    A flower
  </div>
  <div class="with-liga">
    <h1>With</h1>
    Affinity.
    A flower
  </div>
  <div class="without-liga">
    <h1>Without</h1>
    Affinity.
    A flower
  </div>
</body>
```
![Capture d’écran de 2019-09-03 12-10-32](https://user-images.githubusercontent.com/952243/64164651-dd279400-ce43-11e9-974b-4d3086ac98a3.png)

**Comment by liZe** [comment] 2019-09-10 08:42
@Davide-Cocchiara Did you find a solution?

**Comment by Davide-Cocchiara** [comment] 2019-09-10 11:47
@liZe Thank you for answering and sorry for not answering earlier; Was busy publishing a book ;D

**Comment by liZe** [comment] 2019-09-10 12:04
> Was busy publishing a book ;D

:smile:

> I could send it to you, if you want.

Yes, I'd like to know what's wrong.

> I "fixed" it by removing font ligatures from the font itself.

Violent solutions are sometimes the easiest ones :hammer:.

**Comment by Davide-Cocchiara** [comment] 2019-09-10 12:30
@liZe Sent you a mail at guillaume.ayoub@kozea.fr with the necessary files.

**Comment by liZe** [comment] 2019-09-11 10:14
@Davide-Cocchiara That's strange, ligatures are in your document, but they're not in mine. Do you know the version of Pango you're using?

(And I didn't know SCP, what an amazing project…)

**Comment by Davide-Cocchiara** [comment] 2019-09-11 14:40
@liZe I'm using the following runtime of GTK on windows: https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/commit/257df8f277f47f848636ee764fa0b3aded978c64?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

So the version was and still is in the latest release, 1.43.0
Pangomm appears to have been updated, so I don't know about that.

**Comment by liZe** [comment] 2019-09-11 15:43
> So the version was and still is in the latest release, 1.43.0

Then it's not related.

Tests about ligatures are launched on Windows and seem to work, so I'm not sure that it's related to the OS. @Tontyna could you please try my snippet above and see if you get the same result :innocent:.

**Comment by Tontyna** [comment] 2019-09-11 18:54
Sure. I would say it's the same result:
![ligature](https://user-images.githubusercontent.com/35614937/64725368-bd900b80-d4d4-11e9-951f-242e2a395841.png)

**Comment by Davide-Cocchiara** [comment] 2019-09-11 20:24
I'd like to point again that the example you provided does indeed work even on my system. The problem exists only on the document I sent liZe by mail.

**Comment by Tontyna** [comment] 2019-09-11 21:45
So

1. @liZe's snippet works for everybody. 
2. @Davide-Cocchiara has a document where only tweaking the font removes the ligatures
3. When @liZe renders the same document  (same html, same css, same font, same WeasyPrint, same GTK version) everything is ok, no need to tweak the font.

Mystery. Guru Meditation required.

When such phenomenons occur to me -- after cursing and banging my head etc. pp. -- I regularely enventually detect that an assumption I made (about same conditions in my test cases) was wrong.

**Comment by knixeur** [comment] 2019-11-26 17:06
Maybe related to #998

**Comment by liZe** [comment] 2019-12-15 14:10
> Maybe related to #998

@Davide-Cocchiara Could you try the current master branch and see if the problem is fixed by #998?

**Comment by Davide-Cocchiara** [comment] 2020-04-07 10:36
It appears to be working now! I must also note that I changed my Python setup a bit, so it might have been running an older version without me knowing. I find it however improbable.
Thanks!

**Comment by liZe** [comment] 2020-04-07 11:11
> It appears to be working now!

:smile:

> I must also note that I changed my Python setup a bit, so it might have been running an older version without me knowing. I find it however improbable.

It might also be another version of Pango, who knows…

> PS: Took me a while to reply back, but hey, better late than never!

No problem, thank you!

**Closed by liZe** 2020-04-07 11:11 UTC
Labels: bug
