### ISSUE TITLE
Text encoding issue on OSX

### ISSUE THREAD

**Issue by mikhuang** [Kozea/WeasyPrint#95] opened 2013-05-25 07:35 UTC
Hello again,

The PDFs I print are visually great, however when I try to copy and paste text, I end up with unknown characters, e.g. `���������������������������� ����������������` when I copied `WeasyPrint converts HTML/CSS documents to PDF` after PDFing the WeasyPrint site. It also breaks searching the PDF. Any ideas why this might be happening? I'm using both Preview and Adobe Acrobat to view. Thanks!

WeasyPrint==0.19.1
cairocffi==0.4.3
lxml==3.1beta1

**Comment by krautnerds** [comment] 2015-01-12 19:02
I'm experiencing the same issue for all text in OSX with version 0.23 of weasyprint.
Is there already some progress in Pango? Is there an issue on the Pango website where I can read about the progress or also contribute?

**Comment by SimonSapin** [comment] 2015-01-12 23:06
@krautnerds I’ve recommended that this issue be reported upstream to Pango, but I don’t know if anyone did. The best you can do is probably report it yourself (and if it’s duplicate someone will tell you then.)

**Comment by behdad** [comment] 2015-01-13 18:10
Can you produce a simpler test using pangocairo Python bindings?  Then file a bug against pango with the script and produced PDF.

Test with latest Pango and cairo please.  Thanks.

**Comment by krautnerds** [comment] 2015-01-14 10:23
@SimonSapin Is it possible for you to create the script requestet by @behdad? I don't have experience with pango...
I can file it in the mailing list / bug tracker for you afterwards.

@behdad: Should it be filed in the mailing list or in the bug tracker?

**Comment by behdad** [comment] 2015-01-14 19:16
Filing at bugzilla.gnome.org please, product pango.

**Comment by kdeldycke** [comment] 2015-06-02 09:52
I'm also having the issue on OSX 10.10.3 with WeasyPrint dependencies installed from Homebrew.
```python
$ pip freeze
(...)
cairocffi==0.6
CairoSVG==1.0.13
cffi==1.0.0b2
cssselect==0.9.1
html5lib==1.0b6
lxml==3.4.4
pycparser==2.13
Pyphen==0.9.1
tinycss==0.3
Unidecode==0.4.17
WeasyPrint==0.23
```

**Comment by kmoore-grnds** [comment] 2016-07-23 21:25
In doing some testing it does seem to be a reproducible error with how pango is handling fonts on OSX.  I was able to recreate the issue directly w/ a simple test using `pango-view`  It does seem to be a font specific issue.  If you specify certain fonts directly you'll get a clean PDF with copyable text.

A work around seems to be using some subset of OSX fonts that convert correctly.

```
font="Helvetica"; pango-view --no-display --output out_${font}.pdf --text 'The quick brown fox jumped over the lazy dog.' --font "${font}"; open "out_${font}.pdf"

    RESULT: out_Helvetica - 􀀁􀀂􀀃􀀄􀀅􀀆􀀇􀀈􀀉􀀊􀀋􀀌􀀍􀀎􀀋􀀏􀀐􀀅􀀑􀀒􀀃􀀓􀀋􀀔􀀃􀀊􀀕􀀂􀀃􀀖􀀗􀀘􀀙􀀓􀀋􀀚􀀛

font="Verdana"; pango-view --no-display --output out_${font}.pdf --text 'The quick brown fox jumped over the lazy dog.' --font "${font}"; open "out_${font}.pdf"

    RESULT: out_Verdana - The quick brown fox jumped over the lazy dog.


font="Arial"; pango-view --no-display --output out_${font}.pdf --text 'The quick brown fox jumped over the lazy dog.' --font "${font}"; open "out_${font}.pdf"

    RESULT: out_Arial - The quick brown fox jumped over the lazy dog.


font="Arial Narrow"; pango-view --no-display --output "out_${font}.pdf" --text 'The quick brown fox jumped over the lazy dog.' --font "${font}"; open "out_${font}.pdf"

    RESULT: out_Arial Narrow - The quick brown fox jumped over the lazy dog.


font="Avenir"; pango-view --no-display --output "out_${font}.pdf" --text 'The quick brown fox jumped over the lazy dog.' --font "${font}"; open "out_${font}.pdf"

    RESULT: out_Avenir - The quick brown fox jumped over the lazy dog.

font="Batang"; pango-view --no-display --output "out_${font}.pdf" --text 'The quick brown fox jumped over the lazy dog.' --font "${font}"; open "out_${font}.pdf"

    RESULT: out_Batang - The quick brown fox jumped over the lazy dog.

font="Andale Mono"; pango-view --no-display --output "out_${font}.pdf" --text 'The quick brown fox jumped over the lazy dog.' --font "${font}"; open "out_${font}.pdf"

    RESULT: out_Andale Mono - The quick brown fox jumped over the lazy dog.

font="Courier"; pango-view --no-display --output "out_${font}.pdf" --text 'The quick brown fox jumped over the lazy dog.' --font "${font}"; open "out_${font}.pdf"

    RESULT: out_Courier - 􀀁􀀂􀀃􀀄􀀅􀀆􀀇􀀈􀀉􀀊􀀋􀀌􀀍􀀎􀀋􀀏􀀐􀀅􀀑􀀒􀀃􀀓􀀋􀀔􀀃􀀊􀀕􀀂􀀃􀀖􀀗􀀘􀀙􀀓􀀋􀀚􀀛
```

**Comment by behdad** [comment] 2016-07-24 01:11
Ok that's good info.  I think I know what's going on, or at least can debug now.  Continuing here: https://bugzilla.gnome.org/show_bug.cgi?id=769122

**Comment by liZe** [comment] 2019-01-24 17:14
Closing, as it's not our bug anymore. Please visit https://gitlab.gnome.org/GNOME/pango/issues/260 to comment on this issue.

**Closed by liZe** 2019-01-24 17:14 UTC
Labels: bug
