### ISSUE TITLE
Long elements getting pushed to next page when using top & bottom margin and font

### ISSUE THREAD

**Issue by vollkorn1982** [Kozea/WeasyPrint#860] opened 2019-05-06 21:34 UTC
I built a letter template which works fine on weasyprint 45, but breaks on versions 46 and 47. The reduced, minimal example is this HTML file:

```
<!DOCTYPE html>
<head>
    <style>
	@page {
		margin-bottom: 40mm;
		margin-top: 20mm;
	}

	.content {
		margin-top: 78.46mm;
	}

	.content pre {
		font-size: 8pt;
	}
    </style>
</head>

<body>
    <div>
		<div class="content">
            <p>
                A short paragraph
            </p>

            <pre>
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
			very long wall of text
            </pre>
        </div>
    </div>
</body>
</html>
```

With weasyprint 45 ([test_45.pdf](https://github.com/Kozea/WeasyPrint/files/3149913/test_45.pdf)) it looks as I expect it and a page break splits the very long wall of text on page 1 and 2. But on weasyprint 46 ([test_46.pdf](https://github.com/Kozea/WeasyPrint/files/3149914/test_46.pdf)) and 47 ([test_47.pdf](https://github.com/Kozea/WeasyPrint/files/3149915/test_47.pdf)) this does not happen.

If I remove just any of the `margin-*` or `font` elements, the paragraph is again being split as expected.

**Comment by liZe** [comment] 2019-05-15 10:11
Believe it or not, it's actually a duplicate of #851.

**Closed by liZe** 2019-05-15 10:11 UTC
