### ISSUE TITLE
Problem rendering fonts with Katex

### ISSUE THREAD

**Issue by davdmc** [Kozea/WeasyPrint#1215] opened 2020-09-17 11:05 UTC
I tried quite hard to find the solution to this problem somewhere else but I couldn't. I'm working on Windows. I'm converting the following text:

    Hello: $`x`$

to PDF and this is my result:

![image](https://user-images.githubusercontent.com/51912226/93462422-98538b80-f8e6-11ea-840e-9ad307cbed1f.png)

If I save the resulting html from Python Markdown and open it as a html file, it renders correctly. The following code is my configuration for Python Markdown:

```python
        html = markdown.markdown(text, extensions=['markdown_katex', ], extension_configs={
            'markdown_katex': {
                'no_inline_svg': True,      # fix for WeasyPrint
                'insert_fonts_css': True,
            },
        })
        HTML(string=html).write_pdf(self.exportPath)
```

I wonder if I'm missing something. I tried to get the PDF using both the CDN provided by Katex and downloading the CSS and adding a font configuration in the python code.

Here is the result when trying to convert from the saved html file (renders correctly) to pdf using WeasyPrint console command in verbose mode:

```
INFO: Step 1 - Fetching and parsing HTML - filename.html
INFO: Step 2 - Fetching and parsing CSS - https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css
WARNING: Ignored `text-rendering:auto` at 1:4793, unknown property.
WARNING: Ignored `width:min-content` at 1:5147, invalid value.
WARNING: Ignored `display:-ms-inline-flexbox` at 1:6812, invalid value.
WARNING: Ignored `fill:currentColor` at 1:20842, unknown property.
WARNING: Ignored `stroke:currentColor` at 1:20860, unknown property.
WARNING: Ignored `fill-rule:nonzero` at 1:20880, unknown property.
WARNING: Ignored `fill-opacity:1` at 1:20898, unknown property.
WARNING: Ignored `stroke-width:1` at 1:20913, unknown property.
WARNING: Ignored `stroke-linecap:butt` at 1:20928, unknown property.
WARNING: Ignored `stroke-linejoin:miter` at 1:20948, unknown property.
WARNING: Ignored `stroke-miterlimit:4` at 1:20970, unknown property.
WARNING: Ignored `stroke-dasharray:none` at 1:20990, unknown property.
WARNING: Ignored `stroke-dashoffset:0` at 1:21012, unknown property.
WARNING: Ignored `stroke-opacity:1` at 1:21032, unknown property.
WARNING: Ignored `stroke:none` at 1:21065, unknown property.
INFO: Step 2 - Fetching and parsing CSS - CSS string
INFO: Step 3 - Applying CSS
INFO: Step 4 - Creating formatting structure
INFO: Step 5 - Creating layout - Page 1
INFO: Step 6 - Drawing
INFO: Step 7 - Adding PDF metadata
```

There was a previous conversation with the markdown-katex creator [here](https://gitlab.com/mbarkhau/markdown-katex/-/issues/11).

**Comment by davdmc** [comment] 2020-09-17 12:14
I solved it for the local css as I made a mistake with the font storage folder. However, I would really appreciate if anyone could share any insight on how to configure the font configuration for a CDN.

**Comment by davdmc** [comment] 2020-09-18 14:41
Thanks! I will try if needed. In terms of the local fonts, if I don't add the FontConfiguration() for katex, it displays the formulas correctly with a incorrect font. If I include the font configuration for the katex CSS, the fonts are not rendered.

In Linux it works perfectly! Maybe is something related to Cairo / Pango?

**Comment by davdmc** [comment] 2020-09-22 23:34
I finally managed to render the document with the proper font. The only way I found so far is to install the fonts system-wide in the computer and delete a cached file in C:\msys64\mingw64\var\cache\fontconfig. However, I would really like to know if the only way of using fonts in Windows is through installation or I can use local fonts.

**Comment by liZe** [comment] 2020-10-21 19:32
Hello!

Thanks a lot for your bug report. This bug is actually a duplicate of #1237 (even if it’s older, life’s unfair :wink:). You can follow its resolution, and don’t hesitate to complain if it doesn’t fix your problem!

**Closed by liZe** 2020-10-21 19:32 UTC
