### ISSUE TITLE
WeasyPrint inspect dump to stderr

### ISSUE THREAD

**Issue by castedo** [Kozea/WeasyPrint#1779] opened 2022-12-20 18:37 UTC
This might be a new feature idea, or maybe one already exists. Is there a WeasyPrint rough equivalent to the Inspect functionality of modern browsers?

If not, perhaps there could be some magic backdoor HTML element attribute which triggers an Inspect-like dump to stderr of information about the styling of that HTML element?

**Comment by liZe** [comment] 2022-12-27 15:10
Hi!

Having an "inspector" would be awesome, it’s an old idea (it’s even a duplicate of #1671), but it’s not easy to even define what it would look like in a PDF file. Currently, I mainly use `inotifywait` with a PDF reader that’s able to reload the file on change, but that’s far from perfect.

What would be useful in this inspector for you, and how do you imagine it in your dreams (even if you probably don’t dream of that 😁️)? Let’s continue the discussion in #1671!

**Closed by liZe** 2022-12-27 15:10 UTC
