### ISSUE TITLE
Extra space before code in heading with 

### ISSUE THREAD

**Issue by craigpla** [Kozea/WeasyPrint#997] opened 2019-11-20 19:42 UTC
![weasyprint_space_issue](https://user-images.githubusercontent.com/45947206/69271284-90319f00-0ba2-11ea-8098-0c9134b8d28a.png)

Here's the html:
```
&gt;&gt;&gt; bool(&#39;Hello&#39;)
True</code></pre>
<h3 id="more-about-the-print-function">More About the <code>print</code> Function</h3>
<h3 id="more-about-the-print-function-1">More About the <code>print</code> Function</h3>
<ul>
<li>Taking multiple arguments
<ul>
```
When I started typing in here, I had no idea what ailed it. Turns out changing the code/pre font from Courier_New to SourceCodePro fixed it. So I don't really need an answer or a fix, but maybe it's an issue somewhere else too, that nobody's stumbled across yet.

**Comment by liZe** [comment] 2019-11-23 10:07
> When I started typing in here, I had no idea what ailed it. Turns out changing the code/pre font from Courier_New to SourceCodePro fixed it. So I don't really need an answer or a fix, but maybe it's an issue somewhere else too, that nobody's stumbled across yet.

I suppose it's a duplicate of #628, that only happens with some Microsoft fonts.

Could you please provide a small HTML+CSS sample in #628?

**Closed by liZe** 2019-11-23 10:07 UTC
