### ISSUE TITLE
Implementation of fillable forms

### ISSUE THREAD

**Issue by saileshkush95** [Kozea/WeasyPrint#1382] opened 2021-06-17 07:30 UTC
I'm trying generate fillable pdf form using this library. I'm curious weather we can able to create fillable forms using this libarary

**Comment by liZe** [comment] 2021-07-12 13:35
Hello!

It’s would be a nice feature. It’s actually a duplicate of #61, you can follow news about this feature in that issue.

**Closed by liZe** 2021-07-12 13:35 UTC
