### ISSUE TITLE
adapt to pydyf v0.11.0 to avoid TypeError: PDF.__init__() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by teese** [Kozea/WeasyPrint#2205] opened 2024-07-17 11:08 UTC
A few days ago in an update to 0.11.0, pydyf removed the version and identifier parameters from their PDF class:
Here's the commit:
https://github.com/CourtBouillon/pydyf/commit/15a4625f9f010e42b43643b55514b03823c601d2

I assume pydyf doesn't use semantic versioning, because this looks like a breaking change to me.

My current version of weasyprint (59.0) now gives an error "TypeError: PDF.__init__() takes 1 positional argument but 3 were given"

I assume this is due to line 120 of weasyprint/pdf/__init__.py, which includes both a version and identifier.
`pdf = pydyf.PDF((version or '1.7'), identifier)`

**Comment by grewn0uille** [comment] 2024-07-17 11:11
Hi,

That’s a duplicate of #2204, #2203, #2202 and #2200.

**Closed by grewn0uille** 2024-07-17 11:11 UTC
