### ISSUE TITLE
Odd line width/wrapping in PDF code blocks

### ISSUE THREAD

**Issue by mtkennerly** [Kozea/WeasyPrint#1234] opened 2020-10-13 19:40 UTC
Hello! Apologies if this is documented somewhere, but I couldn't find an answer when I did some searching.

I'm using Pandoc to convert Markdown to PDF, with WeasyPrint as the `--pdf-engine`. Everything looks good, except for the line width and wrapping in code blocks. Pandoc's intermediate HTML file looks okay, which is why I think this is something on the WeasyPrint side.

I've created a repository to show what I'm doing:

* Repo: https://github.com/mtkennerly/playground
* Markdown file: https://raw.githubusercontent.com/mtkennerly/playground/7bf98fe6b6d5fd39731a2ad6a466747dcc942453/docs/sample.md
* Pandoc invocations: https://github.com/mtkennerly/playground/blob/7bf98fe6b6d5fd39731a2ad6a466747dcc942453/.github/workflows/main.yaml#L22-L25

Here are the HTML and PDF files generated by the invocations in the GitHub workflow:

[samples.zip](https://github.com/Kozea/WeasyPrint/files/5373675/samples.zip)

How the HTML looks (what I want)

> ![image](https://user-images.githubusercontent.com/4934192/95907065-031ea800-0d69-11eb-8b9b-34c8c5d40edb.png)

How the PDF looks (*not* what I want):

> ![image](https://user-images.githubusercontent.com/4934192/95907121-13cf1e00-0d69-11eb-9672-c19ce0cc5550.png)

The PDF has a lot of unnecessary line wrapping, far before the edge of the code block. I would only want lines to wrap if they extend to the far edge of the code block.

I've also experimented with specifying some extra CSS, but it didn't seem to help, and I'm not sure why the default CSS would look okay in the HTML version but not in the PDF version anyway.

**Comment by liZe** [comment] 2020-10-13 20:32
Hi!

It’s fixed in the current `master` branch. I’m trying to find the related issue that’s already been closed.

**Comment by liZe** [comment] 2020-10-13 20:34
> I’m trying to find the related issue that’s already been closed.

It’s a duplicate of #1000.

**Closed by liZe** 2020-10-13 20:34 UTC

**Comment by mtkennerly** [comment] 2020-10-13 21:01
@liZe Thanks, using the latest code from master works much better :+1: I'm still seeing something a little odd with how very long lines wrap, though. (I can make a separate ticket if you'd like, but maybe it's already covered by another one.)

[samples2.zip](https://github.com/Kozea/WeasyPrint/files/5374051/samples2.zip)

HTML:

> ![image](https://user-images.githubusercontent.com/4934192/95915559-4f6fe500-0d75-11eb-86c6-f1f7c5f4ff48.png)

PDF:

> ![image](https://user-images.githubusercontent.com/4934192/95915460-23ecfa80-0d75-11eb-9eef-ed5504271e41.png)

The PDF does wrap it, but each line is cut off prematurely, and there are some extra blank lines after the last wrapped line.

**Comment by liZe** [comment] 2020-10-13 21:10
> I'm still seeing something a little odd with how very long lines wrap, though.

Oh, that’s odd, for sure 😒.

> (I can make a separate ticket if you'd like, but maybe it's already covered by another one.)

I’d love that!
