### ISSUE TITLE
Internal links not working in sample report

### ISSUE THREAD

**Issue by Tablel352** [Kozea/WeasyPrint#1101] opened 2020-04-18 21:16 UTC
The report sample (https://weasyprint.org/samples/report/report.pdf) has a table of contents, with clickable internal links to the different chapters. In this pdf everything works fine.

But after running weasyprint on report.html/report.css (https://github.com/Kozea/WeasyPrint/tree/gh-pages/samples/report), the links are broken in the pdf.

versions: Weasyprint 51, Ubuntu 16.04

**Comment by Tontyna** [comment] 2020-04-18 21:51
Clickable links require Cairo >= 1.15.4, Ubuntu 16.04 has probably an older Cairo version installed.

You can check that by running

```
python -m weasyprint --info
```

**Comment by liZe** [comment] 2020-04-18 23:30
> Ubuntu 16.04 has probably an older Cairo version installed.

You’re right, Ubuntu 16.04 provides Cairo 1.14.6.

**Comment by jmborer** [comment] 2020-05-01 17:30
python -m weasyprint --info does not work on Windows:
AttributeError: module 'os' has no attribute 'uname'

How can I find out which version of Cairo is installed? Thelinks don't work as well with the example.

**Comment by Tontyna** [comment] 2020-05-01 20:34
> python -m weasyprint --info does not work on Windows

Will work in the next WeasyPrint version. Until then:

```
python -c "import cairocffi; print(cairocffi.cairo_version())"
```

**Comment by liZe** [comment] 2020-05-12 14:03
Closing, as it’s probably caused by an old version of Cairo.

**Closed** 2020-05-12 14:03 UTC

**Comment by Dashrath158** [comment] 2024-06-17 04:57
I just installed weasyprint to create pdfs of some reports, it is a flask app and we use jinja2 templates. So in table of contents i wanted the contents to be clickable and go to the ids that i hypelinked but when i convert the pdf the llinks dont work they just end with an error "Your file couldn’t be accessedIt may have been moved, edited, or deleted. Can someone help?
ERR_FILE_NOT_FOUND" 

**python -m weasyprint --info**
  System: Linux
  Machine: x86_64
  Version: #1 SMP Thu Jan 11 04:09:03 UTC 2024
  Release: 5.15.146.1-microsoft-standard-WSL2
  
  WeasyPrint version: 61.2
  Python version: 3.8.10
  Pydyf version: 0.10.0
  Pango version: 14407

**Comment by liZe** [comment] 2024-06-17 07:11
> "Your file couldn’t be accessedIt may have been moved, edited, or deleted
> ERR_FILE_NOT_FOUND"

It’s not a problem in WeasyPrint. Your link points to a path to a file that doesn’t exist. Maybe you used the whole URL instead of an anchor?

> also there is no cairo version shown in the command output.

WeasyPrint doesn’t use Cairo anymore, that’s why.

If your problem is not solved by using anchors instead of whole URLs, please open a new issue with a HTML sample (not a jinja template) to reproduce your problem.
