### ISSUE TITLE
ModuleNotFoundError: No module named 'weasyprint.fonts'

### ISSUE THREAD

**Issue by rafaelrdealmeida** [Kozea/WeasyPrint#1426] opened 2021-08-23 15:36 UTC
I'm trying to use the `weasyprint.fonts` with no success, can anyone tell me where I'm going wrong?

![Captura de tela de 2021-08-23 12-34-41](https://user-images.githubusercontent.com/18035347/130475583-fc64c7b9-aef2-4639-a1f7-acc23c5a03c4.png)
![Captura de tela de 2021-08-23 12-33-26](https://user-images.githubusercontent.com/18035347/130475586-0ece0057-3a43-4a09-b845-382a35bc8131.png)

**Comment by grewn0uille** [comment] 2021-08-23 15:40
Hello!
The import has changed since v53. Now it’s `from weasyprint.text.fonts import FontConfiguration`.

Duplicate of #1419.

**Closed by grewn0uille** 2021-08-23 15:40 UTC

**Comment by AhmadAbdallah13** [comment] 2022-10-24 10:59
Hello, @grewn0uille.
the latest version of pango in poetry is 0.7.6. How can I work around this as downgrading weasyprint is not a choice since there is a bug in version 52.5 that is solved in version 55.0.

**Comment by grewn0uille** [comment] 2022-10-24 11:16
Hello @AhmadAbdallah13,
It’s [this pango](https://pango.gnome.org/) and not the python package with the same name.
You can install it with the package manager of your distribution, don’t hesitate to look at the [documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation) :)

**Comment by AhmadAbdallah13** [comment] 2022-10-24 11:52
@grewn0uille thank you for the prompt response. will check it out.
