### ISSUE TITLE
pdf rendering: first bullet point at wrong position

### ISSUE THREAD

**Issue by slartibart70** [Kozea/WeasyPrint#1529] opened 2021-12-26 15:10 UTC
Hi,
i'm rendering a pdf coming from pandoc with WeasyPrint version 53.4
On any pdf page, if the first item/line is a bulleted item, the bullet point is moved to a wrong position.

Please see the attached screenshots, for the html output in chrome, and pdf output 

html-rendering:
![html](https://user-images.githubusercontent.com/10506408/147412231-8371ca21-00b1-4a18-bab5-d363572ebccf.png)

pdf-rendering
![pdf](https://user-images.githubusercontent.com/10506408/147412250-15cc5c06-9e57-4b6c-8075-f768d94566be.png)

**Comment by liZe** [comment] 2021-12-26 17:33
Hello!

Thanks for the bug report. It’s actually a duplicate of #1058, we should change the issue title to indicate that it’s not only limited to ordered lists.

**Closed by liZe** 2021-12-26 17:33 UTC
