### ISSUE TITLE
Relative Div containing Absolute Divs not creating multiple pages

### ISSUE THREAD

**Issue by jeffgabhart** [Kozea/WeasyPrint#375] opened 2016-10-27 23:23 UTC
I am creating blocks that have absolute positioned data within each block. When rendered with weasyprint, I get only one page even though there is enough html for two pages.

Sample code
```

<div style="position: relative; height: 400px; border: 1px solid black; width: 100%;">
  <div style="position: absolute; top: 50px; left: 10px">Position 1</div>
  <div style="position: absolute; top: 250px; left: 30px">Position 2</div>
</div>
<div style="position: relative; height: 400px; border: 1px solid black; width: 100%;">
  <div style="position: absolute; top: 50px; left: 10px">Position 3</div>
  <div style="position: absolute; top: 250px; left: 30px">Position 4</div>
</div>
<div style="position: relative; height: 400px; border: 1px solid black; width: 100%;">
  <div style="position: absolute; top: 50px; left: 10px">Position 5</div>
  <div style="position: absolute; top: 250px; left: 30px">Position 6</div>
</div>
<div style="position: relative; height: 400px; border: 1px solid black; width: 100%;">
  <div style="position: absolute; top: 50px; left: 10px">Position 7</div>
  <div style="position: absolute; top: 250px; left: 30px">Position 8</div>
</div>

```

Sample pdf
[report.pdf](https://github.com/Kozea/WeasyPrint/files/557259/report.pdf)

**Comment by liZe** [comment] 2016-10-28 10:07
Thanks for reporting this issue! That's a subtle duplicate of the old #36.

**Closed by liZe** 2016-10-28 10:07 UTC
