### ISSUE TITLE
Fixed table heights and vertical stretching.

### ISSUE THREAD

**Issue by mikerockett** [Kozea/WeasyPrint#1144] opened 2020-06-17 12:26 UTC
Given:

```html
<table style="height:10cm">
  <thead>
  <tbody>
  <tfoot>
</table>
```

In Weasyprint, the height is honoured, however the body is not stretched to the point where the footer touches the bottom of the container.

![image](https://user-images.githubusercontent.com/4586280/84897746-68f27000-b0a6-11ea-8241-facad4e1a697.png)

In the browser (as tested in Chrome), the table grows to match the height, as expected.

![image](https://user-images.githubusercontent.com/4586280/84897768-73146e80-b0a6-11ea-8710-a871b21f149e.png)

Is there perhaps a workaround for this?

Thanks! :)

**Comment by liZe** [comment] 2021-01-16 13:45
Oh, that’s actually a duplicate of #1092.

**Closed by liZe** 2021-01-16 13:45 UTC
Labels: bug
