### ISSUE TITLE
display issue: cut off text on right with embedded svgs

### ISSUE THREAD

**Issue by lutostag** [Kozea/WeasyPrint#438] opened 2017-03-09 15:43 UTC
Rendering http://pastebin.com/VnFjqJeg the bottom right text isnt displayed. https://imgur.com/a/xFpid is the example render.

For the non-base64 encoded svg cairosvg renders it as expected with the text.

http://pastebin.com/RavWhMrp is pip freeze

**Comment by liZe** [comment] 2017-03-10 13:12
Thank you for reporting this issue!

It's a duplicate of #278. TL;DR: it's a bug in Cairo fixed in the ustable 1.15.4 version.

**Closed by liZe** 2017-03-10 13:12 UTC
