### ISSUE TITLE
Unicode is broken

### ISSUE THREAD

**Issue by wisedier** [Kozea/WeasyPrint#293] opened 2016-01-18 10:59 UTC
I tried to convert html to pdf using below python code.
```python
def html2pdf(html):
    """
    :param html: rendered jinja2 html text
    :type html: unicode
    :return: PDF bytes
    """

    html = HTML(string=html, encoding="utf-8")
    with BytesIO() as pdf_buffer:
        html.write_pdf(pdf_buffer)
        pdf_buffer.seek(0)
        pdf = pdf_buffer.getvalue()

    return pdf
```

Below html code is passed `html` into `html2pdf` function
```html
<span class="warning">본 쿠폰의 무단사용 및 불법복제 시, 법적인 제제를 받을 수 있습니다.</span>
<span class="warning">또한 한 번 발급된 쿠폰은 재발행이 불가하며 사용된 쿠폰은 재발행 및 삭제가 불가능합니다.</span>
```

Below image is a screenshot shows unicode is broken.
<img width="478" alt="2016-01-18 7 48 26" src="https://cloud.githubusercontent.com/assets/3814100/12389534/bf71919e-be1c-11e5-8db2-6c0efcc2098e.png">

I tested under __Python 2.7.11__ in __Ubuntu 14.04.3 LTS__ (3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux) and upgraded packages to the latest version. However, in OS X, it properly works. I think this problem depends on some of required packages.

**Comment by liZe** [comment] 2016-01-18 12:18
This bug report is funny on my browser:
![capture d ecran de 2016-01-18 13-13-52](https://cloud.githubusercontent.com/assets/952243/12391061/5ba6df66-bde5-11e5-8f92-de09fa812454.png)

More seriously, the problem is not Unicode, it's the font you use to render your document. On OS X, the font used (probably the default one, if you didn't set one in the stylesheet) has the requested characters, but on Ubuntu the font used to render the document is a [fallback font](https://en.wikipedia.org/wiki/Unicode_fallback_font).

You can set the font you want to use in the stylesheet, and your problem will be fixed.

**Closed by liZe** 2016-01-18 12:18 UTC

**Comment by SimonSapin** [comment] 2016-01-18 12:37
To be fair there is a bug here. When a font doesn’t have a requested character, per the CSS spec the rendering engine should [try harder](https://drafts.csswg.org/css-fonts/#font-matching-algorithm) than we do to find *some* font that has it, and only use a fallback font as a last resort.

However font selection is in the realm of Pango, so we likely can’t fix this short of rewriting all of WeasyPrint’s text and font handling to not use Pango. (Which unfortunately isn’t likely to happen any time soon.)

**Comment by plahoti** [comment] 2016-12-26 02:45
@liZe: I added a font family in my stylesheet explicitly, and still see a similar issue.

Platform: Centos release 6.8 (Final)
Software/Package versions:
Weasyprint 0.34
Pango 1.40.3 on top of cairo 1.14.8 (freetype 2.7, fontconfig 2.12.1), glib 2.38.2 and harfbuzz 1.3.4

**Comment by liZe** [comment] 2016-12-26 11:42
@plahoti Could you please provide a short sample of HTML+CSS that doesn't work for you?

**Comment by plahoti** [comment] 2016-12-26 14:32
@liZe: As it turns out, I did not have the specified font family installed in my environment. Post doing that, it worked like a charm. Apologies and thanks for your concern.

**Comment by khaledhosny** [comment] 2016-12-26 15:56
Pango should do font fallback just fine, it might be that there was no fonts with Korean support installed on the system. Either that or something is seriously broken.

**Comment by liZe** [comment] 2016-12-26 16:22
Here's the [only reliable source](https://www.freedesktop.org/wiki/Software/fontconfig/ToDo/) I've found about the links between FontConfig (used by Pango at least on UNIX-like platforms) and CSS2 font name fallback. I can't find any other information about this.
