### ISSUE TITLE
Non-breaking whitespace ahead of <a> element is ignored

### ISSUE THREAD

**Issue by timtroendle** [Kozea/WeasyPrint#1185] opened 2020-08-06 07:02 UTC
When there is a non-breaking whitespace between a word an an `<a>` element, that non-breaking whitespace is ignored.

In the following example, the first two paragraphs work as expected, but not the third. Here, the non-breaking whitespace ahead of the `<a>` element is ignored. (You may need to adapt the line length to reproduce this issue.)

```html
<html>
<head>
</head>
<body>
    <p> <!--Normal whitespace, line should break after "Figure".-->
        lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem lore
        Figure 1
    </p>
    <p> <!--Non-breaking whitespace, line should break before "Figure".-->
        lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem lore
        Figure&nbsp;1
    </p>
    <p> <!--Non-breaking whitespace, line should break before "Figure".-->
        lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem lore
        Figure&nbsp;<a href="github.com">1</a>
    </p>
</body>
</html>
```

[Resulting pdf](https://github.com/Kozea/WeasyPrint/files/5033120/test.pdf)

**Comment by liZe** [comment] 2020-08-06 14:16
Thank you for this issue. This is a duplicate of #1075, we’ll continue the discussion there.

**Closed by liZe** 2020-08-06 14:16 UTC
