### ISSUE TITLE
AssertionError: Got 'Counter-' between two lines. Expected nothing or a preserved line break

### ISSUE THREAD

**Issue by robinschoss** [Kozea/WeasyPrint#313] opened 2016-05-02 08:26 UTC
On my production server, I get the above error in this context:

> Got 'Counter-' between two lines. Expected nothing or a preserved line break
> site-packages/uwsgidecorators.py in manage_spool_request at line 60
> 
> ret = f(vars) 
> file = HTML(string=string).write_pdf()

I can NOT reproduce this on the same setup locally, despite the OS, packages, and even database being identical. Any ideas where to start debugging this?

**Comment by liZe** [comment] 2016-05-02 09:58
@robinschoss thanks for the report.

Debugging this kind of bugs is really difficult. You're right, the first step is to find a way to reproduce the bug… There are many reasons why you can't reproduce, but it's probably related to either:
- the versions of cairo, pango or harfbuzz that are different on your server and your local setups, or
- the fonts installed.

As you said that you use the same setup, I think that it's caused by the fonts. That's a very common reason why documents are not the same on different computers, and that's an almost sure reason if you didn't explicitely specified a font family in the CSS.

You can try to render another document with the same CSS on production and see which font is embedded in the generated PDF, then install this font locally, force its use in the CSS and see if you can reproduce the bug.

If it doesn't work, we'll have to find another solution!

**Comment by liZe** [comment] 2016-05-16 11:12
@robinschoss Did you find a solution to reproduce this bug?

**Comment by liZe** [comment] 2016-11-22 00:31
Probably fixed now that #389 is fixed.

**Closed by liZe** 2016-11-22 00:31 UTC
Labels: bug, crash
