### ISSUE TITLE
WaseyPrint chaged color image

### ISSUE THREAD

**Issue by iulihardt** [Kozea/WeasyPrint#852] opened 2019-04-18 13:37 UTC
Hi, 

I implemented wasyprint in my Django project, but it was change my image colors, when I render in html it work! but when use wasyprint change some imges color tones.

![image](https://user-images.githubusercontent.com/29605451/56364806-dd413300-61c5-11e9-95f7-2a74f9aec788.png)

How can I fix it?

**Comment by liZe** [comment] 2019-04-18 15:15
Could you please provide the original images and the generated PDF file?

**Comment by iulihardt** [comment] 2019-04-18 17:09
> Could you please provide the original images and the generated PDF file?

I selected other image, and it was change too.

image:
http://54.81.166.8:8080/media/variantes/madeiras/duratex/small-alta-cristallo-padrao-borgonha.jpg

.HTML without weasyPrint (to be rendering)
[html.zip](https://github.com/Kozea/WeasyPrint/files/3095414/html.zip)


PDF created by weasyprint:
[Primeiro-MoodBoard(3).pdf](https://github.com/Kozea/WeasyPrint/files/3095415/Primeiro-MoodBoard.3.pdf)


And code:

```
class Render:
    @staticmethod
    def render(path: str, params: dict, filename: str):
    
                   
        html_string = render_to_string(path, params)
        pdf = HTML(string=html_string).write_pdf()

        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment;filename=%s.pdf' % filename
        return response


class PDF(View):
    def get(self, request, *args, **kwargs):
        context = {}       
            
        moodboard = get_object_or_404(MoodBoard.objects.filter(id=self.kwargs.get("id"),
                     user=self.request.user))
        
        context['moodboard'] = moodboard
        if moodboard.titulo == None:
            name = 'moodboard'
        else:
            name = (str(moodboard.titulo)).replace(" ","-")
        
        return Render.render('produtos/moodboard_print.html', context, name)
```

if you want anything else, just say me!

**Comment by liZe** [comment] 2019-05-30 08:41
I can reproduce but I don't know where it comes from. There's probably a bug in Cairo or in GDK-Pixbuf, but it's sure it doesn't come from WeasyPrint. I'll try to create a minimal use case and let you report the bug where it belongs.

**Comment by iulihardt** [comment] 2019-05-30 13:24
Ok! 

I will read more about Cairo and GDK-Pixbuf! However for my applicantion, in that moment, I printing my DOM and save as .pdf!

Too thank u for your time and help!

**Comment by liZe** [comment] 2019-05-30 15:14
> However for my applicantion, in that moment, I printing my DOM and save as .pdf!

Converting your image in another format is enough to fix it with WeasyPrint. I don't know why the problem only happens with this image, there must be something strange with it.

**Comment by liZe** [comment] 2019-05-30 17:20
OK, it's a bug in Cairo's PDF generation backend. Generating a PNG works.

A simple workaround you can use now is to remove lines 219-220 from images.py: https://github.com/Kozea/WeasyPrint/blob/2ce03092f145e7388f4a06420afa2f1269364c90/weasyprint/images.py#L219-L220

I'll try to find exactly where the bug is in Cairo, and to report it.

**Comment by liZe** [comment] 2019-05-30 20:03
OK, I've found what's going on. This bug is a duplicate of #315. The commit in Cairo that was fixing this bug has been reverted, and you can read more about this on [Cairo's GitLab](https://gitlab.freedesktop.org/cairo/cairo/commit/bf597b89288b6271f56031d5a20bfaf59f146d4c).

There's no way I can help you with Cairo's code :unamused:. By the way, according to [Cairo's issue leading to the revert](https://gitlab.freedesktop.org/cairo/cairo/issues/156), many other PDF viewers should be able to display this image correctly.

As a workaround, you can:
- remove the two lines set above from WeasyPrint,
- install Cairo version >= 1.15.4 but <= 1.15.14,
- convert your image from CMYK to RGB,
- convert your image from CMYK to CMYK using a tool different from the ones from Adobe.

I hope you'll find a solution!

**Closed** 2019-05-30 20:03 UTC
