### ISSUE TITLE
OSError: cannot load library Help

### ISSUE THREAD

**Issue by coolyear123** [Kozea/WeasyPrint#1442] opened 2021-09-08 16:37 UTC
I've tried everything to install weasyprint on Windows and I'm trying to use it with Blabel but every time I run my code I get the error. I don't know how to fix this.

OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

**Comment by liZe** [comment] 2021-09-08 17:13
Hello!

If you’re using Python 3.8 or newer, it’s for sure a duplicate of #1435. Is that the case for you?

**Comment by coolyear123** [comment] 2021-09-08 17:34
I was using Python 3.9 but then I tried using 3.7 and I still get the same error.

**Comment by grewn0uille** [comment] 2021-09-08 17:49
Hello!
This kind of issues on Windows is often caused by unreachable libraries. This [part of the documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#missing-library) may help you.

**Comment by liZe** [comment] 2021-09-16 16:05
Feel free to reopen if needed. We’ll improve the situation in #1435 though.

**Closed by liZe** 2021-09-16 16:05 UTC
