### ISSUE TITLE
Text clipped when using text-anchor="middle"

### ISSUE THREAD

**Issue by cielecki** [Kozea/WeasyPrint#2137] opened 2024-04-26 18:53 UTC
```html
<html>
  <meta charset="utf-8" />

  <svg
    style="width: 300px; height: 300px; background-color: red"
  >
    <text
      x="50%"
      y="50%"
      stroke="blue"
      text-anchor="middle"
      stroke-width="2"
      font-size-"100"
    >
      3
    </text>
  </svg>
</html>
```

Result:
<img width="70" alt="image" src="https://github.com/Kozea/WeasyPrint/assets/101296/e760586f-8b9b-4b0c-be61-44538067454c">

**Comment by cielecki** [comment] 2024-04-26 19:43
never mind it's fixed on main

**Comment by liZe** [comment] 2024-04-26 21:35
Duplicate of #2136.

**Closed by liZe** 2024-04-26 21:35 UTC
