### ISSUE TITLE
pip install WeasyPrint issues

### ISSUE THREAD

**Issue by djangopythoner** [Kozea/WeasyPrint#1147] opened 2020-06-19 14:09 UTC
File "D:\Django Application\MainApp\env\lib\site-packages\weasyprint\__init__.py", line 440, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "D:\Django Application\MainApp\env\lib\site-packages\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values, media_queries
  File "D:\Django Application\MainApp\env\lib\site-packages\weasyprint\css\computed_values.py", line 18, in <module>
    from .. import text
  File "D:\Django Application\MainApp\env\lib\site-packages\weasyprint\text.py", line 14, in <module>
    import cairocffi as cairo
  File "D:\Django Application\MainApp\env\lib\site-packages\cairocffi\__init__.py", line 50, in <module>
    ('libcairo.so', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "D:\Django Application\MainApp\env\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
(env)

**Comment by Tontyna** [comment] 2020-06-19 16:08
Duplicate of #589, #721, #957, ...

**Comment by liZe** [comment] 2020-06-21 08:33
Hello @djangopythoner,

To fix this problem, you can follow the tips given in the issues listed above, or you can carefully apply [the rules given in the documentation](https://weasyprint.readthedocs.io/en/latest/install.html#windows). Another (easier) solution is to use WeasyPrint with [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Closed** 2020-06-21 08:33 UTC
