### ISSUE TITLE
Vertical centering using display: table-cell not working

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1404] opened 2021-07-26 08:02 UTC
Improper dimensions of the page on page 2 (latest WP from Github)

https://beta.print-css.rocks/lesson/lesson-center-vertical

**Comment by grewn0uille** [comment] 2021-07-26 08:16
Hello!
Thanks for the bug report. I think it’s a duplicate of #1092.

**Closed by grewn0uille** 2021-07-26 08:16 UTC
