### ISSUE TITLE
Non-printing characters support

### ISSUE THREAD

**Issue by mrunderline** [Kozea/WeasyPrint#1508] opened 2021-11-27 08:22 UTC
we are using weasyprint(53.0) to generate persian pdf and have problem with [thin-space](https://www.compart.com/en/unicode/U+2009) (or half-space).
here is some examples:
this one taken in webview mode:
![Screenshot from 2021-11-27 11-32-18](https://user-images.githubusercontent.com/23085360/143673735-ec410251-3789-4b56-98a6-594aac58d8c4.png)
and this one is after generating a pdf with weasyprint:
![Screenshot from 2021-11-27 11-32-24](https://user-images.githubusercontent.com/23085360/143673732-6b4a74a8-9ee8-4f6a-8332-8e8877bddbf0.png)

as you can see, the pdf result has some some problem with thin-space. I also try to change my font to solve this problem, but nothing happen. would you please help me to solve this problem?

**Comment by liZe** [comment] 2021-11-27 11:28
> would you please help me to solve this problem?

I think that the problem is caused by alignment, not by the thin-space character. Could you please share an HTML+CSS sample that causes the problem?

**Comment by mrunderline** [comment] 2021-11-27 12:42
css:
```
h2 {
  border: 1px solid #ccc;
  padding: 3mm;
}
```

html:
```
<h2>کارشناسی ارشد ناپیوسته</h2>
<h2>کارشناسی‌ارشد ناپیوسته</h2>
```

result:
![Screenshot from 2021-11-27 15-39-14](https://user-images.githubusercontent.com/23085360/143681682-3d4f2f1f-534f-4cb8-a2c0-d2fe24ce1cca.png)

**Comment by liZe** [comment] 2021-11-28 18:15
Oh, you’re right, there’s a problem because of this space. Let’s find what!

**Comment by liZe** [comment] 2021-11-28 18:49
The culprit character is not a thin space, it’s a [zero-width non-joiner](https://en.wikipedia.org/wiki/Zero-width_non-joiner). This character is a non-printing character, and there’s a bug with these characters in WeasyPrint.

**Comment by liZe** [comment] 2021-11-28 18:51
Thanks a lot for this bug report! It’s now fixed and tested.

**Closed** 2021-11-28 18:50 UTC
Labels: bug

**Comment by mrunderline** [comment] 2021-11-29 07:32
thanks a lot, i'm so eager for new version! 🤘🏻
