### ISSUE TITLE
The table in html can not show correctly in PDF file

### ISSUE THREAD

**Issue by Lucifer-ly** [Kozea/WeasyPrint#1275] opened 2020-12-20 12:14 UTC
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PDF-Download</title>

    <style type="text/css">
        table{table-layout: fixed}
        td{word-break: break-all; word-wrap: break-word; vertical-align: center}
    </style>

</head>

<body>

<h1 style="align-content: center">title</h1>
<table class="table table-bordered" border="1" align="center" bordercolor="#000000">

    <thead>
    <tr>
        <th>id</th>
        <th>protein_id</th>
        <th>sequence</th>
        <th>variant</th>
        <th>result</th>
    </tr>
    </thead>

    <tbody>
    {% for data in all_data %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ data.protein_id }}</td>
            <td style="white-space: normal" width="50%">{{ data.sequence }}</td>
            <td>{{ data.variant }}</td>
            <td>{{ data.result }}</td>
        </tr>
    {% endfor %}
    </tbody>

</table>

</body>

</html>
```

The data of sequence in my project is a long string, after transforming the website to PDF file,the long string can not wrap, and the whole content do not look like a table. Can anyone teach me how to fix it, thank you.

**Comment by liZe** [comment] 2020-12-31 22:39
Hello.

Your table doesn’t look like at table because WeasyPrint doesn’t break your cell. We don’t support `word-break` yet :/, your issue is probably a duplicate of #1153.

**Closed by liZe** 2020-12-31 22:39 UTC
