### ISSUE TITLE
small-caps is sometimes not applied to wrapped justified text

### ISSUE THREAD

**Issue by brendanhowell** [Kozea/WeasyPrint#1014] opened 2019-12-21 13:16 UTC
Text with small-caps and justification ends up with some wrapped lines with a small-caps style applied and others not. Removing the `text-align: justify` renders as expected. Here's a minimal test case (with attached PDF output):

```
<!DOCTYPE html>
<html lang="en">
  <head>
  <title>NEWS</title>
  <meta charset="utf-8">
  <style>
    body {
      font-family: "CMU Serif";
    }
    h1 {
      font-variant: small-caps;
      text-align: justify;
    }
    #testdiv {
      width: 200px;
    }
  </style>
  </head>
  <body>
    <div id="testdiv">
      <h1>All Small Caps that is long enough to wrap but some lines get SC and others just stay The Same.</h1>
      <div>This is a normal div so the content is styled as expected</div>
    </div>
  </body>
</html>
```
[capstest.pdf](https://github.com/Kozea/WeasyPrint/files/3991413/capstest.pdf)

**Comment by liZe** [comment] 2019-12-21 14:04
Thanks for reporting.

It’s a duplicate of #954, it’s fixed in current `master` branch (and in upcoming version 51).

**Closed by liZe** 2019-12-21 14:04 UTC
