### ISSUE TITLE
PDF output missing text on only certain SVGs

### ISSUE THREAD

**Issue by craigmac** [Kozea/WeasyPrint#1655] opened 2022-06-09 13:45 UTC
For some reason a mermaid.js graph with a type of graph 'TD' renders fine in Chrome/Firefox but when I convert the HTML to PDF with weasyprint using pandoc then open the PDF in Chrome, Firefox, and Adobe Acrobat Reader (DC and Pro), the text for the top-down style graphs is always missing, but the sequence graph (left-to-right style) renders fine. I've tried changing the text in the examples because there was a font-awesome specific thing there that I thought might be only rendering in HTML but not PDF because it can't be embedded/found. No luck. I've tried changing the text of the top-down graph completely (very last SVG in the attached html file), with the same result in the PDF, no text on the top-down SVGs, and _only_ the top-down ones.

Output of pandoc call `pandoc --standalone --output bugreport-bare.pdf bugreport-bare.html --pdf-engine=weasyprint`:

```text
WARNING: Ignored `text-rendering: optimizeLegibility` at 18:7, unknown property.
WARNING: Expected a media type, got '(max-width: 600px)'
WARNING: Invalid media type ' (max-width: 600px) ' the whole @media rule was ignored at 21:5.
WARNING: Ignored `overflow-x: auto` at 107:7, unknown property.
WARNING: Anchor defined twice: 'title-block-header'
```

In attempt to rule out weasyprint/pandoc conflict, I tried skipping pandoc and using weasyprint directly with
`weasyprint bugreport-bare.html bugreport-bare.pdf` which gave this output:

```text
WARNING: Ignored `text-rendering: optimizeLegibility` at 18:7, unknown property.
WARNING: Expected a media type, got '(max-width: 600px)'
WARNING: Invalid media type ' (max-width: 600px) ' the whole @media rule was ignored at 21:5.
WARNING: Ignored `overflow-x: auto` at 107:7, unknown property.
WARNING: Anchor defined twice: 'title-block-header'
```

Same WARNINGs as the pandoc call gave, so that's reassuring.  Unfortunately in the PDF output the issue remained: top-down graphs don't have their text drawn.

Is it something about that type of SVG itself that is being generated incorrectly? I'm asking here first before I go to mermaid-cli and ask there because it is currently rendering fine in browser as a link to SVG images. I've searched here and found some slightly similar issues, but I'm not using javascript or inline base64, these are just straight img links to the SVGs. Is there a process for debugging SVGs themselves that you'd recommend? Is it just that Chrome/Firefox SVG rendering is more permissive? So many questions!

I'm attaching the small HTML test page I'm using with the SVGs it needs, and the PDF with the missing text on top-down graphs.

[bugreport.zip](https://github.com/Kozea/WeasyPrint/files/8870853/bugreport.zip)

**Comment by liZe** [comment] 2022-06-09 14:05
Hi!

Thanks for this bug report. That’s actually a duplicate of #1441

**Closed by liZe** 2022-06-09 14:05 UTC

**Comment by craigmac** [comment] 2022-06-09 15:40
Seems there kind-of a workaround by disabling HTML labels, but with the caveat that it will probably break other things :/ https://github.com/mermaid-js/mermaid-cli/issues/112
