### ISSUE TITLE
font metrics sometimes throw off line positioning

### ISSUE THREAD

**Issue by rbergmair** [Kozea/WeasyPrint#931] opened 2019-08-29 18:52 UTC
I have the following HTML:
```
<!DOCTYPE html>
<html lang="en">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>A Design</title>

<style>

body, p, h1 {
  font-family: 'Prociono';
  font-size: 10pt;
  line-height: 12pt;
  text-align: justify;
  hyphens: auto;
}

@page {
  size: 148.0mm 210.0mm;
  margin-top: 12.0mm;
  margin-bottom: 21.0mm;
  margin-left: 17.0mm;
  margin-right: 17.0mm;
}

p:before {
  content: "▪ ";
}

p {
  margin: 0;
}

</style>

</head>

<body>

<h1>A Design That's Trying to be Very Clever</h1>

<p>Line 1: This is an example of a design that's trying to be very
clever and having unintended side-effects weasyprint.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Dolor sed viverra
ipsum nunc aliquet bibendum enim. In massa tempor nec feugiat.</p>
<p>Nunc aliquet bibendum enim facilisis gravida.</p>
<p>Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Amet luctus
venenatis lectus magna fringilla. Volutpat maecenas volutpat blandit aliquam
etiam erat velit scelerisque in. Egestas egestas fringilla phasellus faucibus
scelerisque eleifend. Sagittis orci a scelerisque purus semper eget duis.
Nulla pharetra diam sit amet nisl suscipit.</p>
<p>Sed adipiscing diam donec adipiscing tristique risus nec feugiat in.</p>
<p>Fusce ut placerat orci nulla. Pharetra vel turpis nunc eget lorem dolor.</p>

</body>

</html>
```

Note the box-drawing character.  There seems to be something weird about the baseline offset of that character in this particular font (Prociono) which you can get here:
https://github.com/theleagueof/prociono

Now, the intent of this file is to have every line be exactly 12pt (= 16px) high.  But this is what the placement of the lines actually looks like: The line boxes with the box drawing character are taller than the other ones.

```
 0|  0|54.288|16.000|A Design That's Trying to be Very Clever
  0|  1|79.221|16.697|▪     Line 1: This is an example of a design that's trying to be very clever
  0|  2|95.918|16.000|and having unintended side-effects weasyprint.
  0|  3|111.918|16.697|▪     Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius‐
  0|  4|128.616|16.000|mod tempor incididunt ut labore et dolore magna aliqua. Dolor sed viver‐
  0|  5|144.616|16.000|ra ipsum nunc aliquet bibendum enim. In massa tempor nec feugiat.
  0|  6|160.616|16.697|▪     Nunc aliquet bibendum enim facilisis gravida.
  0|  7|177.313|16.697|▪     Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Amet luc‐
  0|  8|194.010|16.000|tus venenatis lectus magna fringilla. Volutpat maecenas volutpat blandit
  0|  9|210.010|16.000|aliquam etiam erat velit scelerisque in. Egestas egestas fringilla phasellus
  0| 10|226.010|16.000|faucibus scelerisque eleifend. Sagittis orci a scelerisque purus semper
  0| 11|242.010|16.000|eget duis. Nulla pharetra diam sit amet nisl suscipit.
  0| 12|258.010|16.697|▪     Sed adipiscing diam donec adipiscing tristique risus nec feugiat in.
  0| 13|274.707|16.697|▪     Fusce ut placerat orci nulla. Pharetra vel turpis nunc eget lorem dolor.
```

![sample_actual](https://user-images.githubusercontent.com/14801887/63967961-d0e7b380-ca9e-11e9-84cb-7e1b511da0a9.png)

**Comment by rbergmair** [comment] 2019-08-29 19:02
I've submitted PR #932 to show you how I'm currently working around the issue for my book project.

**Comment by liZe** [comment] 2019-09-04 15:41
Hello!

> Note the box-drawing character. There seems to be something weird about the baseline offset of that character in this particular font (Prociono)

The problem is that Prociono doesn't have the square character you're using for the bullet. The bullet is rendered using another font (a fallback font) in the `::before` box whose height is 12pt (it's the line height).

The `::before` box and the text are aligned using their baselines. If Prociono's baseline and the fallback font's one are different (and they probably are), the total line height has to be increased to align the baselines.

You can see the problem in a browser too, but the results may be different as WeasyPrint and browsers usually don't use the same fallback fonts.
![Capture d’écran de 2019-09-04 17-35-12](https://user-images.githubusercontent.com/952243/64269567-628d7000-cf3a-11e9-83b4-600699534f47.png)
(That's Chrome with DejaVu for bullets and Garamond for text. There's an extra space before the lines with a bullet.)

So, that's not a bug in WeasyPrint, that's just the way the spec is :smile:.

There are many solutions to "fix" that. The easiest one is to add a `line-height: 0` property on your `::before` box. Of course, you can also change the character used for the bullet, or change the font…

**Comment by rbergmair** [comment] 2019-09-04 17:17
Thanks for the reply!  Will try that solution with `line-height: 0` on the weekend!

**Comment by rbergmair** [comment] 2019-09-07 09:12
FWIW: The solution with `line-height: 0` works for the example I posted, but not for my book-project.  It seems there are more problems intervening there that I'm not fully aware of right now and don't have the energy to try to track down, given that I already have an (albeit hacky) solution.  I guess I'll stick with using my patch.  But thanks anyway for tracking down the problem for me and everything.

**Comment by liZe** [comment] 2019-09-18 13:51
Let's close this issue, as it's probably caused by a character missing in the font. The "problem" is the same for other browsers too.

**Closed by liZe** 2019-09-18 13:51 UTC
