### ISSUE TITLE
Wrong layout around break of page

### ISSUE THREAD

**Issue by ildarworld** [Kozea/WeasyPrint#2044] opened 2024-01-19 09:39 UTC
Hello there, 

im seeing issue when printing page with table layout around page break. 
All required data for reproducing is attached. (just need to place static data somewhere and change references in HTML file)

It is working fine in version 53.4 but any more higher version has same behaviour.

![image](https://github.com/Kozea/WeasyPrint/assets/20387073/cc9376a4-1b70-495a-a48a-8af9e891a05d)

[data.zip](https://github.com/Kozea/WeasyPrint/files/13987142/data.zip)

**Comment by liZe** [comment] 2024-01-27 09:48
Hi!

Thanks for the report.

There are actually 2 different problems.

## First problem

Bottom images don’t appear at the bottom of the first page because we fixed #36. Your "item"s reach the bottom of the page (before rotation, that doesn’t affect the layout), so they are displayed on the next page. As they are absolutely positioned, they overlap the first row of the next page.

It’s easier to understand what happens when removing the rotation and `overflow: hidden` on td:

![Capture d’écran du 2024-01-27 10-30-51](https://github.com/Kozea/WeasyPrint/assets/952243/d9cface3-02c8-4a0f-94ec-aa572a67109e)

The bottom images (EAC and other logos) are below the page bottom, so they’re displayed on the next page.

You can "fix" this problem with something like
```css
.bottom-images {
  margin-top: -20mm;
  transform: translateY(20mm);
}
```

You’ll then get the images back at the bottom of the first page.

## Second problem

Items are displayed twice at the top of the second page. There’s probably a bug in WeasyPrint causing this problem, we have to investigate.

It may be caused by td’s `overflow: hidden`. Removing it seems to fix the problem (you can try to use it as a workaround until the bug is fixed.)

**Comment by ildarworld** [comment] 2024-01-27 18:24
Thanks a lot @liZe 🙂 will have a look )

**Comment by liZe** [comment] 2024-06-07 07:46
The second problem is now fixed in `main`.

**Closed by liZe** 2024-06-07 07:46 UTC
Labels: bug
