### ISSUE TITLE
"CAIRO_STATUS_NO_MEMORY" on Windows

### ISSUE THREAD

**Issue by Brachamul** [Kozea/WeasyPrint#713] opened 2018-10-20 00:07 UTC
Hi !

Using Weasyprint 0.42.3 on Windows, I'm getting the following error when calling `weasyprint.HTML(url).write_pdf`:

`("cairo returned CAIRO_STATUS_NO_MEMORY: b'out of memory'", 1)`

Strangely, this does not occur on my production environment running on my provider, even though the Weasyprint version and my Django app are exactly the same.

What could I do to troubleshoot this issue ? I've looked at the other issues, but I'm not using SVG nor @font-face.

**Comment by liZe** [comment] 2018-10-21 14:53
Hi!

`CAIRO_STATUS_NO_MEMORY` is returned by Cairo for a lot of situations, it's difficult to know what's going on with this small amount of information.

We have to find what's different between your production and your development environments. It may be libraries versions (Cairo for example). Another possibility is that your Django app is launched differently, for example with a debugger or a multi-threaded process in your development stack.

**Comment by Brachamul** [comment] 2018-10-21 15:46
Hello @liZe , thanks for your reply.

What's the best way to methodically check what could be causing the memory error ?

**Comment by liZe** [comment] 2018-10-26 16:32
> What's the best way to methodically check what could be causing the memory error ?

Two different possibilities:
1. Launch the app on your dev environment the same way you launch your app on production.
2. Compare versions of Python and libraries (at least Cairo and Pango).

**Comment by Brachamul** [comment] 2018-10-27 09:17
Thanks !
Sorry for the noob question, but what's the simplest way to know what Cairo and Pango versions I'm running ?

**Comment by Tontyna** [comment] 2018-10-27 09:56
I use the following Python snippet:

```python
from weasyprint.text import pango
from cairocffi import cairo_version_string

print('Pango:', pango.pango_version())
print('Cairo:',cairo_version_string())
```

**Comment by Brachamul** [comment] 2018-10-27 10:05
Great thank you @Tontyna.

This is my dev server (the one where I get the memory error):
Pango 14201 / Cairo: 1.15.12

This is my prod server:
Pango: 13603 / Cairo: 1.13.1

Additionally, it looks like my prod server is running without threads, whereas my dev is running with threads. If I disable threads with --nothreading on manage.py runserver, instead of the NO_MEMORY error, I just get an endlessly loading page.

I'll go ahead and try to get the same versions running on both environments, but since one is Windows and the other is Unix, I'm not sure I'll be able to.

**Comment by liZe** [comment] 2018-10-30 10:20
> If I disable threads with --nothreading on manage.py runserver, instead of the NO_MEMORY error, I just get an endlessly loading page.

Do you use WeasyPrint in a web app and try to render a page of the web app?

**Comment by Franky1** [comment] 2018-10-30 13:06
_I get the same error when trying to convert a very simple markdown file to pdf:_

```
C:\WinPython\WinPython64-3.4.4.6Qt5\python-3.4.4.amd64\lib\site-packages\weasyprint\fonts.py:41: UserWarning: @font-face is currently not supported on Windows
  warnings.warn('@font-face is currently not supported on Windows')

Traceback (most recent call last):
  File "c:\Users\xxxxxxxx\Documents\Git\Python\myproject\myproject.py", line 162, in <module>
    makepdf()
  File "c:\Users\xxxxxxxx\Documents\Git\Python\myproject\myproject.py", line 81, in makepdf
    base_url=None)
  File "C:\WinPython\WinPython64-3.4.4.6Qt5\python-3.4.4.amd64\lib\site-packages\md2pdf\core.py", line 54, in md2pdf
    html.write_pdf(pdf_file_path, stylesheets=css)
  File "C:\WinPython\WinPython64-3.4.4.6Qt5\python-3.4.4.amd64\lib\site-packages\weasyprint\__init__.py", line 183, in write_pdf
    target, zoom, attachments)
  File "C:\WinPython\WinPython64-3.4.4.6Qt5\python-3.4.4.amd64\lib\site-packages\weasyprint\document.py", line 503, in write_pdf
    surface.show_page()
  File "C:\WinPython\WinPython64-3.4.4.6Qt5\python-3.4.4.amd64\lib\site-packages\cairocffi\surfaces.py", line 584, in show_page
    self._check_status()
  File "C:\WinPython\WinPython64-3.4.4.6Qt5\python-3.4.4.amd64\lib\site-packages\cairocffi\surfaces.py", line 160, in _check_status
    _check_status(cairo.cairo_surface_status(self._pointer))
  File "C:\WinPython\WinPython64-3.4.4.6Qt5\python-3.4.4.amd64\lib\site-packages\cairocffi\__init__.py", line 79, in _check_status
    raise exception(message, status)
MemoryError: ("cairo returned CAIRO_STATUS_NO_MEMORY: b'out of memory'", 1)
```

My versions are:
**Pango: 14203
Cairo: 1.15.14**

**Comment by Brachamul** [comment] 2018-10-30 13:41
> Do you use WeasyPrint in a web app and try to render a page of the web app?

Yes. The document is normally sent over email, but I also have a URL that produces the document to be downloaded, in case a user needs the document resent, or if I need to debug.

**Comment by Tontyna** [comment] 2018-10-30 14:07
Does your Windows happen to be Win 8.1?

I'm asking because recently #665 strange Cairo behavior was detected on Win8.1

**Comment by Franky1** [comment] 2018-10-30 14:10
My Windows version is **Windows 7 Enterprise 64 Bit**

**Comment by Brachamul** [comment] 2018-10-30 14:16
Running Windows 10 here.

**Comment by Tontyna** [comment] 2018-10-30 15:54
@Franky1 could you post your *simple markdown file*? Maybe I can reproduce the error an maybe find out what's going wrong?

**Comment by Franky1** [comment] 2018-10-30 16:45
Yes, but i don't think that's the problem...
I think there is a general problem with the dependencies of WeasyPrint on windows?

```markdown
# gateway-tester

Simple GUI program to perform the production test of the Gateway.

## Installation for Development

1. Install Python 3 and add to PATH
2. Install the libraries from requirements.txt with `pip install -U library`
3. Install the latest **gtk3** Runtime for Windows 64Bit from: <https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases>
4. Check if PATH is set

## Build binary

1. Install **pyinstaller** with `pip install -U pyinstaller`
2. Run script to build windows binary

## Installation of Runtime

tbd.
```

**Comment by ypapouin** [comment] 2018-11-14 15:47
Same issue using WinPython.
After reinstalling python using official installer and re-adding same packages using pip, I don't have this issue anymore.

**Comment by liZe** [comment] 2019-01-24 16:49
I'm not sure that we can do much about this.

@Brachamul @Franky1 is the problem now fixed for you?

**Comment by Brachamul** [comment] 2019-01-24 17:06
@liZe Unfortunately I moved to another solution, so I can't tell you if the issue is fixed. If it's useful to you, you can tell me and I'll try to find some time recreating my previous environment and trying to reproduce the bug.

**Comment by liZe** [comment] 2019-01-24 17:10
> If it's useful to you, you can tell me and I'll try to find some time recreating my previous environment and trying to reproduce the bug.

Thank you, but there's no need to spend some time trying to reproduce a problem other users don't have. I suppose it was caused by some dependencies, and it's probably fixed now.

If someone gets the error again, please reopen, we'll try to find a solution.

**Closed by liZe** 2019-01-24 17:10 UTC
