### ISSUE TITLE
Tiff image not supported

### ISSUE THREAD

**Issue by AMontagu** [Kozea/WeasyPrint#1154] opened 2020-07-06 09:26 UTC
Hi !

I have some issues with picture taken from samsung phone. Indeed the images are upload as JPEG but are in TIFF format.

This format is not supported by WeasyPrint (actually I think is more a problem of pixbuf compile options). 

Here is the error: Failed to load image at "URL" (Pixbuf error: Error interpreting JPEG image file (Unsupported marker type 0x03))

I read https://github.com/Kozea/WeasyPrint/issues/182 and tried USE="jpeg jpeg2k tiff" emerge -av x11-libs/gdk-pixbuf but emerge is not a know command. 

Do you have any steps to allow pixbuf supporting tiff image ? I will contnue to look and post solution If I found it.

Informations: I am on docker alpine:3.11.2

Package installed: 
```
RUN apk --update --upgrade add zlib \
    jpeg-dev \
    zlib-dev \
    freetype-dev \
    lcms2-dev \
    openjpeg-dev \
    tiff-dev \
    tk-dev \
    tcl-dev \
    bash \
    cairo \
    pango \
    gdk-pixbuf \
    py3-cffi \
    py3-pillow \
    py-lxml \
    postgresql-dev \
    python3-dev \
    libffi-dev \
    libxml2-dev \
    libxslt-dev \
    libffi-dev \
    gcc \
    musl-dev \
    libgcc \
    openssl-dev \
    curl \
    msttcorefonts-installer fontconfig
```

**Comment by AMontagu** [comment] 2020-07-06 09:49
Same error on debian:10.4 with package:

```
RUN apt install -y build-essential libpq-dev python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
```

**Comment by liZe** [comment] 2020-07-06 17:24
Hello!

Your problem is a duplicate of #1136: it’s [a bug in gdk-pixbuf](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/70) that’s been fixed but not released. We’ll have to wait for a new version of gdk-pixbuf, there’s nothing we can do here :/.

I close this bug, please follow #1136 to get news about your problem.

**Closed by liZe** 2020-07-06 17:24 UTC

**Comment by AMontagu** [comment] 2020-07-06 17:26
Sorry for the duplicate. Thought I had looked enough. 

Thank you for the answer.
