### ISSUE TITLE
Issues with text indent and multi column layout

### ISSUE THREAD

**Issue by richiedunk** [Kozea/WeasyPrint#785] opened 2019-02-01 23:32 UTC
I'm trying to create a newspaper layout with a dropped first cap. Works great when text in a div is just one column (see right in the picture) but when I add `column-count: 3;` the drop cap gets indented. Take the columns out and it's fine again.

![untitled](https://user-images.githubusercontent.com/8997917/52155119-fdf2f580-2678-11e9-93d2-badbd25bb8d6.png)

Any ideas? What additional info do you need from me? Happy to help if I can - not been involed in open source before but would love to contribute.

**Comment by liZe** [comment] 2019-03-01 12:59
Has your first letter a `float: left` attribute set? If it is, it's probably a problem between floats and columns.

**Comment by liZe** [comment] 2019-03-01 13:17
See #757 too.

**Comment by liZe** [comment] 2024-07-11 14:09
This is a duplicate of #757.

**Closed by liZe** 2024-07-11 14:09 UTC
Labels: bug
