### ISSUE TITLE
weasyprint crashes Python interpreter on import

### ISSUE THREAD

**Issue by clstaudt** [Kozea/WeasyPrint#1537] opened 2022-01-11 18:08 UTC
```
╰─ python                                                                                                                (tuttle) 
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:24:02) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import weasyprint
fish: Job 1, 'python' terminated by signal SIGSEGV (Address boundary error)
```

Environment:

macOS 11.6.2  (ARM)
Python 3.9.7
weasyprint 53.3   via conda-forge

**Comment by liZe** [comment] 2022-01-12 08:15
Hello!

It’s probably a duplicate of #1533, we can continue to discuss there.

Unfortunately, it’s hard to know what’s going on: we don’t have a Mac at home to try, and [tests pass on GitHub Actions](https://github.com/Kozea/WeasyPrint/runs/4761923963).

The best solution is probably to discuss about this problem with the developers of cffi on [this issue](https://foss.heptapod.net/pypy/cffi/-/issues/523). The next step is to find a reliable way to reproduce the bug on your computer. Don’t hesitate to ping me if I can be helpful (I’m already following cffi’s issue and get notifications when new comments are written).

**Closed by liZe** 2022-01-12 08:15 UTC
