### ISSUE TITLE
string-set / named strings in meta data

### ISSUE THREAD

**Issue by Tontyna** [Kozea/WeasyPrint#575] opened 2018-02-13 22:20 UTC
Quoting the [spec on Named Strings](https://drafts.csswg.org/css-content-3/#named-strings):

> Named strings are a convenient way to pull metadata out of the document for insertion into headers and footers. In HTML, for example, META elements contained in the document HEAD can set the value of named strings. In conjunction with attribute selectors, this can be a powerful mechanism:
> 
> ```css
> meta[author] { string-set: author attr(author); }
> head > title { string-set: title contents; }   
> ```

It's a pity that this 'powerful mechanism' isn't available in WeasyPrint.

**Reason**: 
`<head>` element's display style == 'none'. So `formatting_structures.build.element_to_box()` returns subito, doesn't create a box for it and its META children. And of course doesn't collect their `string-set`s.

Until now I thought that this behavior -- ignoring invisible elements -- was correct. But:

> The content values of named strings are assigned at the point when the content box of the element is first created (or **would have been created if the element’s display value is none**)

says the spec in [§ 2.7.2 The string() function](https://drafts.csswg.org/css-content-3/#string-function), emphasis applied by me.

This seems contraintuitive, considering the rule for counters in [CSS Lists and Counters 8.4](https://drafts.csswg.org/css-lists-3/#counters-without-boxes):

> An element that does not generate a box (for example, an element with display set to none, or a pseudo-element with content set to none) cannot set, reset, or increment a counter. The counter properties are still valid on such an element, but they must have no effect. 

I suspect they reversed that for named strings, only to make the meta-strings possible.

**No quick fix available**
because within the layout process named strings are comunicated via the `Box.string_set[]` -- but invisible elements don't create boxes....
Maybe one could somehow append the strings of invisible elements to the box of the nearest visible parent element? In the case of metas that would be `<html>` -- but there is no `Box.parent_box`.
Or somehow link the `string_set` to the *element* not to the Box -- but the Boxes don't remember their html element.
Or invent a special `class InvisibleBox(Box)`.
Or ...

BTW: The above `string-set` property for the `html > title` is ignored by WeasyPrint ("invalid value") unless we replace `content` with `contents()`.
-- that's [ISSUE 3](https://drafts.csswg.org/css-content-3/#issue-40a1e681): "Should the contents keyword be replaced with content()?"

**Comment by liZe** [comment] 2018-02-15 01:59
Thanks for the explanation! Closing, as it's a duplicate of #473 (but this great comment will be linked there).

**Closed by liZe** 2018-02-15 01:59 UTC
