### ISSUE TITLE
unexpected justification

### ISSUE THREAD

**Issue by tomek1024** [Kozea/WeasyPrint#1023] opened 2020-01-09 20:40 UTC
In very seldom cases (combination of margin values, text, text settings and fonts) weasyprint incorrectly breaks the line. I attach the source as well the result. I use manual hyphenation.

html:
```html
<!doctype html>
<html lang='pl'>
  <head>
    <meta charset="UTF-8">
    <link href='style.css' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <p><strong>LIS&shy;BETH SALAN&shy;DER</strong> &amp; Aga wyszła spod prysz&shy;nica.</p>
  </body>
</html>
```

CSS:
```css
@font-face {
  font-family: "BookmanOld";
  src: url("https://zecer.elibri.com.pl/lte/fonts/BookmanOld/BookmanOld_R.ttf");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "BookmanOld";
  src: url("https://zecer.elibri.com.pl/lte/fonts/BookmanOld/BookmanOld_RB.ttf");
  font-weight: bold;
  font-style: normal;
}


@page {
  size: 160mm 235mm;
  margin-left: 21mm;
  margin-right: 21mm;
}


html { hyphens: manual; }

body {
  margin: 0;
  font-size: 14pt;
  font-family: BookmanOld;
}

p {
  text-align: justify;
  text-indent: 7mm;
  letter-spacing: -0.02em;
}
```

[test.pdf](https://github.com/Kozea/WeasyPrint/files/4042385/test.pdf)

**Comment by liZe** [comment] 2020-01-09 23:10
Hello, and thank you for this issue.

I can’t reproduce the bug :unamused:. Could you please give the output of `weasyprint -i`?

**Comment by tomek1024** [comment] 2020-01-10 08:53
Sure:

```
System: Linux
Machine: x86_64
Version: #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019
Release: 5.0.0-37-generic

WeasyPrint version: 50
Python version: 3.6.9
Cairo version: 11510
Pango version: 14014
CairoSVG version: 2.4.2
```

**Comment by Tontyna** [comment] 2020-01-10 23:55
@liZe too bad that `weasyprint -i` fails on Windows due to the availability of [`os.uname()`](https://docs.python.org/3/library/os.html#os.uname): recent flavors of Unix.

**Comment by liZe** [comment] 2020-01-11 15:28
> @liZe too bad that `weasyprint -i` fails on Windows due to the availability of [`os.uname()`](https://docs.python.org/3/library/os.html#os.uname): recent flavors of Unix.

That’s why I should write tests for the features I add :unamused:.

**Comment by liZe** [comment] 2020-01-13 23:10
I’m pretty sure that it’s a duplicate of #1025, could you please try the current `master` branch and see if it’s fixed?

**Comment by liZe** [comment] 2020-01-13 23:11
> I’m pretty sure that it’s a duplicate of #1025

(Having line-break problems when using soft hyphens and justification, I really hope that it’s the same bug.)

**Comment by tomek1024** [comment] 2020-01-14 08:39
I'm afraid the problem still exists :( I have put the test file on-line for you convenience: https://zecer.elibri.com.pl/lte/unexpected-justification.html

**Comment by liZe** [comment] 2020-01-14 16:33
> I'm afraid the problem still exists

:cry:

> I have put the test file on-line for you convenience

Thanks, but it also works for me… I suppose that it’s a problem in older versions of Pango, I’ll try your version as soon as I can.

**Comment by liZe** [comment] 2020-01-14 16:34
> I’ll try your version as soon as I can.

I have the bug with your version of Pango. I’ll try various versions to know which one fixes the bug.

**Comment by liZe** [comment] 2020-01-14 16:36
It’s broken with 1.42.x versions too.

**Comment by tomek1024** [comment] 2020-01-14 16:41
Thank you checking. Can you give me a hint how to upgrade pango?

**Comment by liZe** [comment] 2020-01-14 16:56
It’s at least fixed with Pango 1.44.4. Older 1.44.x versions don’t compile anymore for me.

> Thank you checking. Can you give me a hint how to upgrade pango?

On Ubuntu, Pango is too old, even with the latest released version of Ubuntu. There’s [a package in the next version you can try to install](https://packages.ubuntu.com/focal/libpango-1.0-0), but I suppose that upgrading only Pango can break your system (at least your graphical interface).

If you don’t know how to get back to your version of Pango using your terminal, you shouldn’t try this.

If it’s a virtual machine or anything you can break safely, you can try. [This tutorial](https://medium.com/@george.shuklin/how-to-install-packages-from-a-newer-distribution-without-installing-unwanted-6584fa93208f) seems to be OK. You have to install the Pango package from the `focal` version on your `bionic` version (example is from `xenial`, to `trusty `).

:warning: **Please don’t do this if you don’t want to break your system.** :warning:

**Comment by tomek1024** [comment] 2020-01-14 22:16
thank you for your advice :) using a virtual machine for testing seems to be the right idea. Thank you!

**Closed** 2020-01-17 11:10 UTC

**Comment by tomek1024** [comment] 2020-09-15 15:16
@liZe - I finally have a new virtual machine:

```
> weasyprint -i

System: Linux
Machine: x86_64
Version: #49~18.04.2-Ubuntu SMP Wed Aug 26 16:29:02 UTC 2020
Release: 5.4.0-45-generic

WeasyPrint version: 50
Python version: 3.6.9
Cairo version: 11510
Pango version: 14014
CairoSVG version: 2.4.2
```
As you wrote, the line is broken correctly, although there is no hyphen at the end of line. Could you please have a  look at this?

https://zecer.elibri.com.pl/lte/unexpected-justification.html

![image](https://user-images.githubusercontent.com/25573/93229550-024d2300-f777-11ea-96b2-df8946c9ba4f.png)

**Comment by liZe** [comment] 2020-09-15 16:16
I can reproduce, but I don’t have the problem with another font. Now trying to know why…

**Comment by liZe** [comment] 2020-09-15 16:25
OK, the problem comes from a line break that shouldn’t happen. For some reason (spoiler alert: a floating point rounding error), the hyphen that was fine during the layout doesn’t doesn’t fit during the display, and the line breaks after the (invisible) soft hyphen.

@tomek1024 Could you please open a new issue with this problem?
