### ISSUE TITLE
How do preserve links in document?

### ISSUE THREAD

**Issue by Lucurus** [Kozea/WeasyPrint#1202] opened 2020-08-27 09:37 UTC
Hi,

I have a HTML string containing links that have special characters (like `#`) in them which are, when generating the pdf, replaced by the `%xx` escapes.

Is there any way to turn this feature off?

Thanks!

Example:

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>-</title>
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    .display.math{display: block; text-align: center; margin: 0.5rem auto;}
  </style>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<p><a href="example.com/#">examplelink</a></p>
</body>
</html>
```

gets generated as _example.com/%23_ in the pdf.

**Comment by Tontyna** [comment] 2020-08-27 10:03
Duplicate of #1176 
The `%23` is a feature of your PDF Viewer.

**Closed** 2020-08-27 10:10 UTC
