### ISSUE TITLE
PDFs cause memory spikes in Apache PDFBOX

### ISSUE THREAD

**Issue by thasmin** [Kozea/WeasyPrint#780] opened 2019-01-30 15:34 UTC
We're having an issue when printing PDFs with software that uses Apache PDFBox. We opened a ticket with them and they claim that there is a problem with how WeasyPrint uses transparent backgrounds. Can this be addressed in WeasyPrint?

https://issues.apache.org/jira/browse/PDFBOX-4448

**Comment by Tontyna** [comment] 2019-01-30 16:52
The PDF stuff is created by - - - Cairo :-1:

**Comment by liZe** [comment] 2019-01-30 19:49
This issue is a duplicate of #238, but we may find a workaround for the particular case of empty backgrounds.

> The PDF stuff is created by - - - Cairo

Well, it's probably WeasyPrint's fault here :wink:.

**Comment by liZe** [comment] 2019-01-30 21:40
@Tontyna You'll be happy to know that fixing this bug is made complicated because of … [a new bug in Cairo](https://gitlab.freedesktop.org/cairo/cairo/issues/357).

**Closed** 2019-01-30 21:57 UTC

**Comment by liZe** [comment] 2019-01-30 22:05
@thasmin This "bug" is now closed, as we don't draw empty patterns for empty page backgrounds anymore (see 17cd8e9).

It doesn't mean that this problem won't happen with other documents. The [bug in Java Print Services](https://blog.idrsolutions.com/2012/05/avoid-transparency-when-printing-in-java/) can happen as soon as there's a transparent layout to draw. But the bug is not in WeasyPrint anymore :wink:.

**Comment by tresf** [comment] 2019-01-31 15:56
@liZe thanks for the patch!

Before 17cd8e9:

* 😢 Apache PDFBOX takes `11` seconds, > `1GB` heap

After 17cd8e9:

* 😀 Apache PDFBOX takes `1` second, `37MB` heap

Upgraded to `master` using:

```bash
pip3 install git+git://github.com/Kozea/WeasyPrint@master
```

**Comment by thasmin** [comment] 2019-01-31 21:32
Great job finding and fixing this "bug". That was really quick. We appreciate the work.
