### ISSUE TITLE
inexplicable change of font weight

### ISSUE THREAD

**Issue by castedo** [Kozea/WeasyPrint#1778] opened 2022-12-20 13:46 UTC
STEPS:
Run weasyprint (57.1) on
[good.html.txt](https://github.com/Kozea/WeasyPrint/files/10268763/good.html.txt)
[bad.html.txt](https://github.com/Kozea/WeasyPrint/files/10268762/bad.html.txt)

GOT:
[good.pdf](https://github.com/Kozea/WeasyPrint/files/10268747/good.pdf)
[bad.pdf](https://github.com/Kozea/WeasyPrint/files/10268753/bad.pdf)

EXPECTED:
The Foo Bar title and text to be the same between the two pdf files, specifically the lighter font weight for both.

COMMENTS:
The only difference between the two HTML files is whether the anchor text has some text or is just spaces. It seems like having text in the anchor triggers the font weight style to get lost.

**Comment by liZe** [comment] 2022-12-20 14:50
Hi!

Thanks for the report.

The problem is actually caused by WeasyPrint thinking that the `font-weight: 300` and `font-weight: 400` are actually the same font. It picks either the 300 or 400 font to display both. You can see that even the "good" file is wrong because it uses the 300 font in the paragraph (it should be using the 400 one).

The font used is the first one drawn. When the link is displayed at first, it uses 400 everywhere. When the title is the first one, it uses 300.

I suspect that there’s something wrong in the way we give the font weights to FontConfig when we add `@font-face` fonts. And I really hope that it’s not a behavior of Pango that can’t be configured 🤞️.

**Comment by liZe** [comment] 2022-12-20 22:19
A fix has been added on the `fix-font-face` branch. Feel free to test!

This change looks harmless, but as explained in the commit, finding a reliable key for the fonts cache is a nightmare. Your document is broken only for certain font weights, only with `@font-face` rules (works with the same fonts installed locally). It’s hard to add related non-regression tests, and each time we change this code we can break other use cases in very subtle ways.

We’ll try this fix on other complex documents and check that everything works fine. We may include it in a 57.2 version, but waiting for 58.0 could be wiser.

**Closed** 2022-12-23 11:13 UTC
Labels: bug
