### ISSUE TITLE
Raise instead of logging a warning when resouce (eg: image, css) is not found while rendering HTML to PDF

### ISSUE THREAD

**Issue by ringeringeraja** [Kozea/WeasyPrint#1710] opened 2022-08-22 07:12 UTC
I have a situation where the rendering of the documents is critical.
So I'd like to catch "not found" exceptions in HTML files.

Reproduction steps:
- Have a HTML with broken reference to local resources (absolute path) (eg.: `<img src="/folder/non-existent.jpg" />`)
- Load it with weasyprint.HTML(string='<!DOCTYPE html>...', base_url='/tmp/example')
- Render it with render().copy().write_pdf()

It would be really nice if was there a "strict=True" parameters to be set somewhere to raise on 404s.

**Comment by liZe** [comment] 2022-08-23 20:10
Hi!

> So I'd like to catch "not found" exceptions in HTML files.

That’s currently possible by giving a custom [`URL Fetcher`](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#url-fetchers) that calls the standard URL fetcher but raises an error when there’s a 404.

Having a simpler API for that may be interesting, but as usual it’s hard to find something that is OK for everyone. You need to catch 404 errors, but what about other error messages, timeouts and unknown image formats for example? A custom URL fetcher is harder to write but lets everyone do exactly what they want.

(It’s actually a duplicate of #351, let’s continue the discussion there if needed.)

**Closed by liZe** 2022-08-23 20:10 UTC
