### ISSUE TITLE
OSError: no library called "cairo" was found cannot load library 

### ISSUE THREAD

**Issue by TropicolCoder** [Kozea/WeasyPrint#1334] opened 2021-04-09 18:05 UTC
Hi,
I am facing an issue with running weasyprint
os: windows 10 pro
os version: 64 bit - x64-based-processer
Python version: Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
IDE : Pycharm 2020.3.5 (Ran the code within the terminal of the IDE)
Output of 'WHERE libcairo-2.dll': C:\Program Files\GTK3-Runtime Win64\bin\libcairo-2.dll

also I added 'C:\Program Files\GTK3-Runtime Win64\bin' to beginning of path and I am still getting this error:

(Scripts) C:\Users\HP\PycharmProjects\MyShop>python -m weasyprint http://weasyprint.org weasyprint.pdf
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\HP\PycharmProjects\MyShop\venv\Scripts\lib\site-packages\weasyprint\__init__.py", line 440, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\Users\HP\PycharmProjects\MyShop\venv\Scripts\lib\site-packages\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values, media_queries
  File "C:\Users\HP\PycharmProjects\MyShop\venv\Scripts\lib\site-packages\weasyprint\css\computed_values.py", line 18, in <module>
    from .. import text
  File "C:\Users\HP\PycharmProjects\MyShop\venv\Scripts\lib\site-packages\weasyprint\text.py", line 14, in <module>
    import cairocffi as cairo
  File "C:\Users\HP\PycharmProjects\MyShop\venv\Scripts\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\HP\PycharmProjects\MyShop\venv\Scripts\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
cannot load library 'C:\Program Files\GTK3-Runtime Win64\bin\libcairo-2.dll': error 0x7e
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by Tontyna** [comment] 2021-04-09 18:53
Make sure that in the terminal of your IDE `C:\Program Files\GTK3-Runtime Win64\bin\` is still at the beginning of the `PATH`.

**Comment by Tontyna** [comment] 2021-04-09 18:56
Did you restart Pycharm after you added 'C:\Program Files\GTK3-Runtime Win64\bin' to the beginning of your path?

**Comment by TropicolCoder** [comment] 2021-04-09 19:10
> Make sure that in the terminal of your IDE `C:\Program Files\GTK3-Runtime Win64\bin\` is still at the beginning of the `PATH`.

Yeah, I just confirmed that.

**Comment by TropicolCoder** [comment] 2021-04-09 19:10
> Did you restart Pycharm after you added 'C:\Program Files\GTK3-Runtime Win64\bin' to the beginning of your path?

Yes I did, but I'm still getting the same error

**Comment by Tontyna** [comment] 2021-04-09 21:24
I'm not familiar with Pycharm but `error 0x7e` indicates that someone (a plugin? the shell plugin itself? the project?) already loaded one of the helper DLLs that libcairo-2.dll requires and the interfaces don't match.

**Comment by liZe** [comment] 2021-04-26 17:20
I think that it’s a duplicate of #1339, you’ll get more information there.

**Closed by liZe** 2021-04-26 17:20 UTC
