### ISSUE TITLE
Got u'Printed-' between two lines. Expected nothing or a preserved line break

### ISSUE THREAD

**Issue by kingshukb** [Kozea/WeasyPrint#417] opened 2017-01-31 14:44 UTC
This issue is similar, to #389, however i am 
getting this error while trying to create pdf from html:

from weasyprint import HTML, CSS
 HTML(string=output).write_pdf(pdf_file_name, stylesheets=[CSS(string=css_string)])

I have attached the stack-trace in detail:
[Weasy_error.txt](https://github.com/Kozea/WeasyPrint/files/742225/Weasy_error.txt)

I am using : 
WeasyPrint==0.34

Thank you for providing WeasyPrint!

**Comment by liZe** [comment] 2017-01-31 17:22
> Thank you for providing WeasyPrint!

Thank you for reporting :wink:!

Could you please provide your HTML and CSS samples?

**Comment by liZe** [comment] 2017-02-02 15:03
I think that it's been fixed by #410, could you please try the current master branch?

**Comment by liZe** [comment] 2017-02-06 11:34
No news is good news, I'm pretty sure that it's fixed now.

**Comment by jsatt** [comment] 2017-05-15 21:35
I don't think this is actually fixed. I'm getting a similar error on our production servers.

weasyprint 0.36
```python
weasyprint.HTML(string=<<string in attached file>>).write_pdf('/tmp/raw_test.pdf')
```
[html and css used](https://github.com/Kozea/WeasyPrint/files/1002553/weasysample.txt)
[traceback](https://github.com/Kozea/WeasyPrint/files/1002555/weasyerror.txt)

**Comment by liZe** [comment] 2017-06-03 13:54
It's now fixed (duplicate of #449).

**Closed** 2017-06-08 12:37 UTC
