### ISSUE TITLE
Nested <thead>

### ISSUE THREAD

**Issue by macaba** [Kozea/WeasyPrint#1162] opened 2020-07-15 15:27 UTC
I have a table with a `<thead>` and mostly ordinary rows. Some of the rows are nested tables with their own `<thead>`.

I would like page breaking and the "repeat header on page break" behavior to work for all these nested tables.

If I have valid HTML then the top level table will happily page break and repeat the header however any nested tables don't split on page breaks.

![image](https://user-images.githubusercontent.com/1031306/87563131-ca622a80-c6b6-11ea-969b-b77bc22e56ad.png)

I did find a workaround; if I have invalid HTML (I remove the `<tr><td></tr></td>` around the nested table) then it works but with small unwanted side effects for some elements after the table (obviously!). It's almost like the table page breaking algorithm is only working one level deep (it considers any `<tr>` to be unpagebreakable, including `<tr>`s that contains my large nested tables).

Is there some CSS that I can apply to make the valid HTML work?

**Comment by liZe** [comment] 2020-07-18 16:11
Hello!

This bug is a duplicate of #36: when you have nested tables, the child table can’t break because the parent cell is atomic. There’s not much you can do but avoid nested tables for now :cry:.

**Closed by liZe** 2020-07-18 16:11 UTC
