### ISSUE TITLE
Bad column width at pdf generation

### ISSUE THREAD

**Issue by fcabaud** [Kozea/WeasyPrint#1842] opened 2023-03-15 13:02 UTC
I'm using python3.7, weasyprint = "58.1" on Ubuntu 22.10.
As you see in next image, I have a column with a fixed width in my html file

![image](https://user-images.githubusercontent.com/5073643/225314856-6d5d2615-57df-419b-b53d-0d17f962e0d6.png)

when I used weasyprint, I have a non-fixed colum
![image](https://user-images.githubusercontent.com/5073643/225315676-a7bff308-6f2a-4fcb-9204-82a744269622.png)
[special_test.zip](https://github.com/Kozea/WeasyPrint/files/10980044/special_test.zip)

**Comment by fcabaud** [comment] 2023-03-15 13:03
> I'm using python3.7 on Ubuntu 22.10 with weasyprint = "58.1". As you see in next image, I have a column with a fixed width in my html file
> 
> ![image](https://user-images.githubusercontent.com/5073643/225314856-6d5d2615-57df-419b-b53d-0d17f962e0d6.png)
> 
> when I used weasyprint, I have a non-fixed colum ![image](https://user-images.githubusercontent.com/5073643/225315676-a7bff308-6f2a-4fcb-9204-82a744269622.png) [special_test.zip](https://github.com/Kozea/WeasyPrint/files/10980044/special_test.zip)

**Comment by liZe** [comment] 2023-03-15 13:12
Hi!

Thanks for the bug report. It’s actually a duplicate of #1383.

**Closed by liZe** 2023-03-15 13:12 UTC
