### ISSUE TITLE
Profile big tables

### ISSUE THREAD

**Issue by SimonSapin** [Kozea/WeasyPrint#70] opened 2013-04-04 14:50 UTC
> mop___: finally found time for the performance test :S having one large table which spreads across 100 pages consumes LOADS of memory :S filesize is still 67kb :S
> mop___: 6gb memory and counting :D

http://pastebin.com/HLVrTmxt

**Comment by liZe** [comment] 2017-07-17 17:13
I can't reproduce this issue anymore. I've tried to render a 10000-line table, it took 108 seconds on my computer with about 3GB of RAM used (between 10MB and 15MB per page). I've just used 10000 instead of 100 in the script above. The output is a 239-page, 164kB PDF.

Of course, we could be better. Firefox takes about 2s and 100MB to render the same page.

**Comment by liZe** [comment] 2017-07-17 17:50
The example provided by @si13b still fails.

**Comment by liZe** [comment] 2017-07-22 12:31
Good news:
![perf](https://user-images.githubusercontent.com/952243/28490849-703f6a54-6ee4-11e7-821d-7ab8afd6d5cf.png)

- The red line is Python 3.5 before 344cb08.
- The blue line is Python 3.6 before 344cb08.
- The black line is Python 3.6 after 344cb08.

Python 3.6 is a huge improvement thanks to [compact dicts](https://mail.python.org/pipermail/python-dev/2016-September/146327.html).

344cb08 prevents style dicts to be copied each time a box is duplicated. I have to check that it doesn't break anything with the W3C suite, it may have introduced subtle bugs but I'm pretty confident.

Oh, and I think that the "40 minutes" from the last comment were not true :wink:.

**Comment by xrmx** [comment] 2017-07-22 14:15
@liZe amazing, thanks!

**Comment by liZe** [comment] 2017-07-22 22:47
The results are very good for other documents too. I've tested the examples of #384, they're both significantly faster and less memory consuming thanks to Python 3.6 and this commit.

There's room for more improvement though (before I close this issue). Inline boxes need really more memory than block boxes, I don't really know why. That's why you get memory problems with tables: there are lots of text lines in tables (at least one per cell).

**Comment by liZe** [comment] 2017-08-03 17:19
I've done my best to both add optimizations and clean the code, and I'm really happy with the result. I've done some benchmarks with Python 3.6 on Linux, for 4 different versions:
- 0.39,
- 344cb08 (first step with important optimizations),
- 033f473 (style dicts frozen for "security" purpose, but less optimized), and
- 84bdee1 (style dicts that can be modified, but modification only happens at "secure" moments).

I had also tested 0.31 **with Python 3.5** in #384.

I'm closing this issue as the easy part has been done. If anyone is interested in even better performance, you only have to:
- freeze `StyleDict`s, as it will avoid terrible future (current?) bugs, help us keeping a simple code (see the TODO in the StyleDict class), and make them hashable; and
- deduplicate styles given by csssselect2 for elements that share the same style: each box will only carry a reference instead of a whole style copy, that will probably save a little bit time and ~75% of the memory for large documents like the exemple given here (small CSS, huge HTML).

This work can be done here for sure, but also in CSSSelect2 (if possible, it would be better).

Good luck!

(Spoiler alert: named pages coming soon may hurt this speed a little bit.)

# Large document

It's the large document given as example here, with 3000 pages of paragraphs and tables.

0.39:
- More than 30 minutes (?)
- 8944MB

344cb08:
- 450s
- 6419MB

033f473:
- 430s
- 7695MB

84bdee1:
- 385s (wow)
- 6216MB (30% less than 0.39)


# Alice Adventures in Wonderland

https://www.gutenberg.org/files/11/11-h/11-h.htm

Long document with repetitive justified text.

0.31:
- 12.5s 
- 162MB

0.39:
- 7.2s
- 143MB

344cb08:
- 6.8s
- 109MB

033f473:
- 6.3s
- 111MB

84bdee1:
- 6.2s (14% less than 0.39)
- 105MB (27% less than 0.39)

# HTML5 Specification

https://www.w3.org/TR/html5/

Long document with a lot of lists and underlined links.

0.31:
- 6.0s
- 146MB

0.39:
- 4.2s
- 137MB

344cb08:
- 4.1s
- 106MB

033f473:
- 4.0s
- 117MB

84bdee1:
- 3.8s (10% less than 0.39)
- 105MB (23% less than 0.39)

# Online Wikipedia

https://en.wikipedia.org/w/index.php?title=HTML5&printable=yes

Printable version of a Wikipedia page, not downloaded before, long left-aligned paragraphs with floats.

0.31:
- 7.9s
- 134MB

0.39:
- 7.2s
- 130MB

344cb08:
- 6.1s
- 104MB

033f473:
- 6.1s
- 108MB

84bdee1:
- 6.0s (17% less than 0.39)
- 101MB (22% less than 0.39)

**Closed by liZe** 2017-08-03 17:19 UTC
Labels: performance
