### ISSUE TITLE
Add link to local files

### ISSUE THREAD

**Issue by 0xecute** [Kozea/WeasyPrint#466] opened 2017-05-12 06:47 UTC
Hello.
I need to add links to local files (in the same directory as the PDF) so when the user click then the local file opens.
I tried to use 
` <a href="file://abc.xls">`
 but it doesn't work.
Is there any way to do this from the html? 

Thanks a lot for your work!

**Comment by liZe** [comment] 2017-06-15 05:39
It's a duplicate of #437, the feature has been added in the current git version.

**Closed by liZe** 2017-06-15 05:39 UTC
