### ISSUE TITLE
Line-height is not correcly set on Windows when multiple fonts are listed in font-family

### ISSUE THREAD

**Issue by robert-schaft-hon** [Kozea/WeasyPrint#415] opened 2017-01-27 15:10 UTC
I installed weasyprint 0.34 on windows 64 and ran the acid test.
The results were close to what is described on http://weasyprint.org/ , But additionally to the explained (and expected) opacity problems, there were some grave positioning problems:
- The topmost bar of the smiley is positioned around a "smiley-pixel" too high.
- The smiley has a connected black eyebrow
- below the eyes separates a horizontal bar of around "0.5 smiley-pixel" the smiley.

The positioning problems are the same with png and pdf.
So weasyprint 0.34 doesn't pass the acid2 test any more.
Test it yourself: 

C:\Users\rs\Downloads\weasyprint>weasyprint http://www.webstandards.org/files/acid2/test.html acid-test.png
WARNING: @font-face is currently not supported on Windows
WARNING: Invalid or unsupported selector '[class=second two]', Expected ']', got <IDENT 'two' at 14>
WARNING: Ignored `error: \}` at 90:74, unknown property.
WARNING: Ignored `m
rgin: 2em` at 93:14, unknown property.
WARNING: Ignored `width: 200` at 95:14, invalid value.
WARNING: Ignored `border: 5em solid red ! error` at 96:14, invalid value.
WARNING: Ignored `background: red pink` at 97:14, invalid value.
WARNING: Parse error at 93:29, unexpected ; token in selector
WARNING: Failed to load image at "http://www.damowmow.com/404/" (HTTPError: HTTP Error 403: Forbidden)
WARNING: Failed to load image at "data:application/x-unknown,ERROR" (Pixbuf error: Unrecognized image file format)

![acid-test](https://cloud.githubusercontent.com/assets/16668999/22375589/0ad4beee-e4ab-11e6-8c75-32541d4f51ff.png)

**Comment by liZe** [comment] 2017-01-27 16:50
Thanks for reporting this issue.

Acid2 is included in the [test suite](https://travis-ci.org/Kozea/WeasyPrint/). The test is not launched on Linux because cairo's version is too old, but it's launched on MacOS and it works. I've tried on my Linux computer and it works too.

Judging from the screenshot, here's a severe problem with fonts and I think that's why it fails for you. The line height is not calculated correctly, it's obvious when you look at the "Standards compliant?" section. I'm pretty sure that it's a duplicate of #37. There's a [bug reported on pango](https://bugzilla.gnome.org/show_bug.cgi?id=455940) that's probably related too.

**Comment by liZe** [comment] 2017-03-25 21:37
@robert-schaft-hon Any news about this issue?

**Comment by robert-schaft-hon** [comment] 2017-04-18 13:19
@liZe: It is not clear to me, what I can do. In Acid 2 test, I see no font definition with multiple fonts or any font-familiy, that I could change too ease the work for pango (or whatever).

The referenced pango bug is open since 2007.
The other referenced weasyprint bugs are also stalled.

So how could I help you? What could I test.

**Comment by liZe** [comment] 2017-04-18 14:28
@robert-schaft-hon There's a bug in Pango, the maintainer doesn't have access to a Windows machine and asks for help to debug. Maybe you can ask him how you can debug, he's really nice and will probably be happy to get some help fixing this really old issue :smile:.

**Comment by liZe** [comment] 2017-07-08 19:48
Closing, as there's nothing we can do here. Please try to help the Pango maintainer if you want to help.

**Closed by liZe** 2017-07-08 19:48 UTC
Labels: bug
