### ISSUE TITLE
box-sizing: border-box not applied for table cells

### ISSUE THREAD

**Issue by kohlerdominik** [Kozea/WeasyPrint#1169] opened 2020-07-20 16:55 UTC
Hi

I found an inconsistent behaviour between Chrome rendering an WeasyPrint:

### The Issue
In Chrome it's possible to use `box-sizing: border-box` for table cells. But in WeasyPrint, it seems that the format is not allowed.

In the following example we see this:
```
Row1: default behaviour
Row2: apply 'box-sizing: border-box'
Row3: apply 'display: inline-block; box-sizing: border-box;'
```

As we can see, in chrome, Row2 behaves as expected. However, in WeasyPrint it doesn't. It's neccessary to force another cell-type (in this case `inline-block`) to make it work.

In WeasyPrint:
![grafik](https://user-images.githubusercontent.com/18621527/87964442-87d78e00-caba-11ea-8ce4-844116e1cef2.png)

In Chrome:
![grafik](https://user-images.githubusercontent.com/18621527/87964187-244d6080-caba-11ea-82dc-7d0fae6c6209.png)

The HTML code:
```html
<html>
<body>

<style>
td {
  width: 30mm;
  padding-left: 15mm;
  padding-right: 15mm;
  height: 10mm;
  background-color: red;
  margin: 0;
}

#row1 {
  // default
}

#row2 {
  box-sizing: border-box;
}

#row3 {
  display: inline-block;
  box-sizing: border-box;
}
</style>

<table>

  <tr>
    <td id="row1"></td><td id="row1"></td><td id="row1"></td>
  </tr>
  
</table>

<table>
  <tr>
    <td id="row2"></td><td id="row2"></td><td id="row2"></td>
  </tr>
</table>
   
<table>
  <tr>
    <td id="row3"></td><td id="row3"></td><td id="row3"></td>

  </tr>
</table>

</body>
</html>

```

### Expected Behaviour
WeasyPrint should allow box-sizing on table-cells too, without forcing another box type.

**Comment by liZe** [comment] 2020-07-20 18:42
Hello and thank you for this report!

I think that it’s a duplicate of #226. Closing, this example will be listed in the original bug report.

**Closed by liZe** 2020-07-20 18:42 UTC
