### ISSUE TITLE
Draw svg images by in pdf where  HTML object created by6 string

### ISSUE THREAD

**Issue by ildarworld** [Kozea/WeasyPrint#1624] opened 2022-04-18 13:33 UTC
Hey there!

**OS:** MacOS 12.3.1 on M1
**Version:** weasyprint = "^53.4"

Creating HTML object by passing string won't draw svg as an image in a pdf file. Nevertheless if create the same by  filename, everything working fine. Both examples are below, just replace sag file name

```python
from weasyprint import HTML
from tempfile import NamedTemporaryFile

html_str: str = """
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <div class="label">
          <div class="barcode-image">
             <p> HAAAAAAAAAAAAA </p>
            <img src="svgfile.svg" />
          </div>
    </div>
  </body>
</html>
"""

html: HTML = HTML(string=html_str)
html.write_pdf(target="output_by_string.pdf", presentational_hints=True)

with NamedTemporaryFile(mode="w") as file:
    file.write(html_str)
    file.flush()
    html_by_file_name = HTML(filename=file.name)
    html_by_file_name.write_pdf(target="output_by_file_name.pdf", presentational_hints=True)
```

**Comment by liZe** [comment] 2022-04-18 14:05
Hello!

That’s a duplicate of #1381. When you give a filename, you also implicitly give a path that can be used to resolve relative URLs. This path is not given when you use a string, but you can provide a `base_url` parameter to solve that!

**Closed by liZe** 2022-04-18 14:05 UTC

**Comment by ildarworld** [comment] 2022-04-18 18:55
> Hello!
> 
> That’s a duplicate of #1381. When you give a filename, you also implicitly give a path that can be used to resolve relative URLs. This path is not given when you use a string, but you can provide a `base_url` parameter to solve that!

Sorry for spending your time,

**Comment by liZe** [comment] 2022-04-18 19:01
> Sorry for spending your time,

No problem, have fun with WeasyPrint!
