### ISSUE TITLE
Bug: pydyf version 0.11.0 breaks PDF generation

### ISSUE THREAD

**Issue by paultop6** [Kozea/WeasyPrint#2207] opened 2024-07-18 08:57 UTC
Call to pydyf.PDF in weasyprint/pdf/__init__.py no longer works with pydyf version 0.11.0 (works fine with 0.11.0).

The function signature has been changed from `__init__(self, version=None, identifier=None)` to `__init__(self)`

**Comment by grewn0uille** [comment] 2024-07-18 09:08
Hi,

That’s a duplicate of #2206, https://github.com/Kozea/WeasyPrint/issues/2205, https://github.com/Kozea/WeasyPrint/issues/2204, https://github.com/Kozea/WeasyPrint/issues/2203, https://github.com/Kozea/WeasyPrint/issues/2202 and https://github.com/Kozea/WeasyPrint/issues/2200.

**Closed by grewn0uille** 2024-07-18 09:08 UTC
