### ISSUE TITLE
Flex-grow does not work on inline elements

### ISSUE THREAD

**Issue by LukasKlement** [Kozea/WeasyPrint#1680] opened 2022-07-10 19:39 UTC
A wrapper with display: flex and two nested inline elements with flex: 1 should occupy each half of the available width. However, in WeasyPrint v56 the inline elements do not grow.

Minimum reproducible example (added colour to illustrate the issue):
```
<html>
  <head>
    <style>
      .line {
        position: relative;
      }

      .item {
        display: flex;
        justify-content: center;
        width: 100%;
      }

      .primary-language,
      .secondary-language {
        flex: 1;
        text-align: right;
      }

      .primary-language {
        padding-right: 12pt;
        background-color: yellow;
      }

      .primary-language::after {
        content: '';
        border-width: 1pt;
        border-style: solid;
        border-color: var(--color-text);
        position: relative;
        top: 1pt;
        display: inline-block;
        width: 8pt;
        height: 8pt;
        position: absolute;
        left: 50%;
        transform: translateX(-5pt);
      }

      .secondary-language {
        text-align: left;
        padding-left: 12pt;
        color: var(--color-text-secondary);
        background-color: aquamarine;
      }
    </style>
  </head>
  <body>
    <div class="line">
      <span class="item">
        <span class="primary-language">Coffee</span><span class="secondary-language">قهوة</span>
      </span>
    </div>
    <div class="line">
      <span class="item">
        <span class="primary-language">Tea</span><span class="secondary-language">شاي</span>
      </span>
    </div>
    <div class="line">
      <span class="item">
        <span class="primary-language">Hot milk</span><span class="secondary-language">حليب ساخن</span>
      </span>
    </div>
  </body>
</html>
```

When the nested elements are `<div>` insted of `<span>`, the example works as expected.

**Comment by liZe** [comment] 2022-07-10 20:07
Hello!

Thanks for the bug report. Isn’t this a duplicate of #1652?

**Comment by liZe** [comment] 2022-07-16 21:10
Let’s continue the discussion in #1652.

**Closed by liZe** 2022-07-16 21:10 UTC
