### ISSUE TITLE
Tables overflowing page limits

### ISSUE THREAD

**Issue by RafaelLinux** [Kozea/WeasyPrint#727] opened 2018-11-06 15:06 UTC
I'm not sure if is a previosly commented issue, but this is the case: Two distinct tables are overflowing page limits, one at bottom and the other one at right. In the screenshots, you can compare Firefox print preview output (left side) and weasyprint output (right side). I coded CSS to show on screen closer to print output, and on screen, the table overflowing at right is correctly displayed.

I'm using latest weasyprint and parameter "--presentational-hints"

This is the table overflowing at bottom:
![weasyprint - table bottom overflow](https://user-images.githubusercontent.com/13048959/48072658-52ebb080-e1dd-11e8-8777-62aad2b0fd23.png)

This is the table overflowing at right:
![weasyprint - table right overflow](https://user-images.githubusercontent.com/13048959/48072665-57b06480-e1dd-11e8-89a8-25bc300e7932.png)

[weasyprint issues.zip](https://github.com/Kozea/WeasyPrint/files/2553691/weasyprint.issues.zip)

Any idea what's wrong? 

Thank you

**Comment by liZe** [comment] 2018-11-06 15:55
Hello!

> This is the table overflowing at bottom:

That's because we can't break pages in a table line. See #36.

> This is the table overflowing at right:

That's a different issue. I have to check what's happening.

**Comment by liZe** [comment] 2018-11-06 16:01
> I have to check what's happening.

There's a 'width="793"' attribute set to your table, looks like it's larger than the page.

So for me, there's nothing wrong in WeasyPrint (except for the first case corresponding to #36).

**Comment by liZe** [comment] 2018-11-06 16:03
(By the way: the page style is much better like this :wink:)

**Comment by RafaelLinux** [comment] 2018-11-07 09:15
> That's because we can't break pages in a table line. See #36.

So .... I'm in trouble. Despite page style "maybe" is better :P  we have no control about the content of the table lines. Usually, tables have large cells that contains text, so we can't do nothing about it cause the format must be respected for legal reasons. That's a big inconvenient if we want to use Weasyprint ... I need to think if we can use a workaround cause we was betting for weasyprint as final solution to obtain PDFs  :(

> There's a 'width="793"' attribute set to your table, looks like it's larger than the page.

Unfortunately, that's a table property assigned by editors, but it's override as you can see, by CSS. As you can see on screen and when previewing the print, the tables are adjusted to they content, ignoring the width.

Thank you for your clarification

**Comment by liZe** [comment] 2018-11-07 10:10
> Unfortunately, that's a table property assigned by editors, but it's override as you can see, by CSS.

Oh, I see. None of the values you set in CSS are supported by WeasyPrint (`unset` and `fit-content`). Adding `width: auto` before `width: unset` will work.

**Comment by RafaelLinux** [comment] 2018-11-07 14:59
I tried adding adding `width: auto` before `width: unset` has you suggested. It solves the right-side overflowing, but have ugly collateral effects over all the other tables in document. This is the comparison screenshot. At the left side is with the original CSS. At the right, with you suggestion:
![weasyprint - table witdth after adding width auto before width unset solved overflow](https://user-images.githubusercontent.com/13048959/48137624-c5729400-e2a2-11e8-90a7-7a58ca8577c7.png)
But here, a piece of collateral effects on the other tables:
![weasyprint - table width after adding width auto before width unset unwanted collateral effect](https://user-images.githubusercontent.com/13048959/48137748-05d21200-e2a3-11e8-92fc-5d10d5f47719.png)

And while inspecting the effects on all the document, I discover accidentally something very worrying, not related with the CSS, but with weasyprint. Take a look at this screenshot:
![weasyprint - table dissapeared between pages](https://user-images.githubusercontent.com/13048959/48138114-de2f7980-e2a3-11e8-876f-86d45454bfe3.png)
As you can observe, a little table is dissapeared just when it's between pages. The html code for this table is simply:
`<table cellspacing="0" cellpadding="0" border="1"><thead><tr><th id="th069E20400000" valign="top">Anexo IV<br>Contrato menor</th></tr></thead></table>`
I'm afraid it's consequence of bug #36 , but not sure.

That bug is a stone in the road in our way to use weasyprint :( , cause we can not lost any word in our PDFs.

Thank you for the suggestion about the CSS.

**Comment by liladude** [comment] 2019-04-26 15:50
Hello, I am here to report a similar related problem. I have tables with really long text on them, which is why  I have put "td {page-break-inside: auto;}" in my css (even if this should be the standard). Unfortunately the table overflow my bottom margin... and it only happens with weasyprint (so far)!

**Comment by liZe** [comment] 2019-07-25 09:38
> Hello, I am here to report a similar related problem. I have tables with really long text on them, which is why I have put "td {page-break-inside: auto;}" in my css (even if this should be the standard). Unfortunately the table overflow my bottom margin... and it only happens with weasyprint (so far)!

I'd really like to have a short HTML sample showing this problem, because I can't reproduce.

**Comment by liZe** [comment] 2019-07-25 09:39
> Hello, I am here to report a similar related problem. I have tables with really long text on them, which is why I have put "td {page-break-inside: auto;}" in my css (even if this should be the standard). Unfortunately the table overflow my bottom margin... and it only happens with weasyprint (so far)!

This is what's reported by bug #36.

**Comment by liZe** [comment] 2019-09-16 12:25
> That bug is a stone in the road in our way to use weasyprint :( , cause we can not lost any word in our PDFs.

We've greatly improved the way tables are rendered between pages in #941. #36 is not fixed yet, but we can now use `break-*` rules for `tbody` and `tr`, and **we don't lose tables anymore**.

I think that I can close this issue, as:
- we don't break `td`s, but that's what #36 tracks,
- we're able to correctly break between `tr`s and `tbody`s, even respecting `break-*` rules,
- we don't "forget" lines anymore.

Feel free to reopen if there's anything I didn't think of!

**Closed by liZe** 2019-09-16 12:25 UTC
Labels: bug
