### ISSUE TITLE
print sum of a table column to next page 

### ISSUE THREAD

**Issue by ritiksoni00** [Kozea/WeasyPrint#1592] opened 2022-03-10 22:24 UTC
If you call `.render()` on an `HTML` object, you get a `Document` object whose `.pages` attribute is a list of `Page` objects. You can shuffle this list all you want before calling e.g. `.write_pdf()` on the document, without modifying the layout code. I suppose you could use the pages’ `anchors` attribute to check which page contains a given element, if you give it an ID: e.g. `<h2 id=toc>` and `if 'toc' in page.anchors: ...`

See details in the documentation: http://weasyprint.org/docs/api/

So yeah, I suppose we could add limited support for `target-counter()` that only works if the target is earlier in the document, then you could have a TOC at the end and shuffle pages to put it at the beginning again. I guess you’d want something like `@page :first { counter-reset: page 2 }`, not sure if that works right now. Maybe named pages (#57) would be useful there as well.

This sounds reasonable. It’s just a matter of someone doing the work now. Unfortunately nobody is actively working on WeasyPrint at the moment.

_Originally posted by @SimonSapin in https://github.com/Kozea/WeasyPrint/issues/23#issuecomment-62674356_

`if 'toc' in page.anchors: ...` is doing weird behavior,  putting some random values in that particular element. 
#

i want to achieve something like this

![Screenshot from 2022-03-08 14-26-52](https://user-images.githubusercontent.com/47344024/157202948-cc7a15e1-2313-446d-a7a2-e44d9f275a4c.png)

**Comment by liZe** [comment] 2022-03-12 10:58
Hello,

That’s a duplicate of #1201, and unfortunately there’s no good solution to this problem :/.

**Closed by liZe** 2022-03-12 10:58 UTC

**Comment by ritiksoni00** [comment] 2022-03-12 17:49
hey lize,
Thanks for pointing out the duplicate. and I hope we can get it in the future.
